### ISSUE TITLE
Win10 Window-snapping tools don't affect this program

### ISSUE THREAD

**Issue by aeoncleanse** [FAForever/downlords-faf-client#1007]
I use Aquasnap. There is a free version if you wish to investigate.

**Comment by 1-alex98** [comment]
Also duplicate lemme search. Can not find it but the issue exists somewhere

**Comment by micheljung** [comment]
We're not using Windows' windows decorations so unless I find a way to customize the native windows controls, this will never work.

See https://stackoverflow.com/questions/37454818/javafx-custom-window-with-native-behavior
