### ISSUE TITLE
irc color bug

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/downlords-faf-client#1013]
when coloring usernames in the irc the chat history applies those colors but future chat messages will not
example https://i.imgur.com/cV8VNr8.png

would be nice if future messages would consider the custom colors as well
tested in v0.9 rc9

**Comment by 1-alex98** [comment]
@Brutus5000 where is the PR did it get merged?

**Comment by Brutus5000** [comment]
https://github.com/FAForever/downlords-faf-client/pull/1112
