### ISSUE TITLE
[0.9-rc9] Game Table View - List of mods not readable

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/downlords-faf-client#1014]
In the table view the list of mod can be shortened:
![grafik](https://user-images.githubusercontent.com/6843462/48283220-2a251e80-e45c-11e8-9e1c-b7ab55fdd9b1.png)

There is no way to show the full list. Hovering does not show a popup. Also the detail view on the right side does not show the mod names.
Only the tile view shows the full list.

**Comment by Katharsas** [comment]
~I think the current tile view does not show mods either. So as far as I now, there is now way to see the full mod list of a game for now.~
Ok, mod list is visible in tile view, though a bit ugly.

**Comment by Katharsas** [comment]
I guess adding mods to the details view would also be nice.
