### ISSUE TITLE
Game Table View doesn't show password protection indicator properly (in german)

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/downlords-faf-client#1017]
![grafik](https://user-images.githubusercontent.com/6843462/48301837-3eb4f580-e4f4-11e8-9cf5-7d8fb809ee6d.png)

**Comment by germanicianus** [comment]
This can be fixed with the translations file. The lock is encoded as Unicode escape sequence there because it is taken from a special font. Apparently POEditor messes up escape sequences.

**Comment by Brutus5000** [comment]
This should be solved in rc11, at least it is for all other cases where u2xxx characters where show. I would assume that the rendering show abbreviation characters because the column is not wide enough?
