### ISSUE TITLE
[0.9-rc11] Open replay file without the client being open

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/downlords-faf-client#1018]
This is less of an issue and more of a feature request:
When double clicking a .fafreplay file that is associated with the java client exe while the client isn't running nothing happens.

With the python client the updater runs/patches the game and opens the file just fine (even while the client isn't open and you aren't logged in etc)
Would be nice to have this in the java client as well

**Comment by Sheikah45** [comment]
You should need to be logged in before downloading any files otherwise the ownership checks could be circumvented
