### ISSUE TITLE
[0.8.0 Beta] fa_path.lua not found?

### ISSUE THREAD

**Issue by Teledahn** [FAForever/downlords-faf-client#1020]
Running downlord's FAF client v0.8.0-beta from https://github.com/FAForever/downlords-faf-client/releases/download/v0.8.0-beta/dfc_windows_0_8_0-beta.exe

After patching, linking my steam account, locating my FA install directory I can launch and play custom games from the 'play' tab but I cannot launch Co-Op games.  I'm greeted by the following error when attempting to launch one, regardless of level selection.

```
Failed to setup initial search path.

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /log C:\ProgramData\FAForever\logs\game.log /gpgnet 127.0.0.1:64566 /mean 1500.0 /deviation 500.0 /savereplay gpgnet://127.0.0.1:15001/8827288/Teledahn.SCFAreplay /country CA /numgames 0

Callstack:
	Unknown symbol (address 0x008cef50)

Last 100 lines of log...

warning: Running "C:\ProgramData\FAForever\bin\init.lua" failed: cannot read C:\ProgramData\FAForever\bin\..\fa_path.lua: No such file or directory
         stack traceback:
         	[C]: in function `dofile'
         	C:\ProgramData\FAForever\bin\init.lua(2): in main chunk

```

No mods or other changes.  Starting from current steam version of Forged Alliance and installing FAF with the above (Downlord 0.8.0 beta) client.  As the log states 'fa_path.lua' does not exist in the directory FAForever\bin.

Is there a known resolution to this?  Can I create the file myself?

**Comment by micheljung** [comment]
Sorry for the inconvenience and thank you for reporting. This will be fixed in version 0.9.0-beta which I'm planning to release today.
