### ISSUE TITLE
Unnecessary dots

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/downlords-faf-client#1034]
Are these dots intended in the switch between tiles and list games?

![downlords-faf-client_2018-11-13_18-18-21](https://user-images.githubusercontent.com/10947024/48430840-8778e280-e770-11e8-90f9-7a9d3071dcfb.png)

**Comment by 1-alex98** [comment]
What language are you using?

**Comment by speed2CZ** [comment]
english

**Comment by speed2CZ** [comment]
Ok it actually happens in the window is smaller, but it doesnt need to be super small for this to occur
