### ISSUE TITLE
messages of foes show up

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/downlords-faf-client#1035]
when adding someone to your foe list all his past messages are hidden - but the messages written after that will be visible while the username is not visible
![image](https://user-images.githubusercontent.com/24656673/48432716-7d0d1780-e775-11e8-984b-fb01d3cec7b7.png)

**Comment by 1-alex98** [comment]
thx

**Comment by 1-alex98** [comment]
I think i fixed this once no idea where it went

**Comment by micheljung** [comment]
Yes I also think this has been fixed. Please reopen if not.
