### ISSUE TITLE
Readme missing information about JavaFX dependency

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/downlords-faf-client#1040]
When I try to build the sources, I get an error that JavaFX dependencies are missing.
Looks like they are not part of the regular dependency declarations of gradle.

**Comment by micheljung** [comment]
Output would be appreciated

**Comment by Brutus5000** [comment]
I get a localized message:
`Fehler: Zum Ausführen dieser Anwendung benötigte JavaFX-Runtime-Komponenten fehlen`
