### ISSUE TITLE
Two different deserializations of Faction

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/downlords-faf-client#1041]
We have Jackson annotations telling me that the ordinal is supposed to be used: https://github.com/FAForever/downlords-faf-client/blob/develop/src/main/java/com/faforever/client/game/Faction.java#L33

But the client is using Gson, so the Jackson annotations have no effect. So actually FactionTypeAdapter should be used: the https://github.com/FAForever/downlords-faf-client/blob/develop/src/main/java/com/faforever/client/remote/gson/FactionTypeAdapter.java

But which one is correct now? I need this information as the Java server is supposed to send the faction to the client in preparation of GW.

**Comment by Sheikah45** [comment]
Conflict deserialization no longer present in client repo
