### ISSUE TITLE
Working forever on task

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1045]
![image](https://user-images.githubusercontent.com/19996713/48742430-3b8dd800-ec5f-11e8-8f53-c6d0100989de.png)
Even so no task is being processed windows icon does not stop to blink in green light...

**Comment by micheljung** [comment]
This doesn't seem to happen on every machine. Not yet sure what causes it or how to reproduce :\
The code to stop the animation is in place.

**Comment by 1-alex98** [comment]
Yeah it seems to be some kind of race condition

**Comment by micheljung** [comment]
Does this still happen?

**Comment by 1-alex98** [comment]
I think yes

**Comment by Sheikah45** [comment]
This was solved by just removing the animation as from my investigation the issue seemed to be that the handle for the icon bar became invalid if it was not updated after a period of time.

Fixed in #2232
