### ISSUE TITLE
Add Rating as a search option for replays in vault

### ISSUE THREAD

**Issue by RecklessCharger** [FAForever/downlords-faf-client#1048]
How to view and sort replays by player rating in either live, online or local replays?

**Comment by 1-alex98** [comment]
I think we had that but it meant that if u searched for rating >1000 only one player had to had >1000 for the game to appear and we can not change that. And because ppl did not get that we removed it.

**Comment by RecklessCharger** [comment]
But that makes sense! If I search I want any of the players to have a rating of x or more. I want to find replays of a certain standard....

**Comment by 1-alex98** [comment]
Maybe add that option and name it "Any player's rating"  but also rename all other options that act in the same way as "any ...."
