### ISSUE TITLE
Find player aliases

### ISSUE THREAD

**Issue by RecklessCharger** [FAForever/downlords-faf-client#1053]
Is there a means to search for player aliases as in the old python client? Would be a 'nice to have'. Oh and thanks for all the hard work on the new client - its looking really good now

**Comment by 1-alex98** [comment]
You can right click a player and click player information which will show u his name history. Is that what u want or is that that you want to know how was named "cristal13" before?

**Comment by Brutus5000** [comment]
Player information is currently broken due to API issues. The loading of achievements takes so long, that you run into a Gateway Timeout.

**Comment by 1-alex98** [comment]
Yeah but that should not effect other stuff loading or does it?

**Comment by RecklessCharger** [comment]
Yeah that's what the Python client allows. You can search for a specific name and get all their aliases.

**Comment by 1-alex98** [comment]
Yeah same here just search for a player in chat and see this name history. But does not work if player is offline etc.

**Comment by Brutus5000** [comment]
It's working again. As such I'm closing the ticket:

![grafik](https://user-images.githubusercontent.com/6843462/52883896-cbfb8c00-316c-11e9-9b8b-d1be92ddab90.png)
