### ISSUE TITLE
Add total game time as search criteria in replay vault

### ISSUE THREAD

**Issue by RecklessCharger** [FAForever/downlords-faf-client#1057]
Would it be possible to add total game time as a search criteria in the replay vault please?
(would make searching for longer more interesting games easier)

**Comment by Brutus5000** [comment]
This is currently not possible. The client queries our API for the games, which looks up the database record populated by the server. The server is not saving the total gametime (and probably doesn't even know it).

Therefore I close this issue for now.

**Comment by RecklessCharger** [comment]
OK it's visible in the info for each replay so that will have to do I guess
