### ISSUE TITLE
After closing the game, remaining replay data isn't sent to the server

### ISSUE THREAD

**Issue by Wesmania** [FAForever/downlords-faf-client#1063]
Steps to reproduce:
1. Launch wireshark, snoop on port 15000.
2. Launch the client, host a game, run the game, quit after a few seconds.
3. No data beyond SYN and FIN is sent. It's expected that at least the replay header (e.g. 'P/1000000/foo') gets sent after launching the game.

**Comment by Brutus5000** [comment]
Most probably related to the buffer not being released in the end and related to https://github.com/FAForever/downlords-faf-client/issues/973

**Comment by Wesmania** [comment]
Or to the buffer not being flushed before closing the server socket.

**Comment by Brutus5000** [comment]
That's what I meant.

**Comment by 1-alex98** [comment]
It is true what you say Stream is neither flushed nor closed

**Comment by micheljung** [comment]
I feel ashamed. Thanks for investigating and reporting.

**Comment by Wesmania** [comment]
Confirming fixed.
