### ISSUE TITLE
supreme score board doesn't show correct replay id

### ISSUE THREAD

**Issue by EmielWitteman** [FAForever/downlords-faf-client#1069]
0.9.2-beta
mods: common mod tools v1, supreme score board v2.0
replay id is incorrect in live game, it is good in replay though

(phyton faf client has same issue after 0.18.0-rc2+3017, that is why I am still using that version)
<img width="282" alt="2018-12-08 22_05_28 bad id" src="https://user-images.githubusercontent.com/38175365/49690874-1ee71080-fb38-11e8-88d3-f1e522e41e78.png">
<img width="352" alt="2018-12-08 22_21_54 good id" src="https://user-images.githubusercontent.com/38175365/49690875-1ee71080-fb38-11e8-9bb7-5351c55343be.png">

**Comment by 1-alex98** [comment]
hmmnot sure if that is a client issue but it might

**Comment by 1-alex98** [comment]
logs?

**Comment by EmielWitteman** [comment]
the old phyton client log:
```
info: /savereplay
info: SSB >>> TRACE GetReplayId()... from cmd /savereplay 8943504
debug: Loading module '\000/mods/supremescoreboard/modules/score_mini.lua\000'
info: SSB >>> TRACE SetLayout()...
```
This is with downlords, diff, left is replay, right is the game
<img width="1103" alt="2018-12-09 ids" src="https://user-images.githubusercontent.com/38175365/49702377-bf503a00-fbf7-11e8-8d77-2b83b27d0b24.png">
apparently the command line call /savereplay is no longer parsed correctly, 
The old client does this:
/savereplay "gpgnet://localhost/8950120/Mielus.SCFAreplay"
The new:
/savereplay, gpgnet://127.0.0.1:65106/8947048/Mielus.SCFAreplay
And the port number is parsed as replayed by SSB

from SSB score_manager.lua:

```
function GetReplayId()
    local id = nil
    --log.Table(GetFrontEndData(''), 'GetFrontEndData')
    local syncID = GetFrontEndData('syncreplayid')
    if HasCommandLineArg("/syncreplay") and HasCommandLineArg("/gpgnet") and syncID ~= nil and syncID ~= 0 then
        id = syncID
        log.Trace('GetReplayId()... from cmd /syncreplay ' .. tostring(id) )

    elseif HasCommandLineArg("/savereplay") then
        local url = GetCommandLineArg("/savereplay", 1)[1]
        local lastpos = string.find(url, "/", 20)
        id = string.sub(url, 20, lastpos-1)
        log.Trace('GetReplayId()... from cmd /savereplay ' .. tostring(id) )

    elseif HasCommandLineArg("/replayid") then
        id =  GetCommandLineArg("/replayid", 1)[1]
        log.Trace('GetReplayId()... from cmd /replayid ' .. tostring(id) )
    end
    return id
end
```

lua has no regexp support :-(, quick and dirty fix:
```
--local lastpos = string.find(url, "/", 20) --don't bother searching..
id = string.sub(url, 26, 32)
```

So a change in the client broke SSB v2.0 and a fix is easy

**Comment by 1-alex98** [comment]
So is there anything we should change? I am not 100% sure what u talked about

**Comment by 1-alex98** [comment]
/savereplay, gpgnet://127.0.0.1:65106/8947048/Mielus.SCFAreplay
So is this valid or not should we remove the "," or what?

**Comment by EmielWitteman** [comment]
it is the port specification in the /savereplay command which throws of SSB, the string is no longer parsed correctly. I suspect since both the phyton and java client do this "new" port thing (since august 2018 or so) because of changes in the server. Should be fixed in SBB in my opinion, that is why I closed the issue.

**Comment by 1-alex98** [comment]
Oh ok yeah, we use a custom port for the replay sever ;) This more robust. So if some application is running on the standard port it still works
