### ISSUE TITLE
[LINUX]Exception when downloading a map for live replay ends in a 404

### ISSUE THREAD

**Issue by Wesmania** [FAForever/downlords-faf-client#1073]
A stack trace caught when trying to watch a live replay:

```
java.util.concurrent.CompletionException: java.lang.NullPointerException
	<snip>
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.NullPointerException
	at java.base/java.nio.file.Files.provider(Files.java:99)
	at java.base/java.nio.file.Files.isDirectory(Files.java:2220)
	at com.faforever.client.map.MapService.readMap(MapService.java:223)
	at com.faforever.client.map.MapService.addSkirmishMap(MapService.java:210)
	at com.faforever.client.map.MapService.lambda$downloadAndInstallMap$15(MapService.java:439)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:49)
	at com.github.nocatch.NoCatch.noCatch(NoCatch.java:34)
	at com.faforever.client.map.MapService.lambda$downloadAndInstallMap$16(MapService.java:439)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	... 22 more
```

From what I can tell, `getPathForMap` can return null, but it isn't handled anywhere, so it eventually gets passed to isDirectory.

Looking deeper, I suppose that DownloadMapTask does not download the map correctly, and yet it throws no exception:
`Downloading map dualgap_fix_adaptive.v0007 from http://content.test.faforever.com/faf/vault/maps/dualgap_fix_adaptive.v0007.zip`
This address returns 404. I think that the DownloadMapTask should throw an IOException in that case, but I'm a bit lost in the task / future callback soup so I'm not sure. Either way, the null from getPathFromMap should be handled, and that I suppose is a separate issue.

**Comment by 1-alex98** [comment]
This a a known Linux issue i belive. Right you were on Linux and I think that happens in gerneral when downloading maps on linux.

**Comment by tatsujb** [comment]
@axel1200  downloading maps works fine on linux if you simlink maps (and mods) folders. 

what is an issue though is this : 
![Screenshot from 2019-05-11 13-43-56](https://user-images.githubusercontent.com/5132359/57569279-dd160b00-73f2-11e9-86c7-f3842da618e3.png)
after clicking ok the game starts up as if started from steam. (intro video and ends up at main menu)

**Comment by 1-alex98** [comment]
I was told that happens if 5 min did not yet pass

**Comment by 1-alex98** [comment]
try again 1 min later

**Comment by 1-alex98** [comment]
![image](https://user-images.githubusercontent.com/19996713/57586834-f5be1800-74fb-11e9-9716-64c76a1538be.png)
There it return null, we should rather make a proper error message there

**Comment by 1-alex98** [comment]
It is because linux is case sensitive

**Comment by tatsujb** [comment]
linux is indeed case sensitive.

**Comment by Wesmania** [comment]
IIRC many maps freely mix case between zips, directory names and filenames. Copious use of lowercasing should fix this.

**Comment by 1-alex98** [comment]
new server new luck
