### ISSUE TITLE
Double clicking on FAF logo makes the client fullscreen

### ISSUE THREAD

**Issue by Rackover** [FAForever/downlords-faf-client#1075]
Not present in 0.8.0
In 0.9.0 upwards double clicking anywhere on the window makes it go fullscreen.
It's great, except when it conflicts with other commands and makes the client fullscreen when it was not intended. Double clicking on the FAF logo is the only way to access connection parameters.
Maybe either make the FAF logo single click, or remove the fullscreen on double click if the click is eaten by another command ?

**Comment by 1-alex98** [comment]
Double clicking a lot of things make the client full screen
