### ISSUE TITLE
Logging out doesn't refresh Featuredmods

### ISSUE THREAD

**Issue by Rackover** [FAForever/downlords-faf-client#1076]
When logging out from the client and logging in using a different API, FeaturedMod (and probably other stuff) don't get refreshed at all, making it impossible to start a game on the newly connected API.

**Comment by 1-alex98** [comment]
sure that is something we should work on? I think that is fine... if you want a proper restart i think you will have to restart

**Comment by Rackover** [comment]
Well then it should be impossible to change the API url when logging out if the API has already been connected. If you can change it but it doesn't change, it's a bug, not a feature.
But let me tell you it would be much more appreciated if we could just, you know, change the API by logging out and in again like it says it can.
