### ISSUE TITLE
Don't cap local replay list after 300 files

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/downlords-faf-client#1078]
Right now there is a hard limit of 300 local replays to show.

https://github.com/FAForever/downlords-faf-client/blob/d5cf40884953a578858c01c3ff0ca9843a82189e/src/main/java/com/faforever/client/replay/ReplayService.java#L170

There needs to be a better we of preventing OutOfMemoryExceptions with some sort of paginated loading.

**Comment by ch3oh** [comment]
If the limit must remain for the near future then at least display the most recent 300 replays.  

For info I have a replay folder containing 4,688 replays from 18/05/2013 through to 24/01/2019 so any upper limit needs to be somewhere north of this.

**Comment by TheKoopa321** [comment]
I agree it would be a great improvement. At least to show the latest instead of the oldest.

You can modify the .class file in downlords-faf-client-0.9.3-beta.jar and replace 300 with 1000 for exemple. I did it and it works fine.

**Comment by 1-alex98** [comment]
The thing is we need to do some kind of paging then if we load 4688 replays the client will run out of Memory

**Comment by EcoNooob** [comment]
I'd say the biggest issue is that it shows the first 300 replays instead of the latest 300 replays. The local replay vault is now useless unless i want to watch replays from 2013.
