### ISSUE TITLE
Provide easy means to list and join chat channels

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#1088]

**Comment by Katharsas** [comment]
As Axel just showed me, join should be easy since its basically already implemented like when you close all channels.

**Comment by Katharsas** [comment]
Related:
https://github.com/FAForever/downlords-faf-client/issues/532

**Comment by Katharsas** [comment]
Existing channels (like language channels) can be advertised in the UI used for opening a new channel, which should become easier to access with https://github.com/FAForever/downlords-faf-client/issues/532
Related: https://github.com/FAForever/downlords-faf-client/pull/854

**Comment by Sheikah45** [comment]
Not going to be implemented due to lack of channels for now
