### ISSUE TITLE
Chat - autocomplete of names doesnt work for only IRC users

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/downlords-faf-client#1092]
So today I wanted to ping all the peasants on the moderators and friend list, but when writing Phil and pressing tab, nothing happened... expected result was to autocomplete to  PhilipJFry_irc

After quick test I found out the autocomplete of names by pressing Tab works only for FAF users and not for those who are only connected to IRC

**Comment by 1-alex98** [comment]
@Brutus5000 where is the PR ??? did it get merged
