### ISSUE TITLE
[ Linux ] [ v0.9.3-beta ] notifications make no sound.

### ISSUE THREAD

**Issue by tatsujb** [FAForever/downlords-faf-client#1099]
on linux notifications don't do ping sounds nor do they really conform to what you configure them to.

what works : 

- positioning 
- disabling friend joins game notification
- disabling ranked 1v1 notification
- disabling PM received notification

what doesn't work :

- sound
- disabling notifications entirely (I suspect that game full notification remaining is intentional but friend joins and friend leaves notifications also remain when all notifications are off)
- disabling friend online
- disabling friend offline
- after game review

**Comment by Sheikah45** [comment]
stale need to see if this is still an issue
