### ISSUE TITLE
Periodically verify game location settings

### ISSUE THREAD

**Issue by Askaholic** [FAForever/downlords-faf-client#1100]
I recently had the issue that my game location was configured wrong because it used to be installed on one drive, but then was moved to a different drive. The `Supreme Commander Forged Alliance` folder still existed, but it only had the `maps` folder left. Everything else including `bin` got deleted.

The result is that when you try to launch a game, the client does it's usual update and download map stuff, but then just stops with no sign of an error or anything. (It logs the exception which is how I discovered that this is what was happening).

It would be nice if:
  * a). There were some error handling for File IO (because lets be honest, we can't seriously expect file io to never fail)
  * b). There were an error message indicating that the game path was set incorrectly or was no longer valid. Checks for this error could happen on startup and notify the user to fix their settings, or even be triggered from the error handling in part a. Better than just displaying an error, this could even grey out the host/join game buttons so that the user isn't fooled into thinking everything is ok.

To my pleasant surprise the client already implements some validity checks when setting the game path initially which would have been part c.

**Comment by Katharsas** [comment]
Maybe same: https://forums.faforever.com/viewtopic.php?f=3&t=17694
