### ISSUE TITLE
[Feature Request] Please allow deleting maps from game creation dialog or map vault

### ISSUE THREAD

**Issue by Justify87** [FAForever/downlords-faf-client#1102]
![grafik](https://user-images.githubusercontent.com/10554299/51611433-84903000-1f1f-11e9-9377-97b6a849da59.png)

Either via left click --> delete or delete key/button
Or make the map vault able to list and delete locally installed maps

**Comment by 1-alex98** [comment]
Second one would be better

**Comment by Justify87** [comment]
Yeah at first glance, the second one would be better. But from a user perspective, the dialog for creating a game is the one that need the ability for deleting maps too, because that's when I notice that I need to delete all the crap maps. And I don't want to leave my already setted up game just to go to the map vault.

**Comment by Sheikah45** [comment]
Uninstall implemeneted in map vault
