### ISSUE TITLE
Map Vault: Search for width/height in km rather than pixels

### ISSUE THREAD

**Issue by Justify87** [FAForever/downlords-faf-client#1105]
![grafik](https://user-images.githubusercontent.com/10554299/52336490-59204180-2a05-11e9-9c9a-6db6a8f0e0b5.png)

The first parameter (max players) doesn't matter here. No matter if I use only height or only width or both, no maps are found. 

This query gives all maps greater than 20k:
latestVersion.width=gt="2000"
This though does not work:
latestVersion.width=="2000"
This shows setons and dual gap (20k maps):
latestVersion.width=lt="2000";latestVersion.maxPlayers=="12"

Maybe width and height are accidentally converted to strings and searched/sorted alphanumerically? idk

As a side note:
Plz use symbols instead of words here:
![grafik](https://user-images.githubusercontent.com/10554299/52336668-c9c75e00-2a05-11e9-8a0b-6065feb2363d.png)

Much faster to understand because of icon recognition and they don't need translation

**Comment by Brutus5000** [comment]
I can't see the German translation on this screenshot but in English, the name clearly indicates that width and height are in pixels and not in kilometers.
256px = 5km
512px = 10km
...

Could take an improvement, but technically no error.

**Comment by Justify87** [comment]
There is no mentioning of the unit being pixels in the translation. Why would you even do that if the game measures it in kilometers and all users talk about map sizes in kilometers, except maybe map creators? What ever the reasons - at least both should be available. Otherwise it's just confusing and to the average user it surely appears to be an error. Since some forum post mentioned this client will be the standard client from march 2019 onwards this is definitley something that should be working as expected for the average user.

**Comment by Brutus5000** [comment]
I know. That's not the only case where the query builder is not optimal.
For the pixels: this is what is read from the map files and stored in the database. Technically we can, of course, map this to kilometers but I do not believe that the current query builder architecture is capable to do this.
Needs an overall refactoring to make it more user-friendly. This is also a known topic in the feedback thread.

**Comment by germanicianus** [comment]
> There is no mentioning of the unit being pixels in the translation.

Yes, at least not in the German translation. In English and Chinese the unit "px" is mentioned.

**Comment by Sheikah45** [comment]
Fixed in #2044
