### ISSUE TITLE
Sort tournaments by newest

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/downlords-faf-client#1113]
Mountain:

in the Java client in the tournaments tab the oldest tournaments are at the top, would it be possible to make it so newest tournaments are at the top?

forwarded from tournament director Rowey:

"I'm not sure how easy this is but its a suggestion. with the Tournaments tab in the Java Client it would be nice to have the new tournaments at the top of the list instead at the bottom and also maybe to purge the tournament listings that date back to 2016"

**Comment by 1-alex98** [comment]
Tournament sorting acctually makes sense all those at top are the ones still open

**Comment by Brutus5000** [comment]
Looks like something recently broke it :(
