### ISSUE TITLE
Error fetching maps

### ISSUE THREAD

**Issue by MikZZ-faf** [FAForever/downlords-faf-client#1114]
java.util.concurrent.CompletionException: java.nio.file.InvalidPathException: Illegal char <:> at index 7: starway:_krasnograd.v0001.png

**Comment by 1-alex98** [comment]
We know this error for years lemme check the staus. So this is definetly a duplicate

**Comment by 1-alex98** [comment]
#902 #852 #614

**Comment by 1-alex98** [comment]
https://github.com/FAForever/faf-java-api/pull/208 we solved it for newely uploaded maps however their are still old maps that conatin illegal characters

**Comment by 1-alex98** [comment]
told mods to hide map
