### ISSUE TITLE
u00200 instead of Whitespace in Leaderboard Co-Op

### ISSUE THREAD

**Issue by Serverfrog** [FAForever/downlords-faf-client#1116]
In the Leaderboard of the Co-Op, instead of a Space,, a u00200 is printed
![u00200](https://user-images.githubusercontent.com/1306404/53258970-42007580-36ce-11e9-9729-6f772252f8da.PNG)

**Comment by germanicianus** [comment]
Usually the text is edited on https://poeditor.com and not directly in the translation files, but POEditor messes Unicode escaping up.

**Comment by 1-alex98** [comment]
Yeah it needs to be done in poeditor @Serverfrog you are gonna do it or shall i?

**Comment by Serverfrog** [comment]
@axel1200 sadly i can't see any projects on POEditor

**Comment by 1-alex98** [comment]
oh true @micheljung will need to invite you i fear

**Comment by Serverfrog** [comment]
seems like it was fixed in POEditor. Need a Pull from that

**Comment by 1-alex98** [comment]
Yes
