### ISSUE TITLE
git repo releases are not browsable by api?

### ISSUE THREAD

**Issue by tatsujb** [FAForever/downlords-faf-client#1125]
https://gist.github.com/lukechilds/a83e1d7127b78fef38c2914c4ececc3c

the above trick gets me : 

```
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/repos/releases/#get-the-latest-release"
}
```

if I just try  https://api.github.com/repos/FAForever/downlords-faf-client/releases/latest

tags does not work either : 

```
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}
```

https://api.github.com/repos/FAForever/downlords-faf-client/tags/latest

the following does not work either in shell : 
```
curl --silent "https://api.github.com/repos/FAForever/downlords-faf-client/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'
```

**Comment by Brutus5000** [comment]
This is probably related to all releases marked as pre-release.
The list itself is here https://api.github.com/repos/FAForever/downlords-faf-client/releases and seems to be properly sorted, so as a workaround you could always fetch the first element in that list (but without guarantees that it won't break later on)
