### ISSUE TITLE
edits to client.prefs aren't taken into account.

### ISSUE THREAD

**Issue by tatsujb** [FAForever/downlords-faf-client#1127]
say you started FAF for the first time. you logged in then you closed it.

you then edited the .faforever/client.prefs to the appropriate values for your game's location.

when you start FAF back up the fields are still empty/haven't changed.

where else are these values supposed to be changed.

may be a linux-specific issue.

**Comment by 1-alex98** [comment]
The values are not supposed to be changed at all in the client.prefs. You are suppossed to set them in settings or else where. But when you do it should actually have an effect. Tell me exactly what u changed and what u expect it to do...

**Comment by tatsujb** [comment]
well I'd like for editing FAF settings to be scriptable as a part of my install script.

**Comment by 1-alex98** [comment]
Sorry but from the description u provide i can not see what u are doing nor what the issue is

**Comment by tatsujb** [comment]
ok so I'd like for a non-human entity, a bot, a machine, a script, (while FAF is closed), to simply via modification of files, edit FAF's setting's.

and then when the actual human starts FAF, FAF will have said settings in it's settings page currently being applied. 

I've edited the file `$HOME/.faforever/client.prefs` while FAF was closed then opened up FAF to find the settings not applied in the settings window of FAF.

I grasp from this that editing `$HOME/.faforever/client.prefs` is the **wrong** way to script the editing of FAF's settings.

my question is what is the **right** way to edit FAF's settings?

the context is this : https://github.com/tatsujb/installFAFscript
I want to "scriptically" edit these two setting lines specifically : 
![screenshot from 2019-03-03 04-27-31](https://user-images.githubusercontent.com/5132359/53690540-c0af7f80-3d6c-11e9-9e83-36a25ce7e1f3.png)

"game location" and "command line format for executable"

**Comment by 1-alex98** [comment]
I think it is the right way to do it ;) maybe on linux it is the wrong location up that is more a question for @Geosearchef

**Comment by tatsujb** [comment]
yeah I think it actually applies but what's shown in the GUI isn't ncessarilly loaded from that file, it just saves to that file if ever the value is edited in GUI. It probably loads from `.com.faforever.client.FafClientApplication` I'll test and see if edited values actually apply even if they don't show when I have the time. if that's the case then we can close this as for the purposes of my install script it would be sufficient.

**Comment by 1-alex98** [comment]
Ok so values are written as soon as you close the settings window. You should definetly only write to that file if the client is closed otherwise it might be over written or not loaded

**Comment by tatsujb** [comment]
I'm having to run FAF to generate the file, then loop a "sleep" until prefs has a "username" value, then kill faf, then edit the values and immediately re-run to obtain the desired effect. a bit hacky 

is it reasonable to be asking of you guys/Downlord the ability to pipe run args to faf, args including most of the important values in this prefs file?

would seem neat to me. kinda like how I can script logging in to steam and downloading and running this and that.

...I wager this is a tall ask.

In any event you were right I can sorta get the behavior I want from altering that file.
