### ISSUE TITLE
map vault: display number of downloads & latest map version

### ISSUE THREAD

**Issue by badbwoi** [FAForever/downlords-faf-client#1136]
Hey,
I like the way you present map stats and love "times played" because it shows the plays of a map over all versions! 

It would be a nice addition to actually display the total amount/number of downloads from a map, like you do it with "times played". Now sorting for "downloads" is applied, but no value for downloads is shown.
And could you please add the information about the latest map version, that should not be missing.
![image](https://user-images.githubusercontent.com/28671151/55026521-733cd000-5003-11e9-9b9d-0dc9c3e65e3f.png)

**Comment by 1-alex98** [comment]
Not sure if we have that value

**Comment by 1-alex98** [comment]
Yeah we do

**Comment by 1-alex98** [comment]
Easy to abuse tho i can just push my map to top downloaded with a script i write in like 10 min... Tho that would be quite obvious

**Comment by 1-alex98** [comment]
We only display latest versions at all so there would not need to be such a thing as to highlight if a map is the latest version

**Comment by badbwoi** [comment]
> 
> 
> Easy to abuse tho i can just push my map to top downloaded with a script i write in like 10 min... Tho that would be quite obvious

I see your point, but couldn't that be done with plays as well, if someone really wanted to?

>
>
>We only display latest versions at all so there would not need to be such a thing as to highlight if a map is the latest version

Displaying the latest map version and having the latest map version is a different thing. By adding the latest version a map maker or player can identify if he already has the latest version. Now we can only check via "install/uninstall" if we are on the latest map version. I would just love to see the actual number somewhere in the map info.
I remember a notification that a new version of the map is available when you host a game, but that seem to be disabled.

**Comment by 1-alex98** [comment]
Ok so maybe we should make that a separate issue

**Comment by 1-alex98** [comment]
I think we have an issue on the download count number already as well

**Comment by badbwoi** [comment]
Hey, sorry for the delay.
How should we progress now? 
I could not find an issue for "display downloads", so should I make a separate issue for latest map version? Or is it okay like it is now?

**Comment by Sheikah45** [comment]
Version is displayed and downloads are no longer counted
