### ISSUE TITLE
map description to long to be displayed

### ISSUE THREAD

**Issue by badbwoi** [FAForever/downlords-faf-client#1137]
Hello, parts of the description are cut off (to long to be displayed).
Due to this bug, content is at the moment not accessible.
Could you please give the description more space or make the window responsive to the amount of text?  
![image](https://user-images.githubusercontent.com/28671151/55027283-31148e00-5005-11e9-87a3-b0e298c7fc98.png)

**Comment by badbwoi** [comment]
Please fix this. I have this problem with almost all of my maps. 
Unfortunately, the link to my map information is cut off. So maybe the statement of drunk_robot could be avoided.

![dfc_map_info_issues_questions](https://user-images.githubusercontent.com/28671151/71322126-4f3fe980-24c4-11ea-9c6f-14df4ee1d884.png)
How do I check/make sure that my reply is not to long? It seems to be to long to be displayed as well.

**Comment by 1-alex98** [comment]
It is a bug we will try to show it all
