### ISSUE TITLE
improvement suggestions for search feature

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/downlords-faf-client#1138]
Some small requests/suggestions regarding the replay vault search:

- allow users to filter by ladder rating (currently you can filter by global only)
- allow users to sort by review score/amount of reviews (would help casters and others who wanna watch nice replays)
- change the featured game mode filter to a dropdown displaying the available game modes so people don't have to guess how the ladder game mode is called

**Comment by PhilipJFryFAF** [comment]
another issue i stumbled across:
when looking for specific factions you get these results
cybran -> aeon
aeon -> uef
uef -> cybran
seraphim -> seraphim
i guess the main faction ids are messed up somewhere

**Comment by 1-alex98** [comment]
Please always make one issue per issue. These are all seperate issues but as soon as i fix one i close the ticket and all the others are lost!!!!

**Comment by Sheikah45** [comment]
Fixed in #2044
