### ISSUE TITLE
Remember password when creating game

### ISSUE THREAD

**Issue by RecklessCharger** [FAForever/downlords-faf-client#1140]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%245%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/FAForever/downlords-faf-client/issues/1140)

Can we please have the client remember the password ('Password (optional)') as well as the status of the 'Only show to friends' check box when in the Create Game dialologue? Its a pain having to click these every time when you are playing a series of private games. This is what the happened in the Python client.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- [<img src='https://avatars3.githubusercontent.com/u/19996713?v=4' alt='axel1200' width=24 height=24> axel1200](https://issuehunt.io/u/axel1200) ($5.00)

### Submitted pull Requests
- [#1494 Remember password fo games](https://issuehunt.io/r/FAForever/downlords-faf-client/pull/1494)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/FAForever/downlords-faf-client/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by 1-alex98** [comment]
That is a good suggestion

**Comment by Brutus5000** [comment]
Did you just pay $0,50 to IssueHunt for nothing? xD
