### ISSUE TITLE
Local replays not updating till client restarted

### ISSUE THREAD

**Issue by RecklessCharger** [FAForever/downlords-faf-client#1141]
Can we at least have a refresh button for local replays as I don't think any local replays of games in the current session are shown. Client needs to be restarted.

**Comment by Fealthas** [comment]
Yes, this is super annoying. Local replays do not show up after you have played a game.

**Comment by 1-alex98** [comment]
yes we can... but takes time

> https://www.bountysource.com/teams/faforever if it is super annoying
