### ISSUE TITLE
Allow random selection of ladder maps in custom game

### ISSUE THREAD

**Issue by RecklessCharger** [FAForever/downlords-faf-client#1143]
Would it be possible to have a button in the create game dialogue (for a custom game) perhaps next to the existing random map button to select a map from the ladder pool?

There is a convoluted way to do this already by selecting a 1v1 ranked match, then selecting show ladder maps, then closing your eyes and clicking one randomly, then clicking on create game.

Options via a drop down to select from 5x5, 10x10 or 20x20 (randomly) for both ladder maps and all maps would also be a nice to have.

**Comment by 1-alex98** [comment]
Please discuss that somewhere like in slack or on the forum if that is actually we want. I think it is not needed at all
