### ISSUE TITLE
Background image not properly displayed

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#1146]
Note the top and bottom

![image](https://user-images.githubusercontent.com/1864183/55575633-99532600-570f-11e9-9482-3ee79a73c7b7.png)

Probably introduced by #1059

**Comment by 1-alex98** [comment]
defenitely introduced by #1059

**Comment by micheljung** [comment]
I meant #1089 which fixes #1059 

It changed from `-fx-background-size: cover, auto;` to `BackgroundSize.DEFAULT` and I am 99% sure it's caused by this
