### ISSUE TITLE
Client application (and FAF ICE window) just dissapered when game played.

### ISSUE THREAD

**Issue by SpheroidDev** [FAForever/downlords-faf-client#1150]
Client 0.10.1-beta (just updated)
During match (~30 min from start) lost connect to all players (all quiet). Wait for about 2 minutes. Try to find some helpful info in FAF ICE debug windows and not find one. And Downlord's Client window too. Then just dissapered silently. No error messages or something. No downlords-faf-client in OS process list.
I restarted client several times, so some logs may be not in actual state.

Game ID: 9563914

[ice-adapter.log](https://github.com/FAForever/downlords-faf-client/files/3100768/ice-adapter.log)
[downlords-faf-client.log](https://github.com/FAForever/downlords-faf-client/files/3100769/downlords-faf-client.log)

**Comment by jkstpierre** [comment]
This happened to me as well, I would love this issue to be fixed.

**Comment by 1-alex98** [comment]
@Geosearchef Any Idea what happend here?

**Comment by Geosearchef** [comment]
Yes, the client crashed without any trace.
The adapter now keeps running if it is in a game and the client crashes due to that.

**Comment by 1-alex98** [comment]
Hmm bad without any trace is hard to solve

**Comment by 1-alex98** [comment]
Well hard to solve if i can not reproduce?

**Comment by 1-alex98** [comment]
Was probably OOME
