### ISSUE TITLE
AccessDenied for FAForever/bin folder

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/downlords-faf-client#1154]

**Comment by Brutus5000** [comment]
Can someone confirm that this was fixed with 0.10.3-beta?

**Comment by Geosearchef** [comment]
it wans't

**Comment by 1-alex98** [comment]
Please provide more info for that issue

**Comment by 1-alex98** [comment]
What is the issue? How do i reproduce...

**Comment by 1-alex98** [comment]
Not enough information , inactive
