### ISSUE TITLE
Missing map when in game

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/downlords-faf-client#1155]
A lot of players are missing maps after joining a game. One user reported adding the following folder structure solved the issue:

```C\ProgramData\FAForever\user\My Games\Gas Powered Games\Supreme Commander Forged Alliance\maps```

**Comment by speed2CZ** [comment]
This was the path to download maps to when the normal one in documents coundn't be used for w/e reason (like permissions and stuff)

**Comment by Brutus5000** [comment]
Can someone confirm that this was fixed with 0.10.3-beta?
