### ISSUE TITLE
In game dialogue are not being displayed correctly in FAF SC(supreme commander 1) coop missions.

### ISSUE THREAD

**Issue by akermen4** [FAForever/downlords-faf-client#1156]
There seems to be two issues with this:
1.The cutscenes don't show up in dialogue box(only factions logo are appearing).
2.secondly,the dialogues are not being displayed in correct order(for example you can hear four dialogues at once).
This problem only seems to with SC and Custom coop missions.
SCFA coop missions are fine.

**Comment by speed2CZ** [comment]
Here's a hacky solution: https://forums.faforever.com/viewtopic.php?f=78&t=16674&p=167547&hilit=unpack#p167547

Did you download the voice files via downlords client? If so then they prolly didnt get unpacked properly. Check if the files are where they should be as I described in the forum post.
Another issue could be a badly generated init file which doesn't load the the files...
Let us know

**Comment by akermen4** [comment]
It works,both issues are solved.
Thank you

**Comment by 1-alex98** [comment]
@speed2CZ is that the thing with unpack /movies to some differnent folder?

**Comment by speed2CZ** [comment]
hm, yes?

**Comment by 1-alex98** [comment]
You told me when i did tutorials that all /movies need to be unpacked to some folder and i implemented this however this is still not merged

**Comment by speed2CZ** [comment]
Yeah, thats the thing, same system as for coop, much needed.

**Comment by 1-alex98** [comment]
I will try to push tutorials again. @micheljung @Geosearchef can one of you deploy tutorial featured mod I can help you do it I already did it on the test server....

**Comment by 1-alex98** [comment]
it is fixed in 1.0.1RC2, if the RC would launch XD

**Comment by 1-alex98** [comment]
I build a RC5 now u can test if it works there
