### ISSUE TITLE
Finish theming implementation

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/downlords-faf-client#1158]
1. There is no documentation about how to create a theme, what files are required (e.g. theme.properties) and where to put it. There is also no documentation of the versioning concept.
2. The combo box for choosing a theme in the settings is disabled in the fxml. You cannot choose a valid theme if you have one.
3. (After manually enabling the combobox) If you choose a theme that has disabled the combobox you are locked in it forever (or until you delete the preferences). [That happened to me with a copy of the current theme and I was locked out again]. This setting should be set in the code to prevent shenanigans of theme creators.
4. The current theme does not seem to be remembered in th combobox after restart.

**Comment by micheljung** [comment]
Theming was never finished, but it's documented in code :D The button is, therefore, disabled on purpose.

**Comment by Brutus5000** [comment]
see #1792
