### ISSUE TITLE
notification options don't work

### ISSUE THREAD

**Issue by VoRGoR** [FAForever/downlords-faf-client#1160]
You can entirely turn notifications off or on, but individual options do not work.
For example:

![notifications](https://user-images.githubusercontent.com/8906373/56474761-2fa87b00-6476-11e9-8dc2-3b3ed158a6bf.PNG)

Literally nothing in the blue circle does anything. The top turn off/on all is the only thing that works.

**Comment by 1-alex98** [comment]
duplicate
