### ISSUE TITLE
"Play" Tab: Game info view not being updated when lobby closed

### ISSUE THREAD

**Issue by ArXen42** [FAForever/downlords-faf-client#1161]
The problem seems to be something like missing "lobby closed" event handling. Maybe it's intended behaviour though, not sure.

1. Create some lobby.
2. Click on it in FAF client, so that lobby info info would be shown at the right side.
3. Abandon the game (or launch it), lobby should disappear from the list of games.
4. Despite lobby no longer being in the list, it's info would still be shown at the right side.

Example: game "800 1500" displayed at the right side was already finished when the screenshot was taken:
![image](https://user-images.githubusercontent.com/10744285/56536567-09163d00-6567-11e9-8332-d408531d2c68.png)

**Comment by micheljung** [comment]
Yes we should remove it when the game is no longer in the list.

**Comment by 1-alex98** [comment]
No wait that is not fixed by this ups
