### ISSUE TITLE
Inform about planned or current downtime on login screen

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#1166]
Just like the battle.net client ![image](https://user-images.githubusercontent.com/1864183/56648959-81265500-6684-11e9-8513-88094eaa7104.png)

**Comment by 1-alex98** [comment]
We have a link to status page, I think that's enough for now

**Comment by 1-alex98** [comment]
Well actually https://developer.statuspage.io/ is an option and would be doable in a fair amount of time I guess

**Comment by 1-alex98** [comment]
The probelm is gonna be the rate limit

**Comment by 1-alex98** [comment]
not sure if they are gonna allow 1000/requests per Minute

**Comment by Sheikah45** [comment]
We now have the banner on the news page and broadcast messages
