### ISSUE TITLE
Add "Time" sorting option to Vault Live Replays

### ISSUE THREAD

**Issue by Gandalf2k15** [FAForever/downlords-faf-client#1168]
It would be awesome if you could sort by time on the live replays vault like it was on the legacy client so you can see when a game was started...

**Comment by 1-alex98** [comment]
You can do that already or am i mistaking?

**Comment by Gandalf2k15** [comment]
nope there is no option to sort it by time started

**Comment by 1-alex98** [comment]
Thats what i just merged by @Wesmania XD
