### ISSUE TITLE
Better order of vault search options

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/downlords-faf-client#1169]
Currently the filter list for searching stuff on the online replay vault is hard to use:
one small but effective improvement would be to change the order in which the filters are listed

right now the first option a user gets is to search by Player UID -> most ppl don't even know their own uid not to mention anyone elses

would be great to have player name, player rating, game mode and map name on top so users can easily search more easily

**Comment by 1-alex98** [comment]
@PhilipJFryFAF make me a list in which order you would like to have them (maps,mod,replay search term)

**Comment by PhilipJFryFAF** [comment]
my arbitrary list:
```
Player Name
One of the player's (global!!!!) rating
One of the player's ladder rating -> does not exist as of yet but can be done by editing the search queue string so the api supports looking for ladder rating already - pls add this option while you're at it
Game mod short name
Map name
Player faction
Player start position
Max. players
Map is ranked
ID -> should be renamed to Replay ID
Player ID
Title
Start Time
End Time
Validity
Victory Condition
Player team
Host username
Host ID
Description
Map width
Map height
Map version
Map folder name
```
