### ISSUE TITLE
IPV6 causes problems in vault

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1176]
http://forums.faforever.com/viewtopic.php?f=3&t=17473#p173922 @Geosearchef can we just incooperate the solution you posted in the forums???

**Comment by Geosearchef** [comment]
Yeah, afaik you can set this option using System.setProperty()

**Comment by 1-alex98** [comment]
No be can just set it in the run configs and in the instal4j file no need of any java code

**Comment by 1-alex98** [comment]
Exception is : `Address family not supported`
