### ISSUE TITLE
Error 34 when installing client

### ISSUE THREAD

**Issue by iamtheeggmansroyal** [FAForever/downlords-faf-client#1178]
cant install the update or install the app from scratch keep getting the same error app/data/local/temp/ij4_nlog_11.log

**Comment by 1-alex98** [comment]
Please copy the whole error! I can not guess the error from the file name...

**Comment by iamtheeggmansroyal** [comment]
C:\users\iamtheeggman\appData\local\temp\ij4_nlog_12.log

sorry I copied it sloppily thanks for your help

**Comment by 1-alex98** [comment]
What is the error or does it say `C:\users\iamtheeggman\appData\local\temp\ij4_nlog_12.log` and nothing else and next would be could you send that log file

**Comment by iamtheeggmansroyal** [comment]
the file doesn't exist yet? its an error while installing so it isn't on my hard drive. 
it might help you to look at the last patch or the patch before it because this same error happened to me then and you guys fixed it.

**Comment by iamtheeggmansroyal** [comment]
oh above the line it says an internal error occurred error 34

**Comment by 1-alex98** [comment]
I am really sorry but i still can not imagine what the error looks like.
Btw the patching process is not done by us but by a program called install4j

**Comment by iamtheeggmansroyal** [comment]
everytime I try it the nlog_# goes up one

**Comment by 1-alex98** [comment]
Honestly what is the message you get it certainly wont be a file path. I mean I never had an error installing it and so I have no idea what the error says or reads... Please tell me. But I am pretty doubtful it only states a path...

**Comment by 1-alex98** [comment]
Does the `C:\users\iamtheeggman\appData\local\temp\ij4_nlog_12.log` not exist. If it does please upload it here

**Comment by iamtheeggmansroyal** [comment]
the error says error 34. the filepath does not exist on my comp yet

**Comment by iamtheeggmansroyal** [comment]
error code 34

**Comment by 1-alex98** [comment]
Maybe start with installer with debug option as described [here](https://stackoverflow.com/questions/27238616/the-executable-generated-by-install4j-doesnt-start)

So 
1. Windows+R
2. Type cmd
3. cd pathToTheInstaller
3. dfc_xxxxx.exe /create-i4j-log

**Comment by 1-alex98** [comment]
It should open a window which tells you where it writes it log to. Please forward that log to me

**Comment by iamtheeggmansroyal** [comment]
thanks it was a good idea but for some reason when I look in my downloads folder the download doesn't appear, it just appears in downloads on my internet explorer. so theres no filepath I can find
. I FAIL

**Comment by 1-alex98** [comment]
Well that is a problem you need to solve yourself can not really help you there

**Comment by iamtheeggmansroyal** [comment]
hmmm I finally just reinstalled the .3 client and downloaded the patch through the client again and it worked for some reason. must have been an issue with ie and chrome or an ai just messing with me. thanks for trying to help me.
