### ISSUE TITLE
Don't store username and password hash in the client.prefs file

### ISSUE THREAD

**Issue by foodlfg** [FAForever/downlords-faf-client#1180]
The client stores the hash of the password in the `client.prefs` text file.
The file stores configuration related info mainly and may be requested for troubleshooting which causes the user unwillingly share his/her password.

I think it would be better to store the password hash in a separate file, in a gziped binary file even along with the username for better safety when `Automatic login` is requested.

**Comment by 1-alex98** [comment]
Maybe we just encrypt it with idk his cpu name, something that stays the same on his system. I mean ppl should still not give out that info but if they so it is not completely exposed

**Comment by 1-alex98** [comment]
I mean in the long run we wanna have a jwt token stored there. Tho the sever does not yet accept that
