### ISSUE TITLE
Increase lobby connection wait time before proxy is engaged.

### ISSUE THREAD

**Issue by robbotik** [FAForever/downlords-faf-client#1186]
It seems the proxy between players is engaged too quickly in game lobbies. People who would otherwise be able to connect normally end up routed through the proxy instead. In this case, it's possible to avoid the proxy by having people join in different orders. It's assumed this is due to an individuals hardware or network location able to accept connections slightly quicker than it's able to instigate them.

This is mostly an issue in regions far outside the proxy server location, where being connected that way is unstable and causes extreme, unplayable lag in games.

**Comment by 1-alex98** [comment]
This is an issue for faf ice adapter
