### ISSUE TITLE
Lobby is interpreting CPU restrictions as 'ranking' restrictions

### ISSUE THREAD

**Issue by dev-nulled** [FAForever/downlords-faf-client#1187]
Looks like a new tweak was put in.  A title in the lobby saying 'CPU < 250' pops a warning that people are over a rating of 250 should not join... You can continue to join despite the warning.

**Comment by 1-alex98** [comment]
There is no cpu rating in the client and it might have different outcome then the one in the game

**Comment by dev-nulled** [comment]
Right - the message in the title is custom - saying if you have a CPU rating over 250, don't join.  The UI is looking at that message and saying - you mean the 'user rating' needs to be between 0-250.

**Comment by 1-alex98** [comment]
ah ok yeah we already got that issue somewhere and also we wanna add server support for rating boundaries
