### ISSUE TITLE
Bugsplatt.dll  access denied

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1188]
Bugsplatt.dll Error avoiding or better error message

**Comment by 1-alex98** [comment]
@micheljung once said when I suggested to not copy bugsplatt.dll on every game launch but only if it was not copied yet. I do know suggest to still copy them every time but still launch game and proceed if we are unable to copy those files. Because tons of users need to restart the game every like 3rd time they play because of the game not closing correctly (including me) .

**Comment by micheljung** [comment]
How about we find out why the came doesn't close properly (doesn't it, really? But why can we start it "again" then, when only a single instance is allowed?). Or rather; why the file is locked.

Then we fix that properly rather than displaying some long message the user doesn't really know what to do about it.

**Comment by 1-alex98** [comment]
We can not do much about it if you don't want to dig into assembly code if you wanna rule out the core cause of it. I would assume. Anyway for me there are tons of other stuff I would rather dig into because this is an issue which is annoying but with the above or a silent version of it everything works as expected.

**Comment by 1-alex98** [comment]
@micheljung The game's process does not terminate but sets its self to halt in some way which makes it a zombie  process. We could probably kill it as it is our child or reverse engeneer, but this needs hours and hours of work (probably) and maybe in the end we will not be able to do anything against it... The py client had some similar implementation of what I implemented but silently. Now that ppl are switching to java client. That is one of the most annoying thing that can happen to you as a user... The game does not launch to some bugsplatt.dll that you never heard of before and you need to restart. As a user I would say java-client is a piece of shit i need to restart my computer every 3rd game(if i even get to the idea and not just deinstall because the client does not work). So this message is a huge huge huge improvement. I do admit that there is further space/potential for improvement and I would really like you  or anybody else to suggest and implement further improvements(like for example killing the child(if that is that easy idk or debug the cause of all this) but for the time being users and tec support needs to be helped and that is a huge improvement for them, no matter if there would possibly be a even better solution. But till this better solution is found we need to go in the right direction and not have the user restart the computer...
