### ISSUE TITLE
[ Linux ] is linux tarball name going to change again?

### ISSUE THREAD

**Issue by tatsujb** [FAForever/downlords-faf-client#1191]
for my script I had to make this rather silly commit : https://github.com/tatsujb/installFAFscript/commit/f23bdbaf91c2ee5e9f041365f632283a90da4d03

what's going on?

I didn't really see the point of an extra underscore before the name of the archive but I was like "heck it, so long as it doesn't change"

and it did inexplicably : this was not part of the release notes : https://github.com/FAForever/downlords-faf-client/releases

and now it's no more leading underscore but an even more curious dual underscore after `dfc`

`dfc__unix_...` I imagine this isn't the way it's going to stay and that the aim was to be at : `dfc_unix_...` 

if so could I know so as to anticipate this change for my next release?

thanks for the continued work on the client.

**Comment by 1-alex98** [comment]
We did not really change anything there. No idea how the undescore got there... Maybe it would be best for you to read out the name in your script that should be pretty easy

**Comment by 1-alex98** [comment]
The next one is gonna be without underscore dfc_unix_0_10_5-beta.tar.gz

**Comment by tatsujb** [comment]
I'd like some pointers on this because the current setup I have which figures out how to calculate the syntax for three different syntaxes for the same version number and for said version number took me awhile to figure out.

**Comment by 1-alex98** [comment]
https://api.github.com/repos/FAForever/downlords-faf-client/releases 
With one or two greps you should quickly find the install files naem

**Comment by 1-alex98** [comment]
See what i wrote on slack

**Comment by tatsujb** [comment]
that's exactly what's in my code already : 

```
faf_version_number=$(curl -v --silent https://api.github.com/repos/FAForever/downlords-faf-client/releases 2>&1
\ | grep '"tag_name": '
\ | head -n 1
\ | cut -f4,4 -d'"')
faf_version=$( echo ${faf_version_number:1} | tr '.' '_' )
wget https://github.com/FAForever/downlords-faf-client/releases/download/$faf_version_number/dfc__unix_$faf_version.tar.gz
```
take a good hard look. there is no pattern that can make us get it entirely.

right now I can just grab the version number.

**Comment by 1-alex98** [comment]
Was just an idea

**Comment by Brutus5000** [comment]
The underscore is used so the .exe is on top of the github releases list, otherwise it does not get fetched by the website.

**Comment by tatsujb** [comment]
so right now it's not getting fetched? btw browsers can tell what OS you're on that's how steam and plenty of other websites (chrome download) have a download button that takes you to the right kind of file automagically. could we do that for FAF's website? I know how to do it in JS

**Comment by 1-alex98** [comment]
Build it. Normally nobody is willing to touch website
