### ISSUE TITLE
Vault replay search criteria not working

### ISSUE THREAD

**Issue by CyrilPaulus** [FAForever/downlords-faf-client#1194]
The search criteria are not working for the online replay section of the Vault.

There is a least two problems 

* Search button doesn't work, nothing happens when we click on it.
* Sort by doesn't work, it doesn't expand when we click on it.

Edit:
It seems to happen because somehow the value I had stored in my configuration for the sort field isn't present anymore in the sort choices. I don't know how I managed to do that.

Still I have a fix that could prevent such case, is it necessary ?

**Comment by 1-alex98** [comment]
Oh it is because we deleted some i think

**Comment by CyrilPaulus** [comment]
Okay then my commit should also fix it if the list is changed again in the future.
