### ISSUE TITLE
user folder/encoding issue

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/downlords-faf-client#1201]
The game Supreme Commander - Forged Alliance looks up this directory to find maps/mods (outside of the ones in the game install directory):
`C:\Users\%username%\Documents\My Games\Gas Powered Games\Supreme Commander Forged Alliance\mods`
`C:\Users\%username%\Documents\My Games\Gas Powered Games\Supreme Commander Forged Alliance\maps`
The Client stores mods/maps from the vault in those 2 directories respectively.

If a user has uncommon chars in the windows username (e.g. `Фёдор`) then the game will not be able to pick up maps/mods from that folder which results in people being unable to play with such mods/maps

The legacy client deals with this by storing maps/mods in
`C:\ProgramData\FAForever\user\My Games\Gas Powered Games\Supreme Commander Forged Alliance\maps\` and
`C:\ProgramData\FAForever\user\My Games\Gas Powered Games\Supreme Commander Forged Alliance\mods\`

I suggest we do the same unless someone has a better idea.

Possible alternatives include:
1) storing maps/mods in the game install directory 
  + is a known location (since the user has to tell the client where fa is installed anyway) 
  + allowing the user to store these files on a drive that is not the one containing the OS 
  - mods/maps in the game install are not being printed in the game log which makes bug tracking/troubleshooting a lot harder
2) allowing the user to select a mod/map directory of their own choice
 + maximum freedom
 - probably too much freedom for the average user

attached a client and game log where the windows username was `Фёдор` and i stored maps/mods in the user directory with downlords faf client
the client was able to see the map/mod but the game itself couldn't use them despite looking up the user folder for them
[downlords-faf-client.log](https://github.com/FAForever/downlords-faf-client/files/3148660/downlords-faf-client.log)
[game.log](https://github.com/FAForever/downlords-faf-client/files/3148661/game.log)

**Comment by 1-alex98** [comment]
What about a setting with 

- user specific maps/mods location
- faf specific maps/mods location

and the user can toggle between the two. and we make the programdata one the default so nobody has any issues

**Comment by PhilipJFryFAF** [comment]
i forgot to add one more drawback to the freely selected folder:
since you have to tell the game via the init file where to look for mods/maps the user specific folder would not be recognized by the non-faf patched game (same as the programdata fallback) and if someone wipes their client prefs (cause of whatever issue they have with their client settings) then the user will have to set that path again in the client

**Comment by 1-alex98** [comment]
Well but the toggle option seems good like that nothing can go wrong. Both dirs are ok

**Comment by 1-alex98** [comment]
https://forums.faforever.com/viewtopic.php?f=2&t=4507&p=172915&hilit=symlink+linux#

**Comment by zlo-faf** [comment]
To me, storing maps and mod in game folder looks like  the best idea. Mainly because people, for some reason tend to creat small C drive partition, and fill it with ragbage and then having trouble with free space.

**Comment by 1-alex98** [comment]
No that is not possible... game is only gonna be able to find maps/ mods in certain folders...
