### ISSUE TITLE
Admin check has false positives

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1205]

**Comment by Nojoke185** [comment]
loading 10.6 RC1 and getting warning that it is running as admin
As far as i can tell i have never set this to run as admin

running from : C:\Program Files\Downlord's FAF Client\downlords-faf-client.exe
log below

[downlords-faf-client.log](https://github.com/FAForever/downlords-faf-client/files/3149959/downlords-faf-client.log)
