### ISSUE TITLE
Waffle is closing on the 16th of this month. 

### ISSUE THREAD

**Issue by douglasg14b** [FAForever/downlords-faf-client#1207]
Noticed you guys use Waffle for a Kanban board since you have it tagged on the readme. They are shutting down on 5/16/2019, and recommend migrating your waffle projects to github.

https://waffle.io/closing-its-doors

**Comment by 1-alex98** [comment]
Well we dont use it anyway

**Comment by douglasg14b** [comment]
I was mentioning it since you have issue tracking links to it in your readme...

**Comment by 1-alex98** [comment]
Maybe we should just remove that
