### ISSUE TITLE
Chat layout rework

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/downlords-faf-client#1212]
- [ ] Align chat usernames to the right of the column in compact mode.
- [ ] It was also suggested to align the messages itself to one column (right of the aligned username column) so that the chat doesn't go nuts when the client is small.
- [x] If a username is too long, it should be replaced by ... .
- [x] There should be some padding on the left of the write message box
- [x] More clearly distinguish chat user categories

Other suggestions:
- Making messages more readable by alternating backgrounds:
[https://pp.userapi.com/c850436/v850436620/7ea23/Q4BPl4GkDjY.jpg](https://pp.userapi.com/c850436/v850436620/7ea23/Q4BPl4GkDjY.jpg)

http://forums.faforever.com/viewtopic.php?f=2&t=17068#p170815
http://forums.faforever.com/viewtopic.php?f=2&t=17068#p170817

**Comment by Sheikah45** [comment]
Done all that will be for this with colors and alignment wont change in default theme
