### ISSUE TITLE
Show all used mods

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/downlords-faf-client#1219]
If there are too many mods, the client doesn't show all of them and just shows e.g. "2 more". Would be nice if there were a way to display all of them, e.g. as a tooltip when hovering.

**Comment by Brutus5000** [comment]
I would suggest adding it to the game_details.fxml (that is the detail view on the right side if you click on a game)

**Comment by 1-alex98** [comment]
we do that now in pop up
