### ISSUE TITLE
Show years in player rating history

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/downlords-faf-client#1220]
The player rating history shows dates below the graph which can get pretty useless if the history spans multiple years.

![](http://forums.faforever.com/download/file.php?id=16509)

**Comment by Androish** [comment]
I would like to add that right now X is not a function of time, but a function of number of games. This is partly why it looks this strange.

While that is ok I guess, I would much rather prefer it being a function of time, or atleast have the option of doing it that way.

I want to see my rating being a straight line if I am not playing any games :D

**Comment by Androish** [comment]
This is basically the same as #935
