### ISSUE TITLE
Sort lobbies by friends to the top

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/downlords-faf-client#1222]
There should be a present option / by default the game hosted by friends should be sorted to the top of the game list, indicating that it's hosted by a friend.

**Comment by shalkya** [comment]
Also give more option for lobbies sorting. We lack the ability to sort them by average rating. (also if you refaf, it should remember that you want to sort out by rating)

**Comment by 1-alex98** [comment]
Maybe rather mark them in some way

**Comment by Sheikah45** [comment]
Closed by #2264 with added highlighting
