### ISSUE TITLE
Allow deleting local replays

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/downlords-faf-client#1227]
http://forums.faforever.com/viewtopic.php?f=2&t=17068&start=60#p173729

**Comment by fultonm** [comment]
Hi, I'd like to take this on. Are there any special considerations to keep in mind? My initial thought for where to place the "Delete Replay" button would be on the Replay Details modal, to the right of the "Report Game" button.

As a side note, in the linked topic, they also talk about the grid based interface for FAF Replays and Local Replays. I wonder if supporting a list interface such as the one used for Live Games would be a good UX improvement?

**Comment by Sheikah45** [comment]
Yeah feel free to take this on. With regards to the grid that is not something I think is as interesting or good as it requires supporting two different formats for all future changes which we want to avoid.
