### ISSUE TITLE
Consider switching/disabling background image by default

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/downlords-faf-client#1232]
The background image is the opposite of good and clear UI design and annoys a lot of people.
Maybe we should disable it by default or replace it with some more generic that makes the background a bit more interesting than just one color.

**Comment by 1-alex98** [comment]
i like it

**Comment by Rackover** [comment]
This background image not only hasn't much to do with FA, but also plays against the readability of the chat and of the client overall. It should be disabled by default like it was the case in v0.8 and earlier, and the decision to display an image or not should be left to the user / user's theme.
In a default case, readability is first priority.
