### ISSUE TITLE
add back the channel topic

### ISSUE THREAD

**Issue by shalkya** [FAForever/downlords-faf-client#1234]
so TD can actually ping stuff in the channel (eg : challonge link, streams etc)

**Comment by Geosearchef** [comment]
issue 1234, wow

Probably not gonna happen, there was a lot of debate about this (don't remember where, may have been slack) and the common opinion was that the channel topic never was the solution needed. It was removed from the java client on purpose.

**Comment by Brutus5000** [comment]
The latest info from Slack was Downlord would be okay with it if we add it as sort-of-message on opening the channel. So it's not supposed to stay non-stop visible, but only if a channel is opened or the topic is changed.

**Comment by 1-alex98** [comment]
Moderators are really keen of having it visible non-stop...
