### ISSUE TITLE
Friendslist is inaccurate

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/downlords-faf-client#1237]
Only 4 friends are shown as online, there's many many players missing from that list.
[downlords-faf-client.log.2019-05-07.0.gz](https://github.com/FAForever/downlords-faf-client/files/3154832/downlords-faf-client.log.2019-05-07.0.gz)

**Comment by 1-alex98** [comment]
Also i found not all players are shown on ne that are

**Comment by 1-alex98** [comment]
i was missing one player and when i rejoined aeolus he reappeared
