### ISSUE TITLE
ProgramData files (faforever patch) not downloaded upon ladder game start

### ISSUE THREAD

**Issue by Rackover** [FAForever/downlords-faf-client#1242]
only custom game creates the files in programdata, ladder search does not.
That means installing the client on a clean maching and starting with a ladder match actually creates a crash, since init.lua and other files are missing.

**Comment by 1-alex98** [comment]
Did you test that that it actually does?

**Comment by Rackover** [comment]
This happened two times on two different PCs
The first time, there was no prior installation of the client nor of the game, so programdata files just weren't there. It crashed at launch because of init.lua missing, etc, and I had to host a custom game so that it would download required files.
The second time, there was an outdated FAF patch version since I hadn't played in a long time. Updated the client, tried to match Ladder against askaholic, the game crashed on launch because the patch version was different than the one I was trying to connect to. Had to create a custom games so that the client would update my FAF patch, then ladder worked.

**Comment by 1-alex98** [comment]
Tried on production client downloads .nx2 files and faforever.faf and starts game normally

**Comment by 1-alex98** [comment]
Can not reproduce this

**Comment by 1-alex98** [comment]
Did you do this on the test server?
Because might be something there is configured wrongly...

**Comment by Askaholic** [comment]
I believe this happened when we were testing on the test server, yes.

**Comment by 1-alex98** [comment]
Tell me if you find this happening on prod...

**Comment by Rackover** [comment]
https://i.imgur.com/bj4pknj.png

**Comment by Rackover** [comment]
As this issue is obviously not solved, please re-open.
