### ISSUE TITLE
Parsing rating from title is not a good idea

### ISSUE THREAD

**Issue by Katharsas** [FAForever/downlords-faf-client#1245]
I just tried to host a coop game with title "all welcome 3-4 players " and on second try "3-4 players all welcome ". It seems like the client tries to parse the title and misinterprets the "3-4 players" as rating range, and subsequently sets the rating range to "3-4". If the parsing of desired rating from title is basically `[0-9]*-[0-9]*`, it should be removed. This way of parsing rating from title is WAY too pimitive. Or ut should at least require there to be an "r" or "rating" after the number range.

Client version 0.10.5

**Comment by Katharsas** [comment]
Oh, btw. the games title was "all welcome 3-4 players " and on second try "3-4 players all welcome ". Damn, looks like the client trys to parse the rating range from the title and fails miserably. If the parsing of desired rating from title is basically [0-9]*-[0-9]*, it should be removed. This way of parsing rating from title is WAY to pimitive.

**Comment by Katharsas** [comment]
I just looked at the regex parsing in game.java and i think the best course of action would be to remove it. Since this client is now the official one, most people will be able to use the explicit rating boundary input fields when creating a custom game anyway. This is imo the proper way to set rating bounds.

(Btw: In the Tiles view, the rating bounds are not visible. And rating bounds that are parsed from title have the problem that if they are displayed, they are redundant information since the bounds are also in the title. Also, if average rating of players inside lobby would be displayed, then we have kind of 3 times the same/similar information.)

If you want to me to do that i can make a pull request.

**Comment by Brutus5000** [comment]
It's not a client issue, it's a lack of server support to create a game with a dedicated rating range.
While you can set it in the create game form, right now it has no effect on the server.

**Comment by Katharsas** [comment]
Ok so what you mean is that the rating range feature was built with server support in mind? Ok, but i don't want to remove the feature, i want to remove the automated parsing (title -> form).

Rating range not working in the server is an orthogonal problem for this. Ideally i guess the rating range input fields should be removed/hidden (as well as the column displaying the ranges in the game table) as long as the server doesn't support this anyway. But that is a different issue. I can open one for that as well and maybe also do that.

**Comment by dev-nulled** [comment]
I get the rating feature desires (I'd like the same) - but parsing the game title should not be it (or it should be very specific pattern).  We've had issues where we were saying CPU scores should be under a certain range, and the client would interpret that as a desire to restrict by rank.

**Comment by Katharsas** [comment]
Especially since the client tells people that want to join a game that their rating is too high or too low (even if they can join anyway) based on this inaccurate title parsing.

**Comment by tatsujb** [comment]
removing the parsing could be done but then rating would be handled by java FAF client allone and adding the rating handling would be another uphill climb added to the python client.

**Comment by Katharsas** [comment]
What do you mean. Solving this issue by removing title parsing should not have any effect whatsoever on the python client because this changes nothing at all about the server.

**Comment by tatsujb** [comment]
well, we could implement this the clean way and have rating range as one of the attributes of the hosted game, that's what I'm saying. So, server-side change aswell.

**Comment by Katharsas** [comment]
Oh yeah sure. Would put that in a different issue though since it probably affects quite a few things (and i can easily implement this removal here, i cannot implement a server change currently).

**Comment by Katharsas** [comment]
Same problem again: https://forums.faforever.com/viewtopic.php?f=3&t=17603
I think i will create pull request that
- removes title parsing
- disables/greys out rating range input field (for now) on new game form 
- hides rating range column (for now) in both custom games and coop games list

**Comment by 1-alex98** [comment]
Well better talk it through with e.g. @micheljung otherwise you might end up doing work for nothing

**Comment by Askaholic** [comment]
If you want server support for rating ranges, make a server issue or ping me in slack if one already exists
