### ISSUE TITLE
Call webhook on server full

### ISSUE THREAD

**Issue by sshlio** [FAForever/downlords-faf-client#1247]
I would like to set a simple http POST on server full notfifcation so i can push it to my iPhone with IFTTT. I can issue an PR but i need some tips where to start and which files to modify.

**Comment by Brutus5000** [comment]
The GameFullEvent is posted to the EventBus.
You can subscribe to this event either in the existing method or into a new @Component class with a new @Subscribed method.
See here for the current implementation:  
https://github.com/FAForever/downlords-faf-client/blob/develop/src/main/java/com/faforever/client/fa/OnGameFullNotifier.java

**Comment by 1-alex98** [comment]
push ppl at faf to seploy java-server. This is not something that should be built into client
