### ISSUE TITLE
Crash on start 

### ISSUE THREAD

**Issue by trnapster** [FAForever/downlords-faf-client#1249]
After installing the Client crashes instantly after I start it. I'm seeing the Splash Screen for a few seconds after which Windows tells me that "downlord-faf-client.exe stopped working". It appears that it creates an invisible, unresponsive window called "FA Forever Login".

I have pretty much cleaned all previously existing files including client.prefs and the Folder in ProgramData.

I was asked on Discord to create a Thread Dump. However I was unable to generate one with jstack after the application stopped responding. I was only able to generate one shortly before that. I'm not sure how useful that is though.

[downlords-faf-client.log](https://github.com/FAForever/downlords-faf-client/files/3193359/downlords-faf-client.log)
[thread_dump.txt](https://github.com/FAForever/downlords-faf-client/files/3193360/thread_dump.txt)

**Comment by 1-alex98** [comment]
yeah probably not useful ;)

**Comment by 1-alex98** [comment]
It depends on how much effort you want to put into it I can try to profile it via teamviewer on your machine. Not even sure if that would give us the answer to why this happens?

**Comment by trnapster** [comment]
Fixed it by reinstalling windows. No idea what the problem was
