### ISSUE TITLE
Properly handle errors when game binary update failed

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#1251]
See comments at https://github.com/FAForever/downlords-faf-client/commit/6bfdaa63e4860dc6f6e64729643026f1c428cef1

We really need to understand why this happens, and it does happen because the game process is still running, we should probably offer the user to kill it or abort, rather than just continuing.

**Comment by 1-alex98** [comment]
Well or we check if they actually need to be copied ;) Would also solve this I think

**Comment by 1-alex98** [comment]
Would that also be an option?
