### ISSUE TITLE
On nix systems, maps will not be found if filename case does not match

### ISSUE THREAD

**Issue by johnhce** [FAForever/downlords-faf-client#1256]
On linux/unix systems, file name case is significant.  Map file names with mixed case letters might not be found if the map entry in the replay does not match the file on disk.

**Comment by Wesmania** [comment]
Confirming, it's really annoying.

**Comment by 1-alex98** [comment]
@Wesmania maybe u can help us fix it :D

**Comment by Wesmania** [comment]
Misclick, ofc I intended to say I can take a look :)

**Comment by 1-alex98** [comment]
I belive this was fixed reopen if not so
