### ISSUE TITLE
irc user color suggestions

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/downlords-faf-client#1264]
Please allow users to set colors for user groups (eg all friends in blue and all mods in purple)
changing colors for individual users can be tiring and you can only do it for users who are online atm (unless you edit your client prefs i guess)

having group colors would make things a lot easier - bonus points if you make it so that individually set colors overwrite the user group color so i can make all the mods white and color gieb pink as god wanted him to be

**Comment by dev-nulled** [comment]
The default red for allies chat is almost impossible to read when watching casted games.

**Comment by 1-alex98** [comment]
Not sure what yu mean @dev-nulled
