### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/downlords-faf-client#1267]
![Taskmgr_2019-05-21_21-39-12](https://user-images.githubusercontent.com/10947024/58125505-0283ef80-7c11-11e9-8aa6-930fcaaca4b5.png)
I've heard the gpu is better for mining bitcoins but still...

dfc_windows-x64_0_10_6-RC4
[downlords-faf-client.log](https://github.com/FAForever/downlords-faf-client/files/3204190/downlords-faf-client.log)

**Comment by 1-alex98** [comment]
What does the Ram usage say?

**Comment by speed2CZ** [comment]
I'll check that out next time it happens.

**Comment by 1-alex98** [comment]
Ring me up next time and we can profile the application

**Comment by speed2CZ** [comment]
![ProcessHacker_2019-07-26_13-52-56](https://user-images.githubusercontent.com/10947024/61949953-bbb5cb80-afac-11e9-8798-ade0bcc6b78f.png)
After few hours of running it's spiking to 100% on a single core every few seconds
https://gist.github.com/speed2CZ/23636220d4155f9584fad3fa107b985a

**Comment by 1-alex98** [comment]
1 gigabyte of RAM usage sounds like memory leak

**Comment by speed2CZ** [comment]
So just sitting in a chat doesn't cause this. But going to the vault and searching for a replay. Then it starts happening

**Comment by Katharsas** [comment]
Could be GC being pressured because of memory usage (see https://github.com/FAForever/downlords-faf-client/issues/1104)

**Comment by Katharsas** [comment]
@speed2CZ Can you try the new RC https://github.com/FAForever/downlords-faf-client/releases/tag/v1.0.0-RC11 and check if this has become better?

**Comment by speed2CZ** [comment]
![firefox_2019-11-16_17-32-57](https://user-images.githubusercontent.com/10947024/68996195-332ea400-0897-11ea-853e-eb9914cfe6ec.png)
it's still spiking to 100% on one core

**Comment by 1-alex98** [comment]
version + log

**Comment by 1-alex98** [comment]
+heap dump if newest version
