### ISSUE TITLE
Game is started with previous featured mod loaded

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/downlords-faf-client#1268]
We have several reports via Slack and Forums that games are started with previously played featured mods (Nomads and Claustrophobia confirmed).

The reason is probably the init script not being properly overridden. We need to check that.

**Comment by 1-alex98** [comment]
Ok so I tried and it did not work

**Comment by 1-alex98** [comment]
I hosted a game with only me in it having Claustrophobia  turned on then I started normal faf and all worked as expected in order to further address this we will need a) client logs or b) a more detailed description of what happend

**Comment by Brutus5000** [comment]
This is probably related to the file lock issue of the client (bin folder etc.)

**Comment by 1-alex98** [comment]
So u wanted us to open up a error window if init file can not be overwritten...

**Comment by Brutus5000** [comment]
Here is the forum post with logs: https://forums.faforever.com/viewtopic.php?f=3&t=14865
The user did not mention an error popup.

**Comment by 1-alex98** [comment]
This post is from py client and 2 years old

**Comment by 1-alex98** [comment]
...

**Comment by Brutus5000** [comment]
Check the last answer :P

**Comment by axel1200** [comment]
2014...

**Comment by 1-alex98** [comment]
yes no logs...

**Comment by 1-alex98** [comment]
Not reproducable
