### ISSUE TITLE
desktop shortcut

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/downlords-faf-client#1269]
pls add a tick box to the install wizard to create a desktop shortcut for the client exe

**Comment by 1-alex98** [comment]
Ok this needs to be set in install4j config

**Comment by 1-alex98** [comment]
Needs to be done by @micheljung or @Geosearchef  or one of them might need to give me an install4j license. I dont think I can do it without the UI...

**Comment by 1-alex98** [comment]
https://www.ej-technologies.com/resources/install4j/help/doc/help.pdf page 185

**Comment by 1-alex98** [comment]
Got the license from downlord so might do it soon TM

**Comment by 1-alex98** [comment]
Duplicate #356
