### ISSUE TITLE
Upload to mod storage Post (FAF)

### ISSUE THREAD

**Issue by ilnurzalyatov** [FAForever/downlords-faf-client#1276]
I took as a basis the mod Total Mayhem ( removed it unbalanced units) replaced the HP and the time of construction of turrets.
Now I want to upload a mod in Faf to play with friends.
I changed the name of the mod to Tutal Mayhem 
But at the same time I'm in the Authors of fashion pointed out the one who created Total Mayhem.
But the problem.
when I try to upload the mod comes out error 401 
More on the screenshot.
![Снимок66666666666666666](https://user-images.githubusercontent.com/51294207/58763547-a2704000-8564-11e9-973d-6aeb26e928e1.PNG)
I updated faf myself today.
How to fix ?
[text.txt](https://github.com/FAForever/downlords-faf-client/files/3244936/text.txt)

**Comment by ilnurzalyatov** [comment]
[Новый текстовый документ.txt](https://github.com/FAForever/downlords-faf-client/files/3244940/default.txt)

**Comment by 1-alex98** [comment]
the whole mod

**Comment by 1-alex98** [comment]
Closed due to inactivety
