### ISSUE TITLE
Accept game launch configuration from server as in GW

### ISSUE THREAD

**Issue by Askaholic** [FAForever/downlords-faf-client#1281]
For team matchmaking we will be adding configuration options to the `game_launch` command. The client will need to check if these args are present and set the appropriate command line arguments to FA.

For argument names see this PR: https://github.com/FAForever/server/pull/428/files#diff-51c4c921447c6af4a36cbf90068e05c3

**Comment by 1-alex98** [comment]
There is a branch for GW I think where this was done

**Comment by 1-alex98** [comment]
I think this is something for @Geosearchef he already did the team match make stuff

**Comment by Geosearchef** [comment]
gw_on_ice, I will take a look when implementing teammatchmaking, currently I'm still on the party system.

**Comment by Brutus5000** [comment]
Hmm. We need to check if the server change still works on old clients. I dislike coupling a server release with a client release.

**Comment by Askaholic** [comment]
You are thinking that the extra fields in the message could cause an exception in the client? 

The message still contains the same commands as before, which was just `numgames` I think, so if the old clients ignore extra fields there shouldn't be a problem.
