### ISSUE TITLE
Map IDs do not show in detail window

### ISSUE THREAD

**Issue by CouncillorMorax** [FAForever/downlords-faf-client#1283]
![no map ids](https://user-images.githubusercontent.com/23299209/59161283-c70d7000-8aae-11e9-9164-84d323a15512.jpg)

There is no way of finding the map identification number within the client. This information is necessary for reference to coding management of the vault, among other tasks.

Can that info please be added to that pop-up, detail view window?

**Comment by 1-alex98** [comment]
They are shown in modor btw ...
