### ISSUE TITLE
map search criteria: prop reclaim stats

### ISSUE THREAD

**Issue by badbwoi** [FAForever/downlords-faf-client#1284]
Hey guys,

how about using the prop statistics as search criteria for maps in the map vault.
The FAF editor already calculates the prop statistics for a map..

![image](https://user-images.githubusercontent.com/28671151/59189323-17053900-8b7a-11e9-9af4-c5b104a012d4.png)

..why don't we add the information to the scenario.lua when saving a map in the FAF editor or calculate it while uploading a map (no allowing manual editing). 

![image](https://user-images.githubusercontent.com/28671151/59193744-014a4080-8b87-11e9-8b29-0ccf09b38637.png)

That would enable us to sort maps via "props_total_mass" or "props_total_energy" in the vault.

![image](https://user-images.githubusercontent.com/28671151/59189933-bc6cdc80-8b7b-11e9-88bc-785110b68034.png)

Issues:
_Implementation via FAF editor or map upload?_
Ozonex likes the idea and would add it to the FAF editor if needed. This way values could be changed manually. If we like to avoid that, we should calculate and write the values while uploading a map.

_What to do with old maps?_
Calculate value via script and add values to the db?! If we do like that, we could also use the script to recalculate the values if e.g. prop values were changed.

_Advanced: Calculate total map reclaim (props + units)?_
To get the total map reclaim we could calculate the reclaim value of units as well, but that would lead to problems with adaptive maps (amount depends on settings)

What do you think?

This issue is connected to https://github.com/FAForever/db/issues/195 & https://github.com/FAForever/faf-java-api/issues/320

**Comment by 1-alex98** [comment]
The client is not gonna parse this info evenr ->way to complex so either this gets saved as stats by api or whatever but then this issue is in the wrong repo
