### ISSUE TITLE
Unit tests fail if the developer has a second adapter

### ISSUE THREAD

**Issue by Rackover** [FAForever/downlords-faf-client#1294]
https://i.imgur.com/tWFPP69.jpg
I need to disable my secondary screen via my adapter configuration and then the tests pass. As long as my second screen is active (two monitors), tests fail, else test pass (single monitor)

**Comment by 1-alex98** [comment]
Not necessarily I do have one as well and it woks. probably depends on which side your main screen is

**Comment by Sheikah45** [comment]
Tests were made headless
