### ISSUE TITLE
JavaFX "Error: JavaFX runtime components are missing..."

### ISSUE THREAD

**Issue by Katharsas** [FAForever/downlords-faf-client#1298]
When i use either AdoptOpenJDK 10 or 11 and try to build and start the client locally, i get the following error, like some others:
`Error: JavaFX runtime components are missing, and are required to run this application`

Potential cause, citiation from https://stackoverflow.com/questions/52569724/javafx-11-create-a-jar-file-with-gradle :
> This error comes from sun.launcher.LauncherHelper in the java.base module. The reason for this is that the Main app extends Application and has a main method. If that is the case, the LauncherHelper will check for the javafx.graphics module to be present as a named module:
`Optional<Module> om = ModuleLayer.boot().findModule(JAVAFX_GRAPHICS_MODULE_NAME);`
> If that module is not present, the launch is aborted. Hence, having the JavaFX libraries as jars on the classpath is not allowed in this case.

I don't really understand fully what is going on here, but the proposed second fix works:
Add a new java class with a main method and define that class as entry point for the application. This class must not extend javafx's Application. It just simply calls the Application implementation like this:
```
package com.faforever.client;

public class Main {
	public static void main(String[] args) {
		FafClientApplication.main(args);
	}
}
```

I can make a pull request if you want (tell me).

**Comment by Katharsas** [comment]
Ok, this is kinda funny.
This fix works **ONLY** if i use an Eclipse configuration to directly start the Main classes main method. However, `gradle bootRun` is still broken (same error as before). So the fix kinda works, and kinda not.

(i did change 
```
jar {
  manifest {
    attributes "Main-Class": "com.faforever.client.FafClientApplication",
        "Implementation-Title": "Downlord's FAF Client",
        "Implementation-Version": version,
        "Implementation-Vendor": "Downlord"
  }
}
```
to 
```
jar {
  manifest {
    attributes "Main-Class": "com.faforever.client.Main",
        "Implementation-Title": "Downlord's FAF Client",
        "Implementation-Version": version,
        "Implementation-Vendor": "Downlord"
  }
}
```
)
Seems like I actually need to fully understand that stackoverflow page to know whats going on precisely : (

**Comment by 1-alex98** [comment]
Well putting it on the classpath is kind of cheating we should be able to also put it on the modulepath with gradle

**Comment by Katharsas** [comment]
Ok so when i add
```
bootRun {
    classpath sourceSets.main.runtimeClasspath
    main = "com.faforever.client.Main"
}
```
then `gradle bootRun` also works. But i don't know if this messes with bootRun in a way that it should not. Works however. I don't know enough about modules to talk about how to do it properly the module way. Feel free to take this over from here. At least people can use this fix for now to get local development going.

**Comment by Katharsas** [comment]
I threw together a commit containing the workaround changes:
https://github.com/Katharsas/downlords-faf-client/commit/4d9cf26d980d536a7e1ea296ad5e6d8d4ae42aac
Anybody using IntelliJ will also want to change the entry point in the `.idea` folder but since i don't use IDEA i cannot test it and wont fix that.

**Comment by 1-alex98** [comment]
Something like that https://discuss.gradle.org/t/gradle-doesnt-add-modules-to-module-path-during-compile/27382

**Comment by Katharsas** [comment]
This solution implies using a "modularized" project from what i can see (it defines a module-info.java). However currently, the client does not seem to use modules in any way. Do you guys want to migrate to  a project that fully used modules?

Im currently looking into that. But if you don't want to go full modules yet, i would suggest to use fix until it happens (Because i think mixing non-module and module approach together will probably be hard and annoying, but i will have a look).

**Comment by Katharsas** [comment]
Also the whole sitation is complicated, see
https://github.com/openjfx/openjfx-docs/issues/55
and i am not sure if IDEs and everything are up to the task of going full module (Eclipse just crashed for me when i edited the module-info.java). If this was my project, i would definitely wait for half a year before doing the switch.
Then there is the fact that most OpenJDK documentation/examples use a JDK 12.

Edit: Tried to use the `org.openjfx.javafxplugin` but didn't get anything to work, so for now i think we should use this ugly fix unless somebody else wants to fix this in a different way.

**Comment by Katharsas** [comment]
@axel1200 
Unless somebody else plans to fix this with modules, i need this fix to be merged into master (as soon as i have pull request up). As long as it isn't, i cannot really do any work (or i can, but it is a major pain in the ass and i need to rebase everything i want to work on on this fix and after that un-rebase it for you guys or install a second version of Eclipse just for FAF, both of which is painful).

So i will create a pull request because i don't think we will solve this with modules any time soon.
