### ISSUE TITLE
Anti virus stopping patch

### ISSUE THREAD

**Issue by Zhoot** [FAForever/downlords-faf-client#1301]
I'm getting two errors when I'm trying to launch a game, or join one.
I've tried re-installing multiple times, with admin rights and not. Same as launching the client with and without admin rights.

Here's the first one;
https://pastebin.com/hPVvM4mH

Here's the second one:
https://pastebin.com/HXC1WUY6

**Comment by christopherfowers** [comment]
Working with a friend to troubleshoot his installation. He's having the same issues. Started yesterday. 

I've looking at his permissions settings on the folder for his user and system I don't see anything different from my own configuration. That said my game launches fine.

**Comment by 1-alex98** [comment]
Might be anti virus blocking the downloading of the new patch

**Comment by 1-alex98** [comment]
Something is blocking the client from writing the file C:\ProgramData\FAForever\bin\ForgedAlliance.exe

**Comment by 1-alex98** [comment]
Chances are it is an anti virus

**Comment by 1-alex98** [comment]
@PhilipJFryFAF said since the new patch there were many issues with anti viruses blocking the patching... which software do u use?

**Comment by Zhoot** [comment]
I can confirm. I disabled my Anti-virus and created a game. It downloaded the file and started the game. I then turned my AV on and tried hosting again and it worked.

**Comment by 1-alex98** [comment]
Would be cool if u could say which av u are using

**Comment by 1-alex98** [comment]
And maybe write an email to them so they add the client on the whitelist etc or if u tell me the av author I can try contact them

**Comment by 1-alex98** [comment]
@christopherfowers did u try that as well?

**Comment by Zhoot** [comment]
My apologies Axel, I did think about it but wanted to give you a chance to reply. I'm using AVG Antivirus

**Comment by 1-alex98** [comment]
![image](https://user-images.githubusercontent.com/19996713/59966011-212e1c80-9516-11e9-9e92-2c33b2a4aca9.png)

**Comment by 1-alex98** [comment]
Maybe report as well https://www.avg.com/en-us/false-positive-file-form

**Comment by christopherfowers** [comment]
@axel1200 I am going to work with my friend to see if this might resolve his issues. He is using Avast. I am almost certain that this will be the case given the conversations between you and OP earlier.

**Comment by christopherfowers** [comment]
Also Thank you for looking into this so quickly.
