### ISSUE TITLE
Multiple ping sounds in a row

### ISSUE THREAD

**Issue by bullydozer** [FAForever/downlords-faf-client#1305]
Not a big issue, but it's pretty irritating when you're doing something else on the PC and someone sends multiple PM's and it just keeps spamming that annoying notification sound. One's enough, I know you've sent me messages, don't need a reminder every few seconds. also i heard this was said already, but flashing icon when you get pm'd like with faf would be nice (like it is on python), instead of the small hard-to-notice "2" on faf icon.

**Comment by bullydozer** [comment]
speaking of notifications, i'm still getting "person went offline" pop-ups despite that being disabled. re-enabling and disabling didnt fix it, don't know why it happens but just leaving it here.

**Comment by 1-alex98** [comment]
You can tun of the sound for notifications in the coming release

**Comment by bullydozer** [comment]
I do like having a notification sound, but play it only once even if multiple messages are sent, not every time i get a message.. for instance when someone sends 6 messages in 2 seconds (like happened today lol) i get 6 beeps in 2 seconds
