### ISSUE TITLE
ś instead of 's

### ISSUE THREAD

**Issue by bullydozer** [FAForever/downlords-faf-client#1306]
again very small issue but irritating nonetheless. Idk if others have it, but whenever i try to type 's, I get ś instead, goes for multiple letters tho, not just s. This happens EXCLUSIVELY on downlord client so isn't a problem on my side i think, more something to do with the client

**Comment by 1-alex98** [comment]
Well it has probably something to do with java fx

**Comment by micheljung** [comment]
@bullydozer what's your keyboard layout?

**Comment by bullydozer** [comment]
Qwerty

**Comment by 1-alex98** [comment]
won't fix
