### ISSUE TITLE
Foes can join your hosted games

### ISSUE THREAD

**Issue by VoRGoR** [FAForever/downlords-faf-client#1313]
If you foe someone with 0.10.6-Beta, they can join your game.

In the python client, foes cannot see your game, and so cannot join.

I think since this was was a very obscure feature it was just overlooked, so this would be an *enhancement* , but not a bug per se, but I cannot be sure.

**Comment by 1-alex98** [comment]
Well if u which such a feature it needs to be enforced by the server... So this is not missing but unwanted

**Comment by 1-alex98** [comment]
if the server does not send the games of foes there is not a single line that needs to change in the client

**Comment by VoRGoR** [comment]
> if the server does not send the games of foes there is not a single line that needs to change in the client

You can also join games via other people, sometimes, as a note. But if you think this is better done server-side you are almost certainly right and I will bow to your judgement :P
