### ISSUE TITLE
missing command line switch

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/downlords-faf-client#1317]
If a user deletes the "%s" in the command line switch field in the client settings they effectively break the client -> following error will appear upon hosting/joining a game after that:

```
java.util.concurrent.CompletionException: com.github.nocatch.NoCatchException: java.io.IOException: Cannot run program "/init" (in directory "C:\ProgramData\FAForever\bin"): CreateProcess error=2, The system cannot find the file specified
```

Please don't allow users to break the client by removing the content of the command line switch field

**Comment by 1-alex98** [comment]
Yes we know that but thx for the issue and bringing it t my attention
