### ISSUE TITLE
Rename variable name

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1318]
https://github.com/FAForever/downlords-faf-client/commit/f20ebea6fe2d59248079e4b067be30073c3afbc0#r34071814
![image](https://user-images.githubusercontent.com/19996713/60214988-fa018300-9866-11e9-8e1e-b07d06a2b1a8.png)

**Comment by 1-alex98** [comment]
The question is what do I call it then...?

**Comment by Katharsas** [comment]
RESTORED (like MS does)
https://docs.microsoft.com/en-us/dotnet/api/system.windows.window.windowstate?view=netframework-4.8
