### ISSUE TITLE
Add sort by ladder rating in advanced chat filter

### ISSUE THREAD

**Issue by Cheyans** [FAForever/downlords-faf-client#132]

**Comment by micheljung** [comment]
I still don't get why you would want to do that :P

**Comment by Cheyans** [comment]
I mean my original reason was that usually on ladder you're not supposed to know who is searching, but I mean blocking that functionality because of that seems kind of dumb. So I really don't see a reason not to, especially for only ladder players who are looking for a game and no one is searching which happens a lot during US night times.

**Comment by 1-alex98** [comment]
dont see a reason for it either
