### ISSUE TITLE
LaunchCommandBuilderTest fails if project path contains space

### ISSUE THREAD

**Issue by Katharsas** [FAForever/downlords-faf-client#1323]
during test method `testCommandFormat()`.

This is because (unlike the `defaultBuilder` instance in the same test) it fails to wrap the `%s` part of the format string in double quotation marks. While i could sinply add quotation marks in the test, i think it would be better idea if the `%s` would not have to be wrapped in quotation marks in the first place (the `LaunchCommandBuilder` can do that by itelf just fine), so that there is no possibility to even forget this.

It seems like the regex can properly deal with redundant double quotations which could come from exising scripts that already use double quotations (like [here](https://github.com/tatsujb/installFAFscript/blob/2e21412a41a98d79ddb71c795bb28453123923b4/faf.sh#L750)), probably best to specifically add a unit test for that.

Edit: Looks like it cannot properly deal with triple double quotation marks.
Edit2: Ok looks like fixing that is pretty easy.

**Comment by Katharsas** [comment]
@tatsujb I linked the line of your Linux script above that is affected by this change. This should mean that you can now replace `\"%s\"` with `%s`, but i cannot test this on linux.

**Comment by tatsujb** [comment]
@Katharsas finally got around to testing it.
it does work but : 

- A the default value in that field in a client not touched by my script is still : `"%s"`
- B both with and without the double-quotes works

regardless I'm including this change in my next version. thank you for the pointer! :)

**Comment by Katharsas** [comment]
B) is intended, i don't want to break existing stuff. You don't need to change anything if you don't want to. Its just going to not be necessary anymore.

About A), yeah should maybe be changed. On the other hand, i don't want to open a PR for just that^^
