### ISSUE TITLE
Pop out tabs?

### ISSUE THREAD

**Issue by Cheyans** [FAForever/downlords-faf-client#133]
Not sure if this is a good thing or not, but someone requested the ability to see chat and games at the same time. Maybe a more functional way of doing this is by allowing people to pop out tabs so they can view any tabs at the same time

**Comment by axel1200** [comment]
![image](https://user-images.githubusercontent.com/19996713/27014818-92698cc6-4f00-11e7-8b37-b5de245fc4ce.png)
crazy shit no?

**Comment by micheljung** [comment]
Lovely! Can they be "popped back in"?

**Comment by axel1200** [comment]
You can by closing the Window... I thought about which button or how to popp them back in and i think it is most intuitive to use the close button. I might also enable dragging them back though :#

**Comment by micheljung** [comment]
See also:
https://www.youtube.com/watch?v=q_n23Ah1ftQ

This would fix #256 as well? But we had to make it look less ugly :)

**Comment by micheljung** [comment]
Or https://www.youtube.com/watch?time_continue=21&v=ALYtkXrzHDI which might be the one you used?

**Comment by micheljung** [comment]
And for the record, [this feature has been requested 5 years ago](https://bugs.openjdk.java.net/browse/JDK-8092098) and has most recently be targeted to Java 10 - so not gonna happen in the next few years.

**Comment by axel1200** [comment]
You could drag them back in.

**Comment by 1-alex98** [comment]
Well not really planned and I wanna clean up
