### ISSUE TITLE
Endless ladder search times

### ISSUE THREAD

**Issue by EcoNooob** [FAForever/downlords-faf-client#1342]
Possible issue where new people can't find ladder games having searched for hours. Hard to say there's a bug, could be that just nobody is searching. But I've heard a decent amount of new players complain that they can't ever find a ladder game while searching for hours.

Finally managed to get a log from AtomicTangerine:
[downlords-faf-client-Copy.log](https://github.com/FAForever/downlords-faf-client/files/3363982/downlords-faf-client-Copy.log)

AtomicTangerine: | I've sat here for 2 hours trying to get into a ranked 1v1 and this shit, even in peak hours, wont find me a single game

http://forums.faforever.com/viewtopic.php?f=3&t=17735

**Comment by Askaholic** [comment]
This should go in the FAForever/server repo. Maybe @Brutus5000 can transfer it.

We have been working on this recently, hopefully the last server update will help. We have rewritten the algorithm to be smarter, and we are in the middle of fixing a bug with the new player rating adjustment system that was supposed to make it easier for new players to find matches, but it was not written correctly.

**Comment by 1-alex98** [comment]
I can transfer issue but not to the server repo for unknown reasons

**Comment by 1-alex98** [comment]
oh probably because I have no rights in the server repo

**Comment by 1-alex98** [comment]
just reopen on the server
