### ISSUE TITLE
Server status warning/alert indicator

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/downlords-faf-client#1343]
Add an indicator for displaying warnings/alerts (Ladder broken, game Patch broken, being investigated...)

**Comment by Brutus5000** [comment]
Well in best case you read this from statuspage.io and statuspage is properly hold up to date.

**Comment by Geosearchef** [comment]
Nobody can edit that Page (at least nobody that is actually online)

**Comment by Brutus5000** [comment]
I can edit this page.

**Comment by Geosearchef** [comment]
And you at the moment are not regularly online, downlord seems to have left, none of the other server admins or mods are able to edit the page

**Comment by Brutus5000** [comment]
The online argument is BS. just because people burn FAF while I'm gone for two days (which I already said when I was asked for) doesn't mean I'm not online regularly. We can give access to more people. I don't see the point of this discussion.
How about some constructive ideas?
We need a service independent of FAF server and statuspage offers exactly this.

**Comment by Geosearchef** [comment]
This was not about the current incident. I'm just saying more people should habe access.

About constructive ideas, how about a db entry with message and severity level, a way for mods to update that and display that to clients via api or server?

**Comment by Brutus5000** [comment]
That's a bad idea when we do a server update and the db is down (which happens quite often compared to "ladder broken") and is also way more important to notify about.

**Comment by 1-alex98** [comment]
Well as this converted into a discssion about whether or not to give @Geosearchef access I am closing this. Btw give Geo access if possible he is not gonna break anything XD
