### ISSUE TITLE
exe download

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/downlords-faf-client#1344]
every time a user hosts or joins a game on faf he will download the ForgedAlliance.exe file

i assume the client checks the MD5 value and compares it with the one on the server and since the exe gets modified on the client side after downloading the MD5 doesn't add up which causes the problem

would be nice if users would not have to download the 12MB of exe each time the host/join any lobby

**Comment by norraxx** [comment]
IMHO, this should be solved on HTTP via HEAD request.
Ask server for `Last-Modified`, if date is modified, then download.
Nginx as it is, doesn't compute md5 and create md5 response on server side is not efficient. Even with cache server will compute md5 for all files that users will download. It's hard hit on HDD.

**Comment by 1-alex98** [comment]
What? @norraxx no it is saved in the database XD

**Comment by 1-alex98** [comment]
To be honest it works all the time it is just this time @Geosearchef did the patch and he did not know about the client sided modification i think and did not enter the correct md5 value into the db(it worked before). 
Tho the client sided modification is strange and i dont know what it is good for and we might probably wanna try to get rid of it...

**Comment by norraxx** [comment]
Horrible decision to store data in db :-/

**Comment by 1-alex98** [comment]
It is not really an issue...

**Comment by PhilipJFryFAF** [comment]
so apparently not a client issue - afaik brutus wants to change the way the exe is being deployed which would also solve this issue (i suppose)
