### ISSUE TITLE
Starting ForgedAlliance.exe while downloading exe

### ISSUE THREAD

**Issue by Manfet** [FAForever/downlords-faf-client#1345]
After pressing "play" for 1v1 ranked match the lobby started downloading the exe and while downloading found a game started FA. At this point I was sure this would end up as problem but did not know how to proceed and really after 4 mins the game desynced. But after now reading this other bug (#1344), I am not sure if the old exe really was a problem or not. Still it is probably not the best idea to start the exe while downloading a "new" version of the exe.
Problem occured while Issue #1344 was open as well. Might be related.

**Comment by Sheikah45** [comment]
Should be solved with change to matchmakers
