### ISSUE TITLE
[Feature Request] Display reviews and score for previous versions of mods

### ISSUE THREAD

**Issue by douglasg14b** [FAForever/downlords-faf-client#1348]
This is very much needed for mods that update periodically. As their reviews are all lost, and they can't really stand out anymore, especially compared to older mods that have not been updated in years. It kind of defeats the purpose of reviews if they just vanish when the version is iterated.

The current display hurts mods that are new or updating, since it's hard to distinguish popular, but regularly updating mods from the noise. Especially when the highest rated mods that are features on the vault are just old mods that have not seen updates for years. Uvesto is a good example of this, which I've seen passed over by both myself and friends that are new to FAF because it has no reviews, yet is fairly popular, well made, stable, regularly updated, and highly rated.

**Proposal 1:**

- Compile all review scores into the mod score in the mod vault view.
- Include all review counts as the review count in the mod vault view
- On the mod details modal, display current versions score and reviews separate from combined previous versions
  - Reviews have a small icon with the version# the review was for

**Proposal 2:**

- Display current review score and # of reviews alongside combined score and # of reviews in Mod Vault view
- On the mod details modal, display current versions score and reviews separate from combined previous versions
  - Reviews have a small icon with the version# the review was for

**Example Mod Vault:**

![image](https://user-images.githubusercontent.com/1400380/61164551-27873700-a4cb-11e9-89d8-f2b1a9010eb5.png)

Please let me know your thoughts. I'm a bit passionate about this, since it makes finding decent mods harder than it should be. And is a bit disheartening to see your mods reviews vanish whenever it's updated...

**Comment by 1-alex98** [comment]
Good proporsal. Is some work tho :D

**Comment by Katharsas** [comment]
Why even have reviews for certain mod versions separately? Imo the concept of a 'mod' and verions of that mod should be 1:N and reviews should be related 1:1 with the 'mod' and not the versions. Similar to how Play store or steam reviews work. Multiple scores are just confusing imo.

**Comment by 1-alex98** [comment]
Well maybe the first version was total shit and u wanna be able to get rid of those 🤔

**Comment by Katharsas** [comment]
Creation-date-based weighting of reviews to skew the average towards weighjting new reviews higher?^^
Edit: I guess this is what "recent" reviews are for in steam, so i guess showing two review scores does make sense, if they are clearly labeled.

**Comment by douglasg14b** [comment]
@Katharsas 
I'd say two review scores are understandable. Recent vs Overall. The goal being to prevent a broken version from skewing the scores. To aid in UX, hover-over text should be available to distinguish between the two.

I don't believe it would be difficult to create a weighed score as well if that's a better option. Hell, when I am at my workstation next I could probably fashion such a think from the API. It would be in JS or C# though, but the logic should be simple enough to translate over to Java. The concern there is that it might artificially inflate or deflate some mods scores, the recent vs overall rating would probably be safer.

@axel1200 
I'm familiar with API ingestion, but not with UI's aside from WPF & HTML/CSS. Is the extra work side of this on the UI side, or the API ingestion side?

____________________________________________

Side note. I don't see any fields in the API for keeping track of plays or downloads of a mod. I could have sworn the old client had something like this....
