### ISSUE TITLE
Custom map lists

### ISSUE THREAD

**Issue by Cheyans** [FAForever/downlords-faf-client#135]
[e]MagicDragon: 
ok the idea is for players to be able to build their own map lists and also being able to play a random map from that list. when you join a lobby you can see host's current list somewhere if he wishes/using it (some button maybe). for example i can build my own list of 1v1 maps and just host a game on a random map from that list. or make lists of good 2v2 3v3 etc maps to pick from cause its often a pain to find a cool map to play
16:51

[e]MagicDragon: 
also this could be used for tourneys like WWPC

**Comment by 1-alex98** [comment]
Don't seee this in a forseeable future
