### ISSUE TITLE
Reconnection loop when signing in from two locations

### ISSUE THREAD

**Issue by Askaholic** [FAForever/downlords-faf-client#1351]
The interaction between the client auto reconnection system and the lobby server kicking out old connections when a new signin for a currently signed in user is detected causes the client to go into an infinite loop of reconnecting if two clients are currently signed in as the same user.

We ran into this on the test server when multiple people were trying to sign in with the same username. The first person's connection would get terminated by the server when the second person logged in, causing the first person's client to automatically sign in again which then kicked out the second person's client and so on...

I imagine this doesn't come up very often because of unique ID requirements. But if that ever goes away it would probably be a good idea to NOT auto reconnect if you get disconnected because you signed in from another location.

**Comment by Sheikah45** [comment]
For this it would be good if the notice style was changed to be unique to indicate multiple logins rather than relying on parsing the text of the message.

**Comment by Askaholic** [comment]
We can use the existing "kick" style which I think the client will already handle correctly.

**Comment by Sheikah45** [comment]
Sounds good

**Comment by Sheikah45** [comment]
Will be handled server side
