### ISSUE TITLE
Client can't start from network drive

### ISSUE THREAD

**Issue by BlackYps** [FAForever/downlords-faf-client#1357]
fails with `java.io.FileNotFoundException: \programme\downlord's faf client\jre\lib\security\default.policy (The system cannot find the path specified)`
Apparently the client uses the name of the network drive, in this case "Programme", instead of the drive letter. Of course it then failes to find the file, because that path does not exist.

**Comment by 1-alex98** [comment]
This is an issue with install4j you can open an issue on their repository if u like
