### ISSUE TITLE
crash on start

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/downlords-faf-client#1358]
got a user on discord who cannot get the client to run due to the following error:
[error_dl_client.txt](https://github.com/FAForever/downlords-faf-client/files/3416080/error_dl_client.txt)
[downlords-faf-client.log](https://github.com/FAForever/downlords-faf-client/files/3416091/downlords-faf-client.log)

i tried the following things so far:
- wiping the client prefs in `%appdata%\Forged Alliance Forever\`
- adding an exception to the AV (malwarebytes) for the client exe
- reinstalling the client

i have no idea why this error occurs on the machine of the user so if someone could provide a solution that would be great

**Comment by 1-alex98** [comment]
really strange. That sounds like something edited the ui file(fxml file)...

**Comment by 1-alex98** [comment]
Maybe turn off AV completely

**Comment by 1-alex98** [comment]
Closing due to lack of information
