### ISSUE TITLE
Display ladder queue pop time / Fix ladder 1v1 available match popup

### ISSUE THREAD

**Issue by Askaholic** [FAForever/downlords-faf-client#1361]
The last server update (v1.1) changed the matchmaking system such that now matchmaking happens on a scheduled interval, instead of whenever a player starts searching.

We should add timer somewhere on the ladder1v1 tab that counts down the time until the next pop so people know when it's going to happen. This should help remove some of the mystery behind ranked mode. 

It also means that the logic for sending a "Ladder match available" notification needs to be adjusted a little bit so that you don't constantly get spammed by notifications while sitting in queue.

The `matchmaker_info` message now contains an additional field which is the UTC time (in ISO format) of the next queue pop:
```python
    {
        'command': 'matchmaker_info',
        'queues': [
            {
                'queue_name': 'ladder1v1',
                'queue_pop_time': '2019-07-01T16:53:21+00:00',
                'boundary_80s': [],
                'boundary_75s': []
            }
        ]
    }
```

**Comment by Katharsas** [comment]
@Askaholic Brutus suggested "Next matching in X:XX". What di you think?

**Comment by Askaholic** [comment]
Seems awkward to me. I think `Next round: 2:12` is better. I think you can use the fact that it counts down every second to allow you to remove words, since it's pretty obvious from even just the number what it means. 

If there were more players I would say just put the timer, and no text. But the problem with that is if the timer hits 0 and no game starts, then you still don't know what's going on, and you can't tell if its working correctly or if it's bugged.
