### ISSUE TITLE
Fix failing test on develop 

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1362]
```
com.faforever.client.chat.ChatChannelUserItemControllerTest > testSetChatUser FAILED
    org.mockito.exceptions.verification.WantedButNotInvoked at ChatChannelUserItemControllerTest.java:130
```
After this test failing on develop several times I added @Ignore Annotation but it needs to be fixed in the future.

**Comment by 1-alex98** [comment]
Also all other test from PircBotXChatServiceTest.class do fail randomly. It seems to be the connect method that has issues.

**Comment by 1-alex98** [comment]
Addes @Ignore for the whole class

**Comment by Katharsas** [comment]
Funny because all of those tests probably need to be rewritten anyway for my ChatService refactor^^

**Comment by 1-alex98** [comment]
Yes I hope u are gonna refactor them for good
