### ISSUE TITLE
hide mods

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/downlords-faf-client#1365]
Mods which are marked as hidden in the mod vault are being shown in the java client when you search for them.
They should not be shown when marked as hidden.
Example of such a mod: 
Mod Name: `BrewLAN 0.4`
Mod ID: `4538`

The legacy client does not show such a mod which is marked as hidden

**Comment by PhilipJFryFAF** [comment]
probably same issue as #755

**Comment by 1-alex98** [comment]
like #755 only for mods

**Comment by 1-alex98** [comment]
Somebody remember me I want to do this
