### ISSUE TITLE
Allow https redirect on reading remote preferences

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/downlords-faf-client#1369]
When I configure our reverse proxy to forward all http traffic to https, there is a JSON parsing error. (see here https://github.com/FAForever/downlords-faf-client/issues/1368).

The client needs to be able to follow a redirect.

**Comment by Brutus5000** [comment]
Right now it's broken by design:
https://bugs.openjdk.java.net/browse/JDK-4620571?focusedCommentId=12159233&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-12159233

**Comment by 1-alex98** [comment]
Ehm in the issue it say resolved 2002

**Comment by 1-alex98** [comment]
Fixed in java 4

**Comment by 1-alex98** [comment]
Ah and they agreed to not redirect between protocols...

**Comment by 1-alex98** [comment]
So we have an issue... We should just change the url to https and once we have a way to enforce updates we can one day disable http completely
