### ISSUE TITLE
High CPU/GPU usage when searching ladder

### ISSUE THREAD

**Issue by JeanMars** [FAForever/downlords-faf-client#1371]
Hi,
client has an abonormal high GPU usage when searching for 1v1 ladder (see attached picture):
more than 40% of GPU resources just to animate "searching for "opponent" progress bar.
Note that CPU looks pretty abnormal too (~25%).
I would not expect this kind of resource usage for a search.
Using latest downlord release. Did not check for previous releases.
![faf_ladder_search_cpu_gpu](https://user-images.githubusercontent.com/8044910/62006751-3e718e80-b145-11e9-868b-235ee6d14a44.png)

**Comment by 1-alex98** [comment]
So does it stop when u stop searching?

**Comment by JeanMars** [comment]
Yes, only when searching I can see this high GPU and CPU usage.
When game starts, it stops as well.

**Comment by 1-alex98** [comment]
Funny

**Comment by 1-alex98** [comment]
For me it is 3% usage with ladder search and 0% without

**Comment by 1-alex98** [comment]
But I have some crazy fast cpu

**Comment by 1-alex98** [comment]
https://bugs.openjdk.java.net/browse/JDK-8200239

**Comment by andreasley** [comment]
On some systems, hardware acceleration is used for the UI. I see 25% load (!) on a RTX 2080 when searching for a 1v1 ranked match. If that can't be offloaded to the GPU (depending on hardware and drivers), it's very likely that a CPU core is completely pegged.

**Edit:** Confirmed. Disabling hardware acceleration for the client leads to high CPU usage instead of GPU.

**Comment by andreasley** [comment]
I've tried limiting the framerate to 10fps like this:

```
public static void applicationMain(String[] args) {
    PreferencesService.configureLogging();
    System.setProperty("quantum.multithreaded", "false");
    System.setProperty("javafx.animation.pulse", "10");
    launch(args);
}
```

GPU usage was still over 10% and the animation was very jerky.

**Comment by andreasley** [comment]
Something in JavaFX is just broken. I've tried replacing the `JFXSpinner` with https://github.com/HanSolo/CircularProgressIndicator and the result is almost exactly the same: 30% load on the GPU.

Caching the node doesn't help either and the different rendering pipelines (`d3d`, `es2` etc.) don't make any difference.

Options:
- Hope that some update to JavaFX or drivers makes things more efficient
- Remove the progress indicator altogether
- Replace the progress indicator with a linear progress bar that completes as the clock runs down and is updated once every second

**Comment by Katharsas** [comment]
Maybe just put one of those spinning, circular loading indicators there instead of the bar?
Edit: Oh my bad, thats what `JFXSpinner` is.

**Comment by andreasley** [comment]
> Maybe just put one of those spinning, circular loading indicators there instead of the bar?

Unfortunately, as described in my previous comment, that doesn't seem to help. :(

Either there's a fundamental problem with animations in JavaFX, or something else is going on (e.g. some rendering loop or a driver problem). I'm planning to do some testing with a very basic app to rule that out.

**Comment by andreasley** [comment]
A bare-bones JavaFX application with just an `JFXSpinner` or `JFXProgressBar` already requires 5% GPU. While that's already quite much, it's still considerably less than what we're seeing in the client. Something seems to be exaggerating that effect. Maybe some overlay or other Pane that is hidden but still being rendered?

**Comment by Katharsas** [comment]
Maybe the animation causes all other parts of the GUI to get rerendered as well as the animation or something like that.
Anyway, the solution is probably either using an indicator that is less often updated (could be a custom JavaFX timeline animation) or removing it.

**Comment by andreasley** [comment]
I couldn't find any specific problem. JFoenix and the custom styles (style.css) are fine. Removing hidden panes and elements on that tab didn't have any effect. JavaFX just seems to be fairly inefficient.

Updating less than 60 times per second (or whatever the refresh rate on the user's display is) only slightly reduced CPU load in my tests and will make the animation stutter, which isn't great.

I'm out of ideas. :(

@JeanMars, mind sharing some details about your system (CPU, GPU, display resolution and refresh rate)?

**Comment by JeanMars** [comment]
Yeah sure:
Win10 18362
Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 CPUs), ~3.8GHz
16 GB RAM
GeForce GTX 660
2560 x 1440 (32 bit) (59Hz)
Details here:
[DxDiag.txt](https://github.com/FAForever/downlords-faf-client/files/3934345/DxDiag.txt)
Hope that helps,
Jean

**Comment by 1-alex98** [comment]
When I researched that issue it seemed like this was a java fx issue and there is no solution to it atm. (from what i remember)

**Comment by Brutus5000** [comment]
A solution would be to remove the animation causing this, right?

**Comment by andreasley** [comment]
> A solution would be to remove the animation causing this, right?

Yes.
But we have other progress bars and UI elements that are drawn frequently, so removing that one element improves just that specific case.

In the bigger context, I find it worrying that displaying a simple progress bar with JavaFX puts that much strain on a GPU (assuming that the GPU load readings in the Process Monitor are accurate).
Not that we really have a choice regarding using JavaFX with this client.

**Comment by 1-alex98** [comment]
Yes I also find it pretty unconfusing

**Comment by speed2CZ** [comment]
Current version of the client
After 2 hours of sitting in aeolus:
![Taskmgr_2020-03-16_21-42-42](https://user-images.githubusercontent.com/10947024/76798046-1a93b380-67cf-11ea-9462-da0b79947efb.png)
[downlords-faf-client.log.2020-03-15.0.gz](https://github.com/FAForever/downlords-faf-client/files/4340294/downlords-faf-client.log.2020-03-15.0.gz)
[downlords-faf-client.log](https://github.com/FAForever/downlords-faf-client/files/4340295/downlords-faf-client.log)

**Comment by 1-alex98** [comment]
@speed2CZ your problem is likely unrelated to this issue

**Comment by BlackYps** [comment]
we now have a gif instead of the spinner. So this is solved?

**Comment by JeanMars** [comment]
Yeah, much better now, around 10-17%:
![dwfafgpu](https://user-images.githubusercontent.com/8044910/82094141-c472bc00-96fc-11ea-9a9c-fd5ea16f00b4.jpg)

Nice animation BTW :-)
