### ISSUE TITLE
Support replay IDs in chat

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#138]
People often enter replay IDs in chat, like `#12345`. Currently there is an IRC bot who recognizes this and posts a link in order to download the replay. Instead of this, the client should turn such IDs into links.

Whenever a user clicks on such a link, the client should open the replay in the replay vault.

**Comment by themasch** [comment]
Is there any way the client could detect its a proper replay id instead of just checking for /#\d+/? 
I guess, if possible, we should prevent creating links in messages like "`I'm the #1 supernoob!`" .

**Comment by micheljung** [comment]
Other than checking for whether a replay actually exists (but that should be the case for about numbers 1-3'000'000, we could have a different format like `replay:1234` but that seems less convenient ;) And I think the false positives are negligible.

**Comment by axel1200** [comment]
Look at my PR i don't know why its not shown here, but i implemented a copy Link button and had replay Links being opened by the client and not the browser.

**Comment by micheljung** [comment]
The issue ID needs to be linked in the PR description in order to show up here. Title is not enough.

**Comment by andrewtvuong** [comment]
Can we close this since it's merged

**Comment by 1-alex98** [comment]
well I think it used to work but was removed again in some refactoring
