### ISSUE TITLE
"Show modded games" is not optimal

### ISSUE THREAD

**Issue by tatsujb** [FAForever/downlords-faf-client#1380]
Hiding modded games like "x2 eco + t4 shields + t4 mass gen + x6 regen + a thousand other mods that aren't on the vault" makes sense. these are games that people using FAF as intended won't be able to join anyways.

what would be nice is to change both the name and behavior of that button. ideally you'd have one more checkmark which says "no mods at all" which is not ticked by default plus the current tickbox, renamed to "hide non-featured mods" with it's behavior changed to ...well you get it. 

plus "no mods at all" being ticked would hide the "hide non-featured mods" tickbox.

the motivation for this change is that the added degree of precision will be welcome by most if not all users and also featured mods are basically under siege since the implementation of "show modded games" with the default being off.

new players are joining all the time and see no featured mods in their games list and are left to assume they do not exist.

they will never discover the joy of phantomx of nomads, ect...

I can take a look at implementing this myself if that's appropriate.

**Comment by 1-alex98** [comment]
Dont agree with u there... More buttons seem to be more confusing to me

**Comment by tatsujb** [comment]
I'm fine with the same amount of buttons with behavior of "modded" changed to exclude featured mods. 

that's another solution.

I've got more if you are interested.

**Comment by 1-alex98** [comment]
I think it is good the way it is. And it was intended this way...

**Comment by tatsujb** [comment]
Why? is this turning political or something?

**Comment by 1-alex98** [comment]
no just saying my opinion

**Comment by tatsujb** [comment]
what is your opinion? why do you not wish for featured mod to be visible?

**Comment by 1-alex98** [comment]
for me featured mods are also mods and I personally like the play the original games and only sometimes when I feel funny I play featured mods. And I want the checkbox for me to see only games that are relevant to me

**Comment by tatsujb** [comment]
it's incredibly selfish of you to impose that view onto everybody else especially given you are part of the minority of people who hold that opinion, don't you think you're overstepping bounds by utilizing this role as contributor to the downlord FAF project in a power-play?

don't you care that you're dwindling the featured mods community?

**Comment by 1-alex98** [comment]
Ehm I did not say we can not do it. I am just stating my opinion on it

**Comment by 1-alex98** [comment]
> for me featured mods are also mods and I personally like the play the original games and only sometimes when I feel funny I play featured mods. And I want the checkbox for me to see only games that are relevant to me

The one that suggested that feature also felt this way it is a way to only show "normal" games. It is deactivated by default. And can be clicked if you are not interested in modded games for u to easier find games that are relevant to u.

**Comment by 1-alex98** [comment]
> minority of people who hold that opinion

Well am I?

**Comment by tatsujb** [comment]
> The one that suggested that feature also felt this way it is a way to only show "normal" games. It is deactivated by default. And can be clicked if you are not interested in modded games for u to easier find games that are relevant to u. 


which is why I suggested more configurability. 

Nowhere inside this idea, was a vendetta against featured mods explicitly demanded yet that is what is being applied.

the part where it gets unethical, where a personal bias is applied is in assuming that to mean this : 
 > for me featured mods are also mods

that is a huge leap. and bad faith to feign treating this matter 100% as a semantic issue, thereby ignoring any other possible aspects. the expressed idea and takeaway being that they are not endowed with a considerable playerbase, same as, say, "mass x2" sim mod, when recent stats on the stats thread on the forum showed that that is not necessarily true, all things considered it's way more than the nothing we thought.

I also can tell the "semantic reason" it's not your real stance because you started out by trying to downplay this as a ergonomics issue. So if it's one and the other interchangeably it means your true personal motivation still lies beneath, and I suspect it's personal preference, and you realize all too well, just as I do that that is not ok.

> Well am I?

I mean if you absolutely want to poll this, then fine.

**Comment by 1-alex98** [comment]
Well I dont wanna have this polled globally for sure this is way to unimportant, but I don't mind hearing other peoples opinion on it. 

I just stated my personally opinion, I am not the one that decides what is done and what is not... Well maybe I am when in doubt but if @Katharsas / @Brutus5000  / @Geosearchef 
for example said they/one likes your idea I am not gonna stop u ;) 

So again my **personal** opinion:

-I like changing the default being to show mods
-I am afraid of more check boxes making UI more complicated
- Though we could look into some kind of drop down to hide advanced filter options
- Or configuring the behavior of the checkbox in settings

**Comment by 1-alex98** [comment]
And I am also happy to help you

**Comment by tatsujb** [comment]
>-I like changing the default being to show mods
-I am afraid of more check boxes making UI more complicated
Though we could look into some kind of drop down to hide advanced filter options
Or configuring the behavior of the checkbox in settings

Well that's **much** better! Definitely completely the opposite of :

>I think it is good the way it is. And it was intended this way...

And yeah, I had thought of the dropdown as well. 

So long as the default when you first install and run the client isn't to hide featured mods.

As i stated in the OP, the ideal for me would be to also hide "non-featured" sim mods. 

As those types of hosted games are (somehow, ...still) statistically incredibly likely to not be part of the faf vault and result in a fail to join.

The chasm between the two is monstrous and it's bewildering to me that the two have to share a name. 

Anyways if we can have featured mods visible to new players that's already a huge step forward.

**Comment by 1-alex98** [comment]
it does show modded games by default tho 
![image](https://user-images.githubusercontent.com/19996713/63943270-96b2ed80-ca6f-11e9-865c-6b38af9bceaa.png)

**Comment by tatsujb** [comment]
weird. 

I'm trying to test it on another machine but I'm getting the 

`(java:14939): Gdk-CRITICAL **: 19:21:57.095: gdk_x11_display_set_window_scale: assertion 'GDK_IS_X11_DISPLAY (display)' failed
`

error on my virtual machine.

**Comment by 1-alex98** [comment]
no idea
