### ISSUE TITLE
Client sometimes uses whole CPU and causes game lagging.

### ISSUE THREAD

**Issue by norraxx** [FAForever/downlords-faf-client#1383]
Problem:
Client sometimes eats all CPU cores, what it causes - we don't know.

Possible solutions:
1. find and fix that bug
2. use just half threads on CPU

**Comment by norraxx** [comment]
Maybe this could help: https://stackoverflow.com/questions/39476385/set-cpu-affinity-for-a-java-process-when-started-from-eclipse/39478227#39478227

**Comment by 1-alex98** [comment]
Connect a profiler if that happens and we can see

**Comment by 1-alex98** [comment]
Closing to lack of information
