### ISSUE TITLE
OutOfMemoryError (with heap dump)

### ISSUE THREAD

**Issue by Wesmania** [FAForever/downlords-faf-client#1384]
I got an OutOfMemoryError several times on 1.0.0-RC1. I uploaded a heap dump [here](https://drive.google.com/open?id=10u2J1h4oqqPkb46RmihcCtlFj44UyPYW) if you're interested.

**Comment by Katharsas** [comment]
Looks like a leak of JavaFX dirtyNodes (see https://stackoverflow.com/a/46000029/3552897).
The leaked dirty nodes are `player_card_tooltip.fxml` scene nodes and amount for a retained heap size of 174 MB compared to 493 MB total heap size. Does it happen when you do something specific? Are you using the online replay vault a lot?

**Comment by Wesmania** [comment]
Not really, but I get spammed a lot by this message:
`Loading FXML document with JavaFX API of version 11.0.1 by JavaFX runtime of version 10.0.2`
whenever I mouse over a game on the game list. I'm using jdk 10 installed separately to /opt, so I don't know why it's complaining.

**Comment by 1-alex98** [comment]
So you are sure u ran it with jdk 10? Well we install javafx for linux separately... So the issue here is probably u are using a none oracle jdk which makes the program fall back to the java fx version specified in grade which is set to 11 what is wrong

**Comment by 1-alex98** [comment]
What needs to be done:
Change java fx version in gradle.build to 10

**Comment by Brutus5000** [comment]
Might be resolved by https://github.com/FAForever/downlords-faf-client/pull/1423
