### ISSUE TITLE
1v1 queue join button very hidden 

### ISSUE THREAD

**Issue by Fealthas** [FAForever/downlords-faf-client#1388]
Suggest using some of the dead space off to the side to allow quickly getting into 1v1s. No settings needed, those can be changed in the 1v1 tab.
![Untitled](https://user-images.githubusercontent.com/25716039/62842008-85e73700-bc7c-11e9-8f6a-6ff9601149db.png)

Old client allowed joining in 2 clicks, this new one requires 3, and its slightly more hidden than before.

**Comment by Fealthas** [comment]
Plus going to the play tab always switches back to the custom-game view. If you go 1v1 view -> chat -> play, to goes to custom games.

**Comment by 1-alex98** [comment]
I think having both things separated is good and clean
