### ISSUE TITLE
Chat test are a nightmare

### ISSUE THREAD

**Issue by Katharsas** [FAForever/downlords-faf-client#1391]
REALLY bad things are going on with tests inside the `chat` package. Wether tests succeed or fail depends on wether other tests in that package run and in which order. These dependencies exist across classes, which means execution of some test classes affects tests in other classes. Same goes for log output.

if tests are not executed in certain orders, some tests may hang indefinitely.

The cause of these problems seem to have a lot to do with:
- `AbstractChatTabControllerTest`
- `PrivateChatTabControllerTest`

**Comment by 1-alex98** [comment]
they are
