### ISSUE TITLE
Bad encoding in replay more information

### ISSUE THREAD

**Issue by norraxx** [FAForever/downlords-faf-client#1395]
![bad_encoding](https://user-images.githubusercontent.com/26487134/63223131-3d1a0b80-c1b1-11e9-999c-e2710b4708bf.png)

That unreadable code should be russian.

http://content.faforever.com/faf/vault/replay_vault/replay.php?id=10084790

**Comment by Brutus5000** [comment]
But what is the right encoding?

**Comment by norraxx** [comment]
I think it should be utf8, if it's not, we have to solve it somehow.

**Comment by Askaholic** [comment]
Yes that would be what's called [Mojibake](https://en.wikipedia.org/wiki/Mojibake).

If it's Russian and it isn't UTF8 then I would guess windows-1251: https://en.wikipedia.org/wiki/Windows-1251

I don't think I would call this issue "beginner friendly"

**Comment by norraxx** [comment]
In python, there is `chardet`. Maybe we should use alternative way like: https://stackoverflow.com/questions/3759356/what-is-the-most-accurate-encoding-detector ?

**Comment by Kazbek** [comment]
@norraxx I think that I solved this problem. This is pull request https://github.com/FAForever/faf-java-commons/pull/31 .
