### ISSUE TITLE
information on games

### ISSUE THREAD

**Issue by shalkya** [FAForever/downlords-faf-client#1400]
hover over swords in chat should should give information on the hosted/ being played game.

**Comment by 1-alex98** [comment]
Ehm not sure on that if you click on the player u get it

**Comment by shalkya** [comment]
well it's quite the pain, not really ui friendly to say the least.

ie : you need to open a new chat tab with that person to access the information of the game he is in.
also if you want to check several, you start getting plenty of chat tab.

**Comment by Askaholic** [comment]
Yes I agree, I keep hovering over the swords expecting it to give me context on what those arbitrary icons mean. Like how am I supposed to know what the difference between a yellow sword and a white sword, or a single sword and crossed swords is if I can't hover over it for an explanation?
