### ISSUE TITLE
Problem with logging in client

### ISSUE THREAD

**Issue by ChevalierMinor** [FAForever/downlords-faf-client#1401]
Hi! It's ignoring my pressing the authorization button on logging in. 
Log:
[downlords-faf-client.log](https://github.com/FAForever/downlords-faf-client/files/3529268/downlords-faf-client.log)
[downlords-faf-client.log.2019-08-19.0.gz](https://github.com/FAForever/downlords-faf-client/files/3529269/downlords-faf-client.log.2019-08-19.0.gz)

Trying whatever it be from http://forums.faforever.com/viewtopic.php?f=3&t=17912:
open the powershell (Windows + R -> powershell -> enter) and type
tracert lobby.faforever.com
Results:
![123](https://user-images.githubusercontent.com/54396251/63502622-a01fe100-c4d6-11e9-9099-c6431180fa62.png)

Please help! Reinstalled the client, still it's stuck on that button.

**Comment by norraxx** [comment]
Via your logs i see message like:

`Unfortunately, you must currently link your account to Steam in order to play Forged Alliance Forever. You can do so on <a href='https://www.faforever.com/account/link'>https://www.faforever.com/account/link</a>`

So try to go there and link Steam account to your faf account.

**Comment by ChevalierMinor** [comment]
Thx. Hope it is the solution. But it writes:
![12345](https://user-images.githubusercontent.com/54396251/63505259-e75ca080-c4db-11e9-8985-d800b32bf178.png)

Sorry, but how to delete other unnecessary old account or how to unlink the other account?

Made a thread there:
[https://forums.faforever.com/viewtopic.php?f=3&t=18000](url)

**Comment by norraxx** [comment]
@ChevalierMinor Wait until evening (by CEST), leave some contact on you, maybe join https://discord.gg/97GdKX somebody will help you, or/and make topic on forum  http://forums.faforever.com/viewtopic.php. I'm pretty sure that somebody will appear and help you ;-)

**Comment by ChevalierMinor** [comment]
Thank you! ^_^
