### ISSUE TITLE
Going to the play tab always switches back to the custom-game view. If you go 1v1 view -> chat -> play, to goes to custom games.

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1406]
Plus going to the play tab always switches back to the custom-game view. If you go 1v1 view -> chat -> play, to goes to custom games.

_Originally posted by @Fealthas in https://github.com/FAForever/downlords-faf-client/issues/1388#issuecomment-522252719_

**Comment by Sheikah45** [comment]
I believe this was fixed
