### ISSUE TITLE
Better join game UI

### ISSUE THREAD

**Issue by Katharsas** [FAForever/downlords-faf-client#1417]
I feel like the current "Join game" process is lacking, especially for people stuck in download hell due to low internet speeds / lots of mods.

- Some players have trouble even noticing the download status bar so they wonder if play button is broken
- Its impossible to know how long it will take until downloads are complete
- Its not possible to stop joining game (except by joining another game?), so if you decide you dont want to join any game right now the client will continue useless downloads
- If files are downloaded it is usually not clear to which mod or maps these files belong
- Its easy to loose track of the fact that you are currently joining a game
- Its easy to loose track of the fact that you are currently waiting for ladder game
- Joining another game while a join is already in progress is confusing because the client does not give a clear indication which game is being joined right now
- Its not clear to the user if or how waiting for a ladder game and joining a custom game at the same time conflict with each other

Solution:
When waiting for ladder or joing a game, replace the bottom download indicator with a proper full width area that is seen in ALL tabs that inform the user that he is currently waiting/joining, which game for and show detailed information for downloads and allow him to cancel.

Mockup:
![Mockup_join_bar](https://user-images.githubusercontent.com/1922573/64069088-bea67a80-cc42-11e9-9080-649e4f778650.png)
This mockup needs additional thought put into how download of current file is distinguished from general download progress necessary to join and how waiting for ladder would be displayed.

**Comment by Katharsas** [comment]
Another mockup:
![Mockup_join_bar_v2](https://user-images.githubusercontent.com/1922573/64069169-93248f80-cc44-11e9-9125-a1a054933421.png)

When waiting for ladder, the bar could display the selected factions, the remaining queue pop time an a direct button to cancel. When joining a featured mod, that could be displayed as well (like coop).

**Comment by 1-alex98** [comment]
Important is that the client stays functional while downloading

**Comment by Katharsas** [comment]
Another one:
![Mockup_join_bar_v3](https://user-images.githubusercontent.com/1922573/66953846-824aa480-f05f-11e9-9f4d-e5216afc9ccb.png)

**Comment by Katharsas** [comment]
Closing this because i don't have time for it, might reopen later.

**Comment by Katharsas** [comment]
If https://github.com/FAForever/downlords-faf-client/issues/1523 happens, this would need more thought.
