### ISSUE TITLE
Log Spam: Loading FXML / CSS

### ISSUE THREAD

**Issue by Katharsas** [FAForever/downlords-faf-client#1422]
`Loading FXML document with JavaFX API of version 11.0.1 by JavaFX runtime of version 10.0.2`

`Could not resolve '-fx-text-base-color' while resolving lookups for '-fx-text-fill' from rule '*.label' in stylesheet /build/resources/main/theme/style.css`

`Caught 'java.lang.ClassCastException: java.base/java.lang.String cannot be cast to javafx.graphics@10.0.2/javafx.scene.paint.Color' while converting value for '-fx-effect' from rule '*.card' in stylesheet /build/resources/main/theme/style.css`

`Caught 'java.lang.ClassCastException: java.base/java.lang.String cannot be cast to javafx.graphics@10.0.2/javafx.scene.paint.Paint' while converting value for '-fx-background-color' from rule '*.card' in stylesheet /build/resources/main/theme/style.css`

**Comment by Katharsas** [comment]
See also: #1384

**Comment by 1-alex98** [comment]
I addressed this in one PR lemme think ... PR #1415

**Comment by Katharsas** [comment]
Cannot reproduce CSS errors on PR #1415
