### ISSUE TITLE
Users online/offline state bumps the chatlist, closes context menu.

### ISSUE THREAD

**Issue by mirddes** [FAForever/downlords-faf-client#1429]
**Describe the bug**
if you have a context menu open in the userlist (right click to add friend etc) and someone goes offline/comes online. the menu closes. during active periods this can make it very difficult to add friends etc. 

furthermore the list moves slightly (which may be the cause) this can also make clicking on the intended person difficult during busy times

at the very least i dont want the context menu to close. prefer if it also listed the relevant username, with flag preferred.

it's very triggering.

**Comment by 1-alex98** [comment]
There is a n option to turn the notifications off in the settings

**Comment by 1-alex98** [comment]
It might be broken but then we can fix this

**Comment by mirddes** [comment]
It's not the notifications. The list moves.

**Comment by 1-alex98** [comment]
Hmm thats probably hard to solve :D

**Comment by Wesmania** [comment]
The list moves like mad if you stroll midway or near the end. It makes the user list completely unusable - is there *really* no way to fix this? In Qt lists behave sanely out of the box thanks to their view-model thing, can't something like this be done in jfx?

**Comment by 1-alex98** [comment]
yes i know... too much to do

**Comment by mirddes** [comment]
I figure a simple behaviour change that might be viable. The list does
whatever it wants. As soon as you click on someone in the list they are
selected, their position remains static and the list reorders itself around
them.


I have legitimately opened conversations with the person above AND below
the intended recipient  on numerous occasions.

I have no idea what the code solution is but behaviourly it seems straight
forward with a clear goal.

**Comment by 1-alex98** [comment]
Yes this is nice how u put it but not that easy

**Comment by mirddes** [comment]
The list of users retaining focus as a conversation is opened in a new tab
may be easier to implement and largely have the same effect of reliably
opening conversations with the intended recipient in fewer clicks than
currently occurs.

Friending the wrong person will probably ly still happen though.

An add friend button inside every chat tab would be greatly appreciated.

**Comment by Katharsas** [comment]
Keeping the list static is probably too hard.
But keeping right click menu open (even if the user underneath it moves) might be doable.

**Comment by 1-alex98** [comment]
I already have a solution/hack for it... I am on it

**Comment by 1-alex98** [comment]
just what i did right now is ugly

**Comment by 1-alex98** [comment]
I wanna find a better solution

**Comment by 1-alex98** [comment]
Remember me in some days if u want

**Comment by 1-alex98** [comment]
There we go
