### ISSUE TITLE
Watch live replay time is not set when game starts.

### ISSUE THREAD

**Issue by norraxx** [FAForever/downlords-faf-client#1430]
**BUG 1.**

We see `Watch({0})` instead of time till the moment that i can see the game.

Start chat with axel, ask him to join and start game, see screenshot.

There should be the time

![unset param holder](https://user-images.githubusercontent.com/26487134/64487815-7a693a80-d23f-11e9-8872-7c248bbffb9d.png)

**BUG 2**
There is similar behavior:

We see just white (not gray!) `Watch` instead of time till the moment that i can see the game.

**Comment by 1-alex98** [comment]
do u have exception in log?

**Comment by 1-alex98** [comment]
I think I fixed that bug pls reopen if it still exists
