### ISSUE TITLE
Add an option to log stdout and stderr of the adapter

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/downlords-faf-client#1431]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%245%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/FAForever/downlords-faf-client/issues/1431)

Not everything from the ice adapter is logged to its own log. This is needed for investigating most adapter issues. Please add an option in the settings that enables logging stdout and stderr of the adapter process to the client log.

Basically, revert https://github.com/FAForever/downlords-faf-client/commit/4f695052b67a1a0697f34cc9351b18d3387fcbb9 based on an option and make sure the log level is correct.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- [<img src='https://avatars1.githubusercontent.com/u/5748922?v=4' alt='geosearchef' width=24 height=24> geosearchef](https://issuehunt.io/u/geosearchef) ($5.00)
### Submitted pull Requests
- [#1468 Write to an advanced log (LOGBACK)](https://issuehunt.io/r/FAForever/downlords-faf-client/pull/1468)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/FAForever/downlords-faf-client/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by 1-alex98** [comment]
Where is my bountie XD

**Comment by 1-alex98** [comment]
Just kidding

**Comment by 1-alex98** [comment]
Why not in a seperate file

**Comment by 1-alex98** [comment]
How about this
![grafik](https://user-images.githubusercontent.com/19996713/64529511-5a06b200-d30b-11e9-8fa3-bc713bada316.png)
An extra file with that data
