### ISSUE TITLE
CHANGE BEHAVIOR: irc channel/userlist keeps focus when opening new conversations

### ISSUE THREAD

**Issue by mirddes** [FAForever/downlords-faf-client#1432]
When attempting to open conversations with numerous people it becomes very laboursome switching back and forth between new tabs and the user list in the irc channel. Double click username... New tab opens... Paste discord link and welcome message, switch back to irc, double click Next person, rinse repeat. 

This becomes more laboursome as I go, if I attempt to open all the conversations first, the irc channel will eventually scroll off the left side of the window. Along with the associated switching repeatedly back to the irc channel to select each new user. 

I propose new tabs open silently without stealing focus from the irc channel.... So double clicking on all the people I want to talk to in succession opens numerous tabs... Then I can click through each one pasting the desired communication, closing each tab as I go.

I have been rather successful enduring with the current method and have significantly contributed to the growth of the consolidated aus/nz faf community. As a result this issue has really stuck out and is close to home.

"irc channel/userlist keeps focus when opening new conversations"

**Comment by mirddes** [comment]
Why does android insist on making me seem illiterate? Can someone please correct the spelling of behaviour in the title....

**Comment by Brutus5000** [comment]
As usual this will not match everybodies desired behavior (e.g. when **I** double click a user I expect to end up in the chat tab), so we'd need to make this configurable.

**Comment by Katharsas** [comment]
I don't know about any chat application that does this differently. What are you trying to do? Spam inviting every AUS/NZ user into a discord? The private chat was not made for that kind of usage pattern. And arguably we might not want to facilitate that kind of usage.

**Comment by 1-alex98** [comment]
Well donot really see any point in it or please elaborate how that benefits the average user

**Comment by mirddes** [comment]
I am suggesting g the list of users and the chat tab being independent of
one a other. The new conversation tab does indeed come I to focus but the
user list remains visible at all times within chat.

**Comment by 1-alex98** [comment]
This would kind of go against the idea of IRC right

**Comment by mirddes** [comment]
How? It's just UI
