### ISSUE TITLE
Memory Profiling

### ISSUE THREAD

**Issue by Katharsas** [FAForever/downlords-faf-client#1441]
It needs to be easier for users to
- look at GC activity graph and heap usage
- make a correct memory dump (.hprof)

~~Since we already ship a Oracle JDK, it should in theory already come with VisualVM included~~ (seems like this hasnt been the case since JDK 9). Maybe we can add a button to ~~start~~ download/install VisualVM from the client.

We also need a button to make a memory dump, otherwise people who don't know much about Java profiling will never get how easy it is or send us DMP files. Automated dumps are not usefull because they are very big. We don't want to fill users storage with tons of heapdumps that nobody ever looks at anyway.

**Comment by Brutus5000** [comment]
My idea would be a "create diagnostics button" that generates a heapdump, creates 3 thread dumps in 5 sec delay, zips it and asks the user to upload it somewhere

**Comment by Katharsas** [comment]
Closing this since we found a major leak.
