### ISSUE TITLE
Suggestion: Change default tab to "News"

### ISSUE THREAD

**Issue by VoRGoR** [FAForever/downlords-faf-client#1446]
As the title describes, when opening the client, make it always default to news. 
I suggest this in an attempt to improve communication to the players, and it doesn't change much to the user experience - 1 extra click to move from news to chat or play.

**Comment by 1-alex98** [comment]
there is an option to do so in the setting

**Comment by Katharsas** [comment]
The setting should maybe be disabled by default then.

**Comment by 1-alex98** [comment]
Dont think so but that we can discuss
