### ISSUE TITLE
searching by mod uploaders/authors

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/downlords-faf-client#1447]
**Is your feature request related to a problem? Please describe.**
i would like to be able to look up mods by the user who uploaded them in the faf client

**Describe the solution you'd like**
having a value i can select in the drop down for the mod search that says "mod uploader" or something like that

**Describe alternatives you've considered**
none

right now we can search by "mod author" which is a value form the mod_info.lua which may or may not be the current faf username of the mod creator
but for various reasons it would be useful to be able to search by the mod uploader (which tends to be the mod creator)

**Comment by 1-alex98** [comment]
The right relationship is uploader.login for the name of the uploader. This needs to be added to the SearchablePropertyMappings.class along with a message key and the message key needs to be entered with a message in messages.prperties file.

**Comment by salvationFPS** [comment]
I've implemented this searching in https://github.com/FAForever/downlords-faf-client/pull/1559
but while testing it on main server there was only one mod with uploader entity wich contains login. Others was with uploader wich contains only id or even without uploader entity. So looks like 
not much benefit from this :))
