### ISSUE TITLE
hide mods in recent uploads list

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/downlords-faf-client#1448]
**Describe the bug**
when looking at the list of most recent mods the user can still see mods that are marked as hidden

**To Reproduce**
open the mod vault in the java client
click on "more" for the most recent uploaded mods
you will find mods that are marked as hidden (eg `Swarm`)

**Expected behavior**
The user should not see mods that are marked as hidden (same as when the user is using the search feature)

**Comment by 1-alex98** [comment]
https://github.com/FAForever/downlords-faf-client/issues/1555
