### ISSUE TITLE
Playing custom maps doesn't work if "Documents" folder is not in default path on Windows

### ISSUE THREAD

**Issue by Xericore** [FAForever/downlords-faf-client#1449]
**Describe the bug**
I relocated my "Documents" folder in Windows to another drive. Instead of the default "C:\Users\Xericore\Documents" it was pointing to "R:\Documents". When it is pointing to the default, downloading and playing on custom maps works. When it's pointing to "R:\Documents", it doesn't.

**To Reproduce**
1. Set Documents path to non-default folder.
2. Try to join a game with a custom map.
3. You can enter the lobby, but the chat says: "Player doesn't have maps/xxx.lua

**Expected behavior**
Custom maps should work normally when documents folder is in non-default directory.

**OS**
Windows

**Comment by 1-alex98** [comment]
turn on use default vault location in settings

**Comment by 1-alex98** [comment]
The issue is the game and the client have different opinions on where the documents folder is. I guess this is because game is made for win xp. if the locations differ game can not find maps

**Comment by 1-alex98** [comment]
The issue is i got no idea what the logic of the game is to find out what your documents folder is

**Comment by Rackover** [comment]
https://environmentvariables.org 
Some env variables like HOMEPATH may come in help

**Comment by 1-alex98** [comment]
i tried different way they all come to the same result. I have no idea how the game does it

**Comment by 1-alex98** [comment]
u mean it is HOMEPATH/Documents ? or what for the game

**Comment by Ilnahro** [comment]
The problem occurs if the documents folder is moved after the FAF client is installed. The client keeps writing the maps into the old Documents folder (creating a new folder structure if it has been removed) rather than querying Windows for the current location of the Documents folder and using that.

**Comment by 1-alex98** [comment]
True that is acctually the case and an issue :D

**Comment by Ilnahro** [comment]
Workaround for affected users:
Delete client.prefs in %appdata%\Forged Alliance Forever (loses all client settings) or manually changing the path in that file (using notepad).

**Comment by Xericore** [comment]
I've tried the workaround and can confirm that it works.

**Comment by 1-alex98** [comment]
Not relevant anymore new default is ProgramData
