### ISSUE TITLE
Notify on @name mentioning only

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#145]
Let the user specify if he wants to get a notification if someone types his name into the chat or only if it's preceded by an @.

**Comment by axel1200** [comment]
What to do:
ChannelTabController has the onMention Method which Needs to be rewritten
1. ChatPrefs Needs a new BooleanProperty
2. modify theme/settings/settings.fxml (Attention there is a chat.fxml in the same package but it is not used) and add a Checkbox
3. Bind the checked property to the Preference you made(prefernces are stored on the closure of the stage)
4. in the onMention check for the property of ChatPrefs
