### ISSUE TITLE
server error when downloading mods

### ISSUE THREAD

**Issue by BlackYps** [FAForever/downlords-faf-client#1450]
When downloading some mods it returns an error. Example:

Mod 'Notifications v5.1' could not be installed: java.io.IOException: Server returned HTTP response code: 400 for URL: http://content.faforever.com/mods/Notifications v5.1.v0005.zip

When pasting the URL in Firefox the zip file can be downloaded without issues.
This does not happen on all mods. Tested it with TA music mod and that one works.

Supreme Economy even got bad reviews because people can't download it.

**Comment by norraxx** [comment]
See fixes in newest release candidate https://github.com/FAForever/downlords-faf-client/releases

**Comment by norraxx** [comment]
I would close, seems like duplicate to https://github.com/FAForever/downlords-faf-client/issues/1373

@axel1200 what do you think?

**Comment by BlackYps** [comment]
woops, should have also searched the closed issues, my bad.
I am fairly certain that this is the same issue.

**Comment by norraxx** [comment]
@BlackYps Feel free to download the latest RC version, and test it. You can help us make product better.

**Comment by Katharsas** [comment]
The RC releases are invisible now, so if anybody reads this wondering where to get the RC:
https://content.faforever.com/dfc_windows-x64_1_0_0-RC10.exe
