### ISSUE TITLE
Show game chat in client

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/downlords-faf-client#1452]
When not watching the client while in lobby, it could be nice to display the game chat e. g. as notifications. This can be read from the gpgnet messages.

**Comment by 1-alex98** [comment]
just because it is possible 🤔

**Comment by 1-alex98** [comment]
I am really sorry but it seems funny but I dont really see the benefit. I would speak out against it. I can reopen it if u wanna discuss it with me
