### ISSUE TITLE
Code cleanup of Spring components

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/downlords-faf-client#1455]
* [ ]  Remove all `@Inject` and `@Autowired` annotations from the main modules (not the tests!). They are obsolete and no longer required.
* [ ]  Replace hand-written constructors for these components with Lombok's `@AllArgsConstructor` or `@RequiredArgsConstructor` (where applicable - does not work in rare cases where the constructor is doing more than just assigning `private final` variables)
* [ ]  Replace `@PostConstruct` and `@PreDestroy` methods -> add the interface implementations for `InitializingBean` and `DisposableBean` and move the code to the interface method.

**Comment by marcoebbinghaus** [comment]
I am working on this. Feel free to assign me.

**Comment by Brutus5000** [comment]
@marcoebbinghaus Parts of it are already done in https://github.com/FAForever/downlords-faf-client/pull/1457

**Comment by marcoebbinghaus** [comment]
@Brutus5000 okay, I've already finished/completed this locally. How should I go on now? Wait for #1457 and see if I can add something on top of it?
