### ISSUE TITLE
Catching up to some of Pattogo's clients features

### ISSUE THREAD

**Issue by Petricpwnz** [FAForever/downlords-faf-client#146]
So I was telling wAulex all those neat features pattogos client has and he advised me to post them here. (some of them might already be implemented but i have no idea, also posting all together, waulex said he will sort out himself if needed).
1. http://i.imgur.com/kypNTkp.png - displays a line when your client was out of focus for some time, makes it easy to see which chat you haven't read yet after you've been away.
2. http://www.faforever.com/forums/download/file.php?id=3253 - a nice addition xinonny posted in in the forums thread, showing if the game is ranked or not without joining the game.
3. http://i.imgur.com/9hphskS.png notifications when lobby is full.
4. http://i.imgur.com/5RUcUDB.png small but cool thing, interesting to take some comparisons for people of different rating ranges etc.
5. http://i.imgur.com/fKsR88D.png afaik your client already can filter private games, but being able to filter games with mods like on screen would be a nice addition.
6. http://i.imgur.com/olMeKK7.gif hover image preview for streams, videos and pictures (including gifs, they also ofc get looped).
7. http://i.imgur.com/zPmoowb.png shows people whom you've played with. Though from my experience it doesn't work optimally there, if you have someone from your friendlist being one of those guys you've played with then this friend just jumps to the top of your friendlist and not to the "yellow" people. But im not sure what would be the best way for it to work.

**Comment by micheljung** [comment]
Thank you for your input!

**Comment by 1-alex98** [comment]
I think we got all of that
