### ISSUE TITLE
game not launching

### ISSUE THREAD

**Issue by adamokke** [FAForever/downlords-faf-client#1473]
**Describe the bug** game not running when launching

**To Reproduce** idk

**Expected behavior** game not running

**Screenshots**

**OS** windows

**Comment by Katharsas** [comment]
- Please make sure the path to your FA installation (steam) is correct in the settings
- Please provide `downlords-faf-client.log` from `C:\ProgramData\FAForever\logs`
- Can you go to `C:\ProgramData\FAForever\bin\` and check if you are able to run `ForgedAlliance.exe`? If not, check if launching with steam works.

**Comment by 1-alex98** [comment]
Also please provide logs, u can find them by clicking "show log" in the top right of the client

**Comment by 1-alex98** [comment]
Not sufficent information
