### ISSUE TITLE
allow tournament directors (TD) to set the topic

### ISSUE THREAD

**Issue by shalkya** [FAForever/downlords-faf-client#1474]
Topic has been brought back in #1335 (and it's helping a lot moderators, for pinning important information in the chat)
But it is not possible to change the topic. And allowing this, would permit TDs to display and pin important information in the tournament chat. Like the challonge link for example.
I know that you have implemented a tournament tab, but it's not easy to update information on it.

So i guess you can do it as python do : everyone has the right when they create a new channel (by being the first to join the channel : /join mychannel).
Or you give some kind of priviledge to some people TDs/moderators/councilor so they are the only one to update the topic.

Updating topic in python client is done by doing : /topic mynewmessage

**Comment by 1-alex98** [comment]
ehmm is that a client issue?

**Comment by 1-alex98** [comment]
Oh it is because /commands dont work i see
