### ISSUE TITLE
player dedoubling in the list of player

### ISSUE THREAD

**Issue by shalkya** [FAForever/downlords-faf-client#1477]
![image](https://user-images.githubusercontent.com/11618427/67035430-f184cf00-f119-11e9-997c-2267ce11fcc6.png)

I suspect it has been introduced in the last client update.

**Comment by 1-alex98** [comment]
Well no we did nothing on chat

**Comment by 1-alex98** [comment]
![grafik](https://user-images.githubusercontent.com/19996713/67041425-ef287200-f125-11e9-8ade-ebc1f8103e6b.png)
It does not happen normally. I suspect that it happens in some case where u reconnect and list is not cleared correctly

**Comment by 1-alex98** [comment]
I can probably not do much for u i need a log. Or a way to reproduce this

**Comment by 1-alex98** [comment]
Or are those maybe ppl that rejoined IRC?

**Comment by 1-alex98** [comment]
What am i seeing there friend list? Does it occur everywhere

**Comment by shalkya** [comment]
can't say for now, will give log and update once it happens again.

**Comment by shalkya** [comment]
didn't happen again, i'm closing for now
