### ISSUE TITLE
Update to newer version once java fx bug is fixed

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1485]
Remove workarround and update java fx version once bug https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8232814 is fixed

**Comment by Kazbek** [comment]
Just wanted to inform about the status change.

> Status: Closed
> Resolution: Cannot Reproduce

**Comment by 1-alex98** [comment]
Well seems like a need to file a new report and see why he can not reproduce

**Comment by 1-alex98** [comment]
Well I made a small error in the example source code which I fixed and I resubmitted the issue

**Comment by Sheikah45** [comment]
Fixed in #2051
