### ISSUE TITLE
Issues Starting Games from the FAF Client at all

### ISSUE THREAD

**Issue by Abraxos12** [FAForever/downlords-faf-client#1488]
**Describe the bug**
I cannot create games or join games on the FAF client

**To Reproduce**
Start FAF Client Create or join a game

**Expected behavior**
A crash will happen with this error "Failed to setup initial search path.

Program : C:\ProgramData\FAForever\bin\ForgedAlliance.exe
Cmd line arguments : /init init.lua /nobugreport /log C:\ProgramData\FAForever\logs\game.log /gpgnet 127.0.0.1:62624 /mean 1500.0 /deviation 500.0 /savereplay gpgnet://127.0.0.1:54806/10428471/Abraxos.SCFAreplay /country US /numgames 0

Callstack:
    Unknown symbol (address 0x008cef50)

Last 100 lines of log...

warning: Running "C:\ProgramData\FAForever\bin\init.lua" failed: cannot read C:\ProgramData\FAForever\bin..\repo\faf\init.lua: No such file or directory
         stack traceback:
             [C]: in function `dofile'
             C:\ProgramData\FAForever\bin\SupComDataPath.lua(11): in main chunk
             [C]: in function `dofile'
             C:\ProgramData\FAForever\bin\init.lua(27): in main chunk"

**Screenshots**

![](https://cdn.discordapp.com/attachments/611736002356183077/638195198249271356/unknown.png)

**OS**
Windows 10

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by 1-alex98** [comment]
Try again it was a game patch we did and now reverted
