### ISSUE TITLE
Make sure vanila game can not be selected

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1489]

**Comment by Brutus5000** [comment]
Why not? This needs serious description if it is a major bug.

**Comment by 1-alex98** [comment]
Well if u select the vailla version then the game is bugged because it copies wrong stuff. I mean try it yourself. The game starts but gets stuck in connecting. FAF is a supreme commander forged alliance mod not a supreme commander mod.

**Comment by 1-alex98** [comment]
But it is possible to select supreme commander (vanilla) folder and that should not be

**Comment by Katharsas** [comment]
Also make sure `C:\ProgramData\FAForever` can not be selected (see #1495)

**Comment by 1-alex98** [comment]
True

**Comment by Brutus5000** [comment]
We are talking about the game folder selection? I thought we ensure that there is a file called `ForgedAlliance.exe` which does not exist in vanilla?

**Comment by Geosearchef** [comment]
#1355
