### ISSUE TITLE
Tip of the day

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#149]

**Comment by axel1200** [comment]
We might store Tips in DB with ID, Title, Text and Image(additionally). And display such tips one after another always when opening the client. Preferences are gonna remember what the current tip id(1,2,3) was and show the next one. Of curse you should also be able to hide them in general. 

- [ ] who should set this tips and how (show admins the option to add tips via the client)

**Comment by axel1200** [comment]
https://cloud.githubusercontent.com/assets/19996713/23041415/342e8208-f495-11e6-8920-c65b3f89376c.png

**Comment by axel1200** [comment]
![grafik](https://cloud.githubusercontent.com/assets/19996713/23330675/fbafe118-fb53-11e6-8f0b-1b2bfc0e0858.png)

**Comment by micheljung** [comment]
What's the status of this? :) What kind of tips should we give, client, game, both?
I think that game-tips belong into the game launch screen, which leaves us with client tips and raises the question: are there really enough features in the client so this is sensible?

**Comment by axel1200** [comment]
No actually it is redundant, especially with the new "Quick Tips" in the game
