### ISSUE TITLE
right click user name rework

### ISSUE THREAD

**Issue by shalkya** [FAForever/downlords-faf-client#1491]
that's how it is in python with a friend : 
![image](https://user-images.githubusercontent.com/11618427/67903027-dcbd2800-fb6a-11e9-929b-5a79d0184f9b.png)
and for someone that isn't a friend : 
![image](https://user-images.githubusercontent.com/11618427/67903547-20fcf800-fb6c-11e9-9965-6464ed42fa30.png)

that's how it is in java : 
![image](https://user-images.githubusercontent.com/11618427/67903140-26a60e00-fb6b-11e9-9259-f520d46fe8f2.png)

- Python don't allow to add foe when you are friend to the player (reduce the size of the drop down)
- remove ban/kick for people that aren't mods
- make the "view replays" actually work (always grey out)

**Comment by 1-alex98** [comment]
There are issues fo all of those things mentioned. hence this is a duplicate. I am a little too lazy to link them all.
