### ISSUE TITLE
Supersize text

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/downlords-faf-client#1509]
**To Reproduce**
right click into the title field

![downlords-faf-client_2019-11-17_09-28-40](https://user-images.githubusercontent.com/10947024/69005063-b0e8c300-091c-11ea-9a0f-b9435123514e.png)

**Comment by 1-alex98** [comment]
lol

**Comment by foodlfg** [comment]
1.1.2-RC1
on linux too
but i can find normal ones too. the Password field is ok for example:
![Screenshot from 2020-01-06 20-39-32](https://user-images.githubusercontent.com/3427402/71843770-e6ac5b80-30c4-11ea-802d-1746d1ff074f.png)

**Comment by 1-alex98** [comment]
it seems that dues to the dfference in font 2em on the text field are different font size then for the context menu
