### ISSUE TITLE
ZipBombException for valid maps

### ISSUE THREAD

**Issue by andreasley** [FAForever/downlords-faf-client#1511]
Some map file downloads don't work because of a ZipBombException.

According to https://github.com/FAForever/faf-java-api/issues/326, a ZipBombException occurs if the extracted file is more than 100x larger than the zip file. Unfortunately, this seems to be the case for some real maps. 

**To Reproduce**
Download an affected map from the vault, e.g. `crazyrush.v0003`.
https://content.faforever.com/faf/vault/maps/crazyrush.v0003.zip
(10KB; expands to 1.3MB)

**OS**
Windows

**Comment by 1-alex98** [comment]
LOL true ehmm @Brutus5000 what do we do know? Shall I revert updating java commons. I mean I probably don
t want this in the client right?

**Comment by Brutus5000** [comment]
@axel1200 No, we should adjust the parameters, so it fires not so early. The question is, what are the right ones.
Maybe 20MB rather than 1MB?

**Comment by 1-alex98** [comment]
Well the issue is there are maps in the vault that extract to over 80 MB and the zip is minimal. So maybe I set it to 100 MB on the client side I mean client side does not really have this issue

**Comment by 1-alex98** [comment]
And all uploaded maps are checked for zip bombs anyway

**Comment by andreasley** [comment]
> And all uploaded maps are checked for zip bombs anyway

If the server-side check is the same one, how would one upload a map like the aforementioned `crazyrush`?

**Comment by 1-alex98** [comment]
well it was newly introduced @andreasley

**Comment by 1-alex98** [comment]
Nobody can upload these kind of maps any longer, but it only happens if ppl upload maps that are monotonic, those are incompatible with the map vault rules anyway. This is actually pretty funny because the ZIP BOMB check enforces the map vault rules as a side effect. The rule says use more than three textures
