### ISSUE TITLE
Annoying "ICE debug" dialog window behaviour. Please change.

### ISSUE THREAD

**Issue by xponen** [FAForever/downlords-faf-client#1515]
**Is your feature request related to a problem? Please describe.**
There's an anti-user-accessibility behaviour when if the ingame lobby was launched the FAF Client lobby steal focus from the ingame lobby with an "ICE debug" dialog window, but then it never return user to the ingame lobby automatically or give any option to.  

**Describe the solution you'd like**
Please skip this task of needing to Alt-Tab or search Window's Taskbar to find the ingame lobby and return to it. Please stop it. Even if it is important to notify user of the "ICE debug" options & dialog, please give User options to jump back directly to ingame lobby right away with a button. 

**Describe alternatives you've considered**
A quick fix is just stop with that "ICE debug" dialog. If you still wanted to notify User about this dialog then just do it once, don't spam every game.

**Wanna have the bug fixed quickly?**
Will attempt to do this locally.

**Comment by Brutus5000** [comment]
Take the latest pre-release. The ice adapter was moved to the traybar.
