### ISSUE TITLE
Reconnecting does not refetch coop mission list

### ISSUE THREAD

**Issue by Katharsas** [FAForever/downlords-faf-client#1516]
Take API down, log in, start API, coop mission list will stay empty even if you click reconnect.

**Comment by Askaholic** [comment]
This is because coop missions are loaded once when the controller is initialized:
https://github.com/FAForever/downlords-faf-client/blob/c39aed58e2d2e042bad5196745ac093a58bd8a6c/src/main/java/com/faforever/client/coop/CoopController.java#L150

**Comment by 1-alex98** [comment]
load on display maybe

**Comment by Brutus5000** [comment]
No. Load on display is not a good idea.
The reason why this happens is the caching: https://github.com/FAForever/downlords-faf-client/blob/develop/src/main/java/com/faforever/client/api/FafApiAccessorImpl.java#L487

We should evict all caches on logout.
