### ISSUE TITLE
Add a news banner in a visible place (e.g. "Play" tab)

### ISSUE THREAD

**Issue by Wesmania** [FAForever/downlords-faf-client#1531]
Right now the news tab is something that probably nobody ever visits, especially since the client remembers last open tab at exit. That's really bad when we want to find new developers, for example, or communicate some really important news.

How about we place a one-line news banner in some tab that people visit frequently? One such place could be the custom games tab, since virtually everyone visits it whenever they want to play. We could put it at the bottom of the window, fetch a list of news blurbs from the API and display it down there in whatever eye-catching format we think of.

**Comment by 1-alex98** [comment]
Well I just make the news button glow if there are new news, should work in new versions. I think that is enough

**Comment by Wesmania** [comment]
I have doubts about that - I ignored it very effectively last time I launched the client, and barely even looked at the top item on the list :D 
I think it would be good if important news showed themseves to players without them explicitly looking for news.

**Comment by Wesmania** [comment]
I'd really like for this idea to be reconsidered. My argument is that right now you have to go out of your way to check news, even if we nag players with a highlighted tab. Most people will probably just click it then click back immediately - they don't care about news unless the server is down or the game tells them about a new balance patch. If we put important news in the game tab (say, hunting for new devs), then it'll be displayed to everyone for however long we want, not just the 1% interested in news at the moment.

**Comment by 1-alex98** [comment]
I would agrue well if that's the case lets not annoy them :D

**Comment by Wesmania** [comment]
IMHO some news is important enough for us to warrant potentially annoying some people. How many people have seen that last news post about looking for a sysadmin? I'll go ahead and prepare something clientside.

**Comment by 1-alex98** [comment]
Won't fix
