### ISSUE TITLE
Authenticate with lobby server using API OAuth tokens

### ISSUE THREAD

**Issue by Askaholic** [FAForever/downlords-faf-client#1533]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%245%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/FAForever/downlords-faf-client/issues/1533)

See the related PR https://github.com/FAForever/server/pull/473.

The new command replaces `hello` with a command that works almost the same, except instead of taking a username and password, it takes an OAuth token signed by the API. In order to solve the problem of what to do with the IRC password, we thought of having the server generate a password at random, and send it back to the client.

New auth message:
```json
{
    "command": "auth",
    "token": "<token_string>",
    "unique_id": "<unique_id_string>"
}
```

IRC password response:
```json
{
    "command": "irc_password",
    "password": "<new_irc_password>"
}
```
Some details will still need to be worked out.

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- [<img src='https://avatars1.githubusercontent.com/u/1922573?v=4' alt='katharsas' width=24 height=24> katharsas](https://issuehunt.io/u/katharsas) ($5.00)

### Submitted pull Requests
- [#2175 Use hydra for authorization flow](https://issuehunt.io/r/FAForever/downlords-faf-client/pull/2175)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/FAForever/downlords-faf-client/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by 1-alex98** [comment]
So what u say is that the irc thing still needs to be done right?
I mean atm you just return a random string right?

**Comment by 1-alex98** [comment]
Also what about this 
`"unique_id": "<unique_id_string>"`
I mean when I search it in your PR I can only find it in your tests. What is it for ? Do I need it?

**Comment by Askaholic** [comment]
Right, the client would need to read the password sent back by the server and use it to log in to the IRC. I'm not convinced that it's the right thing to do since I think some people log in with a regular IRC client as well as the FAF client, and also we'd be sending the IRC password over an unsecure channel. That's just the quick and dirty solution that we came up with. I think we should probably put more thought into it.

The unique_id is generated by the `faf-uid` executable. It's not a new field, the client is already sending it with the `hello` command. I just included it here for completeness.

**Comment by 1-alex98** [comment]
https://stackoverflow.com/questions/59455089/oauth-2-spring-resttemplate-login-with-refresh-token

Seems like we need to change some stuff there

**Comment by 1-alex98** [comment]
Well why is the channel unsecure @Askaholic I think this is ok. Well of cause IRC could also accept api tokens. Tho I think it is incrediable hard to hack that into our IRC...

**Comment by 1-alex98** [comment]
So turns out the WebClient is reactive and does not fit at all with our CompletableFutures etc. so I think it is a bad idea to use. And the OAuth2RestTemplate does not support using passed refresh_tokens. So I guess I could go either for hacking in refresh_tokens grant in OAuth2RestTemplate or I just use some other Oauth2 library to do all this. I would aim for keeping the RestTemplate but setting the oauth2 header myself with the help of a oauth2 library.

**Comment by 1-alex98** [comment]
@Brutus5000 do you know anything about this topic. Like how I could get a refresh_token grant? And what would u suggest? Go reactive with WebClient? Or set the header our-selves
 🤔

**Comment by 1-alex98** [comment]
@Askaholic what about reloading session when still in game. The old message had a long called "session" which stored the session id and it was send when reconnecting. Is that still a thing. Also there is a field "localIp" is that still used???
