### ISSUE TITLE
Memory leak when download mods/maps

### ISSUE THREAD

**Issue by WoodyWizard** [FAForever/downlords-faf-client#1534]
**Describe the bug**
When i installing mod, memory fast increasing, and creating many same process(in screenshot)

**To Reproduce**
Steps to reproduce the behavior: Just download mods

**Expected behavior**
No memory leak

**Screenshots**
https://imgur.com/a/0ZjrI8y

**OS**
Linux(Arco Linux(same Arch))

**Comment by betrok** [comment]
Those are threads, they all share same memory pool.
And it does not look like there is a leak actuality, the sequential downloading of several large mods does not lead to further increase of ram usage. JVM just doesn't like to return memory to OS.

**Comment by 1-alex98** [comment]
Can u please tell us what makes u think it is a memory leak? Client crashes? Client freezes?

**Comment by 1-alex98** [comment]
This is way to less info to reproduce or investigate? We need to know how much memory the client uses ? Because u can not see that in the info given

**Comment by WoodyWizard** [comment]
I checked, it's happening always without reason(just when client was launched) but when i try download something, memory leak faster.

**Comment by WoodyWizard** [comment]
> This is way to less info to reproduce or investigate? We need to know how much memory the client uses ? Because u can not see that in the info given

Memory leak going to infinity, and computer just freeze after full filling out( i have 16gb memory)

**Comment by betrok** [comment]
Looks like you misconfigured jvm. Something like absurd `-Xmx` argument.

**Comment by WoodyWizard** [comment]
> Looks like you misconfigured jvm. Something like absurd `-Xmx` argument.

Java don't start increasing memory use, but memory going to void, i didn't find process with same memory usages

**Comment by betrok** [comment]
Weird. Provide logs, maybe there is something.

**Comment by Katharsas** [comment]
But Java doesnt use your memory.
If your screenshot is showing threads (which i think it is), then the java process is using 4,3 % memory according to your screenshot, which is fine?. Note that memory is shared between threads, so the 4,3% is shared between all threads in a single process, so the 4,3% it total amount, not multiplied by thread-count.
Btw its normal for the client to have 30 (up to 150 during startup) threads running. Maybe hide threads in htop to get better picture.

If the screenshot shows processes, then you or a script  on your ystem started the client multiple times, so in that case your installation procedure is probably buggy.

**Comment by WoodyWizard** [comment]
> But Java doesnt use your memory.
> If your screenshot is showing threads (which i think it is), then the java process is using 4,3 % memory according to your screenshot, which is fine?. Note that memory is shared between threads, so the 4,3% is shared between all threads in a single process, so the 4,3% it total amount, not multiplied by thread-count.
> Btw its normal for the client to have 30 (up to 150 during startup) threads running. Maybe hide threads in htop to get better picture.
> 
> If the screenshot shows processes, then you or a script on your ystem started the client multiple times, so in that case your installation procedure is probably buggy.

After installing mod/s, ram usage increasing anyway, but with lower speed than when mod/s was installing.
Ram isn't full exempting after close FAF client.
Screenshot with graphic of ram usage: https://imgur.com/a/Khh65pb
Log: https://gist.github.com/StewieFox/15d2b9daacdf59c9eacb6e06f30abb83

**Comment by Katharsas** [comment]
The client by default will use maximum of about 900 MB total. Is the client using more than 900MB at any time (and pls provide a screen where this can be clearly seen)?

**Comment by betrok** [comment]
Well, OS should free all resources associated with the program after termination of the process.
Even if FaF does something wrong, you clearly have problems outside of it.
