### ISSUE TITLE
Pre game lobby UI freezes when hovering over something

### ISSUE THREAD

**Issue by TheRustyStorm** [FAForever/downlords-faf-client#1536]
**Describe the bug**
When i'm in the pre game lobby, as soon as i hover over my rating, faction or something else, the UI freezes and i need to alt tab to get a fresh view.

**To Reproduce**
Go into pre game lobby and hover over faction, rating, map, or something that usually changes when the cursor is hovered over.

**Expected behavior**
Rating popup, hovered faction highlighted or something

**Screenshots**
![asdf](https://user-images.githubusercontent.com/20505981/71322725-15261600-24cb-11ea-87d3-97c4ebbbdc68.png)

**OS**
Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by norraxx** [comment]
imho this bug belongs to `fa` project

**Comment by 1-alex98** [comment]
Please open in fa project, this is not client related.
