### ISSUE TITLE
Ask user for confirmation when quitting FAF while game running

### ISSUE THREAD

**Issue by andreasley** [FAForever/downlords-faf-client#1549]
Sometimes players quit FAF despite having a game running. This breaks some functionality (e.g. correctly saving replays) and should therefore be prevented.

FAF should ask the user for confirmation when he closes the main window or exits FAF some other way while a game is running.

**Comment by 1-alex98** [comment]
Think we have already an issue for that but I am way to lazy to search it so keep this :D

**Comment by heelix** [comment]
It would be nice if the UI that shows a connection issue does not cover the
exit screen.  Most of the time I've ended up alt-f4ing is due to the clean
exit is covered.

**Comment by 1-alex98** [comment]
What @heelix is describing is a completely different issue tho

**Comment by zwpdbh** [comment]
The button related code is in another library, so we can do nothing unless we change the library.

**Comment by andreasley** [comment]
@zwpdbh Umm....what? Your comment does not seem to relate to the issue I reported.

**Comment by 1-alex98** [comment]
He is right the code for the close button is in a library unless we change this library we can not iplement such a feature

**Comment by andreasley** [comment]
> He is right the code for the close button is in a library unless we change this library we can not iplement such a feature

What close button? Again, this doesn't have anything to do with my issue.

**Comment by 1-alex98** [comment]
The button that defines what happens if the close button is pressed is out of our controll atm

**Comment by 1-alex98** [comment]
Well it is in a library we wann get rid of but did not do so yet
