### ISSUE TITLE
OpenJRE12,13 compatibility on Linux

### ISSUE THREAD

**Issue by foodlfg** [FAForever/downlords-faf-client#1552]
**Describe the bug**
1.1.2-RC1

Tested with and results:
- sudo apt install openjdk-11-jre
export INSTALL4J_JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
**ok** - tested basic functionality only

- sudo apt install openjdk-12-jre
export INSTALL4J_JAVA_HOME=/usr/lib/jvm/java-12-openjdk-amd64
**broken**

- sudo apt install openjdk-13-jre
export INSTALL4J_JAVA_HOME=/usr/lib/jvm/java-13-openjdk-amd64
**broken** - the log in window is not displayed correctly, unusable.
I can force myself through the login window using the keyboard, giving my password but it is still unusable.
log: [downlords-faf-client-open-jre13.log](https://github.com/FAForever/downlords-faf-client/files/4027454/downlords-faf-client-open-jre13.log)

I was told that it should work with Java 13 too. :)

**OS**
Linux, Pop-OS 19.04 (basically Ubuntu 19.04)

**Visuals on JRE13**
![Screenshot from 2020-01-06 20-09-57](https://user-images.githubusercontent.com/3427402/71841855-9df2a380-30c0-11ea-99e6-7e408c5b9a89.png)
![Screenshot from 2020-01-06 20-10-07](https://user-images.githubusercontent.com/3427402/71841856-9fbc6700-30c0-11ea-9d59-0ad6fde5215b.png)

**Comment by 1-alex98** [comment]
I said I allowed those version never said they would work :D

**Comment by Geosearchef** [comment]
There is no support for newer Java versions, no matter which operating system you use, as switching to them will require some effort on the code base.
