### ISSUE TITLE
Need to define Forged Alliance location when not Forged Alliance is not installed in default location

### ISSUE THREAD

**Issue by raider001** [FAForever/downlords-faf-client#1554]
**Describe the bug**
It appears that when Forged Alliance is not installed in the default steam location, it will request specify the location it is installed in every time you open the faf client. Furthermore, downloaded maps do not appear.

**To Reproduce**
Install Forged alliance in a secondary steam location (I had a completely seperate hard drive location for this.)
Run FaF client. - It will request a location.
Define the custom location for Forged aliance - The location is set.
Create a game - Note no maps are displayed.

Repeat these steps to see that the location is not the same

**Expected behavior**
The client is expected to remember the default location and maps will be visible when a game is created.

**Screenshots**
![bug](https://user-images.githubusercontent.com/2744321/71964064-ce674880-324c-11ea-86c9-98b2b9eb05bc.png)

**OS**
Windows 10

**Comment by 1-alex98** [comment]
@raider001 Try use the newest Release candiadate fixed that already but did not realease it yet.
