### ISSUE TITLE
Hidden Modifications Still Show in Java Client

### ISSUE THREAD

**Issue by CouncillorMorax** [FAForever/downlords-faf-client#1555]
I have hidden the two mods shown below in the mordor client more than 24 hrs ago, but they are still showing in certain lists on the java client as shown below. I tested this with a few other modifications and it appears to hold true for other cases:

![image](https://user-images.githubusercontent.com/23299209/71930188-2cbafb00-3169-11ea-8100-a194230707ec.png)

**Comment by msgerbs** [comment]
Saw this in today's patch notes. Apologies for digging an old issue but shouldn't this be handled on the server side and just not send the client hidden mods/maps?

**Comment by Geosearchef** [comment]
No, the client should be able to download hidden maps and mods when joining a game.

**Comment by Brutus5000** [comment]
Technically it's more about replay compatibility than about joining games.
