### ISSUE TITLE
Filter games in play tab

### ISSUE THREAD

**Issue by Androish** [FAForever/downlords-faf-client#1556]
Hey, guys, I have a suggestion for the play tab.

The ability to filter games based on some given criteria and have them show at the top.

I think it would be less than optimal to hide the filtered games all together. But being able to feature the games you would prefer on the top should be without any real downsides.

Thinking something like this:
![filtergames1](https://user-images.githubusercontent.com/16946169/72166340-570af380-33c9-11ea-9c05-a27574f37260.png)

For filtering, you could have something that looks kinda like the search parameters currently used for the replay vault.

Being able to sort for rating probably would require server-side support first.

Like this:
![filtersettings](https://user-images.githubusercontent.com/16946169/72166675-f92adb80-33c9-11ea-86c4-c9dd4aeed6db.PNG)

Another feature that would work great together with all of this is to be able to set a notification for a game hosted that first your filters.

Something like this:
![NotificationSettings](https://user-images.githubusercontent.com/16946169/72166803-368f6900-33ca-11ea-8edb-e46c69e57996.PNG)

**Comment by Androish** [comment]
It seems I forgot that I have already suggested something similar:

 #537

But I still think this is a better suggestion

**Comment by 1-alex98** [comment]
Yes but it needs to be disabled by default ppl already complain mp and mod vault search is far to complex

**Comment by 1-alex98** [comment]
Also given that there are mostly 20 games not sure how much an advanced filter would help

**Comment by 1-alex98** [comment]
I mean we already have some filter options like modded games and prvate games and we can also sort them by criterias

**Comment by Geosearchef** [comment]
I think this doesn't give a lot of features to the average users while consuming a huge amount of development time that could be spent on other things.

**Comment by 1-alex98** [comment]
Won't fix
