### ISSUE TITLE
Avatars and channels incorrectly persist accross login sessions

### ISSUE THREAD

**Issue by Askaholic** [FAForever/downlords-faf-client#1558]
**Describe the bug**
I noticed that sometimes when I'm logged in to the main server, the java client shows me as having an avatar. I think this is because on the test server I gave myself some avatars for testing purposes, and when I log in to the test server, those avatars are associated with my username. If I then log out and log back in to the main server without restarting the client, whatever avatar was selected continues to show up in the chat window of my client even though I don't have any avatar on the main server.

Edit: Apparently this also happens for auto-joined channels, as the client has joined me into the moderator channel automatically as well.

**To Reproduce**
1. Log in to test server where you have an avatar.
2. Log out and log in to the main server with the same username.

**Expected behavior**
The selected avatars and the autojoin channels should have been cleared when logging out.

**Screenshots**
![image](https://user-images.githubusercontent.com/17941539/72585005-c6d12080-3898-11ea-811d-06155f09dc04.png)

![image](https://user-images.githubusercontent.com/17941539/72585030-e0726800-3898-11ea-99cc-c6c9cedd12b9.png)

![image](https://user-images.githubusercontent.com/17941539/72585787-d7cf6100-389b-11ea-9fbc-46014f7f0c01.png)

**OS**
Windows

**Related**
#1419

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by 1-alex98** [comment]
Well yes login and log out are critical not ever thing is cleared there may always be funny effects XD
