### ISSUE TITLE
Add button to open validation tool in browser to map upload

### ISSUE THREAD

**Issue by badbwoi** [FAForever/downlords-faf-client#1565]
Hello,
we are  missing a link to the validation tool (https://api.faforever.com/maps/validate) in addition to the already added mapping rules (https://forums.faforever.com/viewtopic.php?f=2&t=17873) in the upload window/process.
![image](https://user-images.githubusercontent.com/28671151/73301193-9f704100-4212-11ea-9332-167350476ef2.png)

The validation tool helps you check and validate your map name / content before upload. It also provides the right file names and pathing. Currently we are enforcing the rules while uploading a map and return these error messages. But the validation tool is not linked and some people don't know why they get this issue or how to solve it.
![name_restriction](https://user-images.githubusercontent.com/28671151/73297157-58cb1880-420b-11ea-9c43-a13562b260f4.png)
![name_okay_names_given](https://user-images.githubusercontent.com/28671151/73297160-5a94dc00-420b-11ea-85b1-ae4e4fc40a2a.png)

Morax also supports the idea of the link.

### **My Dream Upload**
While writing this I like to bring up a long desired dream of mine ;)
I believe the best error free upload can be achieved when we add the validation tool or its features to the upload process. Here are some ideas..

**improve pre upload process**
Encourage people to validate the map (name, scenario) before upload...

Option A:
1) hit `validate/check map` button (needs to be added next to the `upload map` button)
![image](https://user-images.githubusercontent.com/28671151/73296196-81eaa980-4209-11ea-99d0-1814b145c1a3.png)
2) open link to validation tool: https://api.faforever.com/maps/validate
3) manual user input

Option B:
1) hit `validate/check map` button (needs to be added next to the `upload map` button)
2) select map
3) auto-fill validation tool and show results online

**improve upload process**
1) hit `upload map` button
2) select map
3) auto-fill validation tool and show results in upload window
4) if rules are met and no errors remain the upload is possible, otherwise errors are displayed and explained
4.1) server version: complete rewrite of the map files names (folder, scmap, save, script, options, tables, ...) and path (scmap, scenario, script,...) based on validated `name = "map name"` from scenario.lua -> this way removing `.v0001` (from folder and in files) before upload is not a thing anymore

**Comment by HurricanKai** [comment]
Imo with the new (?) restrictions on naming file names should also be renamed to `-save` `-scenario` `-script` to be consistent

**Comment by Geosearchef** [comment]
I added a button for now, a test within the client would be the best solution, but I advocate against that. It'll take way too much time away from more important developement tasks.

**Comment by badbwoi** [comment]
thx for the button.

what exactly are your referring to?
"a test within the client would be the best solution, but I advocate against that."

**Comment by Geosearchef** [comment]
A system within the client that checks what you have selected and tells you what's wrong would be the best solution. But this takes too much time to be worth it for the small amount of people that use the map upload.

![image](https://user-images.githubusercontent.com/5748922/73396586-001a7f00-42e2-11ea-8c5b-d6f6bbf3dd1d.png)
