### ISSUE TITLE
Update installation fails if ICE adapter is still open

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/downlords-faf-client#1569]
**Describe the bug**
Sometimes the ICE adapter is still running after the client has been closed.
In that case the installation throws an error message that it can not create a file.

**To Reproduce**
Try to keep the ICE adapter alive? - then reinstall

**Expected behavior**
Installation works.

**Screenshots**
![image](https://user-images.githubusercontent.com/6843462/73463852-3f96a900-437e-11ea-9407-4e5115297765.png)

**OS**
Windows

Idea for solution: Maybe the install4j installer can check that no ICE adapter process is running before installation.

Reported by visionik.

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by 1-alex98** [comment]
Interesting

**Comment by 1-alex98** [comment]
@visionik said he closed it manually, so maybe try kill ice adapter if user closes client. Well we warn him already if the game is open i guess so that would be ok if u ask me
