### ISSUE TITLE
Update M&M Top Picks Map List

### ISSUE THREAD

**Issue by CouncillorMorax** [FAForever/downlords-faf-client#1571]
**Please add the following (first list) and remove (second list)**:

Dimension One |   | 11889 |   | Chosen
-- | -- | -- | -- | --
Adaptive Ocean Crater |   | 12109 |   | Nardnerdpower
Adaptive Maridia |   | 12273 |   | Morax
Nehtotkas Twin Maidens |   | 13674 | b | biass
Adaptive Flooded Kyoshi |   | 13857 |   | nardnerdpower
Adaptive Salt and Pepper |   | 13912 |   | svenni_badbwoi
Hymn and Bone |   | 13433 |   | biass
Wildpath |   | 13412 |   | biass
Choir and Flagellant |   | 13422 |   | biass
Adaptive Skadi |   | 13401 |   | svenni_badbwoi
Zordam Xolix |   | 12942 |   | Mikkz
Zerg Canyon |   | 13132 |   | saske_kaske
Saskiya |   | 12453 |   | saske_kaske
DualGap Reborn |   | 12986 |   | saske_kaske
The Lost Diamond |   | 13098 |   | Chosen

**To be removed**:

Summer Duel 8v8 |   | 9386 |   | Modified by ceptin
-- | -- | -- | -- | --
  |   |   |   |  
  |   |   |   |  
Winter Duel 8v8 |   | 8100 |   | Modified by ceptin
Maridia |   | 7264 |   | Morax

**Comment by 1-alex98** [comment]
Maps are added on the server by @Brutus5000

**Comment by 1-alex98** [comment]
Not really a client issue but I will leave it open any way

**Comment by Brutus5000** [comment]
Performed it today, forgot to close the issue

**Comment by CouncillorMorax** [comment]
There is an error in the list where "Lobby Sim EP" #13491 its showing up. 

This map was actually hidden so it's not great to see it in the list.

**Comment by Brutus5000** [comment]
Removed it, must be a copy and paste error?!
