### ISSUE TITLE
map preview is missing marker

### ISSUE THREAD

**Issue by badbwoi** [FAForever/downlords-faf-client#1572]
mystery solved:
"create game dialog" in python client creates a blurred map preview without marker for the selected map. that preview is then used in the dl-client as small preview .

________________

Hey,
I'm wondering for some time now why the marker are **not** displayed in some map previews. ![preview error](https://user-images.githubusercontent.com/28671151/73779782-9260ce00-478d-11ea-9335-1b1d178e19ff.JPG)
v56 = GPG Editor
v60 = FAF Editor (skybox)

Its really strange because some maps were even uploaded at the same day. While it worked perfectly for some maps it did not for the other (e.g. latest _Adaptive Sand Box_ vs latest _Adaptive Monument Valley_).
It seems that adaptive, versioning, map version (v56, v60), year and even the day seems to be irrelevant.

It would be really nice to display the marker for **all** maps.
Its not only a problem on my maps, the vault is full of examples.

Any idea what could be the issue? Cause its working in the python client ...
![image](https://user-images.githubusercontent.com/28671151/73780135-321e5c00-478e-11ea-8697-907cf0c7b170.png)

**Comment by BlackYps** [comment]
I noticed that in the map folder there are sometimes two files mapname.small.png and mapname.large.png
I think the client uses the small ones in the vault. That also explains why some images appear so incredibly blurry.
When you click on the map it loads the high resolution one.

**Comment by badbwoi** [comment]
Good idea, but I'm sure that I uploaded all of my maps without any _mapname.small.png_ or _mapname.large.png_. And some maps have the issue others don't.

And from my mapping perspective those files can be deleted before upload. Because they are in most cases not needed, except special maps. The files get sometimes created when hosting a game, but not in any case.  Maybe they get created if the map is not in the vault yet and the map maker believes they are needed in the map folder?! idk.

**Edit: I tested and the images get created in the map folder only when map is not in the vault!**

**Comment by Katharsas** [comment]
The client uses the big ones for the vault (the server will send small ones anyway if big don't exist) and the small ones in the Play tab for custom games list (when in table view) i think, and each of these exist as version with map marker and without map marker. Where images come from / how they are generated i don't know.
(see [my comment on a memory issue](https://github.com/FAForever/downlords-faf-client/issues/1104#issuecomment-507238558))

**Comment by 1-alex98** [comment]
Well the client only displays the newest version of a map. So not really any need to display the concrete version at least I thought so. I am not at all sure what u mean by markers.

**Comment by badbwoi** [comment]
@axel1200 please take a look at the first post/picture again.

Here is an example for one map:
v1: good map preview picture with marker_(I like)_
v2: good map preview picture with marker _(I like)_
v3: blurred map picture and no marker _(I don't like, decreases map quality at first glance)_

v1 > v2 > v3
![image](https://user-images.githubusercontent.com/28671151/74099359-0ea73880-4b23-11ea-8227-caaa2897451b.png)
The question is, **why is there even a difference in the displayed map preview**. I mean some maps were even uploaded at the same day (some previews have _good map preview picture with marker_ others don't e.g. first post)! It seems to me that _good map preview picture with marker_ was the way to go, but something got changed and leads to 2 different results.

Here a picture from most recent uploads:
2 maps have the problem but there are many more.
and no it don't seems to be related to adaptive ;)
![image](https://user-images.githubusercontent.com/28671151/74100149-f25bc980-4b2b-11ea-8674-5b58d6f365ef.png)

It would be nice -from my pov- to support the work of the map maker and not show a blurred version and no marker.

**Comment by badbwoi** [comment]
for ez reading my main questions:

**1) What is the difference between the dl-client map preview and python-client map preview?**
Because in the python client it works fine for all maps (e.g. Adaptive Salt and Pepper, Adaptive Mars - Mangala Fossa & Adaptive Skadi).
![image](https://user-images.githubusercontent.com/28671151/74111442-b3ae2980-4b94-11ea-9664-851ce65d1b22.png)
![image](https://user-images.githubusercontent.com/28671151/74110549-cec96b00-4b8d-11ea-8602-d6ec552f8b11.png)
and that leads us to ...

**2) dl-client: What causes the difference in the displayed map preview?**
Example map versioning: somehow the marker are not displayed in the latest map upload.
_good map preview picture with marker_ (v1 & v2) VS _blurred map preview picture and no marker_ (v3)
![image](https://user-images.githubusercontent.com/28671151/74110841-0f29e880-4b90-11ea-8b51-eeff3f1111cf.png)

**Comment by 1-alex98** [comment]
So your map is displayed 3 times and thats wrong ???

**Comment by badbwoi** [comment]
No, that are the 3 uploaded map version under "Owned Maps". v1 > v2 > v3
The preview of the latest version (v3, on the right) is different from first two images.
The preview of v3 contains no marker and looks much more burred, compared to v1 and v2 of the map.

**Comment by 1-alex98** [comment]
Well yes I see that and u complain about the preview so that is what this is about right?

**Comment by 1-alex98** [comment]
I see the preview with markers 
![grafik](https://user-images.githubusercontent.com/19996713/74111480-0be52b80-4b95-11ea-8b9b-473de0723c7e.png)

**Comment by 1-alex98** [comment]
There is no preview on the server with no marks I fonder where u get that from

**Comment by 1-alex98** [comment]
Only 2 previews

 "thumbnailUrlLarge": "https://content.faforever.com/maps/previews/large/adaptive_mars_-_mangala_fossa.v0003.png",
            "thumbnailUrlSmall": "https://content.faforever.com/maps/previews/small/adaptive_mars_-_mangala_fossa.v0003.png",

**Comment by badbwoi** [comment]
okay nice. how can I fix this on my side? and how could that be avoided?
because i have this for at least 1,5 years now and reinstalled client in between...

**Comment by 1-alex98** [comment]
ONly this map?

**Comment by 1-alex98** [comment]
Every map?

**Comment by badbwoi** [comment]
see my "2 question post", that are all of my maps. 
but -at least for me- many other maps in the vault have the same problem.

**Comment by 1-alex98** [comment]
I mean so the client does not get this image from the server so it must be the client takes the image from your disk. So it will probably have something to do with you being the author and having the original version of the map installe. Maybe the original version of the map has a preview gernated by the map editor and the client takes that over the others

**Comment by 1-alex98** [comment]
Then please provide a map that is public so I can try to view it in my own client (id or name)

**Comment by 1-alex98** [comment]
Only then can I debug the issue

**Comment by 1-alex98** [comment]
Btw are u sure it is version 3 that is blurred and not version one (adaptive mars)

**Comment by 1-alex98** [comment]
And are u using the newest version of the client ? 1.1.2

**Comment by badbwoi** [comment]
take `Adaptive Mars - Mangala Fossa`
v3 has the issue (on my side)
v1 and v2 get displayed with marker/normaly

really strange that I'm getting some kind of "third" preview. Morax told me he has the same issues. so I was under the impression that everybody does.
got v1.1.2 and no notifications...

**Comment by 1-alex98** [comment]
So when u search for adaptive mars it is blurry and without markers?

**Comment by 1-alex98** [comment]
Not in your "own maps"

**Comment by 1-alex98** [comment]
Also installed it now 
![grafik](https://user-images.githubusercontent.com/19996713/74111773-76976680-4b97-11ea-8d71-c709c73c2569.png)
still has markers

**Comment by 1-alex98** [comment]
On the other hand some other maps are missing previews. 
![grafik](https://user-images.githubusercontent.com/19996713/74111829-b9593e80-4b97-11ea-89a4-311ba0a08109.png)

**Comment by badbwoi** [comment]
okay so v3 seems to work for you. twin maiden has no marker for me.
lets compare the map vault ;)
![image](https://user-images.githubusercontent.com/28671151/74111857-fe7d7080-4b97-11ea-9949-cc23923a1000.png)

**Comment by 1-alex98** [comment]
But it has nothing to do with the client. There are 2 versions of the preview on the server small and large. The small one has no markers for some maps:D The large one always has(as it turns out) . If u open preview the large one is shown. 
![grafik](https://user-images.githubusercontent.com/19996713/74111856-fe7d7080-4b97-11ea-88cd-d2fa427e6e24.png)
So the reason the py client has markers is probably becuase it always uses the large one( which is not what we wanna do, because it saves memory to take the small one).

**Comment by 1-alex98** [comment]
And to be honest they all have markers just in some cases it is almost impossible to see them because resolution is low

**Comment by 1-alex98** [comment]
And background is bad

**Comment by 1-alex98** [comment]
Further the generation of preview images is done in the faf-java-api and I think the code is in faf-java-commons.

**Comment by badbwoi** [comment]
okay, then it would be nice if all previews would look the same -maker wise- for the same map size xD

Is the only difference the (missing) marker in the small preview? Because it looks really bad compared to v1 and v2... https://user-images.githubusercontent.com/28671151/74110841-0f29e880-4b90-11ea-8b51-eeff3f1111cf.png

**Comment by 1-alex98** [comment]
Yes i just noticed agan I dont have any blurry map previews like u do 
![grafik](https://user-images.githubusercontent.com/19996713/74111952-ea863e80-4b98-11ea-8cea-7397190eba6b.png)

**Comment by 1-alex98** [comment]
look at your version of it

**Comment by 1-alex98** [comment]
Do u have Adaptive alt and pepper installed?

**Comment by 1-alex98** [comment]
Can u open detils and make a screenshot?

**Comment by badbwoi** [comment]
hopefully many others will see it like you... most of the time I have all my latest maps installed
my view on my map versions...
![image](https://user-images.githubusercontent.com/28671151/74112000-5c5e8800-4b99-11ea-83b3-f0751088ae3e.png)

**Comment by badbwoi** [comment]
do you mean this? 
![image](https://user-images.githubusercontent.com/28671151/74112024-9039ad80-4b99-11ea-8483-e57141d593d8.png)

**Comment by 1-alex98** [comment]
Well u can go delete C:\ProgramData\FAForever\cache\maps and see if that changes something I think it will, because if the images are not from the server they need to be from somewhere else

**Comment by 1-alex98** [comment]
But dont you notice all the maps that are blurry they are mostly from you right?

**Comment by 1-alex98** [comment]
Well not only u also see Paradise bay bluyy which is from Neroxis

**Comment by badbwoi** [comment]
most of my maps, but not all.
but I get it also on maps from other authors.
![image](https://user-images.githubusercontent.com/28671151/74112209-ee1ac500-4b9a-11ea-989c-1e44c97f2635.png)

hey, you indeed solved it! vault is looking great again ;)
![image](https://user-images.githubusercontent.com/28671151/74112264-5f5a7800-4b9b-11ea-8f2a-290810ec95d6.png)
thanks a lot for you time and help!

now I know what to do. final question: should it be cleared by default more often?

**Comment by 1-alex98** [comment]
So let's conclude:
For some maps there are no markers in the small preview that seem to be mainly old maps where there used to be a different method to generate such previews. But you(not me) also see some maps blurry which are not and accutally have marks in the small version that is on the server. Since you dont seem to be using the images from the server u must be using some from the cache. So my prediction is if you clear the image cache the blury is gonign away(only images will stay that are on the server in the version without markers, can not fix that).

So the question that is left is how the fuck did the blury ones get into the cache. Well I know where they come from. In the map folder its self there is an image (the blury one) 
![grafik](https://user-images.githubusercontent.com/19996713/74112321-ec9dcc80-4b9b-11ea-9c69-493ee5450939.png)
The question that remains is in which cases are those images added to the cache?
And then well we should fix that they ever make it into the cache....

**Comment by 1-alex98** [comment]
Not sure if those images are the cause tho 🤔 if u look at your screenshot and the image they seem to be a lot different tho.

**Comment by 1-alex98** [comment]
It might also be the python client that generates those images and puts it int the cache that also the java client uses don't know. Somebody is putting this images to the cache tho.

**Comment by 1-alex98** [comment]
I for example dont use the py client at all, so would explain why u have such images and I dont

**Comment by 1-alex98** [comment]
Would be worth a try to:
1. clear the cache
2. Open py client browse the vault download some maps by joing games
3. watch those maps in java client, see if they are blurry 🤔

**Comment by badbwoi** [comment]
nice summary and good point about python client.
I was thinking its maybe related to the FAF editor.
anyway, but I need to sleep now and will answer/test that tomorrow.

**Comment by 1-alex98** [comment]
Also there seems to be a difference between loading a map in the vault and from disk. Not sure if the differnece is an issue:

So second thing one could do to try and reproduce it is:
1. clear image  cache
2. Install map manually or via py client
3. Select that map in the create game dialog open a game (close it right way afterwards)
4. Only then look at it in the vault and see if it is blurry. ( do not pen vault tab before)

**Comment by 1-alex98** [comment]
I would put my money on the second thing

**Comment by badbwoi** [comment]
100% reproducible if I do steps 1-4 :)
perfect, mystery solved!

Beside the manual fix, it would be nice to "auto delete" the wrong content for cross client user like me. But its not a huge bug, so no idea if effort and result are in a good proportion.

**Comment by 1-alex98** [comment]
Well let's see what I can do, maybe I check fr the version being 1.1.4 and then and only then I clear the cache

**Comment by badbwoi** [comment]
thx a lot @axel1200
