### ISSUE TITLE
onedrive is massive cancer

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/downlords-faf-client#1580]
**Describe the bug**
The client wants to install content from the vault (mods and maps) in the onedrive folder for some reason

**To Reproduce**
use Windows10 combined with onedrive and get a fresh install of the client (with new client.prefs)

**Expected behavior**
the client should not use onedrive -> it should use the regular user folder instead (which is where the game is looking at as well)

**OS**
Windows

I know that we have a fallback location in programdata but users have to turn it on manually and it's just massive cancer that we try to store (potentially) lots of data in their cloud storage for no reason
would be nice if the way we check for the user folder was changed in a way that never picks up onedrive altogether

**Comment by 1-alex98** [comment]
Well it was intended that the client turn on this option on its own but I guess that does not work then

**Comment by Katharsas** [comment]
Which folder are we speaking about here?

**Comment by danfoster** [comment]
Could you explain how to enable this fallback location in `%programdata%`?

Also, since I'm suffering from this problem, please let me know if I can provide any useful debugging info.

**Comment by 1-alex98** [comment]
in settings

**Comment by Sheikah45** [comment]
vault fallback now enabled by default
