### ISSUE TITLE
ICE adapter sometimes not shutdown

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/downlords-faf-client#1582]
**Describe the bug**
The ICE adapter is not shutdown if the client fails to launch the game due to an exception.

**To Reproduce**

1. Delete the ForgedAlliance.exe in C:\ProgramData\FAForever\bin (or whatever path you configured)
2. Create an empty file and keep a write exclusive lock on the file
3. Try to host a game: The client will try to download the file, but this will fail due to the write lock.

You can iterate step 3 as many times as you want, each iteration gives you a new lingering ice adapter process.

**Expected behavior**
If the client can't launch the game, kill the ice adapter process.

**Screenshots**
An armada of renegade ICE adapter tray icons.
![grafik](https://user-images.githubusercontent.com/6843462/74611007-844d6e80-50f8-11ea-9a24-e7e779876f98.png)

**OS**
Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by 1-alex98** [comment]
Can not fully reproduce if I close the client however the ice adpter closes with it
