### ISSUE TITLE
GameInfoMessage: gameType does not exist

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/downlords-faf-client#1583]
**Describe the bug**
The variable `gameType` in the class GameInfoMessage is unused and does not seem to be part of the server protocol. Thus it should be removed.

https://github.com/FAForever/downlords-faf-client/blob/develop/src/main/java/com/faforever/client/remote/domain/GameInfoMessage.java#L28

**Comment by Sheikah45** [comment]
Fixed in 182fedddb7883581ce53079fa98b198e55966698
