### ISSUE TITLE
Follow player

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#159]
Allow to follow a player; if a player joins a game, the user joins the same game.

**Comment by Cheyans** [comment]
maybe we should form groups instead and it opens a separate chat channel for them

**Comment by micheljung** [comment]
Groups (or as they're commonly called, "Parties") would be nice, however they'd need server-side support. Following a player is almost the same and we can do it client-only (for now). People can always create new chat channels, if desired.

**Comment by Cheyans** [comment]
Softly is working on the matchmaker, maybe we can work with him to create a grouping system that will work in both custom games alongside the matchmaker http://forums.faforever.com/forums/viewtopic.php?f=45&t=11400

**Comment by micheljung** [comment]
Good thought, however you can't really prevent it since the information which game you're in is always shared.

**Comment by KaukaHan** [comment]
I think this can be closed. TMM is going to solve this. As for custom games: if a friend joins a game you get a notification and can join that game either by clicking on the notification or rightclicking in the chat tab. i regularly play with a friend and dont feel like this is a problem right now and even less when TMM is expanded to more than 2v2s.

**Comment by Sheikah45** [comment]
I agree
