### ISSUE TITLE
Close issues get rid of 300 issues

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1593]
Well let's face it we have way to many issues. Almost everybody lost track. There are tons of duplicates and so on the main reason being that nobody can know 300 issues by heart. Also it gets way to hard searching them in 13 pages of issues. And let's face it I am never gonna make it beyond page 4 everything beyond that is never ever gona be looked at again.

So my policy is gonna be closing issues pretty harshly, if the issue is:

- A suggestion or a feature request I don't agree with
- A none reproducable bug
- Outdated and is not responded to
- Too much work to be done in a foreseeable future

So ppl are gonna complain. Who are u to decide what features are gonna make it. Well if there is a feature you like and I closed it, search another dev that thinks otherwise that agrees and agrees to implmenting it and I won't close your issue again (given this feature is no harm to the project). 

Thank you for your understanding

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Brutus5000** [comment]
The maintainer has the right to decide if a feature is worth being taken into the codebase, as he is the person who has to live with the consequences.

You have my full support on this.

**Comment by 1-alex98** [comment]
Well maybe I closed one or two issues that I was mistaking for but if so ppl will reopen them. I was being attack before for closing feature requests so I just made that issues so if anybody complains I will just drop this link.
