### ISSUE TITLE
Phantom Nomads Featured Mod

### ISSUE THREAD

**Issue by mirddes** [FAForever/downlords-faf-client#1598]
I really want to play phantom nomads with a full 16 player lobby
Marlo made the mod in 10 minutes. it takes way longer to explain to each person how to manually install (and DEACTIVATE) the mod. it works really good.

I would greatly appreciate having phantom nomads as a featured mod so that the vault automatically installs it. nomads would benefit from the greater exposure a whole additional menu item on the game creation screen would provide.

I suppose there are other featured mod combinations that could easily be implemented, i hear marlo has recently made claustrophobic murder party for a tournament.

manually installing it sucks., it doesn't currently get it's own menu item, is the default until deactivated.

**Comment by 1-alex98** [comment]
This is not a client issue

**Comment by mirddes** [comment]
That's why its marked as a feature request and not an issue. Where is the
correct place to post this if this isn't it?

**Comment by mirddes** [comment]
Last time I checked, selecting game mode is 100% a feature of the client.

**Comment by 1-alex98** [comment]
Well that is a good question XD No it is not the game mods are listed in the database and are sent by the server

**Comment by 1-alex98** [comment]
Well database repo I guess but a featured mod normally needs to be approved and you would probably go to ZUlip and talk to the game councilor

**Comment by mirddes** [comment]
Thank you.

**Comment by Brutus5000** [comment]
There is no way to combine different featured mods as of now. We have a similar issue with nomads coop (see discussion here https://github.com/FAForever/db/pull/196). We'd need to have dependency some sort of dependency resolution, but that would add a lot of complexity.

**Comment by 1-alex98** [comment]
That's kind of why I said db repo ;)
