### ISSUE TITLE
Online Replays Vault: Add option to search for different players in the same game

### ISSUE THREAD

**Issue by FemtoZetta** [FAForever/downlords-faf-client#1610]
When combining criterias with "and", you only get games where the same player is called name1 and name2, which obviously doesn't exist, so it never has any results.

When using "or", you get games with both players, but also games where the players were alone.

So at the moment it's impossible to only search for games with both players in them.

**Comment by bukajsytlos** [comment]
This has to be addressed in API first and I think it will be pretty hard to
do.

**Comment by Brutus5000** [comment]
Yes. Unfortunately a relational database makes queries like this almost impossible after a certain size. The table that contains the players in a game is the biggest we have and contains over 10 million entries.

building a solution in the client (e. g. query both players individually and then only show distinct results) would require ugly hacks to the current vault code.

So I do understand the request, yet it won't come.

**Comment by bukajsytlos** [comment]
I am sorry, but after investigation, this is reallllly hard to do. It would require fundamental rework of the underlying framework.
