### ISSUE TITLE
Highlight Links in Mod vault and make them clickable

### ISSUE THREAD

**Issue by whaleberg** [FAForever/downlords-faf-client#1615]
**Is your feature request related to a problem? Please describe.**

As a new player it's hard to understand from a lot of the mod descriptions either what exactly the mods do or how to use them.  There are also multiple versions of many mods with no clear recommended version.  Some mods have links in their description text, but the links aren't clickable, and the text isn't selectable or copyable which makes them annoying to follow.  

**Describe the solution you'd like**
It would be nice if at least the recommended UI mods had more documentation filled out about them.  A description field is a good start, but they could really use a bit more documentation.  Useful additions might be things like a more detailed description of what they do, what hotkeys they enable, how to activate their features, etc.  
If mod's documentation is primarily maintained somewhere else, it would be good to have a clickable link to access it.  (To a forum thread, github repo, etc) 
 It would also be helpful to have screenshots that demonstrate what the mod looks like in action.   

It's not clear to me if the problems are with mod authors not putting writing documentation or with the UI not being able to display links correctly and not providing the right fields to enable more detailed documentation. 

**Describe alternatives you've considered**
A simple improvement would be adding link fields to allow mods to link to external doc.  It seems like most have a forum thread for announcements and a github repo where they live.  Not having to google around for those would be useful.

**Comment by 1-alex98** [comment]
This might not be the right repo for your suggestion. If you want a link that can be added to the mod this needs to be done in db and java-api. If however you only want to highlight links and make them click able then this is the right repo, please then rename your issue accordingly

**Comment by whaleberg** [comment]
Yeah, I wasn't sure if this was the right place or not.  If I wanted to help add documentation to mods where would I go to do that?  It wasn't clear to me where the mod data is actually stored.

**Comment by 1-alex98** [comment]
Well in the database BUT it is parsed from the files that are uploaded when the author uploads the mod

**Comment by 1-alex98** [comment]
If you want more than links (that need to be added by authors on upload or update) and then you want a separate link for documentation that can be added by a moderator this needs changes and corresponding issues across multiple projects:
- db 
- java-api
- moderation-client
- downloards-faf-client

**Comment by 1-alex98** [comment]
Tho it probably is a lot of work for a seemingly small feature

**Comment by whaleberg** [comment]
I hacked together some code to split out things that look like links and display them as hyperlinks, but I'm stuck on actually launching them in the browser when you click on them.  I expected there to be some built in function to do it trivially, but of course there isn't any 1 foolproof way.  
It seems like maybe you can do something with HostServices but I haven't figured out what.

![image](https://user-images.githubusercontent.com/3135939/76696301-3462b880-6660-11ea-8cf8-1c69ee2ebf8c.png)

**Comment by whaleberg** [comment]
Also, your build instructions "just work" which is always a nice surprise when trying out a new project!

**Comment by 1-alex98** [comment]
@whaleberg use the PlatformService , just add them as a constructor parameter and it will be provided by Spring dependency injection, then use the showDocument(url) Method

**Comment by 1-alex98** [comment]
Also if u are interested in contributing to this project in general you could consider joining Zulip(chat service, like slack). I am happy to send you an invite. In case you like sent me an email alexander.von.trostorff@gmail.com

**Comment by Sheikah45** [comment]
Probably better represented in https://github.com/FAForever/faf-java-api/issues/564 since checks for this would be good
