### ISSUE TITLE
Rarely get connected to #newbie chat without having done so manually

### ISSUE THREAD

**Issue by FemtoZetta** [FAForever/downlords-faf-client#1617]
Since 1.1.3 I sometime get connected to newbie chat randomly after starting the client even though I have over 800 global games (and over 60 ladder) and never joined that chat manually. Happened two times so far. Logs are pointless as far as I can see because they don't log which channels you join, so no logs for you...
Axel asked me to open an issue for it. 
In-game name is FemtoZetta (for testing purposes).

**Comment by 1-alex98** [comment]
I could not reproduce it

**Comment by 1-alex98** [comment]
I logged in as you on the test server and it did not happen.

Can you give me a screen shot of your auto join chat channels. And the profile window. When it happens again.
![Screenshot from 2020-03-15 12-40-55](https://user-images.githubusercontent.com/19996713/76700722-aa940900-66ba-11ea-9fd9-e795bc6fd3b4.png)

![Screenshot from 2020-03-15 12-43-01](https://user-images.githubusercontent.com/19996713/76700716-9819cf80-66ba-11ea-8c1b-acd145e1969f.png)

**Comment by FemtoZetta** [comment]
I don't have any autojoin channels, it just joins aeolus and clan chat automatically
![grafik](https://user-images.githubusercontent.com/61892809/76705124-ac1efa80-66d5-11ea-8b81-74b4a4baa606.png)

But I guess I'll post again when it happens again.

**Comment by FemtoZetta** [comment]
Happened today again lol
![grafik](https://user-images.githubusercontent.com/61892809/76713768-f24a7d00-671a-11ea-98d0-b8605cf64ec4.png)
![grafik](https://user-images.githubusercontent.com/61892809/76713773-01c9c600-671b-11ea-84ff-175f23a09f3c.png)

Also here are the client logs (not sure if they are of use):
https://pastebin.com/1UtMDSHe

**Comment by 1-alex98** [comment]
Hmm nothing in log. strange, we relayy need and option to turn on more logging

**Comment by 1-alex98** [comment]
This seems to be a race condition
