### ISSUE TITLE
Filter breaks chat layout

### ISSUE THREAD

**Issue by FemtoZetta** [FAForever/downlords-faf-client#1618]
Using the filter in chat on the right breaks the chat layout. Screenshots are provided to make it more clear.

[before filter](https://i.imgur.com/i0kg4qT.png)
[after filter](https://i.imgur.com/RiUXfEb.png)

**Comment by 1-alex98** [comment]
where is the break?

**Comment by 1-alex98** [comment]
You still want the categories?

**Comment by FemtoZetta** [comment]
Yes, that's after I "erased" the filter, so there's nothing to filter anymore. I don't need it during filtering, but afterwards, when not filtering anything anymore, it would be nice if it went back to the default.

**Comment by 1-alex98** [comment]
ok

**Comment by FemtoZetta** [comment]
To add a bit: I'm talking about the filter for rating and clan (from the white icon)... The normal filter where you can just filter for name doesn't remove the categories (and it actually brings them back after they were removed by the other filter).
So maybe you can use the normal filter as a reference.
