### ISSUE TITLE
Map goes off the screen because of the alignment

### ISSUE THREAD

**Issue by KionX** [FAForever/downlords-faf-client#1628]
If the game description does not fit in the window, it is centered on the width instead of moving to the line below. And the map goes off the screen because of the alignment.
![Fucked Shit](https://user-images.githubusercontent.com/5648030/77088305-14e3db00-6a26-11ea-9b78-482b1ffee0ba.png)

**Comment by 1-alex98** [comment]
That's probably a duplicate

**Comment by Katharsas** [comment]
I just mentioned it in https://github.com/FAForever/downlords-faf-client/issues/1032#issuecomment-508211524
> Custom games details view currently becomes scrollable horizontally in addition to vertically when the game name is bigger than fits in the windows. This looks bad and adds unnecessary horizontal scrollbar. Just wrap long names.

However it did belong into separate issue anyway (above one is closed).
