### ISSUE TITLE
Creating release/develop/coop shortcuts for launch FAF game without client

### ISSUE THREAD

**Issue by KionX** [FAForever/downlords-faf-client#1632]
![1](https://user-images.githubusercontent.com/5648030/77260216-7f0bb280-6ca8-11ea-8e86-e693e815ba8b.png)
This is proper description.

**Comment by Brutus5000** [comment]
I do not see any benefit for the average user, quite the opposite. Any of these shortcuts will lead to the conclusion that the user did something wrong, as he can't join any games with these.

**Comment by KionX** [comment]
If so?
ForgedAlliance Dev(local)
or
ForgedAlliance Dev(offline)

I think not only about the average user but also about new developers.
Finding out how to run it correctly is not easy.

**Comment by 1-alex98** [comment]
Well upload those on the fa repo i guess...

**Comment by KionX** [comment]
Promising idea. Maybe I can make something more out of it.
I will no longer insist on adding shortcuts. Although I think it might be convenient.
