### ISSUE TITLE
2 New map vault categories: Surivial and "Classic maps people love and hate"

### ISSUE THREAD

**Issue by mirddes** [FAForever/downlords-faf-client#1635]
https://forums.faforever.com/viewtopic.php?f=53&t=18972

Whilst it is reasonable to disagree with the agenda of the article it is difficult to discount the quality of the article and Impossible to refute the popularity and abundance of variants of these maps. 

if u werent aware, the majority of morax’s effort has gone into removing these variants because they’re low effort and trash. It's easy to make an exception for this category, which by its nature has it's own thematic rules.

It highlights and removes these classic maps people love and hate. Shifted entirely to their own category, celebrating instead of alienating the preferences and tastes of a sizable chunk of the community.  I'm sure many people would love to never see these maps again and just as many will actively seek them out no matter what.  Each to their own. We would be making it easier to never see them again. Without reducing our compassion.  Empathy for divergent tastes is critical, as is keeping the vault tidy. No longer will half the top played maps be variations of these maps. Fresh and interesting content will become more accessable. 

Surely adding 2 additional categories to the front page of the vault is easygoing and the time consuming process is curation. I am willing to commit all of the required time to tag all of the affected maps.

Survival is really cool. There are over 150 different survival maps and no 2 keywords finds all of them. I am prepared to confirm the functioning state of each survival map and tag them appropriately.

**Comment by 1-alex98** [comment]
This not a client issue. It first needs support on db and api. Until that's done I am closing this. Also GutHub is not the place to discuss political manners.

**Comment by mirddes** [comment]
Fair enough.thank you for taking you time to look at it and thank you for your feedback.
