### ISSUE TITLE
Explain how to translation is done in Readme or Wiki

### ISSUE THREAD

**Issue by Achilleshiel** [FAForever/downlords-faf-client#1636]
**Translation is difficult enough**
I was working with a couple of friends on the dutch translation. However, we noticed that the languages files have grown organic over time. Which makes comparing the translations very difficult. As keywords are appended, missing, duplicate or misspelled.

**Proposal**
I'd like to build a script that sorts the keywords in a deterministic way. Such that all the language files can be kept easily in the same order.

**Questions**
* This breaks comments in the translation files. As sorting happens per line. Does this matter? Or can we add comment at the end of each line?
* Where should I put the script?
* Last but not least, is this oke with you guys?

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by 1-alex98** [comment]
Translations are done at po editor not in this repo. You know that right?

**Comment by 1-alex98** [comment]
https://poeditor.com/join/project/2oWfdaZQZj

**Comment by Achilleshiel** [comment]
No, I could not find this in the contribution documentation. Where in the documentation can I find more about this?

**Comment by silkeh** [comment]
> Translations are done at po editor not in this repo. You know that right?

@axel1200: This information not present in the contribution guide [here](https://github.com/FAForever/java-guidelines/wiki/Contribution-Guidelines). Where is this documented?

**Comment by Katharsas** [comment]
Changed to doc / wiki issue.

**Comment by 1-alex98** [comment]
This is not an issue related to this repo. You can make such a wiki article if you wish to.

**Comment by 1-alex98** [comment]
I have no access to the contribution guide nor is it for this client in particular

**Comment by 1-alex98** [comment]
https://github.com/FAForever/downlords-faf-client/wiki/Translations
