### ISSUE TITLE
irc user list context menu bug

### ISSUE THREAD

**Issue by PhilipJFryFAF** [FAForever/downlords-faf-client#1642]
**Describe the bug**
when opening the context menu of a user in the irc user list via right mouse button the menu may disappear randomly

**To Reproduce**
try changing the color of a user or something else in that menu

**Expected behavior**
it should not disappear

**Screenshots**
https://puu.sh/Fqtnj/bdc912ee85.mp4

**OS**
Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by shalkya** [comment]
i think it's every time there is someone joining/leaving aeolus that this happen.
When i want to do an action, i write the name of the user so it's only him showing, then i don't have the bug anymore.

**Comment by 1-alex98** [comment]
duplicate #1429
