### ISSUE TITLE
Implement QAI functions directly into client

### ISSUE THREAD

**Issue by Cheyans** [FAForever/downlords-faf-client#165]
!blacklist, !casts, !chatlist, !explode, !flip, !google, !help, !hug, !join, !leave, !link, !move, !ping, !puppet, !reload, !slap, !streams, !taunt, !tourneys, !wiki

We could add a 'Search google for "word" ' and 'Search wiki for "word" ' as context menu options in chat

!tourneys I'll leave for @Technopeon when we create a framework for this

**Comment by Bra1nwash3d** [comment]
some of those commands only make sense, when others can see their results though - to link tech support, a wiki entry, raise public awareness for new casts and so on

**Comment by Cheyans** [comment]
We can directly integrate what is needed straight into chat without a bot.

**Comment by micheljung** [comment]
Some of QAI's functionality should definitely be in the client. For others the advantage is, that it can be used regardless of the client (even with plain IRC)

**Comment by Cheyans** [comment]
Didn't you mention sheeo wanting to remove irc users completely? This would be a step towards that goal.

**Comment by micheljung** [comment]
it's still client-independent. Sheeo even wants to try WebViews to take code away from a specific client.

**Comment by Cheyans** [comment]
I mean that would make it easier to transition to other chat protocols, but this is another issue. I guess for now we can just integrate the things that make sense. Imo those would be:
google, join/leave (already integrated), tourneys, maybe wiki?

**Comment by micheljung** [comment]
The focus of this issue is too broad. Single features will be implemented into the client, but in general I'm not planning to integrate these commands anytime soon.
