### ISSUE TITLE
Auto color friends/foes/moderators in different colors

### ISSUE THREAD

**Issue by RK4000** [FAForever/downlords-faf-client#1659]
Possibly as part of the color format settings, introduce automatic colorization (using some default colors, or, should the user want to, custom picked colors) that would apply to friends, moderators, clanmates and foes.

For example, in the old client:

Normal message: Slightly grey
Moderator message: White
Friend message: Light blue
Clanmate (that is not a friend) message: Light green
Foe message: Red

Those could be the default colors, and then the user can choose what color applies to what type of message as well.

Currently, there is indeed an ability to assign a custom color to each person, but that is very rarely used. I feel this would be a much more useful as it requires less input from the user. (no need to manually assign a different color to each moderator, friend, clanmate, etc.)

**Comment by 1-alex98** [comment]
probably a duplicate

**Comment by Sheikah45** [comment]
Fixed in #2028
