### ISSUE TITLE
Improve map vault pagination

### ISSUE THREAD

**Issue by Farmsletje** [FAForever/downlords-faf-client#1660]
Currently this is what we have: 
![](https://puu.sh/FrvQk/d77f668b6e.png)

And something like this is the standard:  
![](https://puu.sh/FrvQU/bb1eb2efe4.png)

Would be nice to have this added for improved vault usability.

**Comment by Askaholic** [comment]
Btw puush is not good for github issues because the link expire. Instead, attach the files directly via github.
