### ISSUE TITLE
cybran shield + hyves - bad eco bug

### ISSUE THREAD

**Issue by adminxp** [FAForever/downlords-faf-client#1662]
replay 34+ min [https://content.faforever.com/faf/vault/replay_vault/replay.php?id=11372599](url)
recorded video of issue: https://www.youtube.com/watch?v=Ph8BpAL7sDc&feature=youtu.be
description: hyves started to assist shield - doing nothing, shield was not upgraded by them nor healed, just a lot of build power with huge mass consumption for nothing.
If I had no paragon that would exhuast my eco in few seconds.

**Comment by norraxx** [comment]
Dude, wrong repo, here are bugs, that belongs to client, not to game. Check `fa` repository (https://github.com/FAForever/fa)

**Comment by adminxp** [comment]
> Dude, wrong repo, here are bugs, that belongs to client, not to game. Check `fa` repository (https://github.com/FAForever/fa)

I am sorry. created issue there.
