### ISSUE TITLE
Users get stuck in the login screen waiting forever

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1663]
Users do not seem to become a "welcome" message and get stuck loging in forever.

https://github.com/FAForever/server/issues/562

Possible ways to improve the situation:

- [ ] Make a timeout after which we cancle log in
- [x] Improve loging and catch and log potentially swallowed exceptions

User posting this on forum:
https://forums.faforever.com/viewtopic.php?f=3&t=18996&p=183021#p183021

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Askaholic** [comment]
So in the server log I do see quite a few
```
Client <username> dropped. You have been signed out because you signed in elsewhere.
```
which might mean that old connections aren't being closed properly. Or maybe somehow people trigger two connections at the same time which kick each other out.
