### ISSUE TITLE
replace dancing ACU with sane gif

### ISSUE THREAD

**Issue by BlackYps** [FAForever/downlords-faf-client#1665]
For the love of god please replace the dancing ACU with a normal loading gif.
I even made one for you that you can use:

![loading-circle](https://user-images.githubusercontent.com/52536103/78306268-40e17f00-7543-11ea-8e9f-fa588e399a4d.gif)

(it is a white circle on transparent background so it is suited for the dark client but looks not so good in a preview on white background)

**Comment by dmalukov** [comment]
Debatable - I like dancing ACU.

**Comment by iczero** [comment]
I also like the dancing ACU

**Comment by 1-alex98** [comment]
Yes a setting to choose is probably needed

**Comment by micheljung** [comment]
The dancing ACU consumes 20MiB of memory

**Comment by 1-alex98** [comment]
Yeah that might be fixed by making a gif with less quality

**Comment by BlackYps** [comment]
or we use the spinning circle gif and all people that want the dancing acu can use a theme. Theme support is right around the corner, so we don't even need to code a setting to choose the gif anymore.

**Comment by Katharsas** [comment]
Check if we can use a sane format like [APNG](https://en.wikipedia.org/wiki/APNG) instead of gif.
Gif is a horrible format and only has 1 bit transparency "channel" so you cannot create transparent gif that works on bright and dark background without artefacts, as seen in the gif above, which would become a theming problem.

**Comment by micheljung** [comment]
APNG isn't supported by JavaFX https://bugs.openjdk.java.net/browse/JDK-8092356

**Comment by Katharsas** [comment]
Has animating an SVG path via PathTransition been tried? That should cost basically no memory and should work with UI scaling without any artefacts.

**Comment by JaggedAppliance** [comment]
Bump. I wanna know how many of the people that like this actually play ladder regularly.

**Comment by 1-alex98** [comment]
There is an article that explains how to make a theme. A theme for replacing the gif is mostly a matter of putting the gif in the correct folder...

**Comment by 1-alex98** [comment]
https://github.com/FAForever/downlords-faf-client/wiki/Themeing

**Comment by JaggedAppliance** [comment]
The ACU should be in a theme, not the other way around.

**Comment by Farmsletje** [comment]
Something like this can indeed be nice for a theme but should by no way be the default. It's way too cringe for that

**Comment by BlackYps** [comment]
The new tmm UI will not have that gif

**Comment by Sheikah45** [comment]
TMM killed the ACU
