### ISSUE TITLE
Local replays list not updated after game ended

### ISSUE THREAD

**Issue by Arkemlar** [FAForever/downlords-faf-client#1666]
**Describe the bug**
Local replays menu not shows new games that I just finished. Also there are no refresh button or something similar.
Also I noticed about default setup for Available replays menu which is set up by default for my games. But it bugged or something because it shows just finished game but replay has 0 B size and shows exception when I try to launch it. I think that it happens because replay is not ready at server side yet. But local replay should be ready when I quit game and should be watchable!

**To Reproduce**
Open Local replays menu, then go play some game, then return to Local replays menu and see that new game not appears in the list.

**Expected behavior**
New game appears right after you quit FA client. Like it was in old good FAF client.

**OS**
Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by andreasley** [comment]
Actually, replays are reloaded correctly as far as I can tell. But since a few days ago, replays aren't saved locally for some reason. I have not yet found the reason for that.

Can you check your replays folder to see if the expected replays are there?

**Comment by Katharsas** [comment]
Possibly related:
https://forums.faforever.com/viewtopic.php?f=3&t=19012

This happened for me as well for me as well, for example for:
https://content.faforever.com/faf/vault/replay_vault/replay.php?id=11388656
https://content.faforever.com/faf/vault/replay_vault/replay.php?id=11374629
https://content.faforever.com/faf/vault/replay_vault/replay.php?id=11374505

Seems to happen pretty inconsistently, like every second/ third game. Affects both coop and non-coop games. The replay files do not appear in replay folder. Didn't find something in the log from a quick look.

**Comment by andreasley** [comment]
Culprit seems to be here:
```
2020-04-06 00:12:37.642  WARN 1020 --- [      Thread-60] com.faforever.client.game.GameService    : Can't find 11415015 in gameInfoBean map
Exception in thread "Thread-60" java.lang.NullPointerException
	at com.faforever.client.replay.LocalReplayInfo.updateFromGameInfoBean(LocalReplayInfo.java:47)
	at com.faforever.client.replay.ReplayServerImpl.finishReplayInfo(ReplayServerImpl.java:176)
	at com.faforever.client.replay.ReplayServerImpl.recordAndRelay(ReplayServerImpl.java:169)
	at com.faforever.client.replay.ReplayServerImpl.lambda$start$2(ReplayServerImpl.java:99)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Katharsas** [comment]
Ok so the  `game` is null which means that the this method (called from the `onGameInfoFinished` lamda) returns null for the game uid when the replay ends (and the log matches):
https://github.com/FAForever/downlords-faf-client/blob/develop/src/main/java/com/faforever/client/game/GameService.java#L475

So maybe the game gets removed from the `uidToGameInfoBean` too early or something?
https://github.com/FAForever/downlords-faf-client/blob/develop/src/main/java/com/faforever/client/game/GameService.java#L125

@axel1200 was there a change in regards to the map recently?

**Comment by 1-alex98** [comment]
Yes some

**Comment by EmielWitteman** [comment]
same problem, local replays not saved anymore since 7/4/2020, had 2 updates that day: patch 3712 and downlords 1.1.5

could the safequit fix be related? https://github.com/FAForever/fa/pull/3032

noticed one weirdness in game.log 
```
info: Sending game result: 1 victory 10
  info: SSB >>> TRACE GameResults:
  info: Sending stats: {"stats":...
  info: Sending stats: {"stats":...
  info: Sending stats: {"stats":...
  info: Sending stats: {"stats":...
  info: syncing max ping markers: \00015
  info: SSB >>> TRACE Sync.FocusArmyChanged -1
  info: Block is too late !    <-- this seems wierd
  info: terminated
  debug: OpenMovie /movies/menu_background.sfd: 67083

```

**Comment by Arkemlar** [comment]
Telling about Local replays menu bug (namely that the list is not updated after yet another game finished) - that problem for me persisted from the beginning of using downlords faf client which is happened more than half year ago. So that is not a new bug for me. I reported it now because previously did not know where to send bug reports.

**Comment by andreasley** [comment]
> Telling about Local replays menu bug (namely that the list is not updated after yet another game finished) - that problem for me persisted from the beginning

That was a different problem. Since version 1.1.3, the client reloads the replays instantly (also works when files are added/removed to the directory).
The current problem is an entirely different issue and some (most) replays aren't actually saved locally.

**Comment by 1-alex98** [comment]
We did not change something in replay server (local one) I am almost sure it is an issue wit the game patch

**Comment by Wizek** [comment]
I'm also having this issue, and it's a bit frustrating when I want to re-watch a game I was just in, to learn from it, and I need to wait more than 1 hour for the online replay to become available (shows 0 Bytes as size).

**Comment by andreasley** [comment]
@Askaholic What do you think about this, especially the [suggestion from Emil](https://github.com/FAForever/downlords-faf-client/issues/1666#issuecomment-612675218 )?

**Comment by Askaholic** [comment]
If it has anything to do with the `SafeQuit` change, then it would only occur for games where you exit early by using the "Exit to FAF" button from the menu. That should be pretty easy to test.

**Comment by EmielWitteman** [comment]
the phyton client seems to save the local replays just fine

**Comment by andreasley** [comment]
> If it has anything to do with the `SafeQuit` change, then it would only occur for games where you exit early by using the "Exit to FAF" button from the menu.

Isn't this the handler for the "Exit" button on the Score screen, calling `SafeQuit`?
https://github.com/FAForever/fa/blob/720a72f5eca5330ba497320a618a57c7b981cda2/lua/ui/dialogs/score.lua#L467

I've also tried to do some testing:

**2020-04-16**
```
GAME 1: quit without ACU being dead -> replay is saved locally
GAME 2: quit using button "Score" after game was completed, ESC at score screen -> replay is NOT saved locally
GAME 3: quit without ACU being dead -> replay is saved locally
GAME 4: quit using button "Score" after game was completed, button "Exit" on score screen -> replay is NOT saved locally
GAME 5: quit without ACU being dead -> replay is saved locally
GAME 6: quit using button "Score" after game was won, but not ended (survival with Sandbox), button "Exit" on score screen -> replay is saved locally
```

**2020-04-17**
```
GAME 1: quit 1v1 ladder using button "Score" after game was completed, ESC at score screen -> replay is NOT saved locally
GAME 2: not sure; probably quit using button "Score" after dying -> replay is saved locally
GAME 3: quit using button "Score" after game was completed, ESC at score screen -> replay is NOT saved locally
GAME 4: quit using button "Score" after game was completed, ESC at score screen -> replay is NOT saved locally
GAME 5: quit 1v1 ladder game using button "Score" after game was completed, ESC at score screen -> replay is NOT saved locally
GAME 6: quit 1v1 skirmish game without ACU being dead -> replay is saved locally
GAME 7: quit 1v1 skirmish game without ACU being dead -> replay is saved locally
GAME 8: quit 1v1 ladder game without ACU being dead -> replay is saved locally
```

**Comment by andreasley** [comment]
After even more testing, the following pattern is clear:

- If the player leaves a running game, the replay is saved.
- If the player leaves a game that has ended, the replay is **not** saved.

Seems definitely related to https://github.com/FAForever/fa/pull/3032, as @EmielWitteman suggested.

**Comment by Askaholic** [comment]
I don't think this is the problem. I ran some games on the test server which is still on the version of FA before that patch was deployed, and the replay still didn't get saved when I ended the game normally. So it doesn't look like it has anything to do with `SafeQuit`. 

It also doesn't make sense to me for that to be the issue based on the tests you have done. The `SafeQuit` fix only prevents results from being sent when you leave the game early. When you exit after the game has ended properly, all results have already been reported, so the `SafeQuit` change literally doesn't do anything.

**Comment by andreasley** [comment]
Thanks for looking into that, @Askaholic.

My knowledge about the LUA parts is very limited, but I thought it's possible that the `SafeQuit` change somehow exposed a bug in the Java client, because I couldn't find any recent changes in the Java client that could affect the replays.

The underlying issue seems to be what @Katharsas suggested:

1. The game ends, and a `GameResult` is sent to the server
2. The server informs the client about the new `GameStatus` (`CLOSED`). The client then removes the game from `uidToGameInfoBean`.
3. FA exits, the connection from the client to FA is broken and that triggers saving of the replay
4. While saving the replay, the client tries to fetch the `Game` bean and fails to do so, leading to a lost replays.

I don't see any reason why the `Game` bean needs to be fetched that late and will try to change that accordingly.

**Comment by Askaholic** [comment]
Aaah, you know I bet it’s because of this server change https://github.com/FAForever/server/pull/511.

The server started considering games as being over as soon as the sim ended, in other words as soon as “game over” appears on the screen. So maybe when the GameState is changed to CLOSED before the exe is terminated that messes with the replay saving. 

This would explain why the replay is saved when you exit the game early, and not when you hang around on the score screen.
