### ISSUE TITLE
Client queues `ping` messages while offline

### ISSUE THREAD

**Issue by Askaholic** [FAForever/downlords-faf-client#1667]
**Describe the bug**
When the client re-connects to the server after having been offline for a while (such as when you left the client open while your computer went to sleep) it spams ping messages for the entire time that it was offline. 

When I turned on my laptop after having left it sitting there for over a week, the server log was spammed with about `700` ping messages per second.

**To Reproduce**
1. Log in 
2. Let your computer fall asleep for a long time
3. Turn your computer back on

**Expected behavior**
Ping messages should not be generated while disconnected from the server.

**OS**
Windows
Client version 1.1.4

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by 1-alex98** [comment]
interesting
