### ISSUE TITLE
Fix mapping for faction icons in replay details

### ISSUE THREAD

**Issue by FemtoZetta** [FAForever/downlords-faf-client#1668]
Factions are currently mapped as
1 = Aeon
2 = Cybran
3 = UEF
4 = Seraphim
but server uses
1 = UEF
2 = Aeon
3 = Cybran
4 = Seraphim.
Maybe requires a new enum, if changing the current one breaks functionalities.

**Comment by Askaholic** [comment]
You can also verify what the game uses here:
https://github.com/FAForever/fa/blob/720a72f5eca5330ba497320a618a57c7b981cda2/lua/factions.lua#L106

The number is the order in which it appears in that table (remembering that lua tables are 1 indexed)
