### ISSUE TITLE
Change "Show modded games" filter to get more exposure for rated mods and to make more sense.

### ISSUE THREAD

**Issue by RK4000** [FAForever/downlords-faf-client#1670]
As discussed here:
https://forums.faforever.com/viewtopic.php?f=2&t=18993

Main reason: Most if not all people the use "show modded games" filter to remove the games running 40+ sim mods. They do not necessarily want to remove rated mods, and indeed, the existing filter as it currently works, does not filter out games with faf beta, faf develop, labwars, phantom, nomads, etc, to begin with.

Therefore, I propose this filter be changed to "Show unrated mods". The functionality of removing games running 40+ sim mods (some of which are not even in the vault) stays the same, while exposure of rated mods is improved. If phantom and nomads (etc) games show up with the filter enabled, rated mods should too. 

It would make more sense as well, because the current filter does not filter out the mods I mentioned above (phantom, nomads, labwars, faf beta etc), so with the filter saying "show modded games", as it does currently, it implies you won't see modded games, but you still do. With the filter changed to "Show unrated mods", this is also fixed.

(Fixing the ability to rate mods would be nice as well: https://github.com/FAForever/faf-java-api/issues/389 )

**Comment by Sheikah45** [comment]
This would require querying the api on every gameinfo message if it contains mods which at the moment is not something I would want to do
