### ISSUE TITLE
Add an indication that a map is unranked in the custom games overview

### ISSUE THREAD

**Issue by FemtoZetta** [FAForever/downlords-faf-client#1671]
Should probably add an option to filter out unranked games, too.
Since recently some popular maps have been made unranked, this is more relevant than ever. In general players don't get proper feedback about whether a game is ranked or not before joining (some mods don't unrank for example).

**Comment by Sheikah45** [comment]
The server doesnt send any information about whether a game is ranked or not afaik.

**Comment by dev-nulled** [comment]
@Sheikah45 is there logic somewhere that lists what mods count for ranked?  I was already looking at a thumbnail overlay tweak to show if friends were in a game.

**Comment by Sheikah45** [comment]
There is no logic in the client about which mods are ranked. The only way to get this info would be to query the api for every mod and map which can end up being a lot of api queries and we don't want to do that on every game update.

**Comment by dev-nulled** [comment]
Can't imagine it changes that often.  Thoughts on caching the ruleset on client launch?  (and possibly adding a new endpoint on the server side?)

**Comment by Sheikah45** [comment]
This could really only be done by querying the api on every single new game creation which would cause quite the server load and there are too many maps to reasonably pull them all down and store the list locally.
