### ISSUE TITLE
Use open jdk 11 in CI for installer

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1675]
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.7%2B10.1/OpenJDK11U-jre_x64_windows_hotspot_11.0.7_10.zip

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Brutus5000** [comment]
I mirrored it on https://content.faforever.com/jre/OpenJDK11U-jre_x64_windows_hotspot_11.0.7_10.zip as we know of speed issues with Github.

**Comment by 1-alex98** [comment]
cool thx

**Comment by 1-alex98** [comment]
I need a tar gz

**Comment by 1-alex98** [comment]
@Brutus5000 next try https://drive.google.com/file/d/1xYWm42YqrAtWjGRiOi6GveLdD5msKkD3/view?usp=sharing

**Comment by 1-alex98** [comment]
needs to be a tar gz. I bundeled it via install4j(not sure what else it does to the jre)

**Comment by Brutus5000** [comment]
https://content.faforever.com/jre/windows-amd64-11.0.7.tar.gz

**Comment by 1-alex98** [comment]
Does not work yet so for reasons I need to investigate :D
