### ISSUE TITLE
Clientside workaround for coop replays

### ISSUE THREAD

**Issue by Askaholic** [FAForever/downlords-faf-client#1676]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2410%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/FAForever/downlords-faf-client/issues/1676)

## Intro
This is a a sort of mini-guide on how to launch coop replays manually. I'm creating this as a github issue because I think it should be pretty simple to get the client to do this automatically. In the mean time people will need to do the set up themselves.

### Why don't coop replays work?
Coop maps are not stored in the vault like regular maps. This means that the replay server doesn't recognize coop map names, and instead just write `none` into the `fafreplay` header. When the client goes to download the map we see an exception like this:
```
java.io.FileNotFoundException: https://content.faforever.com/faf/vault/maps/none.zip
```

### How to launch coop replays manually
First off, you will want to have the legacy client installed as it will handle updating to the correct version of FA for the replay: https://github.com/FAForever/client/releases

1. Download the replay from the vault. An easy way to do this is to hit the "play" button on the coop tab, and cancel when you see the error, just be aware that it is downloaded into `C:\ProgramData\FAForever\cache\temp.fafreplay`.
2. Change the replay extension from `.fafreplay` to `.coop.fafreplay`. This will tell the legacy client that it should update for the `coop` game mode.
3. Right click the replay and open it with the legacy client. It is probably called `Forged Alliance Forever - Lobby Client`. The legacy client should now update the necessary files, but it will most likely fail with an error message like "Map not found" or a timeout error.
![image](https://user-images.githubusercontent.com/17941539/79805667-13eae580-8313-11ea-8481-808f709a76b1.png)

4. Start the replay from the command line. Open `cmd` or `powershell` and paste in the following command:
```
C:\ProgramData\FAForever\bin\ForgedAlliance.exe /init init_coop.lua /nobugreport /log C:\ProgramData\FAForever\logs\game.log /replay C:\ProgramData\FAForever\cache\temp.scfareplay
```

## Client workaround
I think we should modify the replay launching code so that it skips the map download for coop maps. That way the user can set up their maps directory manually before launching the replay. We should also make sure that the client downloads the correct version of the FA for the replay, as it stands I think it tries to always download the most recent version (the legacy client handles this correctly).

## Criteria for closing this issue
I want to be able to click the "play" button on the coop leaderboard and have the client download and successfully launch the replay. The client should update the `faf` featured mod to the correct version, but may assume that:
1. The map is already present and at the right version
2. The `coop` featured mod is at the right version

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $10.00)

- [<img src='https://avatars0.githubusercontent.com/u/17941539?v=4' alt='askaholic' width=24 height=24> askaholic](https://issuehunt.io/u/askaholic) ($10.00)

### Submitted pull Requests
- [#1866 Fix coop replay parsing](https://issuehunt.io/r/FAForever/downlords-faf-client/pull/1866)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/FAForever/downlords-faf-client/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by 1-alex98** [comment]
Either I am stupid or I tried already to fix it

**Comment by 1-alex98** [comment]
I made a dialog that asks you to start replays even if the map can not be found

**Comment by 1-alex98** [comment]
Anybody that wants to try, go ahead

**Comment by Sheikah45** [comment]
@axel1200 why did you reopen this?

**Comment by Sheikah45** [comment]
Closing for lack of response
