### ISSUE TITLE
Decrease vault search case sensitivity for easier finding of mods

### ISSUE THREAD

**Issue by RK4000** [FAForever/downlords-faf-client#1681]
For example, if someone searches for "Gregs mod" and the name of the mod is "Greg's Mod", the search will not find anything as the search is missing the ' . However, this is un-intuitive as most search engines would still find the mod given those search parameters.

Some common things like the example above as well as other common symbols for example : _ - ( ) etc could be omitted from the case sensitivity of the search engine, so the search words doesn't have to be as precise to find something.

**Comment by Brutus5000** [comment]
This is not possible from client side.

We'd need to add full text search support to the API. This requires us to bring up a search engine like Solr or Elastic into the faf stack. Technically this is possible, but it would take a lot of time. Not sure if anybody is willing to invest it.

I have linked the API ticket.
