### ISSUE TITLE
Loading / Unloading map images in replays tab

### ISSUE THREAD

**Issue by ghost** [FAForever/downlords-faf-client#1682]
When searching for a replay (on the Java client only) and hitting the "More..." button 4-5 times the client slows down. 

This occurs after scrolling down and clicking on "More..." 4-5 times  eventually resulting in a slow / unresponsive UI as the images from the maps are not unloaded. 

An ideal solution to this issue would be to unload unseen images and having a buffer of 2 or 3 images each side of the visible replays on screen to reduce load like android lists would have with decay times.  This however would require a bit of work to implement and the next method already has some of the features implemented to work.

A more realistic and easier to implement solution would be to have the first set of search results loaded when the user searches, then once they request the next set of results using the "More..." those results get loaded but the next time they click "More..." the first set of results get unloaded, that way the user only ever has 2 sets of results loaded and instead would get a new button if they scroll back up to load the previously unloaded results.

If you didn't follow that, you would end up this:
User searches for replays, first set of replays get loaded, they can scroll and view those fine. They want to load the second set of replays below the first set, they hit "More...". This loads the new second set of replays and the user now has 2 sets of replays loaded. They now scroll down and want to load the 3rd set of replays, in this case they hit "More..." and the replays get loaded but at the same time the 1st set of replays get unloaded and a new button called say "Previous..." appears similar to the "More..." button. They can now view the 2nd and 3rd set of replays and go ahead to load the 4th set or the first set again depending on their needs. If they load the 4th set, the 2nd set of replays get unloaded and the 4th get loaded so they can now view 3rd and 4th set of replays. If they decide they want to go back to the 1st set instead they can load the 1st set and unload the 3rd set of replays now being able to view only the 1st and 2nd set.

I hope that's a clear enough description.

**Comment by Sheikah45** [comment]
This should be taken care of with the pagination of the replay vault correct? @axel1200
