### ISSUE TITLE
Missing news images in JDK11

### ISSUE THREAD

**Issue by p4block** [FAForever/downlords-faf-client#1686]
**Describe the bug**
Under jdk11 (worked in 10), under the news tab, most images will be missing.

With the new test version, minimum jdk is 11, so I can't really test again. 

**To Reproduce**
`INSTALL4J_JAVA_HOME=/usr/lib/jvm/java-11-openjdk ./downlords-faf-client`

**Expected behavior**
News item thumbnails show

**Screenshots**
![image](https://user-images.githubusercontent.com/5960575/80873413-a2b71500-8cb8-11ea-897a-91ec46cf7fa4.png)

**OS**
Arch Linux

**Comment by 1-alex98** [comment]
logs?

**Comment by 1-alex98** [comment]
Well on my linux it works fine with jdk 11

**Comment by p4block** [comment]
No unusual output is given in this case. Some articles have pics, some just have grey rectangles.

**Comment by p4block** [comment]
As discovered yesterday, this bug doesn't appear while running the codebase under intellij, it only happens on the Install4J version. Could be a vm options thing.

**Comment by 1-alex98** [comment]
maybe

**Comment by micheljung** [comment]
Obsolete since the news hub has been introduced
