### ISSUE TITLE
Introduce topics to the news page

### ISSUE THREAD

**Issue by FemtoZetta** [FAForever/downlords-faf-client#1688]
With so many Nomads news the need for this became more apparent. The client should have different news topics, maybe something like "Nomads", "server maintenance" and "FAF news" or something like that. At least it shouldn't show Nomads as a main topic you see when you look at the news/open the client.

Until posts can have tags (I'm pretty sure they can't, and I guess the server needs to support that too then?) I suggest just hard coding anything that mentions "Nomad" and moving it to a topic that is not the default one.

**Comment by p4block** [comment]
Posts can have tags, we are just using wordpress for the blog.

The only issue is that any changes to url structure will most likely break news for anyone with an outdated client.

**Comment by Askaholic** [comment]
This is solved by newshub.
