### ISSUE TITLE
Massive clan querying

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/downlords-faf-client#1689]
**Describe the bug**
Our server stats show us that we have massive clan querying on the client.

Out of the top 7 most called endpoints across ALL services, 5 are related to the same elide query.

During a period of ~1 day ~800 unique users caused
~80.000 requests on
`/data/clan?filter=tag=="SCR"&include=leader,founder,memberships,memberships.player&page[size]=1&page[number]=1`

~57.000 request on
`/data/clan?filter=tag=="ONI"&include=leader,founder,memberships,memberships.player&page[size]=1&page[number]=1`

~56.000 requests on
`/data/clan?filter=tag=="OGW"&include=leader,founder,memberships,memberships.player&page[size]=1&page[number]=1`

~39.000 requests on
`/data/clan?filter=tag=="40K"&include=leader,founder,memberships,memberships.player&page[size]=1&page[number]=1`

~38.000 request on
`/data/clan?filter=tag=="JEW"&include=leader,founder,memberships,memberships.player&page[size]=1&page[number]=1`

List goes on like that.

Looks like the client is not caching the clan data at all.

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by norraxx** [comment]
Does this requests produce the slow queries?

**Comment by Brutus5000** [comment]
The queries itself are not slow, but it causes around 1-2GB traffic per day.
