### ISSUE TITLE
default tab to what's new on launching client

### ISSUE THREAD

**Issue by shalkya** [FAForever/downlords-faf-client#1691]
someone talking about that in forum : https://forums.faforever.com/viewtopic.php?f=2&t=19208#p183889

i know you made "what's new" tab highlight when there is news. Nonetheless i think having people landing on the what's new page after launching the client would be better imo. So people actually know and read the messages.

**Comment by Brutus5000** [comment]
There is a setting to say remember my last opened tab. If it's activated, you won't end up on the news.
You could change the default behavior, but that wouldn't change the setting for the existing 25.000 installations out there.

**Comment by shalkya** [comment]
well i guess you can make it "off" by default so new people have this behaviour at least.
The issue with setting is that, you need to be aware of it. I didn't know there was one for this in the client, i thought the "remember my last opened tab" was enforced. Not sure how we can improve the awareness over the different settings.

**Comment by anihilnine** [comment]
I think it would actually be best to remove the setting altogether and force users to land on the news tab. Once we have fresh vibrant news it will add to the community as a whole.

**Comment by anihilnine** [comment]
Failing that could we get a way to clear everyones setting occasionally when we decide? Like when we make a major announcement we hit a button that brings everyone back to the news page.

Failing that could we just wipe the setting once so that people know the news exists at all
