### ISSUE TITLE
Solving the problem of minor news(such as Nomads).

### ISSUE THREAD

**Issue by KionX** [FAForever/downlords-faf-client#1692]
Pin important news on top for a few days.
Or divide the news into two feeds.

**Comment by 1-alex98** [comment]
There is a solution being worked on

**Comment by KionX** [comment]
If the work is will be not completed, open it again.

**Comment by 1-alex98** [comment]
No

**Comment by 1-alex98** [comment]
It is being replaced

**Comment by 1-alex98** [comment]
I am the maintainer of this repo. Instead of complaining all the time be happy stuff gets done. Closing your issue does not mean you can not have the suggested change.

**Comment by KionX** [comment]
```Closing your issue does not mean you can not have the suggested change.```
"Issues" is your personal memo?
