### ISSUE TITLE
Improve UI/UX

### ISSUE THREAD

**Issue by BlackYps** [FAForever/downlords-faf-client#1695]
The client uses two types of buttons. Normal ones (grey) and important ones (white, e.g. "create game" or "search"). White is not really noticable. The white buttons should have a bright color to make them more visible. The button color needs to fit with the rest of the client coloring.
Also the "more" buttons in the vault are not where you expect them. They are on the far right and on the same height as the category headings, making it confusing what the right button is.

**Comment by Sheikah45** [comment]
UI was changed closing this. Open more specific issues for other changes
