### ISSUE TITLE
New v1.2.0-update-test release is absolutely amazing

### ISSUE THREAD

**Issue by tatsujb** [FAForever/downlords-faf-client#1705]
I know it's just a test but I gotta say thank you and how absolutely amazing it is to be able to just

```
sudo apt install -y openjdk-11-jdk
echo 'export INSTALL4J_JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64/"' >> ~/.bashrc
source ~/.bashrc
```

and then be DONE literally done for FAF on linux is just... such a relief

it's amazing to no end and I applaud the work it must have taken to get there!

thank you!

**Comment by 1-alex98** [comment]
What did I change?
