### ISSUE TITLE
can't see everyone talking in aeolus

### ISSUE THREAD

**Issue by shalkya** [FAForever/downlords-faf-client#1710]
![image](https://user-images.githubusercontent.com/11618427/82385647-dc1aaf00-9a32-11ea-941e-dbd29e052d8b.png)
![image](https://user-images.githubusercontent.com/11618427/82385671-eb016180-9a32-11ea-84b8-abfdc1beafee.png)
![image](https://user-images.githubusercontent.com/11618427/82385726-0c624d80-9a33-11ea-8bf6-fee99892383a.png)
I can't see the player Adju talk.

**Comment by shalkya** [comment]
refaf fixed it. Still annoying though.

**Comment by 1-alex98** [comment]
logs?

**Comment by shalkya** [comment]
[downlords-faf-client.log.2020-05-18.0.gz](https://github.com/FAForever/downlords-faf-client/files/4661513/downlords-faf-client.log.2020-05-18.0.gz)
it should be there.

**Comment by Sheikah45** [comment]
The change in the irc backend may have fixed this as I am not able to reproduce. Open if it occurs again.
