### ISSUE TITLE
Tracking Issue: Ladder games starting with wrong players

### ISSUE THREAD

**Issue by Askaholic** [FAForever/downlords-faf-client#1721]
We've seen it happen before that 3 people have showed up in a ladder game, or that someone has the nomads faction. Not sure what the cause is, could be client, server or game related. 

Archsimkat:
> I've been having this issue connecting to ladder games
> It either gets stuck on "Setting up automatch..." or just doesn't match at all . I (~1730) was trying to match my friend (~1770) on ladder for like 10 minutes but no dice. With our rating difference it should have matched pretty quicks
> Also, later I was told I was attempting to connect to a teamgame when I had never (I was only searching ladder), maybe that's related

Found a match but tried to connect to the wrong game?

**Comment by Askaholic** [comment]
Seems that part of the issue is caused when players try to join a ladder game using the `game_join` command. This shouldn’t be possible because ladder games don’t show up in the custom games tab, but unfortunately there are other features like the context menu in the chat tab that let you do this anyways. 

Related #936

**Comment by Askaholic** [comment]
This also: #1761

**Comment by Sheikah45** [comment]
Is this still an issue?

**Comment by Askaholic** [comment]
This can be closed I think

**Comment by Sheikah45** [comment]
Fixed in #1769
