### ISSUE TITLE
"More" Buttons in the vault are in strange positions

### ISSUE THREAD

**Issue by BlackYps** [FAForever/downlords-faf-client#1728]
The "more" buttons in the map, mod, and replay vault are bound to the right edge, which looks a bit odd.
Also they are on the same height as the headlines. So especially in the replay vault you get the problem that after you looked through the list, you have to scroll up again to actually press the right button.

Example:
This button leads you to the highest rated replays:
![grafik](https://user-images.githubusercontent.com/52536103/82937474-7ed1b100-9f90-11ea-91ef-e6796bac1c65.png)

**Comment by Brutus5000** [comment]
:100: if you replace more with pagination (which would solve a lot of memory issues)
