### ISSUE TITLE
Popup windows have several annoyances

### ISSUE THREAD

**Issue by BlackYps** [FAForever/downlords-faf-client#1733]
The popup windows (Create Game, Map Details, Mod Details, Replay Details) have several visual issues:
 - They are always 50px from each border without any limitation, which makes them ridicilously large in fullscreen and destrys the layout when the window is too small
 - The Create Game dialog has a unnecessary headline and no proper close button
 -  also the rating field and the "Min." text are the wrong way around
 - The buttons in the Map Details collide with the title
 - "Description" headline is unnecessary and doesn't exist in the equivalent Mod Details anyway.
 - Install button in Mod Details has the wrong button style

**Comment by Sheikah45** [comment]
does this still apply? The PR was closed saying not needed

**Comment by BlackYps** [comment]
This still applies. I just never finished it to properly use the JFXDialog. You are welcome to finish the PR. I will focus more on tmm and the league system.

**Comment by 1-alex98** [comment]
no it does not apply any more... @BlackYps have a look at develop. We are not using JFX anymore at all

**Comment by BlackYps** [comment]
Well the pr does not apply anymore, but the issue still persists. Some of these can be fixed by simply changing the layout in the fxml files, so these should be relatively easy to reuse.

**Comment by Sheikah45** [comment]
I think most of these have been fixed
