### ISSUE TITLE
New client version shown as -1 bytes

### ISSUE THREAD

**Issue by Askaholic** [FAForever/downlords-faf-client#1737]
Happens both on German and English translations.
![image](https://user-images.githubusercontent.com/17941539/83319587-5514c600-a1ec-11ea-8663-6b7cd02fb004.png)

## System info
OS: Windows
Client: 1.1.7-RC1

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by 1-alex98** [comment]
@Brutus5000 already looked into it I think....

**Comment by Brutus5000** [comment]
Our content server throws 403 if you request it with HEAD. We need to check why, might be related to the docker changes on the content-server.

**Comment by Brutus5000** [comment]
Oh wait I tested this on our servers but current file is on Github. And Github gives 403

**Comment by 1-alex98** [comment]
Brutus suggests to kill the display of size and replace by an estimate

**Comment by Sheikah45** [comment]
Is this still a thing?

**Comment by Brutus5000** [comment]
The problem with Github still exists, but since I'm currently uploading files to my mirror for faster download speed, it's not a problem.
