### ISSUE TITLE
Integrate news hub into client

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1738]
**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by micheljung** [comment]
NewsItem, NewsItemListCell etc. are just lying around unused now.

**Comment by 1-alex98** [comment]
Should be deleted then

**Comment by 1-alex98** [comment]
https://github.com/FAForever/downlords-faf-client/issues/1759
