### ISSUE TITLE
Twitch integration

### ISSUE THREAD

**Issue by tobias-strenger** [FAForever/downlords-faf-client#1741]
(suggestion) Next to the username, indicate whether a livestream is available for this player. Add the option "watch live stream" to the context menu in addition to the "watch game" option.

**Comment by 1-alex98** [comment]
How to we know if ppl have a twitch stream?

**Comment by tobias-strenger** [comment]
ppl have to link their account
https://dev.twitch.tv/docs/authentication
you can get the live status using the stream endpoint  https://dev.twitch.tv/docs/api/reference#get-streams

**Comment by 1-alex98** [comment]
Well such a links needs to be built u say...?

**Comment by 1-alex98** [comment]
Then that's the wrong project to open an issue

**Comment by tobias-strenger** [comment]
im not sure if i get what you mean by building a link in this case. obviously ppl have to confirm somewhere that the same person is behind twitch and faf acc. however, if you know which account you can simply check the status via api call. it returns an empty object in case the player is not streaming

**Comment by 1-alex98** [comment]
That would need website/api/db changes... Think that is a little overkill but that would be needed for such a simple feature I am afraid. First it needs integration there.

**Comment by bukajsytlos** [comment]
and then integrate in client, right? so why closed?

**Comment by OCGDFS** [comment]
sorry if i put it in the wrong project. do you want to have this in the api?

**Comment by KionX** [comment]
axel1200 likes to look for a reason to close.

**Comment by 1-alex98** [comment]
yes I do

**Comment by 1-alex98** [comment]
Because issues become useless once they reach a certain count. And if stuff is not really worth the effort then I normally close them :D

**Comment by Sheikah45** [comment]
From my perspective on top of the integration into the db and api this would also require constantly checking twitch to see if people were streaming which is a bit much for the chat user list and not likely to happen.
