### ISSUE TITLE
Implement TMM queuing

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/downlords-faf-client#1744]
- [x] Display matchmaking queues
- [x] Join / leave / interfact matchmaking queues (and the server)
- [x] Game launch

**Comment by Askaholic** [comment]
Since each queue has a `team_size` associated with it, the client UI should prevent you from queueing into a queue for which your party is too large. Unavailable queues should be clearly identifiable in the UI.

We also need to make sure that whenever the party size changes (player joins or leaves), any ongoing queues are cancelled.

**Comment by Askaholic** [comment]
Queue names should be localized. We should not be directly displaying the names sent by the server (unless localization string is not found), those are more internal identifiers.

We should make sure that everything works at smaller screen sizes too. For instance the "Available Queues" panel should be able to move below the party panel if the screen size is too small.

We should probably remove the profile images to save space.

**Comment by Geosearchef** [comment]
The UI is built to work on smaller devices as well.

About the queuenames, we can't localize them as ww might dynamically add queues on the server (e. g. an event queue).

**Comment by Askaholic** [comment]
I tested it yesterday. Making the window small did not play nicely with the UI. The party panel would shrink to a minimum size and then push the queues panel off the screen. The queues panel should be able to pop below the party panel when needed.

While it's possible to add a special event queue, this doesn't me we shouldn't localize them. Yea the localization might lag behind the queue creation, but it's not like the queues are completely changing every day. We won't be getting rid of ladder any time soon. Use the technical name only as a fallback.

**Comment by Geosearchef** [comment]
About the resize, the window is built to work at 1366x768, I'm not gonna make it work for anything lower.

"it should be able to pop bellw the party panel". This is really hard to implement. I thought about placing it there always, but that's bad for wide resolutions. It would also require a completely different layout for the queue cards, as blocks instead of rows.

**Comment by Askaholic** [comment]
Really? How is it done in the ladder tab? Because it works fine there.

**Comment by Katharsas** [comment]
People with laptops that have Full HD at 150% zoom in Windows (like me^^) end up with a window sized like on a  1280 * 720 screen (but of course sharper), so that would be the best minimum resolution/size target for some people.
