### ISSUE TITLE
TMM: Redesign party ui

### ISSUE THREAD

**Issue by Askaholic** [FAForever/downlords-faf-client#1747]
First we are throwing together something that works, but after that we will need to redesign the UI to be more user friendly (and hopefully pretty too).

Need a nice way of:
- Inviting someone to your party
- Seeing who you have invited
- (Cancelling an invite?)
- Seeing who has invited you to a party
- Kicking players from your party
- Seeing what factions each player has selected (is this feature really that important?)
- Seeing who has readied up
- Other player info like rating/country/avatar

Here's a preliminary mockup which may provide inspiration:
![mockup.png](https://i.imgur.com/Mbz6PrG.png)
https://imgur.com/a/8YfjPwQ

And another one:
![tmm_sample](https://user-images.githubusercontent.com/17941539/84094136-91fe6b00-a9eb-11ea-891e-323ca5ad6bb3.png)

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Geosearchef** [comment]
https://github.com/FAForever/downlords-faf-client/tree/feature/new-tmm-ui

Closing as this is now part of the TMM branch and all dev work is done based on it, so we don't have a ton of dangling issues.
