### ISSUE TITLE
Use CalVer

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#1754]
The client currently (kinda) uses semantic versioning. This is good for APIs - which the client isn't. To the user, semantic versions don't mean much, and looking at a version number, he has no idea how current the version is.

Using [CalVer](https://calver.org/), like e. g. IntelliJ does (e.g. 2020.1), versions would become a bit more user-friendly.

Opinions?

**Comment by 1-alex98** [comment]
That does need code adjustments as well

**Comment by Katharsas** [comment]
I doubt the advantages justify the cost of change. Contributers/testers are used to the current schema.

**Comment by micheljung** [comment]
The schema itself doesn't change: x.y[.z] and we could always go for an explicit x.y.z

It would simply be e.g. 2020.6.0 instead of 1.1.8

**Comment by Sheikah45** [comment]
With the next release we will probably be switching to Calver as it helps to give a sense of how old any client is and the current versioning code supports it.

Having surveyed some of the devs there seemed to be no push back.

I intend to use the format YYYY.MM.Minor-qualifier
