### ISSUE TITLE
Refactor leaderboard 

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1757]
**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Brutus5000** [comment]
What is the point of having an issue with no description at all?

**Comment by 1-alex98** [comment]
Shows up in change notes

**Comment by Brutus5000** [comment]
And how does this description help a user?

**Comment by 1-alex98** [comment]
Maybe not but helps me

**Comment by Sheikah45** [comment]
Not clear what this means
