### ISSUE TITLE
Immediate Notifications not working on java fx 14

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1760]
**Describe the bug**
If there is an Exception and an Immediate Notification is supposed to be opened instead an Exception is throwen about being unable to open such a window.

**OS**
Linux or Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by 1-alex98** [comment]
Might be connected to jfoenix

**Comment by 1-alex98** [comment]
Even persitent notifications are broken

**Comment by micheljung** [comment]
I can't reproduce this
