### ISSUE TITLE
Can join ladder games through player context menu

### ISSUE THREAD

**Issue by Askaholic** [FAForever/downlords-faf-client#1761]
**Describe the bug**
When a player is starting a ladder game and they are the host, they will show up in the chat tab as “hosting” and players (who should not be in the game) can join their game through the context menu causing a bugged ladder game (joining player shows up as nomads faction and is set to observer)

**To Reproduce**
(Easier on test)
1. Queue ladder with 2 players
2. Close client for the guest before the game starts.
3. Join the game with a third client through the context menu.

**Expected behavior**
Show ladder game hosts as “playing ladder” and don’t distinguish between hosts and guests.

**OS**
Linux or Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by 1-alex98** [comment]
But this should also be fixed on server, as this might allow uninvolved players to crash games on purpose even if we remove the option in the client.

**Comment by Askaholic** [comment]
Already done: https://github.com/FAForever/server/pull/590
