### ISSUE TITLE
Pagination of the leaderboard

### ISSUE THREAD

**Issue by Tim-eror** [FAForever/downlords-faf-client#1762]
The leaderboard loads 10,000 Items at once when opened. All other items aren't loaded at all: 
-Add Pagination to enable an user friendly interaction withe leaderboard.
-Stop loading all 10,000 items at one time to enhance loading speed.
-Add possibility to check items further than 10,000.

**Comment by 1-alex98** [comment]
A special request needs to be fired when user searches through the leaderboard

**Comment by Sheikah45** [comment]
Will soon be depreciated so closing this issue.
