### ISSUE TITLE
Pagination of online replays

### ISSUE THREAD

**Issue by Aclrian** [FAForever/downlords-faf-client#1764]
Scrolling througth a huge size of replays is frustrating and replays older than 1 year are less relevant:
add a checkbox for only Replays from the last year 
and a Pagination for a better overview

**Comment by norraxx** [comment]
Or we could make "pages" not scrolling. Less memory consumption, faster client behavior.

**Comment by 1-alex98** [comment]
@norraxx pages are the suggestion...
