### ISSUE TITLE
Download all ladder maps before being able to join the queue

### ISSUE THREAD

**Issue by Askaholic** [FAForever/downlords-faf-client#1767]
From discord,
Tagada:
>  Another idea/possible problem
I suppose that Tmm will work like ladder regarding setting up the match which means that if a player doesn't have the map that was selected the client will start downloading it which creates two problems: 
1st: You are able to cancel the download of the map giving you basically the chance to avoid maps you don't like and fuck with the queue + waste time of other people.
2nd. People with really bad internet connection may download the map for some time ( the bigger ones) and if you don't have any loading screen / information that people are connecting then players may think sth broke and before all 4-8 players download and are ready to join someone may quit thinking it's bugged.

>I see 2 potential solutions that should also be implemented into ladder (as this is a problem there aswell, not as big tho since only 2 people are connecting to each other), either make the process of downloading the map invisible to player so that he can't interact with it while displaying info that there is download happening or Force the client to download all the maps before player is accepted to join the queue ( this could lead to people with worse internet connection to wait for quite some time (depending on the pool size too)) which may be a bad thing since they will sit there downloading first patch then maps instead of playing their first game.

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Sheikah45** [comment]
Due to new large map sizes being introduced to the queue and players with limited internet connections this will not be implemented as it may end up blocking the queue for some users over a single map or stressing player's data limits

**Comment by bukajsytlos** [comment]
couldn't there be a button to sync all maps?

**Comment by Sheikah45** [comment]
Possibly although the point of this issue was to force people to have all the maps downloaded before being allowed to queue

**Comment by Askaholic** [comment]
I think it's a nice idea. You wouldn't be forcing people, but you would be encouraging them to do it anyways. In the end it doesn't really matter whether they download the maps because they were forced, or because they chose to do it. 

Right now the only way would be to click the map list and then click download on every map individually. That's quite a few clicks, and adding a way to do that in 1 click may entice people to make use of it.
