### ISSUE TITLE
TMM: Distinguish between automatch and custom lobby games

### ISSUE THREAD

**Issue by Askaholic** [FAForever/downlords-faf-client#1770]
Right now there is special handling for ladder games based on which featured mod the game is using. This needs to be extended to all matchmaker games in general. Since the plan is for matchmaker games to be played on an arbitrary featured mod, we need an additional property that determines if and where the lobby is displayed in the client.

~We'll need to add `init_mode` to the `game_info` message sent by the server, and replace special logic which checks for the ladder featured mod to check for the init mode instead.~

We'll need to add `game_type` to the `game_info` message sent by the server. See the PR https://github.com/FAForever/server/pull/635.

https://github.com/FAForever/server/issues/605

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Brutus5000** [comment]
I'd rather suggest adding a game type as described in https://github.com/orgs/FAForever/projects/8
