### ISSUE TITLE
Nomads Replays fail to open, normal replays are fine

### ISSUE THREAD

**Issue by Exotic-Retard** [FAForever/downlords-faf-client#1771]
**Describe the bug**
Open any replay containing the nomads mod, the client works fine, but then the game says that the replay is corrupted on launch. Non-nomads replays load fine.

Broken replay (nomads): https://content.faforever.com/faf/vault/replay_vault/replay.php?id=11463794

working replay (not-nomads): https://content.faforever.com/faf/vault/replay_vault/replay.php?id=11762033

99% sure that this is a regression or some weird bug that set itself; the nomads replays worked perfectly fine in the recent past, less than 2-3 weeks ago, considering i was watching nomads replays back then.

**Screenshots**
https://i.imgur.com/IyelwAO.png

**Comment by Brutus5000** [comment]
@Exotic-Retard Can you correlate the problem to a fa-patch? I'm 99,9% sure that replays of featured mods break, when the fa basemod gets an update. (That is an issue of the replay format however)

**Comment by Exotic-Retard** [comment]
looks like you are right, the old replays break when the base patch is updated. i expected them to desync instead of getting corrupted completely though. i guess that sort of explains the issue, but its still a shame i suppose that old replays totally break like that.

Regardless, thanks for your help <3

**Comment by Sheikah45** [comment]
Should have been fixed with #1866 but will still desync due to issues with featuredmod versioning
