### ISSUE TITLE
Add ability to select the number of players on a generated map

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1773]
**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Katharsas** [comment]
Duplicate of / related to  https://github.com/FAForever/downlords-faf-client/issues/1694

**Comment by Sheikah45** [comment]
Implemented in #1803
