### ISSUE TITLE
Show all search results

### ISSUE THREAD

**Issue by krristi427** [FAForever/downlords-faf-client#1775]
In the Leaderboards tab, the search is done as the user types something on the keyboard, showing the first matching item and the rest of users beneath it. This is however not practical and not efficient, thus it is aimed to narrow the search results down to users matching the input pattern: 
ex. if "kr" is given, the results should look something like "krristi"; "kraboom" and so on.

**Comment by Askaholic** [comment]
Basically you are proposing to filter the entire leaderboard based on the search term. So it will only show entries that match what you're typing. In that case it might be nice to have some way of easily jumping to that entry in the list while clearing the filter so you can see who is close to that player on the leaderboard.

**Comment by 1-alex98** [comment]
Well with pagenation that the api supports that can be done... Similar to the leaderboard on the website
