### ISSUE TITLE
Search by Enter click

### ISSUE THREAD

**Issue by krristi427** [FAForever/downlords-faf-client#1776]
The user should also be given the opportunity to search a specific entry of the leaderboard table after clicking enter for increased comfort.

**Comment by Askaholic** [comment]
Can you elaborate a little bit? There is no need to press enter because it searches as you type. Do you mean it should select the text in the textbox so you can just type another username without needing to delete the old name?

**Comment by 1-alex98** [comment]
Yes but with pagenation and not all reults loaded there is the need for a seperate server request

**Comment by Sheikah45** [comment]
Current leaderboard searches as you type
