### ISSUE TITLE
TMM: Switch to new rating type format

### ISSUE THREAD

**Issue by Askaholic** [FAForever/downlords-faf-client#1791]
We are planning on moving rating data from the current tables to new more generic tables created in this PR: https://github.com/FAForever/db/pull/197. The purpose of these new tables is to support more than 2 rating types, primarily for team matchmaking.

The client needs to be able to store arbitrarily many different rating types for each player. This means among other things, moving the `globalRating` and `leaderboardRating` properties on the `Player` class to some `get/set` table with string keys. Each rating type (referred to in the database as a `leaderboard`) has a technical name used to identify it. The technical names for global and ladder are `global` and `ladder_1v1` respectively as defined here https://github.com/FAForever/db/pull/217. We may want to add a `KnownRatingType` enum with these values as there are special cases for them all over the code.

Todo list:
- Store ratings in a get/set table. Get it from `player_info`: https://github.com/FAForever/server/blob/5be249b4d2de29667aad9ae035567bda8e638087/server/players.py#L151
- Use the `rating_type` property of the `game_info` message for determining which rating to display. 
https://github.com/FAForever/server/blob/5be249b4d2de29667aad9ae035567bda8e638087/server/games/game.py#L865
    - Rating shown on the game list
    - Rating passed to FA
- Show all ratings in the get/set table in chat user list

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by MaxNF** [comment]
I'm against spawning more KnownSmthType. You just wrote in Zulip: 

> For a similar reason I don’t think we want an enum for LadderQueue. Which queues are available depends entirely on the server. Some queues may not be permanent (special event queues that run for a month or whatever). At most I think it would be ok to have a special case for 1v1 because that is pretty much guaranteed to be permanent

That's why we do not need to hardcode rating type technical names either. What if we would like to display a rating for some temporary event queue? It will require changing the client code, that is not acceptable, right?
Maybe we can receive all ratings entirely from the server (or rest API) along with their parent queue titles and populate the UI with them?

**Comment by Askaholic** [comment]
Yes but currently global and ladder ratings have special cases everywhere. We won't be able to get rid of them in one pass, we will need to do it incrementally.
