### ISSUE TITLE
Allow Themeing

### ISSUE THREAD

**Issue by BlackYps** [FAForever/downlords-faf-client#1792]
Enable the theme dropdown menu.

**Comment by 1-alex98** [comment]
[Alex.zip](https://github.com/FAForever/downlords-faf-client/files/4808615/Alex.zip)

**Comment by 1-alex98** [comment]
![theme](https://user-images.githubusercontent.com/19996713/85212411-b0048d80-b352-11ea-8a0f-71846316f420.gif)

**Comment by 1-alex98** [comment]
[Alex.zip](https://github.com/FAForever/downlords-faf-client/files/4967300/Alex.zip)
