### ISSUE TITLE
Proper restart on language or theme change

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1794]
Instead of offering the user to close the app. Offer a restart. It is tricky and can probably be achieved best with install4j exe.

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Sheikah45** [comment]
Plenty of apps have settings that require a manual restart so users are used to it at this point so I am not sure the added qol is worth the development burden
