### ISSUE TITLE
Notifications appear twice

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/downlords-faf-client#1798]
When I get a notification of a ladder game being a available or a new private message, the same notification is displayed twice.

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by 1-alex98** [comment]
How do I reproduce that?

**Comment by JaggedAppliance** [comment]
Turn on notifications, I don't know what else to say. It happens every time.

**Comment by 1-alex98** [comment]
Strange pretty sure that's not the case for me...

**Comment by 1-alex98** [comment]
Log maybe... Whats the client version? Any idea why your system setup might be special?

**Comment by JaggedAppliance** [comment]
I have the latest client. I reenabled notifications again so I'll send logs once I see it happen again. This is a clean install also, on a new computer.

**Comment by JaggedAppliance** [comment]
Ok I did a little testing with Knightly. PMs didn't trigger two notifications but being pinged/mentioned in Aeolus triggered doubled notifications. 

[downlords-faf-client.log](https://github.com/FAForever/downlords-faf-client/files/4915153/downlords-faf-client.log)

**Comment by 1-alex98** [comment]
Well ok, so u get 2 notifications if pinged in aeolus. That is some thing somebody could get started with... You are also a moderator right? Maybe that also has an effect

**Comment by JaggedAppliance** [comment]
I'm not a moderator.

**Comment by Sheikah45** [comment]
Cannot reproduce on current version

**Comment by Sheikah45** [comment]
Had it happen to me yesterday again

**Comment by 1-alex98** [comment]
only the chat thing right?

**Comment by Sheikah45** [comment]
Yes only when mentioned in aeolus

**Comment by Sheikah45** [comment]
Can no longer reproduce after the recent chat reworks
