### ISSUE TITLE
leaderboard context menu

### ISSUE THREAD

**Issue by Aksiznarf-Uar** [FAForever/downlords-faf-client#1800]
It would be nice to easily be able to find out information about a player you saw on the leaderboard.

I would like to add a context menu similar to the one you get when right-clicking on a player in the chat. It would show the following options: show user info, send private message, copy username, add/ remove friend, add/ remove foe, view replays.

**Comment by micheljung** [comment]
Or, given that the leaderboard table is quite empty anyways, we could add those actions as icons to each row. Therefore it's more visible and requires one less click.

**Comment by 1-alex98** [comment]
Would be an idea

**Comment by Sheikah45** [comment]
Leaderboard is getting depreciated

**Comment by BlackYps** [comment]
But it is still relevant for the league leaderboard

**Comment by Sheikah45** [comment]
Already implemented
