### ISSUE TITLE
Search field for mods and presets.

### ISSUE THREAD

**Issue by zfxstd** [FAForever/downlords-faf-client#1804]
I'm always frustrated when i want to create game with mods. I have a lot of mods downloaded and i need every time to find mods which i want to activate in my big modlist. The main problem - is time. You need spend some minutes just to find it all, sometimes you have dublicate mods and you not sure which mod that was.

One of my solutions is to add search field, like is it now for maps. 

Second solution, which going to be best one, adding presets. For example, i can save settings like gamename\map\mods\etc in game create menu and then load in 1-2 clicks, so i dont need to search and spend much time for this.

Thanks. 
P.s. Sorry for my bad english :)

**Comment by 1-alex98** [comment]
Presets are a big change. Needs extra control and UI for that

**Comment by ghost** [comment]
working on this !

**Comment by zfxstd** [comment]
That's awesome! Thanks.
