### ISSUE TITLE
Clicking view replays doesn't show the replays of a player without having the maps loaded

### ISSUE THREAD

**Issue by krristi427** [FAForever/downlords-faf-client#1807]
**Describe the bug**
Clicking view replays doesn't show the replays of a player without having the maps loaded

**To Reproduce**
once in chat, upon clicking show replays on a random player for the first time, the program switches to vault/maps and stays there. Once this action is executed again, the program behaves properly 

**Expected behavior**
Once on view replays is clicked, the program should jump to vault/replays, without having to load maps first

**Comment by 1-alex98** [comment]
@BlackYps what happened to the fix that I suggested on this...?
