### ISSUE TITLE
Autojoin language channels

### ISSUE THREAD

**Issue by Cheyans** [FAForever/downlords-faf-client#181]
http://forums.faforever.com/forums/viewtopic.php?f=2&t=6270&start=10#p118347

**Comment by Geosearchef** [comment]
Result of Discussion from slack, (phillipjfry, rackover, axel, geo):

- "so we need to autojoin aeolus, prompt people for language on first start, create an option to auto join own language channel, and create options top autojoin any channel"
- maybe make aeolus unclosable

**Comment by 1-alex98** [comment]
How do I know what the native language channel is called?!

**Comment by Geosearchef** [comment]
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by 1-alex98** [comment]
So is it the native language name?

**Comment by Geosearchef** [comment]
I'd say we just define it that way

**Comment by 1-alex98** [comment]
And what language do we wann Provide all?

**Comment by micheljung** [comment]
I'd make it so that the client initially detects the OS language and stores it in the settings. After that, the user should be able to change it in the settings. Multiple languages should be allowed.

**Comment by Brutus5000** [comment]
Fixed in https://github.com/FAForever/downlords-faf-client/pull/854
