### ISSUE TITLE
Checkbox to only show replays from last year in online replays 

### ISSUE THREAD

**Issue by jofaul** [FAForever/downlords-faf-client#1810]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by micheljung** [comment]
Please write a proper issue description.

Also, the replay search already has the option to search by date. Adding another checkbox that is basically redundant breaks the concept and opens the door for more such requests
- "I want a checkbox that only shows games that I played"
- "I want a checkbox that only shows games that had no mods"
- "I want a checkbox that ..."

So I'm not very keen on seeing this being added.

**Comment by 1-alex98** [comment]
This is something we want 100% as it will dramatically reduce server load and something @Brutus5000 asked for. Normally nobody searches for 7 year old replays those are broken anyways in 90% of cases. So adding this filter by default will make searches a lot quicker and is what Server admins ask for
