### ISSUE TITLE
Feature Request: UI Mod Manager

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/downlords-faf-client#1829]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%245%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/FAForever/downlords-faf-client/issues/1829)

Currently, to change the enabled UI mods you have to host a game. 

I'd like a mod manager like the one available in the old python client which allows me to change which UI mods are enabled without having to host a game.

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- $5.00 have been anonymously funded.
### Submitted pull Requests
- [#1838 Mod manager](https://issuehunt.io/r/FAForever/downlords-faf-client/pull/1838)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/FAForever/downlords-faf-client/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by 1-alex98** [comment]
That already exists

**Comment by 1-alex98** [comment]
I mean if you host a game you can select the mods enabled in the client. There is however no way of telling sim mods and UI mods apart. So what is your feature request???

**Comment by JaggedAppliance** [comment]
It doesn't exist and my feature request is quite clear.
![image](https://user-images.githubusercontent.com/5166284/87862963-b2580880-c94d-11ea-96ca-5fa0cde73732.png)

**Comment by 1-alex98** [comment]
Not clear to me sorry

**Comment by 1-alex98** [comment]
From where can i open it? Can it only select and deselect them? Can it delete installed ones? About about sim mods? Does it only show UI mods?

**Comment by micheljung** [comment]
The title is `UI Mod Manager`, I have a strong feeling that it's only about UI and not sim mods :P

**Comment by 1-alex98** [comment]
Well maybe but would u not do it for both since it is basically the same. Or would you not make a mod manager and then make people select if they wanna manage UI or SIM mods?

**Comment by 1-alex98** [comment]
Making a UI mod only manager makes little sense to me if u can do a UI/SIM mod amanager where u can filter for UI or SIM mods...

**Comment by JaggedAppliance** [comment]
I just have no interest in or use for a SIM mod manager.

**Comment by 1-alex98** [comment]
![grafik](https://user-images.githubusercontent.com/19996713/88096464-f722b000-cb96-11ea-91b8-93b8cfef4011.png)

**Comment by 1-alex98** [comment]
![grafik](https://user-images.githubusercontent.com/19996713/88096493-043f9f00-cb97-11ea-9cd7-2737ea52dd00.png)

**Comment by 1-alex98** [comment]
Also redid create game dialog. Made map image as big as possible. And used the same mod manager there. We could add thre dots or some other way for options to every mod so one could for example do "view details" or "deinstall"

**Comment by 1-alex98** [comment]
> 
> 
> I just have no interest in or use for a SIM mod manager.

Well u might not but others and would allow an overview of installed mods in general.

**Comment by JaggedAppliance** [comment]
Nice one 👍
