### ISSUE TITLE
Chat filter is no longer applied for people joining

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#183]
When the chat user list is filtered by a name in the search field, this filter is no longer applied to people joining afterwards.

I say "no longer" because I'm 99% sure I explicitly implemented this case, and that it worked :-)

**Comment by Cheyans** [comment]
I'm aware of this, I was too lazy to fix it at the time _hides_

**Comment by micheljung** [comment]
Aaaaand we have an assignee :D

**Comment by micheljung** [comment]
> btw when you fix that, could you also make change the gear-icon to the filter-icon and make it *not* to be on top of the text field? :)
