### ISSUE TITLE
Allow managing mods for launch of normal Campaign client

### ISSUE THREAD

**Issue by starslab** [FAForever/downlords-faf-client#1833]
Sometimes I get a bit nostalgic and just want to waste time in the Campaign, without worrying about my idiocy being recorded for all of time. Also I like the full briefings. But I also like the core changes and enhancements in FAF.

I can indirectly get what I want by watching a broken replay in the Vault. This will launch Forged Alliance with the last set of mods I had configured, produce a bad replay error message, and then leave me at the Main Menu, from where I can go and play the campaign.

It would be nice to have this function directly available without depending on broken replays.  If you feel like working miracles, it would be awesome if you could allow the playing of the original Supreme Commander campaign this way as well.

**Comment by 1-alex98** [comment]
These are two things in one ticket. And btw both things were asked before in other issue but dont feel like searching for them now.

**Comment by 1-alex98** [comment]
And u can acctually start the Forged Alliance.exe in C/ProgrammData/bin will also start you the FAF version of FA

**Comment by 1-alex98** [comment]
I think, not sure if you need to give it the init.lua as well
