### ISSUE TITLE
Update M&M Top Picks List May-July 2020

### ISSUE THREAD

**Issue by CouncillorMorax** [FAForever/downlords-faf-client#1834]
Maps to be Added:

July 2020 Additions
--
Adaptive Siberia |   | 15966 |   | Robustness
Adaptive Step Forward |   | 15726 |   | Robustness
Adaptive Rainy Day |   | 15557 |   | Robustness
Palaneum |   | 15955 |   | Chosen
Turtle Rocks |   | 15819 |   | Lenkin
May 2020 Additions
Adaptive Hutts Clutch |   | 15313 |   | Arhurt
Miners End |   | 14880 |   | ElectroMex9000
Gates of Anubis |   | 14735 |   | Mozy
Adaptive Kusoge |   | 14403 |   | Petric
The Crucible |   | 15257 |   | biass
Amoor |   | 13600 |   | Chosen

Maps to be Removed:

Maps to Remove July 2020
--
  |   |   |   |  
Adaptive Canis River |   | 6826 |   | Modified by CookieNoob
Adaptive Hilly Plateau |   | 8061 |   |  
Selkie Isle |   | 5581 |   | Blodir

**Comment by CouncillorMorax** [comment]
Not sure why the table setup is not working here... let me know if this is easier to follow:

https://docs.google.com/spreadsheets/d/1XnA83r2UMewEf2oY2E5YHWpUlO_TftgxbYzntddm0ok/edit#gid=0

**Comment by 1-alex98** [comment]
Not in the client repo. Server admin needs to do this

**Comment by Brutus5000** [comment]
Aw come on we don't have a repo for everything and I need a reminder

**Comment by Brutus5000** [comment]
Done
