### ISSUE TITLE
Map Generator not producing identical maps

### ISSUE THREAD

**Issue by Sheikah45** [FAForever/downlords-faf-client#1836]
Map names are forced to be lower case by the client and this causes the seed to be different between players when generating map names as the host has a map name with capital letters in the seed.

**Reproduce**
Generate a map as host in client and have another player join on separate client

**Expected behavior**
Generated map name should be the same on all clients.

**Comment by Katharsas** [comment]
Should https://github.com/FAForever/downlords-faf-client/pull/1788/commits/3fd54d238db31e581a13735c82d0a1f098c0778b maybe be reverted with the switch to Base32?

**Comment by Sheikah45** [comment]
Yes that can be reverted since there is no more case sensitivity in the map names.
