### ISSUE TITLE
Use Fallback Vault Location as Default

### ISSUE THREAD

**Issue by Sheikah45** [FAForever/downlords-faf-client#1848]
Currently the client tries to place maps and mods into a sub folder in the documents folder. This causes issues with some players not having maps be downloaded correctly or having a difference between where the game looks for maps and where maps are downloaded.

This could potentially be fixed by defaulting to the fallback vault location in programdata as the default and also gives a consistent place to find the maps

Will need to include ability to either migrate maps or use both locations for compatibility

**Comment by foodlfg** [comment]
especially on Linux. 
you have to turn it on anyways if you want a working client.
so it makes sense.

i dont know what is the disadvantage of this on windows.

**Comment by 1-alex98** [comment]
Well there is code that turn it on on linux

**Comment by foodlfg** [comment]
> Well there is code that turn it on on linux

oh nice this means i can remove that step from the wiki.

**Comment by 1-alex98** [comment]
Better try before removing it but should happen automatically
