### ISSUE TITLE
Client sends `civilian` as matchmaker faction

### ISSUE THREAD

**Issue by Askaholic** [FAForever/downlords-faf-client#1852]
Some people trying to reproduce the rating bug on the test server and this happened:
```
TRACE    Aug 05  23:11:18 LobbyConnection                << Blodir: {'faction': 'civilian', 'mod': 'ladder1v1', 'state': 'start', 'command': 'game_matchmaking'}
ERROR    Aug 05  23:11:18 LobbyConnection                'civilian'
Traceback (most recent call last):
  File "/code/server/lobbyconnection.py", line 162, in on_message_received
    await handler(message)
  File "/code/server/lobbyconnection.py", line 849, in command_game_matchmaking
    self.player.faction = message['faction']
  File "/code/server/players.py", line 84, in faction
    self._faction = Faction.from_string(value)
  File "/code/server/factions.py", line 14, in from_string
    return Faction.__members__[value]
KeyError: 'civilian'
WARNING  Aug 05  23:11:18 LobbyConnection                Client Blodir dropped. Garbage command: {'faction': 'civilian', 'mod': 'ladder1v1', 'state': 'start', 'command': 'game_matchmaking'}
```

Somehow the client sent the string `civilian`, but it should only be sending one of `uef, seraphim, cybran, aeon`.

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by 1-alex98** [comment]
That might be @FemtoZetta messing with the faction enum

**Comment by FemtoZetta** [comment]
I doubt that, this was all I changed in the enum:
![grafik](https://user-images.githubusercontent.com/61892809/89515124-3c192a00-d7c6-11ea-8f98-0c372ae7c133.png)

**Comment by 1-alex98** [comment]
ok cool, we will have to look into to it then

**Comment by Sheikah45** [comment]
Likely fixed with change to consistent java commons enum and matchmaker changes
