### ISSUE TITLE
Mac build

### ISSUE THREAD

**Issue by tatsujb** [FAForever/downlords-faf-client#1854]
Start serving Mac builds for this client. 

People on mac resort to building the python client, as per : https://forums.faforever.com/viewtopic.php?f=2&t=16947

Would it be possible to start building for mac as well the way you already do for linux? 

Just asking, I don't have a mac nor do I plan to. 

And yes this would be for pre-Big Sur macs, I imagine that building for the new ARM architecture those have is not easy.

**Comment by 1-alex98** [comment]
Yes it would be possible but I don't have a mac so I am not gonna do that. There is also 1 or 2 issues neeing fixing on mac I think. But all in all java fx is cross platform.

**Comment by 1-alex98** [comment]
It needs somebody with a mac to do that

**Comment by Scabber** [comment]
While im just a tester and shouldnt be talking ... i have tried to compile on my small mac mini. It does have issues (Used same Source, Software and Tools as Win version which runs). 
![MAC compiler output](https://user-images.githubusercontent.com/1526005/92009699-2c4f2000-ed49-11ea-83f3-159a7e227699.png)
i looked at them and i have to say this is not just a 5 minute fix. But if *somebody* fixes these i can provide a mac build.

**Comment by 1-alex98** [comment]
if anybody wants to show me how to set up a mac VM :D

**Comment by tatsujb** [comment]
this seems like a good guide : https://en.wikibooks.org/wiki/VirtualBox/Setting_up_a_Virtual_Machine/Mac_OS_X

**Comment by 1-alex98** [comment]
> The manual installation requires access to the Mac App Store through an existing installation of macOS.

Apple does not like me do develop software for their platform.

**Comment by Sheikah45** [comment]
Same as https://github.com/FAForever/downlords-faf-client/issues/1972
