### ISSUE TITLE
Search bar in Spooky database uses dark grey text on a black background

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/downlords-faf-client#1855]
In the client:
![image](https://user-images.githubusercontent.com/5166284/90173039-b8e66e00-dd9b-11ea-93a7-b8fb8cc208e4.png)

![image](https://user-images.githubusercontent.com/5166284/90172981-a704cb00-dd9b-11ea-86f9-f33c13a641d3.png)

**Comment by 1-alex98** [comment]
Thats cause of the web engine of the client but we can not help it . The only solution is the site changes or it stays that way

**Comment by JaggedAppliance** [comment]
It looks like this on the site:
![image](https://user-images.githubusercontent.com/5166284/90185650-f1dc0e00-ddae-11ea-88a3-70a2f0c5e65e.png)

https://faforever.github.io/spooky-db/#/

**Comment by JaggedAppliance** [comment]
Also why close this? It is a legitimate issue.

**Comment by 1-alex98** [comment]
But there is nothing that can be done
