### ISSUE TITLE
1.2.0 RC1 - Linux - The close button is not displayed for modal windows

### ISSUE THREAD

**Issue by foodlfg** [FAForever/downlords-faf-client#1858]
**Describe the bug**
The close button is not displayed for modal windows
It is there, working but no X can be seen.

**Screenshots**
https://imgur.com/qMmxGBm

**OS**
Linux, Ubuntu 20.04 LTS, openjdk-14-jre, Gnome 3

**Comment by Sheikah45** [comment]
A fix was added in the most recent commit so should be fixed in next release client
