### ISSUE TITLE
1.2.0 RC1 - who is wining a replay is not displayed, no button

### ISSUE THREAD

**Issue by foodlfg** [FAForever/downlords-faf-client#1861]
**Describe the bug**
I cant make the client display who won a replay. There is no button anymore for that. 

**Screenshots**
https://i.imgur.com/qMmxGBm.png

OS
Linux, Ubuntu 20.04 LTS, openjdk-14-jre, Gnome 3

**Comment by 1-alex98** [comment]
@Sheikah45 u fixed that as well right?

**Comment by 1-alex98** [comment]
he fixed it
