### ISSUE TITLE
1.2.0 RC1 - Login screen - password field should be focused

### ISSUE THREAD

**Issue by foodlfg** [FAForever/downlords-faf-client#1862]
**Describe the bug**
The focus on the login screen should be on the password field if the user name is already loaded from the config file.

The user/i expects to be able to write the pass immediately after the login screen appears and if he has already logged in before. in this case end up writing my pass into the name field while revealing it. :3

**OS**
Linux

**Comment by 1-alex98** [comment]
Was this the case before? it was not right?

**Comment by foodlfg** [comment]
> Was this the case before? it was not right?

no, the 1.1.9 client focuses on the password field just fine.

**Comment by 1-alex98** [comment]
ok lemme see

**Comment by 1-alex98** [comment]
fixed it
