### ISSUE TITLE
Pagination last pages empty

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1868]
**Describe the bug**
In many categories the last few pages are empty. E.g. mod most positive.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/19996713/91555474-61b2d280-e931-11ea-945a-fe101b544147.png)

**OS**
Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Sheikah45** [comment]
I noticed this when I was creating the pagination and it seems to be an api issue as the api reports that there are more pages and items than there actually are. It might require an api change to correct this.

**Comment by 1-alex98** [comment]
This will probably be an elide.io issue we need to report then

**Comment by bukajsytlos** [comment]
can we have an example query?

**Comment by 1-alex98** [comment]
on it

**Comment by 1-alex98** [comment]
![grafik](https://user-images.githubusercontent.com/19996713/91588417-68a10b80-e958-11ea-9ad0-fd29b00e0e11.png)

**Comment by 1-alex98** [comment]
http://api.faforever.com/data/mod?sort=latestVersion.reviewsSummary.lowerBound&page[size]=20&page[totals]&page[number]=64

**Comment by Brutus5000** [comment]
Can somebody check if it's fixed now?

**Comment by bukajsytlos** [comment]
well the given url now returns data so I would say yes :D

**Comment by bukajsytlos** [comment]
@axel1200

**Comment by 1-alex98** [comment]
seems fixed
