### ISSUE TITLE
1.2.0 - test very small (likely DPI settings ignored)

### ISSUE THREAD

**Issue by tomaskir** [FAForever/downlords-faf-client#1877]
**Describe the bug**
With previous versions, text in the client was much larger (likely scaled properly with DPI settings).
In 1.2.0, all text in client is very small

**To Reproduce**
Run client on high-res monitor (2k / 4k)

**Expected behavior**
DPI settings should be applied properly to the client - as it seems it was in older versions

**Screenshots**
![image](https://user-images.githubusercontent.com/8025781/91878495-adda7b80-ec7f-11ea-88af-766af032ae8b.png)

**OS**
Windows

**Comment by 1-alex98** [comment]
@micheljung did a new theme maybe the size of text in this theme is no longer density dependent

**Comment by Sheikah45** [comment]
From looking into this I don't think the text was ever density dependent. I think this is just a factor of the theme change
