### ISSUE TITLE
Indicate rehosted games

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#188]
Rehosts should be tagged with some indicator

**Comment by KaukaHan** [comment]
I think this can be closed. players can edit the lobbytitle after they rehosted if they want to. Most rehosts are due to disconnects or laggy players so the players know that the host is going to rehost.

**Comment by Sheikah45** [comment]
This is specifically referring to when people use the rehost option from inside of the game

**Comment by KaukaHan** [comment]
does that change anything ? i think my point is still valid.

**Comment by Sheikah45** [comment]
Probably right
