### ISSUE TITLE
Fix scaling

### ISSUE THREAD

**Issue by FemtoZetta** [FAForever/downlords-faf-client#1887]
With 1.2 we went from 
![this](https://user-images.githubusercontent.com/61892809/92286786-7aa22180-eef7-11ea-880d-ff6d2dcc6c63.png)
to ![this](https://user-images.githubusercontent.com/61892809/92286809-8beb2e00-eef7-11ea-8dae-528221944d28.png)

Please fix, everything is way too small now.

**Comment by 1-alex98** [comment]
this is intended

**Comment by FemtoZetta** [comment]
Ok, wow that's terrible.
