### ISSUE TITLE
Factory Repeat Build Hotkey Doesn't Work

### ISSUE THREAD

**Issue by jkstpierre** [FAForever/downlords-faf-client#1893]
I use a lot of hotkeys while playing faf, but I recently noticed that my hotkey for factory repeat build (currently bound to the Z key) no longer works. All my other hotkeys work fine, but no matter what key I bind for factory repeat build it doesn't work. I've reinstalled both Supreme Commander and the FAF client so I really have no idea what's causing this. FYI, I am on the latest version of the faf client (v1.2.0). 

On a separate note, I tried replicating this issue by playing the vanilla game on steam but I found that it is completely broken now. Whenever I start a skirmish, the map loads but then the game just freezes and my com never spawns.

**Comment by 1-alex98** [comment]
Definetely the wrong Repository the client has nothing to do with this...

**Comment by 1-alex98** [comment]
Also provide logs

**Comment by 1-alex98** [comment]
https://github.com/FAForever/fa
