### ISSUE TITLE
Reset Password leads to 400 Error

### ISSUE THREAD

**Issue by shobhik** [FAForever/downlords-faf-client#1894]
On the latest version (1.2.0 in the bottom left of my screen), trying to reset my account password results in an error message being displayed. The error JSON points out a missing field `currentPassword` expected server-side but since I did enter text in the UI maybe it's being stored as a different field name locally? 

Repro instructions:
Hamburger icon > Settings > Account > (fill in fields) > Change Password

Don't have a log file but the 400 error is shown in the screenshot below as JSON text:

![image](https://user-images.githubusercontent.com/1535459/92678180-42755700-f2da-11ea-932d-b3cf6f089ec5.png)

Oh, and I'm running Windows 10... LMK if you need further instructions to reproduce/debug

**Comment by 1-alex98** [comment]
Just so you know you can reset your password on our website. We might just remove it from the client. We had a discussion before if it should be there after all.

**Comment by shobhik** [comment]
Thanks @axel1200! Appreciate the heads up - I went ahead and reset my pw on the website.

**Comment by Sheikah45** [comment]
Reset password removed
