### ISSUE TITLE
Tutorials not starting on Linux

### ISSUE THREAD

**Issue by tneo** [FAForever/downlords-faf-client#1897]
**Describe the bug**
With the linux Faf client tutorials are not launching.

**To Reproduce**
1) Start client
2) Navigate to tutorials
3) Click on launch tutorial

**Log or error message**
`2020-09-10 15:34:37.930  INFO 24167 --- [lication Thread] com.faforever.client.update.Version      : fromVersion '1.2' is not newer than toVersion '1.2'. No update is required.
> Patching com/sun/webkit/WebPage ...
> com/sun/webkit/WebPage patching succeeded!
> Patching com/sun/javafx/webkit/prism/WCGraphicsPrismContext ...
> com/sun/javafx/webkit/prism/WCGraphicsPrismContext patching succeeded!
2020-09-10 15:34:48.418  INFO 24167 --- [pool-3-thread-5] c.f.c.patch.GameBinariesUpdateTaskImpl   : Updating binaries to 3714
2020-09-10 15:34:48.497  INFO 24167 --- [lication Thread] c.f.client.fa.ForgedAllianceService      : Starting Forged Alliance with command: [/home/user/.faforever/bin/ForgedAlliance.exe, /init, init.lua, /nobugreport, /log, /home/user/.faforever/logs/game.log, /map, FAF_TUT_FourLeaf_BO] in directory: /home/user/.faforever/bin
/home/user/.faforever/bin/ForgedAlliance.exe: /home/user/.faforever/bin/ForgedAlliance.exe: cannot execute binary file
2020-09-10 15:34:48.523  INFO 24167 --- [pool-3-thread-5] com.faforever.client.game.GameService    : Forged Alliance terminated with exit code 126`

**Expected behavior**
Tutorials can start

**OS**
Linux

**Comment by Brutus5000** [comment]
Looking at this error, I'd like to know if regular games start? It looks like you didn't set the decorator correctly, you are executing the windows binary without wrapping it in wine or anything.

**Comment by 1-alex98** [comment]
I also think this is rather unexpected that the tutorials do not start but regular games do

**Comment by 1-alex98** [comment]
Follow the wiki article on how to setup up faf https://wiki.faforever.com/index.php?title=Setting_Up_FAF_Linux

**Comment by tneo** [comment]
The FAF client starts. I tried creating a game as a test, but that fails with the same message, thus apparently the wrapper is not working for me with FAF.

From within Steam I can launch SupCom (FA) without problems. And based upon the wiki I followed the steps. However I don't have a /tmp/proton_user_name/ directory to copy the run file from. I checked my Steam settings as the Wiki suggest (though I'm not sure what I have to look for) and I launch the game, but no proton_user_name directory is created in /tmp.

Does it matter I only used proton 5?

**Comment by 1-alex98** [comment]
Just follow the wiki setup it tells you what version are fine

**Comment by 1-alex98** [comment]
And if you follow it you jet a script generated that starts the game with proton then you need to enter that script in the client settings so the client starts the script and not the exe. In the log I can clearly see you have not done this cause the client tries to start the exe and not some script as it would do if you followed the wiki.

**Comment by tneo** [comment]
Yes. Steam can launch my SupCom installs with proton 5. However the wiki states I need to copy the run file in order to launch, but the mentioned location (/tmp/proton_user_name) does not exist for me to copy a _run_ file from. And I don't know where I could find that file and Steam can launch the game apparently without that run file.

**Comment by 1-alex98** [comment]
yes but without that it is no wonder it does not work you just make the client start the exe

**Comment by 1-alex98** [comment]
U need to enter something with command line format for executable that makes the game start with wine be that the script or "wine %s" 

Did you set the option that it generates such a file. Please go to the forum and search for technical help that does not seem to be a client bug at all.

**Comment by 1-alex98** [comment]
![Screenshot from 2020-09-11 17-38-32](https://user-images.githubusercontent.com/19996713/92945719-f5b68b00-f455-11ea-8502-b60bae547014.png)
