### ISSUE TITLE
Ability to launch replays and live replays while in a lobby

### ISSUE THREAD

**Issue by Androish** [FAForever/downlords-faf-client#1898]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%246%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/FAForever/downlords-faf-client/issues/1898)

Hey,

Say I am waiting in a lobby to fill, And I want to watch either start a replay from the replay vault or a live replay

I can't do that right now. I know its technically possible to do. If I sign in to another account on the old python client I can launch and view replays there while still in a lobby or in a game in the java client. But I lost access to the other account...

I don't know how easy it is to integrate that feature into this client though.

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $6.00)

- [<img src='https://avatars1.githubusercontent.com/u/16946169?v=4' alt='androish' width=24 height=24> androish](https://issuehunt.io/u/androish) ($6.00)

### Submitted pull Requests
- [#1926 Allow to watch replays while in game option](https://issuehunt.io/r/FAForever/downlords-faf-client/pull/1926)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/FAForever/downlords-faf-client/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by 1-alex98** [comment]
@Androish do you know what you need to do to the game for it to be able to run multiple time??? There was a forum article on that I believe

**Comment by 1-alex98** [comment]
https://forums.faforever.com/viewtopic.php?f=2&t=14434

**Comment by Androish** [comment]
Yeah, I knew it was possible like that. But I did not find the thread(or look very hard)

You can't watch live replays like that.  

I think it would be awesome to be able to watch live replays while waiting in a lobby that never fills :)

And I think it's something more ppl than I would appreciate to be able to do

**Comment by 1-alex98** [comment]
I just needed the thing you needed to  set in game.prefs

**Comment by 1-alex98** [comment]
@Androish already works just needs some clean up and details changed

**Comment by 1-alex98** [comment]
![image](https://user-images.githubusercontent.com/19996713/93667543-01720500-fa87-11ea-899c-1e478c6b5b51.png)
