### ISSUE TITLE
Maps not auto downloading

### ISSUE THREAD

**Issue by Sheikah45** [FAForever/downlords-faf-client#1899]
**Describe the bug**
Maps do not auto download when joining a game due to the server change returning 404 errors for the current urls

**To Reproduce**
join a game with a map you dont have

**Expected behavior**
Should download maps before joining lobby. Vault works fine so just need to change the url

**Comment by Brutus5000** [comment]
There is a temporary redirect in place now to prevent the error until we properly fixed it.
