### ISSUE TITLE
[Branch: develop] clicking enter in the input box when searching replays starts some replay

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1906]
@Sheikah45 you making the buttons for starting replay default buttons triggers them if somebody presses Enter in the search input box. We probably wanna revert them being default buttons. Probably same applies to mod and map buttons for install.

**OS**
Linux or Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Sheikah45** [comment]
Hmm didn't think it would take main focus but will change it
