### ISSUE TITLE
Live reload in development

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1917]
My dream is to not need to restart the client after a made changes. There are ways do do this. One could make some code that reloads the complete tab if clicked on play, chat etc. (only for development). Then it needs hot reload of java classes but I would already pleased if it worked only with the theme files. Since the already have a theming support we should be able to built that easily, but maybe Intelij has some functionality on its own for this maybe using that would be interesting. Also Spring has a thing called Spring Developer tools that are supposed to enable live reload, not sure of those are suitable for us. Anyways researching this topic would be interesting.

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by 1-alex98** [comment]
https://docs.spring.io/spring-boot/docs/1.5.16.RELEASE/reference/html/using-boot-devtools.html

**Comment by 1-alex98** [comment]
I got it to work gonna make a tutorial

**Comment by 1-alex98** [comment]
Also it needs some code changes for it to be working well

**Comment by Sheikah45** [comment]
Does it work only with the theme changes or with code changes as well?

**Comment by 1-alex98** [comment]
See video in PR
