### ISSUE TITLE
Show ladder 1v1 maps only works the second time you click on it 

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1918]
**Describe the bug**
The loading of the starting screen of the map vault covers the 1v1 maps if the vault was not loaded before the button clcik

it used to work but we must have broken it when @Sheikah45 and I refactored the vault

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by BlackYps** [comment]
Seems like a recurring issue :D But I hoped I had fixed it for good last time.
