### ISSUE TITLE
Save game log files by game id

### ISSUE THREAD

**Issue by Askaholic** [FAForever/downlords-faf-client#1927]
The client always tells the game to write to `game.log` which means as soon as you open a lobby your previous log file is destroyed. I would like to request that game files be saved like the python client does it, on a per game basis with the game id in the filename. Maybe add some sort of log rotation if you're worried about disk space.

This would allow for a much easier time debugging strange game bugs that only show up every once in a while, since we'd be able to request the log of a specific game from a user. 

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by bukajsytlos** [comment]
#777
