### ISSUE TITLE
Add the friend icon to games that friend of yours are in

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1928]
In the tiles vie in the top right make the smiley that indicates Friend

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by 1-alex98** [comment]
In table no idea how to indicate it

**Comment by Sheikah45** [comment]
Duplocate of #1966
