### ISSUE TITLE
Rackover Unit Database in Client not redirecing to Git hub Pages on UnitID Link

### ISSUE THREAD

**Issue by MrRowey** [FAForever/downlords-faf-client#1929]
**Describe the bug**
In Version 1.2.0 on the Unit Database page using the Rackover Version not Spooky. when you click on the Unit ID it normaly takes you to the Github Page for that Unit which it dose on the web but Via the client it just shows the following

![image](https://user-images.githubusercontent.com/20344151/93710240-fa0d3300-fb3c-11ea-9fca-75239d474073.png)

**OS**
Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by 1-alex98** [comment]
it does redirect but is unable to display it

**Comment by Sheikah45** [comment]
Fixed in v1.4.2

**Comment by Sheikah45** [comment]
specifically not an issue in javafx 15
