### ISSUE TITLE
Avatar not showing up in Java Client user list 

### ISSUE THREAD

**Issue by FtXCommando** [FAForever/downlords-faf-client#1930]
I had assigned the Winner of Hearts avatar to MadMax recently and discovered that the avatar icon does not show up in the list of users for whatever reason. All other avatars seem to work fine, and the Winner of Hearts avatar functions perfectly well in the aeolus chat as well as in the python client. 

I attached some pictures below. Picture 1 is the python client, picture 2 is it working in aeolus chat (worked in both clients), picture 3 and 4 are showcasing that this specific avatar does not work. 

![winner1](https://user-images.githubusercontent.com/43039749/93710434-be5e7300-fb14-11ea-8edb-3ce3ff4b41cb.png)
![winner2](https://user-images.githubusercontent.com/43039749/93710437-c0c0cd00-fb14-11ea-844e-2f81906434ca.png)
![winner3](https://user-images.githubusercontent.com/43039749/93710439-c3232700-fb14-11ea-8c7f-f7c0cf8cc295.png)
![winner4](https://user-images.githubusercontent.com/43039749/93710440-c5858100-fb14-11ea-9a4b-f2e56cdbc03e.png)

**Comment by micheljung** [comment]
maybe some odd image format

**Comment by 1-alex98** [comment]
No seems to be a normal image 
```
"type": "avatar",
            "id": "136",
            "attributes": {
                "createTime": "2017-03-13T22:18:41Z",
                "filename": "Winner of Hearts.png",
                "tooltip": "Winner of Hearts",
                "updateTime": "2020-07-02T07:50:24Z",
                "url": "https://content.faforever.com/faf/avatars/Winner%20of%20Hearts.png"
            },
```

**Comment by 1-alex98** [comment]
Probably got to give it to someone that investigates it or needs to be uploaded on test server

**Comment by FtXCommando** [comment]
Yeah sure, just write whomever to give it out to over here or on zulip.

**Comment by Sheikah45** [comment]
This was because the url for the avatars is from the server and not properly url encoded so the path is "Winner of Hearts.png" rather than "Winner%20of%20Hearts.png" and the string for the image loading done by not the webview is not properly url encoded
