### ISSUE TITLE
Join Discord Button

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#1933]
I think our Discord Server is still quite unknown. You'll only find it if someone tells you or you go to Menu > Links Overview > Discord

I'd like to have a prominent button for joining Discord.

**Comment by FtXCommando** [comment]
It would be really good if there was a way to put such a button immediately on the new matchmaker tab. I feel like putting it in an area where you need to click 3 times to get it won't be as efficient for filling it with casual users.

**Comment by micheljung** [comment]
This is my suggestion:

![image](https://user-images.githubusercontent.com/1864183/93713598-49635b80-fb5d-11ea-8144-7fb2c307c871.png)

It's pretty much implemented, I just need to find out how to truly detach the process from the client.

**Comment by 1-alex98** [comment]
Let's do this I like it

**Comment by 1-alex98** [comment]
> It would be really good if there was a way to put such a button immediately on the new matchmaker tab. I feel like putting it in an area where you need to click 3 times to get it won't be as efficient for filling it with casual users.

Waiting for things that not yet exist is not really a thing I like to do. Has not worked with ICE either XD

**Comment by 1-alex98** [comment]
> This is my suggestion:
> 
> ![image](https://user-images.githubusercontent.com/1864183/93713598-49635b80-fb5d-11ea-8144-7fb2c307c871.png)
> 
> It's pretty much implemented, I just need to find out how to truly detach the process from the client.

Why don't you just open it in the browser? Cause not everybody has Discord installed. Browser finds out if it is installed.

**Comment by 1-alex98** [comment]
![image](https://user-images.githubusercontent.com/19996713/93714042-2d14ee00-fb60-11ea-9f51-7ce2a07aa174.png)

**Comment by micheljung** [comment]
> Why don't you just open it in the browser? Cause not everybody has Discord installed. Browser finds out if it is installed.

Because I have higher ambitions than that ;) it sucks when it needlessly opens the browser. Of course, I also covered the case where Discord isn't installed.
