### ISSUE TITLE
Sign code in CI pipline

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1941]
Get a certificate for code signing and use install4j to do so

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Sheikah45** [comment]
Haven't been able to find a cert that works with out automated pipeline so closing for now
