### ISSUE TITLE
better utilities for vault  searches (custom search presets & slider for min max rating) 

### ISSUE THREAD

**Issue by GrunttiNoob** [FAForever/downlords-faf-client#1944]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2410%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/FAForever/downlords-faf-client/issues/1944)

currently applying the vault searches for online games is a pain in the buttocks. Moreover old queries are lost every time the client is restarted.

To make commonly used searches like less of an hazzle:

- Tick box (or somesuch) for saving previously used vault search queries as a presets
- Buttons for quickly accessing said presets
- Ability to name the search presets ("ladder 1500+", "long setons" for example)
- Sliders for setting min & max rating for searches
- ability to choose between viewing the search results in vault as table rather than tiles (as in the play tab)
![kuva](https://user-images.githubusercontent.com/71841656/94179972-fc0d2400-fea5-11ea-9edc-7e3514ae5840.png)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $10.00)

- $10.00 have been anonymously funded.
### Submitted pull Requests
- [#2044 Feature/#739 vault search ui](https://issuehunt.io/r/FAForever/downlords-faf-client/pull/2044)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/FAForever/downlords-faf-client/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by Sheikah45** [comment]
Fixed in #2044
