### ISSUE TITLE
Font Size in Lobby

### ISSUE THREAD

**Issue by Passenger4761** [FAForever/downlords-faf-client#1945]
The Lobby font seems to have got a lot smaller with the recent update. 

Is there anyway to add an update that gives an option to increase text size in the lobby?

Regards,

Passenger

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by 1-alex98** [comment]
Lobby means where you wait for a game to fill up? Then this is not the right place for your bug report @Passenger4761

**Comment by Sheikah45** [comment]
I believe they just mean the client in general as this was around the time of the 1.2.0 update that changed the UI a lot.

**Comment by Sheikah45** [comment]
Duplicate of #1877
