### ISSUE TITLE
Custom filter for displaying lobbies in play tab

### ISSUE THREAD

**Issue by GrunttiNoob** [FAForever/downlords-faf-client#1946]
a tickbox for applying and saving custom lobby filters 
![kuva](https://user-images.githubusercontent.com/71841656/94181917-d9c8d580-fea8-11ea-958c-0c901bd81d8a.png)

Examples for filters many players would appreciate:

MapNameIncludes: "gap" + "astro"
MinRating: "2000"

**Comment by ryanwalder** [comment]
I would also like to see a custom filter. To expand slightly:

* Filter by Map
* Filter by Sim Mod (eg: Phantom)
* Filter by Mod
* Filter by map player count (min/max players)
* Filter by Title
* Filter by host

Ideally this would all be accessible via a Query like "MAP !=foo,bar,baz AND MODS !=2x, blackops AND SIMMOD = phantom" or similar.

Also slightly unrelated but being able to have a notification based on a query would be awesome if you're looking out for a game on a specific map or simmod etc...
