### ISSUE TITLE
Achievement icons don't show up

### ISSUE THREAD

**Issue by tatsujb** [FAForever/downlords-faf-client#1954]
**Describe the bug**
Achievement icons don't show up

**To Reproduce**
open achievements under player profile

**Log or error message**
nothing

**Expected behavior**
icons for achievements show up

**Screenshots**
![Screenshot from 2020-09-26 17-43-21](https://user-images.githubusercontent.com/5132359/94344447-c7bd7300-001f-11eb-944d-776ba7ed0f7a.png)

**OS**
Linux or Windows

**Comment by tatsujb** [comment]
seeing as some others I've interacted with don't seem to have this it may be a linux bug only

**Comment by Brutus5000** [comment]
Might be fixed as soon as caching runs out on the API. I noticed that the urls were still pointing to http rather than https. Maybe the client didn't follow the redirect here.

**Comment by Brutus5000** [comment]
Yes, it's fixed now.
