### ISSUE TITLE
Segmentation fault with OpenJDK 14.0.2.u12

### ISSUE THREAD

**Issue by dcelasun** [FAForever/downlords-faf-client#1957]
**Describe the bug**
I know the readme says use AdoptOpenJDK or Oracle JDK, but the client has worked perfectly fine with OpenJDK since forever and I thought this might be worth taking a look at.

**To Reproduce**
Just launch the client with OpenJDK 14.0.2.u12

**Log or error message**
[hs_err_pid17083.log](https://github.com/FAForever/downlords-faf-client/files/5294807/hs_err_pid17083.log)

**OS**
Linux

**Comment by micheljung** [comment]
All I can say uis: It happens when loading the WebView (used for chat, unit database), we don't support Linux and we can't do anything about segmentation faults.

Does it happen with AdoptOpenJDK, too?

**Comment by dcelasun** [comment]
> Does it happen with AdoptOpenJDK, too?

Just tested and no, it doesn't happen. I wonder what might be different in upstream OpenJDK.

I think this was triggered by a change on one of the webpages because the client was working fine ~2 days ago and I didn't update anything since then.

> we don't support Linux

I thought Linux was well supported by this client? At least I've never had a problem with this client in well over a year.

Anyway, since this seems to only effect an unsupported JRE I'm gonna go ahead and close this issue.

**Comment by micheljung** [comment]
Glad it works for you!

> I thought Linux was well supported by this client? At least I've never had a problem with this client in well over a year.

Well, we write it in a way that doesn't restrict it to Windows and we even try to provide RPMs. But we don't test in on Linux and if there's a Linux-specific issue, it's unlikely to get fixed by the core contributors :-)

**Comment by 1-alex98** [comment]
There are ppl that offer help for Linux on the forum

**Comment by 1-alex98** [comment]
I don't think we don't support Linux but we indeed have a windows focus as the Linux community is rather small. But I and Brutus use Linux from time to time and I expect major Linux bugs to actually get fixed. But seg faults are incredible hard to fix. And I already heared from others that Openjdk works in version 14 but oracle does not
