### ISSUE TITLE
Improve readability replay vault

### ISSUE THREAD

**Issue by Farmsletje** [FAForever/downlords-faf-client#1958]
![FAForever_jqVumOVKFH](https://user-images.githubusercontent.com/26172055/94498485-8e8d2a80-01fa-11eb-81b9-9463ee7793e4.png)
![downlords-faf-client_xJjX1YHOxk](https://user-images.githubusercontent.com/26172055/94498488-9056ee00-01fa-11eb-9216-9889e315cfed.png)

Imo the java client display is very cluttered. It does display more information than the python one but it doesn't highlight the important information very well, using the same font and size almost everywhere. You can see important values like the date and gametime instantly on the python client.

Also for some reason both the live/local replay vaults are in table format while the online vault is in tile format. Would be nice if, just like for the play tab, people could manually switch between whichever.

**Comment by 1-alex98** [comment]
I don't think we wanna maintain another display format.

**Comment by Sheikah45** [comment]
This is not very clear or actionable as what information is important varies by person. With the new filter search it should also be more clear about what kind of replays you are watching.
