### ISSUE TITLE
blue bar interruption 

### ISSUE THREAD

**Issue by Farmsletje** [FAForever/downlords-faf-client#1959]
When in local replaytab:
![downlords-faf-client_voy4ybWy7q](https://user-images.githubusercontent.com/26172055/94502711-10825100-0205-11eb-8efb-7af53ba2d3d9.png)
When in live replay tab on unwatchable games: 
![downlords-faf-client_BV9JPoHR3n](https://user-images.githubusercontent.com/26172055/94502708-0eb88d80-0205-11eb-97e9-d21a8b60a5f5.png)
When in live replay tab on watchable games: 
![downlords-faf-client_Qu6mDNwYH4](https://user-images.githubusercontent.com/26172055/94502702-0ceeca00-0205-11eb-8b3c-1296d8431e4d.png)

The interruption of the blue bar seems pretty unintentional

**Comment by 1-alex98** [comment]
It is cause it is a button and buttons are not colored blue on the selection of the line
