### ISSUE TITLE
Twitch Button

### ISSUE THREAD

**Issue by Tagada14** [FAForever/downlords-faf-client#1961]
I think that a Twitch button (similar to discord one) that would take you to a livestream tab where you can see all Supreme Commander streams that are live right now would significantly effect the growth of the viewer base for high level 1vs1 Custom/Ladder, Seton's, other team games as well as Official FAF tourneys.

**Comment by 1-alex98** [comment]
Don't think we want this, certainly not in such a prominent place

**Comment by tatsujb** [comment]
we have it now? close?
