### ISSUE TITLE
Start game with high process priority

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#1965]
Reduces interference of other programs.

Maybe make it configurable in case this causes problems for someone.

**Comment by 1-alex98** [comment]
https://bugs.openjdk.java.net/browse/JDK-8187404 not possible with plain java I guess

**Comment by tatsujb** [comment]
If we're doing this (and I do think this is an awesome idea), can my entire fakeFullScreen getup be integrated? 
https://forum.faforever.com/topic/123/guide-fake-fullscreen-and-optimisation

-high priority (what you are looking to do)
-disassociate first core
-remove FA border
-minimise
-maximise
-if you configure that you want it to stretch over two or more screens you can choose the resolution (I volunteer to create the JavaFX interface in the settings)

(one feature that I don't have but would be nice is setting FA to windowed mode automatically)

**Comment by tatsujb** [comment]
> https://bugs.openjdk.java.net/browse/JDK-8187404

that's fine it's not possible in most anything. Today process settings are admin-protected.

just do it the way I do it. 


if the user turns this setting on you can curl my github host of "Process.exe" and call it with the right args just the way I do.

**Comment by bytesizedalex** [comment]
Hi,

This certainly isn't a solution but perhaps to spark conversation. We can change the process priority quite easily with PowerShell, and from testing without needing to be executing in the context of an administrative account.

If we take the FaF client as a simple example, we can manipulate the priority with the PriorityClass method.

```
PS C:\> $faf = Get-Process 'downlords-faf-client'
PS C:\> $faf.PriorityClass = 'High'
PS C:\> $faf.PriorityClass
High
PS C:\> $faf.PriorityClass = 'Normal'
PS C:\> $faf.PriorityClass
Normal
PS C:\>
PS C:\> (([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator"))
False
PS C:\>
```

I haven't looked into the process flow to understand what is invoking what when things run. I seem to recall in C# one can define these levels when invoking an executable but I'm not familiar enough with FaF yet to know what it is doing and how best to approach this.

Perhaps if Java can't define this on launch then it could be adjusted after the fact by another programmatic means. Not sure if this is something people would be interested in investigating together but I'd be happy to try and help as best I can.

**Comment by tatsujb** [comment]
I think C# can do this because it's backed by Microsoft. I think Java cannot do this.

**Comment by bytesizedalex** [comment]
While Java perhaps doesn't have a native option would it be considered acceptable for another component to handle priority/affinity?

Once the application is running it could be called to adjust as desired. In that way we don't need Java to be able to instantiate the process with High priority, we can just adjust it after the fact.

**Comment by tatsujb** [comment]
In which case we've circled back to using process.exe the way I do. (which I'm fine with)

**Comment by bytesizedalex** [comment]
Something I came across, not being a Java dev, I don't know if this would achieve what you guys were looking for - 

[https://stackoverflow.com/questions/27275444/how-to-change-priority-process](https://stackoverflow.com/questions/27275444/how-to-change-priority-process)

**Comment by Sheikah45** [comment]
This requires native tool integration which is likely to cause too many issues

**Comment by micheljung** [comment]
We could easily implement a platform-specific handler for this. For Windows, the API would be: https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setpriorityclass

**Comment by Sheikah45** [comment]
So this is causing many people's AV to just delete the client on game start when it changes the priorities so it will be made optional with default off
