### ISSUE TITLE
Indicate that a game include friends of your

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1966]
**Is your feature request related to a problem? Please describe.**
You are on Discord with your friends and they say they are in a game and it takes you 2 minutes till you understood which game you are supposed to join.

**Describe the solution you'd like**
Highlight the games a friend is in. Possibly with a smiley, the same that is used to indicate somebody is a friend in the player_card_tooltip.fxml (style class friend-icon). Though getting a better icon would also be appreciated. Needs to be done both in the game tiles and game table.

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Atrocyte** [comment]
Fun feature, I've been looking into it.
The friend finding logic is done and in the table view friends are tracked with highlighting when they move from game to game.

![image](https://user-images.githubusercontent.com/7738847/98008847-39de6000-1df5-11eb-8c72-f5a8a002fb18.png)

I was thinking about adding a friend-icon smiley inside the players column, something like this: "4/12 😃".
Is that a suitable place for the smiley?

**Comment by Atrocyte** [comment]
The games with friends will be highlighted and show a smiley to be extra obvious that a friend is in there.

Table formatting:
![image](https://user-images.githubusercontent.com/7738847/98572296-c08fb300-22b5-11eb-93b6-5dffa9d146ed.png)


Tile formatting: 
![image](https://user-images.githubusercontent.com/7738847/98571955-5e36b280-22b5-11eb-92bb-eba3d58ba4c3.png)

**Comment by 1-alex98** [comment]
this stupid smiley icon :D ... We will one day need to replace it with something proper

**Comment by 1-alex98** [comment]
![untitled](https://user-images.githubusercontent.com/19996713/109163647-d5675800-7779-11eb-852b-279e52326600.png)
... not the best designer

**Comment by 1-alex98** [comment]
We could post a call for an icon on forum :D Best icon wins

**Comment by Atrocyte** [comment]
Oh yea that's a great idea @1-alex98 !

**Comment by 1-alex98** [comment]
or maybe somebody finds one in the internet that looks good

**Comment by micheljung** [comment]
Maybe https://icomoon.io/iconsabf18a1/14/673.svg or https://icomoon.io/iconsabf18a1/14/1065.svg
