### ISSUE TITLE
Implement rating range

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#1967]
**Is your feature request related to a problem? Please describe.**
Problem:
You want to only play with players of a certain skill. Let's say all players that have a trueskill rating between 800-1400 or everything above 400. Right now most players state this requirement in the game title but it would be cooler if the server knew about it and if it could also enforce those rules.

The client already implements rating ranges. Or at least it has some UI controls for it.

**Describe the solution you'd like**
When creating a game user should be able to enter a rating range that he considers ok. And also if you wants the server to enforce this rating range. If enforced the games should not be displayed to people with rating that is not in range.

When displaying games the rating range should be displayed in both the tiles and the table. And if the players rating does not match the one of the game a warning should be issued.

**What needs to be done**
The client already shows the rating range of a game. At least in the game table. In the  titles such a date must be added. The client right now parses the rating range from the game title with regex. This parsing must be removed and the value must be read from the server. Also the rating range and whether to enforce it must be sent to the server on game creating. Also the UI for setting such a rating range could be improved/altered.

**How do I talk to the server**
The server messages for creating a game and the message telling the client about changes in games have been altered. They now support field that let the client set such values and the game infos/changes inform the client about the rating range for all games. 

Have a look at this Pull Request(which is deployed):
https://github.com/FAForever/server/pull/651
There you also find a summary of what properties where added to the protocol.

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by 1-alex98** [comment]
in the GameInfoMessage.class u need to add the game_info properties

**Comment by 1-alex98** [comment]
in HostGameMessage.class and NewGameInfo.class u need to add the properties for the host_game

**Comment by chrsin** [comment]
I think I'm pretty much done with most of this except for mapping the data from the server response. 
I could really use some help ironing out those issues.

**Comment by 1-alex98** [comment]
All you need to do is add the properties to the right classes. We can invite you to Zulip(chat service if u like) sent me an email alexander.von.trostorff@gmail.com

**Comment by Katharsas** [comment]
Note: If this lands you can close https://github.com/FAForever/downlords-faf-client/issues/1245 as well.
