### ISSUE TITLE
Private games/modded games are briefely shown when hosted

### ISSUE THREAD

**Issue by Askaholic** [FAForever/downlords-faf-client#1969]
**Describe the bug**
When in the play tab I see lots of private lobbies flash up when created even though I have the private games box unticked. Seems like it only lasts while the game is in the "Initializing" (sent as "closed") state and as soon as the host has joined, the game is filtered out again. Seems to happen for modded games too.

**To Reproduce**
Open play tab

**Log or error message**
This is my log file:

**Expected behavior**
I don't see private games at all

**Screenshots**
![image](https://user-images.githubusercontent.com/17941539/94975514-6d5c6080-04be-11eb-8325-fc683492916f.png)
Notice how the game in the bottom right is both private and has mods enabled, yet still showed up on my screen.

**OS**
Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Askaholic** [comment]
This has not been fixed, I still observe the flashing private lobbies on RC 1.2.2.

**Comment by chrsin** [comment]
@Askaholic can I have you specify which settings you have as when you experience this?
Anything you think might be relevant for recreating.

**Comment by Askaholic** [comment]
Well you can see the settings in my screenshot. 

- tile view
- both boxes unticked
- sort by players descending

I haven’t thought to try it in list view or with other sort parameters. I will try it next time I get a chance.

**Comment by Sheikah45** [comment]
Cannot recreate in current version
