### ISSUE TITLE
Auto reply

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#197]
Let the user set up an auto-reply that is sent when he receives the first PM from a user (per session)

**Comment by axel1200** [comment]
[What do u mean?](https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjJptu2_9TWAhWSh7QKHTThCV0QyCkIKTAA&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DDK_0jXPuIr0&usg=AOvVaw2CD148Fu9z3gUoKhPZ3lON)

**Comment by 1-alex98** [comment]
ok well I think that is pretty advanced if somebody wants that he needs to use a IRC client
