### ISSUE TITLE
Filter aeolus by country 

### ISSUE THREAD

**Issue by tatsujb** [FAForever/downlords-faf-client#1978]
Someone on reddit was looking for duch people in a certain rating range to play with on faf.

I answered that he could filter aeolus by rating : 
![2jjHe1o_d](https://user-images.githubusercontent.com/5132359/95566416-cded1f80-0a21-11eb-910f-eaf7ea0f7af5.jpg)

(Which I discovered on the spot and thought was really cool!)

And i said for the dutch nationality he could just run through the list he gets and pm those with a dutch flag.

That seemed to me like an underwhelming answer. 

I feel like being able to filter by country would be a nice addition!  :)

**Comment by chrsin** [comment]
Created a pull request for this:
https://github.com/FAForever/downlords-faf-client/pull/1979
