### ISSUE TITLE
Automatically update map when hosting a game

### ISSUE THREAD

**Issue by mnooblet** [FAForever/downlords-faf-client#1986]
I've a few maps which got a few plays, one actually got over 3k plays now and I updated the map and added textures and stuff but people still keep playing the old version...

It would be a nice feature to have to either

+force hosts to download the latest version of the map (?)
+or at least display a notice that there is a newer version and that the host can download the map before he creates the lobby

**Comment by 1-alex98** [comment]
I think that's a good idea

**Comment by chrsin** [comment]
Very useful feature indeed!
As I see it we have some clarifications we need out of the way before this can be implemented though.

1. How do we know a newly uploaded map is a new version of another map? (Does the author specify this? Maybe replace the existing version)
2. Do we force the new version on the host? (Or does she select a map and then have a choice of version?)

**Comment by 1-alex98** [comment]
2. We should force new versions

**Comment by 1-alex98** [comment]
1. The whole faf system is based on versions

**Comment by chrsin** [comment]
1. You are right. I even looked at the MapBean class and totally missed the version property. Jeez sometimes it just goes too damn fast!
2. Roger that.

My proposal for a solution would be to check for a new version when the user clicks create. If there is a new version we show a downloading dialog with a description of what is going on. After the download is complete the game is hosted with the new version.

Do we need any kind of automatic updating of maps in the background or is this model good enough? (I'm thinking a new version might change the "minimap picture" and that might result in more downloads.
Any pointers on how to have these background tasks in the client would be much appreciated.

**Comment by 1-alex98** [comment]
I am unsure what your question is

**Comment by chrsin** [comment]
My question is for you to review my proposed solution.

Also, I'm not sure if we need a task in the background of the client that updates the downloaded maps.

**Comment by Marc-Spector** [comment]
@chrsin Hi. Is there any progress?

**Comment by Sheikah45** [comment]
I do not think any work has been done on this yet

**Comment by Marc-Spector** [comment]
:) 
Then I will think about how to implement this feature.

**Comment by micheljung** [comment]
I absolutely think that the client should always download the newest version of a certain map. This is one of the main reasons why we did https://github.com/FAForever/db/pull/24

Think mobile phone apps.

For anyone asking "but what if I want to play an outdated version of a map?": You're out of luck, it's the map author's decision how the map should be (again, think mobile phone apps). If you're unhappy with this, create your own version of the map (although I think that FAF shouldn't allow copied maps).

I suggest that the client should update maps in the background.

**Comment by mnooblet** [comment]
nice 🍺
