### ISSUE TITLE
Can't see my chat

### ISSUE THREAD

**Issue by norraxx** [FAForever/downlords-faf-client#1989]
This is 5 sentence discussion with @axel1200. As you see no chat nothing. Aeolus is empty too.
I can submit messages, even more, I can read popup notifications, but not chat.

Log and screenshot bellow:
[downlords-faf-client.log](https://github.com/FAForever/downlords-faf-client/files/5395900/downlords-faf-client.log)
![Bez názvu](https://user-images.githubusercontent.com/26487134/96345596-da651e00-109a-11eb-8022-680b09f6405d.png)

**Comment by Sheikah45** [comment]
ChatService changed in #2126

**Comment by norraxx** [comment]
<3
