### ISSUE TITLE
Get base faf version for replays from replay data

### ISSUE THREAD

**Issue by Sheikah45** [FAForever/downlords-faf-client#2008]
Currently lots of desyncs happen with old replays because the faf base version is not saved in the replay metadata. However it is in the binary stream. this should be used so that fewer featured mod replays are broken.

**Comment by Sheikah45** [comment]
This is already done

**Comment by Brutus5000** [comment]
Since when? Because we still have quite recent reports about this not working in context with featured mods.

**Comment by Sheikah45** [comment]
This function parses the version from the replay bytes.
https://github.com/FAForever/downlords-faf-client/blob/b1188c53c16d3322371d0ec5273af1ef198bbbb7/src/main/java/com/faforever/client/replay/ReplayService.java#L229

This pull request changed it to use that parsed version for the game update.
https://github.com/FAForever/downlords-faf-client/pull/1866

So I would think that most likely featured mod issues might be some issue with the featured mod versions as I know for example the coop mod version isnt actually in that mod versions json but I will need to take a look for the other featured mods as well.
