### ISSUE TITLE
passwordProtectionColumn dissappeared

### ISSUE THREAD

**Issue by PiskarevSA** [FAForever/downlords-faf-client#2011]
Hello, i am using client version 1.2.2 on Linux.
Problem is related to `Play tab -> Co-Op tab -> Open Games table`
Initially, i saw password protection column (named passwordProtectionColumn in the code), but suddenly it dissappeared and i have no idea why. I think, it was caused by sorting, moving or resizing of the columns.
Also, it looks strange, that `prefWidth < minWidth` in the code below (taken from `games_table.fxml`)
`<TableColumn fx:id="passwordProtectionColumn" editable="false" maxWidth="30.0" minWidth="30.0" prefWidth="20.0" resizable="false" />`

**Comment by Brutus5000** [comment]
Investigation results:
If you uncheck "Show private games" in the Custom games tab and restart the client, the column disappears.
The setting whether to show private games from the custom games tab is persisted in the preferences. But it is applied to all GameTables, also to coop where you don't have the tickbox...

**Comment by PiskarevSA** [comment]
As games table instance on the Co-Op tab always shows private and modded games, so password protection and mods columns should always be shown. On the other hand, Co-Op tab does not need its own copy of this settings since there is no much games at the same time in lobby and filtering not required.
