### ISSUE TITLE
List available channels in add channel tab

### ISSUE THREAD

**Issue by Sheikah45** [FAForever/downlords-faf-client#2027]
Currently channels are not listed anywhere so a user most know about a channel to join the channel. It would be nice if channels were listed in the join channel pane. This should probably not include clan channels

**Comment by Sheikah45** [comment]
Related #1088

**Comment by BlackYps** [comment]
This should also not include the upcoming channels for tmm lobbys.
Excluding these two categories, what channels are left anyway that would be useful for the user to know about?

**Comment by Sheikah45** [comment]
There would still be the language channels and then also any channels people have defined themselves

**Comment by Brutus5000** [comment]
Every language has a channel.
Every clan has a channel.
Tourneys have channels.
All of them are hidden for a purpose as they address a particular audience. Yes you can join them, but in most of them you're not supposed to join (permission on IRC are not working very well in FAF).

**Comment by Sheikah45** [comment]
So is it even worth listing them or should we just not

**Comment by Brutus5000** [comment]
Nobody ever asked for it, so I wouldn't add it.

**Comment by Sheikah45** [comment]
Not needed
