### ISSUE TITLE
Manage active mods UI

### ISSUE THREAD

**Issue by Farmsletje** [FAForever/downlords-faf-client#2039]
When you're done managing your mods in the vault tab you don't have to click "apply" or something similar for it to work, you can just click somewhere else on the screen for the popup window to go away and it will have memorized your changes. But since its super common for such a button to exist i was confused for a second how to save my changes considering there was a "done" button in the old client and if you didn't press it no changes were saved.

My suggestion is to add an apply button to make the manage mods window go away. Seems more user friendly in general even though it isn't necessary

**Comment by 1-alex98** [comment]
I added that originally and ppl complained why it does not auto save and why we would need such an "apply" button if we could auto save instead XD
