### ISSUE TITLE
ladder notifications

### ISSUE THREAD

**Issue by Farmsletje** [FAForever/downlords-faf-client#2056]
see https://github.com/FAForever/downlords-faf-client/issues/22

My comment didn't seem to make it appear at the top of the closed issues list so i assumed nobody would find it unless i make a new issue about it.

**Comment by micheljung** [comment]
The ladder notification exists, which is why #22 was closed, so I'm not sure what this issue here is about? The title doesn't say much.

See also: #1011

**Comment by Sheikah45** [comment]
Ladder notifications removed with tmm
