### ISSUE TITLE
Chat has black background

### ISSUE THREAD

**Issue by BlackYps** [FAForever/downlords-faf-client#2060]
Text in chat has a black background. Interestingly you can sometimes make it go away by selecting and deselecting the text.
Resizing the window also makes it go away.
This is on Linux on v1.3.0-RC1
Worked on v1.2.4-RC1
![grafik](https://user-images.githubusercontent.com/52536103/101285471-99a99b80-37e5-11eb-805b-655b652a1115.png)

**Comment by Sheikah45** [comment]
Must be a javaFX15 difference then

**Comment by 1-alex98** [comment]
Maybe web view patcher broke somehow

**Comment by 1-alex98** [comment]
@Sheikah45 the web view patcher is a dirty hack that changes compiled java fx code to achieve that the background of a web view can be transparent. In the case of java, fx 15  changing code we patch in a pretty dirty way the patch may do a different thing than it originally did.

**Comment by 1-alex98** [comment]
It is part of the client repo and was its own folder. The web view patcher is a so-called java agent. It changes java byte code...

**Comment by Sheikah45** [comment]
ah that is a good point. although it hasnt happened on my windows setup so I have a hard time investigating

**Comment by BlackYps** [comment]
Fixed by using JavaFX 18
