### ISSUE TITLE
Chat user list is not updated correctly in many situations

### ISSUE THREAD

**Issue by Askaholic** [FAForever/downlords-faf-client#2065]
**Describe the bug**
I'm noticing these issues on the TMM version of the client, but I think they may be issues with the base branch.

1. A player who left the game early shows up as still playing. This game had 4 players, and the other 3 do not show up as playing anymore.
![image](https://user-images.githubusercontent.com/17941539/102021282-41b1ee00-3d2b-11eb-84ef-1ab015a8a1c3.png)
The map is permanently stuck and persists when the player joins other games:
![image](https://user-images.githubusercontent.com/17941539/102021408-1aa7ec00-3d2c-11eb-9a67-e84e4dba2e9d.png)

2. Players sometimes show up as chat only even though they are logged in. This issue goes away upon restarting the client, which indicates a problem with synchronizing state. You can see some players have flags which means they must be logged in to the lobby server:
![image](https://user-images.githubusercontent.com/17941539/102022569-357e5e80-3d34-11eb-8dc8-3a5d7862d510.png)

3. Adding friends doesn't add them to the friends section, but does change the context menu entry to "remove friend". (I did not search for the player's name, I just found them in the list)

Related #2061

**OS**
Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Sheikah45** [comment]
It would be better if these were separate issues

**Comment by Askaholic** [comment]
Mmmm, I wasn't sure if they were separate since they all seemed related
