### ISSUE TITLE
TMM player not removed from party if losses internet connection and logs in again

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#2077]
What else is there to say.

**Comment by Askaholic** [comment]
Um, how about screenshots or a description of what happened? This doesn’t help anyone figure out what the problem could be. Is it a client issue, server issue, why? The server has code to remove players from their party if they disconnect so without any further information it’s gonna be pretty hard to fix.

**Comment by 1-alex98** [comment]
I have no idea. You said I should make an issue :D I suggest making a party and one of the ppl cutting the connection(when in game). Happened twice so it seems to be reproducible

**Comment by Askaholic** [comment]
Should be fixed: https://github.com/FAForever/server/pull/708
