### ISSUE TITLE
Nobody recognizes the notification icon

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/downlords-faf-client#2098]
It used to be an alarm bell. Now it's... I have no clue. It looks like a completely retarded opened letter envelope icon with fat yellow dot.

I've seen it in Twitch streams. Nobody recognizes this symbol. Nobody gives it attention if there is a new notification.

Can we get the old alarm icon back?

**Comment by develra** [comment]
I'm taking a crack at this - don't have the correct permissions to assign issue to me.

**Comment by develra** [comment]
https://github.com/FAForever/downlords-faf-client/pull/2101

**Comment by micheljung** [comment]
@Brutus5000 
The "completely retarded opened letter enveleope icon" which "nobody recognizes" is called an "inbox" icon and is used only by some very niche websites like StackOverflow and unpopular software like Discord. So I totally understand that you've never seen it before.

**Comment by Brutus5000** [comment]
It's retarted because the particular icon is very oddly scaled and looks more like an open drawer than an envelope. The yellow dot in the middle of the upper part emphasise even more.

I don't mind an envelope per se, but the one in this font is not good.

**Comment by 1-alex98** [comment]
GitHub uses bell :D

**Comment by micheljung** [comment]
Bell and Inbox are not the same, in Discord:

![image](https://user-images.githubusercontent.com/1864183/103708078-22b41e00-4fb0-11eb-97ea-1b1c67f37e94.png)

And it's not an envelope, it's a stacking tray 👀

![image](https://user-images.githubusercontent.com/1864183/103708238-79b9f300-4fb0-11eb-807e-47cb62547681.png)

**Comment by Sheikah45** [comment]
Closed with #2101
