### ISSUE TITLE
TMM: Disallow watching replays while in queue

### ISSUE THREAD

**Issue by Sheikah45** [FAForever/downlords-faf-client#2105]
**Describe the bug**
Players can watch replays while in queue which could cause mayhem when the game launches

**To Reproduce**
Join queue watch a replay

**Comment by Brutus5000** [comment]
Watchin replays while in game lobby was a mich requested feature (there is an experimental feature toggle). Disabling this without choice seems counter intuitive to me.

**Comment by Sheikah45** [comment]
#1926 only changed the logic for launching replays to allow the replay to start when another game instance was already running. It did not change the logic for joining or hosting a game. Since tmm launches a game later rather than opening a lobby and waiting it is a different situation than what that feature allows.
