### ISSUE TITLE
Hard link the Documents folder -> FaF can't load any mods/maps

### ISSUE THREAD

**Issue by ghost** [FAForever/downlords-faf-client#2107]
Recently I hard-linked to a Netdrive the whole Documents folder which also contains all map/mods for FaF.

For Example, when you go to:

C:\Users\username\Documents\My Games\Gas Powered Games\Supreme Commander Forged Alliance

you get linked to 

G:\My Drive\hardlinks\Documents\My Games\Gas Powered Games\Supreme Commander Forged Alliance

It works perfectly for every other application and game I have used so far, except FaF. Here it gets really weird:

**A**, If I have the mods/maps in:

G:\My Drive\hardlinks\Documents\My Games\Gas Powered Games\Supreme Commander Forged Alliance

he can **see** everything in FaF, but can not load them. I need to have the maps/mods as well in:

C:\Users\username\Documents\My Games\Gas Powered Games\Supreme Commander Forged Alliance

to be able to load them.

**B**, If I have the mods/maps only in:

C:\Users\username\Documents\My Games\Gas Powered Games\Supreme Commander Forged Alliance

then he can not see anything. I need to have them in G:.... as well.

If there is a way to fix this behavior would be nice. Maybe to be able to manually set a path from the FaF to mods/maps?

**Comment by 1-alex98** [comment]
There is a switch in the settings that you can use to store the maps/ mods in a different directory. There you can set that the client stores the vault stuff in C:/ProgrammData/Faforever/ something ... Maybe try that

**Comment by ghost** [comment]
The only setting I have found is the "Vault Fallback Location", but could not find how to enter a path manually. Enabling this made no changes.

**edit**: After a restart of the PC it worked with the Fallback Location. He downloads the maps/mods into the netdrive and load from there without having any other files at C:

Thank you very much for the quick help !
