### ISSUE TITLE
Use OS native notifications

### ISSUE THREAD

**Issue by ryanwalder** [FAForever/downlords-faf-client#2113]
Low Priority

It would be great to have FAF use the OS native notification service rather than it's own. This would mean we can manage FAF notifications along with our other notifications as per our OS specific ways.

**Comment by 1-alex98** [comment]
Not sure. Tell me if I am wrong. But those Windows notifications stay there for a long time right. I mean all our notifications are just interesting when they are shown(message received maybe not). Like x join game y or z is now online. Windows rather treats the notifications like things that are of concern over a longer period. Like you got a message. And then we will have to figure out how to do it on Ubuntu and other Linux distros

**Comment by 1-alex98** [comment]
I guess you can maybe tell windows if it should remember the notification or not

**Comment by ryanwalder** [comment]
I'll be honest I'm a Linux user so can't speak directly for Windows notifications but a quick search seems to show that the length of time a notification is shown is a [system setting](https://www.howtogeek.com/245836/how-to-change-how-long-windows-10-displays-notifications/).

As for linux the standard is the [Desktop Notifications Specification](https://developer.gnome.org/notification-spec/), this is usually implemented via libnotify, I'm not a java dev but I believe the [java-gnome](https://github.com/istathar/java-gnome) lib should provide the relevant bindings for notifications ([docs](http://java-gnome.sourceforge.net/doc/api/4.1/org/gnome/notify/package-summary.html)). This should work across all distros.

For me the reason to integrate them with the system default is that the system default can be configured outside of FAF. For example if I lock my screen and go grab a coffee I'll come back and still be able to see any notifications I would have missed otherwise, say a friend coming online or similar. It also means that if I mute all notifications because I'm on a call or sharing my screen or whatever FAF notifications will honor that setting which it doesn't at present (not the end of the world of course).

**Comment by tatsujb** [comment]
yeah there's not a "per linux distro" notification. there's just the one. I agree that in general this could be a much better user experience but I class this as very low priority.

**Comment by 1-alex98** [comment]
If I had OS specif notifications that means notifications die on Linux XD

**Comment by Sheikah45** [comment]
At the moment javaFX has no support for OS native notifications this is probably a blocker as we do not want to have different implementations for each OS and any implementation would just be a work around.
