### ISSUE TITLE
Client incompatiable with NVidia driver 461.09

### ISSUE THREAD

**Issue by mizar1** [FAForever/downlords-faf-client#2119]
Running FAF client 1.4.0, under Windows 10.  No problem until I updated my NVidia driver to 461.09.  Now joining a game results in a black screen which hides itself before it renders it's contents.  SC is fine when launched manually.  The window is accessible in the Windows toolbar, but clicking on it repeats the process of black screen, and hide before rendering.

**Comment by Sheikah45** [comment]
This is a problem with the Nvidia driver and the game renderer which is not related to the client and also unfortunately we have little power to change. Some workarounds are well documented on the forums and in the discord technical help

**Comment by mizar1** [comment]
As I explained the game works fine without the FAF client, it appears that the client is incorrectly launching the game.

**Comment by Sheikah45** [comment]
Then most likely it is something else and we need more information to act on it

**Comment by Sheikah45** [comment]
Not enough info to act on can reopen if a log or something is added
