### ISSUE TITLE
Matchmaker Learning Popup

### ISSUE THREAD

**Issue by FtXCommando** [FAForever/downlords-faf-client#2121]
This is just a small text edit thing, but could the popup that explains "the system is trying to learn you x% complete" be adjusted a bit to explain what precisely that "learning" entails. I'm thinking something like:

"The matchmaking system is calibrating your skill level; your first few games may be slightly more imbalanced as the system attempts to learn your capability as a player. 

X% Completed."

**Comment by Askaholic** [comment]
Btw this is a server message

**Comment by Sheikah45** [comment]
So this should be moved to the server issues then right?

**Comment by Askaholic** [comment]
Yea or ftx could just make a server PR

**Comment by Sheikah45** [comment]
Server issue
