### ISSUE TITLE
Autojoin everybody into #newbie by default, opt-out via settings.

### ISSUE THREAD

**Issue by Katharsas** [FAForever/downlords-faf-client#2130]
The problem is that most longtime players probably dont even know that newbie chat exists, even if they would be willing to help out. We should make helping noobs one of the major reasons for why the chat exists, and therefore we should join everybody into it by default.

So basically add it to the auto-join options. People can remove it from there if they dont want to join it always.

Edit: We should also sync the #newbie channel to discord.

**Comment by Sheikah45** [comment]
Not planned
