### ISSUE TITLE
False Warn Dialog after join "<1k" lobby

### ISSUE THREAD

**Issue by hsjobeki** [FAForever/downlords-faf-client#2135]
Once you join a lobby which doesnt fit your ranking ( you are 1k+ and try join a lobby named "<1k") and klick join anyways.
The "Ranking Modal" pops every time you try to join any lobby

**Comment by Sheikah45** [comment]
Can you provide a log? I am not able to reproduce this behavior.

**Comment by hsjobeki** [comment]
Mistake was on my side...
