### ISSUE TITLE
TMM: 3 players in party

### ISSUE THREAD

**Issue by Cheyans** [FAForever/downlords-faf-client#2137]
**Describe the bug**
Morax invited both me (Aulex) and F-Odin to a TMM party. We both accepted and created a party of 3.

**To Reproduce**
See the description

**Log or error message**
This is my log file: [client.log](https://github.com/FAForever/downlords-faf-client/files/5937638/client.log)

**Expected behavior**
2 player in TMM party

**Screenshots**
![image](https://user-images.githubusercontent.com/8811789/107129329-a94f6a00-6892-11eb-86d8-32a5c2188d01.png)

**OS**
Windows for me, I'll let F-Odin and Morax comment for themselves

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Sheikah45** [comment]
Not a bug parties can be of any size

**Comment by Cheyans** [comment]
That's not very intuitive when there is only TMM 2v2 support, also what happens when we queue, is it randomly selected between the players or the first ones that join the party queue up? The UI needs to be much more clear in its behavior if this intended.

I understand this feature may grow into 3v3, 4v4 TMM, etc. But in my opinion it should only allow for party sizes up to the max amount of players on a single team as it doesn't provide any benefit to the players and it just makes it more confusing for them.

**Comment by Sheikah45** [comment]
You can only queue for things that are your team size or smaller

**Comment by Sheikah45** [comment]
And this would be a server issue then not a client issue as the server determines party

**Comment by Cheyans** [comment]
They were able to queue and match, I got kicked from the party as a result.

I'll open an issue there.

**Comment by Sheikah45** [comment]
Yes the joining a party while queued is a known issue and I think it will be fixed with the server update
