### ISSUE TITLE
It would be really cool to have sorting games by friends in the game list

### ISSUE THREAD

**Issue by tatsujb** [FAForever/downlords-faf-client#2145]
basically sorting by friends in the games list

**Comment by 1-alex98** [comment]
or just highlight those games right?

**Comment by dev-nulled** [comment]
@axel1200 Highlight or sorted.  99% of the time, I'm looking for what games my friends are in.  Be nice to have some sort of an indicator they were in something.  Same would be true of replays.

**Comment by tatsujb** [comment]
like they should be topmost.

a line and then the rest.

**Comment by Sheikah45** [comment]
similar to #1966

**Comment by tatsujb** [comment]
it is yeah. I like the idea of having the two straight up separated and with a horizontal line in between. would make it a lot easier to browse.

**Comment by Sheikah45** [comment]
Closed by #2264 with added highlighting
