### ISSUE TITLE
New UID implementation

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#217]
In order to log in, a file called `uid.dll` is currently required. This is also the reason why we need a 32 JVM. A new implementation is finally available here: https://github.com/FAForever/uid/

## Task
* Port the new implementation to java so it can be used by the client
* Replace the uid.dll with the new java implementation. Remove all obsolete dependencies (other DLLs)

## Acceptance criteria
* The uid.dll and all its dependencies have been deleted
* The client is able to log in using the new implementation

**Comment by heelix** [comment]
Quick question, did this get folded in?  Seeing a 

java.lang.NoClassDefFoundError: Could not initialize class com.faforever.client.util.UID

On my instance.  (Using a 64-bit JVM, which may be the issue.)

**Comment by micheljung** [comment]
I assume you're running the project from sources? Then yes, you need a 32-bit VM.

**Comment by micheljung** [comment]
Even though we ported the new implementation, we're not going to use this port. Instead, @muellni is creating a self-contained binary which we will use. New issue will follow to address this.
