### ISSUE TITLE
Move to UFT8 plain text lobby protocol

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/downlords-faf-client#2176]
The lobby server connection on port 8001 uses the UTF16 QString based QDataStream protocol.
But in the future (next server update) port 8002 will offer the protocol via UTF8 plain text.

We should drop QT related stuff wherever we can (and also this prepares for a future websocket protocol).

**Questions:**
- How to handle the new port? We can't change the current remote config field for backward compatibility. Add a new one? Or use configured port + 1?
- Should we try to switch to TLS encrypted TCP? (isn't implemented yet, but Traefik should offer it and we could try)
- Can the old clients handle unknown fields in the json?

**Comment by Sheikah45** [comment]
I think we should add a new field to the config .

When I tested this by adding a new field and parsing with gson it just ignored the unknown field

**Comment by Askaholic** [comment]
I think TLS is a good idea.

Also you should consider this new port to be only semi-stable. I might continue to add new ports with additional changes, (like tls if we don’t add it now) and i might want to remove some of the older ones just so we don’t have a million different lobby ports. So maybe fall back to the old port if the new one isn’t available. That way we don’t need to worry so much about breaking people’s clients if they’re still on the second or third newest release.

**Comment by Sheikah45** [comment]
Fixed in #2317 

Also don't remove the utf-8 port it is the new default 😅

**Comment by Askaholic** [comment]
It won’t be changed at this point. If we add/change more stuff like TLS we’ll just do it on a different port
