### ISSUE TITLE
"Show password protected games" doesn't work anymore after single clicking a game to see the preview in the right panel

### ISSUE THREAD

**Issue by Justify87** [FAForever/downlords-faf-client#218]
"Show password protected games" doesn't work anymore after single clicking a game to see the preview in the right panel.

![2016-05-17 12_07_07-apcent](https://cloud.githubusercontent.com/assets/10554299/15318816/2d3ff6c0-1c28-11e6-9e65-96eb5a360475.jpg)

**Comment by micheljung** [comment]
It's reproducible, it works for some games but not for others :\

**Comment by micheljung** [comment]
Well, it's not always reproducible :\

**Comment by Justify87** [comment]
iirc, there was a similiar problem with the standard faf client. It didn't hide all password protected games. Not sure if this is still a problem. This problem appeared for newly created games only, not for games that were already open.

**Comment by axel1200** [comment]
Not reprocudicble anymore, some things were renewed, might have fixed it
