### ISSUE TITLE
Extremly bad performance on linux - with fix for it

### ISSUE THREAD

**Issue by exuvo** [FAForever/downlords-faf-client#2180]
**Describe the bug**
Client UI lags insanely, like 0.5FPS and eats a whole CPU core when just moving the mouse over the client window.

**To Reproduce**
Start client

**Log or error message**
Nothing relevant.

**Expected behavior**
Non-laggy UI

**OS**
Arch Linux 5.11.2-arch1-1
AMD Radeon RX 5700 XT with AMDgpu 19.1.0 driver and mesa 20.3.4
OpenJDK 15

**Fix**
Add -Dprism.forceGPU=true to downlords-faf-client.vmoptions. I assume it must have been running in software rendering mode or something equally stupid.

**Comment by Brutus5000** [comment]
Thanks for that, I'm also in Arch and improved my experience a lot.

**Comment by exuvo** [comment]
Good to see it helped someone so soon!

**Comment by 1-alex98** [comment]
Was it not that if rendered on the gpu it somtimes crashed on some setups :D?

**Comment by 1-alex98** [comment]
Expecially on Linux

**Comment by 1-alex98** [comment]
I think it is there because cpu usage is not as bad as a crash

**Comment by 1-alex98** [comment]
But I am not 100% sure

**Comment by Sheikah45** [comment]
yes I believe that is an issue so I am just trying to find out why it did not use the gpu on some systems where it can

**Comment by Sheikah45** [comment]
Also need to figure out why software rendering is so bad as well since it shouldn't be so drastic a change

**Comment by Sheikah45** [comment]
And actually brutus used it for his linux setup and it worked and improved things drastically he said

**Comment by Wesmania** [comment]
IIRC there was some font bug in JavaFX that was fixed somewhere around 14. If the client is stable, then I say go for it, maybe leave a compatibility option somewhere.

**Comment by Sheikah45** [comment]
is there a known case where this would break?

**Comment by Katharsas** [comment]
I have definitly told some people in the past to set -Dprism.order=sw in order to make their client run. I guess this would break that?

**Comment by Sheikah45** [comment]
yeah it would be nice to know it what cases it breaks then I could better figure out how to add compatibility for those cases

**Comment by 1-alex98** [comment]
Yeah there was some bug and it got fixed javafx 14 IIRC

**Comment by 1-alex98** [comment]
We never really understood the bug or how to reproduce it safely... On some setups it happened on others it did not

**Comment by 1-alex98** [comment]
but -Dprism.order=sw fixed it in all cases soo we used it

**Comment by 1-alex98** [comment]
So maybe if you change it just keep in mind that if complains about native crashes arise then this change could be the cause

**Comment by 1-alex98** [comment]
https://github.com/FAForever/downlords-faf-client/issues/1353

**Comment by Sheikah45** [comment]
yes I think I mostly want to see if there is a way to detect a failure and then remove the option for compatibility sake
