### ISSUE TITLE
Add Percentage of Download for mods

### ISSUE THREAD

**Issue by MrRowey** [FAForever/downlords-faf-client#2187]
I jumped in to a Twith Stream and they were installing Total Mayhem with is a big mod 715Mb and the person whom was streaming was sait waing a while for it to download when it fact it has stoped downloadeing all toget and froze. having a Persentage indicated would make this more clear than the bar which is quite dark to see on the mod download procses. keeping both

**Comment by Sheikah45** [comment]
There already does exist a download progress bar which is a percentage are you looking for more?

**Comment by 1-alex98** [comment]
I don't think a percentage would have helped there

**Comment by Sheikah45** [comment]
I kind of agree that the bar already shows the percentage.
