### ISSUE TITLE
Close FA on `match_cancelled` message

### ISSUE THREAD

**Issue by Askaholic** [FAForever/downlords-faf-client#2188]
# Motivation
Sometimes a matchmaker game can fail to start because one of the players involved does not connect fast enough. When this happens the game will not be recorded in any way. No achievements will be processed, no rating change will be calculated, and no entry will show up in the replay vault. However, sometimes players continue to wait for a while and the game does end up launching several minutes later. The players then end up playing a non-existent game and may be dissappointed when it doesn't show up in their history.

# How to fix it
When a matchmaker game times out during setup, the server sends a message that looks like this:
```json
{"command": "match_cancelled"}
```
Upon receiving this message, the client should react by either 
1. Terminating the running FA process if it has been launched already, or
2. Ignoring the "game_launch" command that might follow in the next few seconds.

NOTE: Number 2 is only necessary due to legacy client support. In version 2 of the protocol, the server will not send a `game_launch` command if the match has been cancelled.

It may also be a good idea to indicate that the match was cancelled in the UI somewhere so the user knows what's going on.

Related: #1750

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Sheikah45** [comment]
I guess in my mind the number 2 makes this difficult unless there is a guaranteed time which a game_launch message would be sent. Otherwise you run into issues of cancelling a custom game someone may launch after

**Comment by Askaholic** [comment]
It would be sent immediately after `match_cancelled` so it should arrive within milliseconds. The problem of course is network code is inherently unreliable so that isn’t a guarantee. It also may be possible for one of the broadcasted “info” messages to be written in between `match_cancelled` and `game_launch`.

I think as long as point 1 happens it will solve all or almost all of the cases where people play non existent games. And then the rest will be solved by dropping the legacy behavior from the server (eventually).

**Comment by Sheikah45** [comment]
What is the reason that legacy behavior has been left in?

**Comment by Askaholic** [comment]
Just because the python client doesn't recognize `match_found`, `match_cancelled`, or `search_info` so the only way it can tell that it's not in queue anymore is if it sees `game_launch`. So if we don't send `game_launch` then people will think they're still in queue when they're not.

**Comment by 1-alex98** [comment]
Whats the server timeout that it happens so often?

**Comment by Sheikah45** [comment]
i think it is also less the timeout but also the case where someone disconnects during launch or cancels during connect

**Comment by Sheikah45** [comment]
My main worry is just false positives where we accidentally close someone's game

**Comment by Askaholic** [comment]
I don’t think you need to worry about that. When you get a game_launch, you start the FA process and get some sort of a handle to it (pid or some java object that wraps the pid). You know that you started that process from the matchmaker, when you get match_cancelled you can terminate it again. Even if the players happen to regain connection in between receiving match_cancelled and you closing the process, it doesn’t matter because the game is already marked as failed on the server, and if you play it out you are essentially playing a ghost game. It won’t get rated or recorded. This is what we want to avoid.

**Comment by Sheikah45** [comment]
This should be easier with the new serverAccessor
