### ISSUE TITLE
Auto Login should remember the environment you logged in to

### ISSUE THREAD

**Issue by Sheikah45** [FAForever/downlords-faf-client#2196]

**Comment by 1-alex98** [comment]
Sure? We did not remember on purpose so that normal user logged into main server after they tested stuff on test server and it not cry in technical help why they see no games and are the only one in chat

**Comment by 1-alex98** [comment]
Or maybe if they just miss-clicked that they would end up on main server after a restart

**Comment by Brutus5000** [comment]
Yeah, I agree with @1-alex98 here. It might be annoying for dev, but it's a failsafe reset for players.

**Comment by Brutus5000** [comment]
Also there is even more stuff that could go wrong:
- If we rename the environments
- If you select an environment but manually override a hostname or similar. What would be saved here?

A lot of complexity for few gain imho. I would not go for it.

**Comment by 1-alex98** [comment]
I guess you could make that behavior but only if dev profile is active or similar...

**Comment by 1-alex98** [comment]
Its a feature not a bug XD

**Comment by Sheikah45** [comment]
yeah you guys make good points just got annoyed with the login and out recently with testing but may not be a good idea.
