### ISSUE TITLE
Faf icon stuck in loading state when generating map

### ISSUE THREAD

**Issue by Cheyans** [FAForever/downlords-faf-client#2200]
**Describe the bug**
When I generate a map **sometimes** the FAF icon in the taskbar stays in the loading state after the map has finished generating.

**To Reproduce**
1. Click create a game
2. Generate a map
3. Wait for the map to generate
4. Map has finished generating, but icon is still in the loading state.

**Log or error message**
This is my log file:
[client.log](https://github.com/FAForever/downlords-faf-client/files/6232820/client.log)
[map-generator.log](https://github.com/FAForever/downlords-faf-client/files/6232826/map-generator.log)

**Expected behavior**
After the map has been generated the icon returns to its non loading state

**Screenshots**
![image](https://user-images.githubusercontent.com/8811789/113069834-2dd1b100-918f-11eb-80a2-6e9f810aef0a.png)

**OS**
Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Sheikah45** [comment]
Fixed in #2232
