### ISSUE TITLE
Windows don't run as admin notification is too annoying

### ISSUE THREAD

**Issue by solismortis** [FAForever/downlords-faf-client#2201]
Some people using Windows always sit on admin rights. Do I really have to read this notification each time I run the client? I don't even know how to run it not as admin.

Can't we have a checkbox for "Don't show again"?

**Comment by Sheikah45** [comment]
Users should not be running the application as admin as this could cause eventual permission and security issues. The warning will not be removed or reduced.

**Comment by solismortis** [comment]
What kind of security issues? Maybe the message should say about them instead.

**Comment by Uveso** [comment]
I also have this notification and its annoying.

I only have an admin acount on my windows and can't change it without loosing my custom HDD file system.
And in case i know the risc (error [13] permission denied...) i would like to disable this warning.
It has no meaning for me. And i will never get this [13] error when i always start the client as admin.

And a check box that doesn't show it again does not detract from the reason this message was created in the first place.
Its only a warning that something could go wrong when you start the client as admin and after this as user.
No reason to nag me til the end of my life.
