### ISSUE TITLE
mentionPattern does not match names that end in `-`

### ISSUE THREAD

**Issue by Askaholic** [FAForever/downlords-faf-client#2202]
People who's names end in `-` can't be pinged.
![img](https://i.imgur.com/e1q64Qc.png)

After messing around a bit, I think this is due to the `\b` word boundary matching. As `-` is not a word character, a space can never match after it (word boundary requires word before and non-word after, or vice versa). You can still ping these people if you put a letter directly after the `-` in order to trigger the word boundary matching.

```java
Pattern p = Pattern.compile("\\b(" + "Box-" + ")\\b", CASE_INSENSITIVE);
Matcher m = p.matcher("I'm Box-");

System.out.println(m.find());
// Prints "false"

Matcher m2 = p.matcher("I'm Box-x");
System.out.println(m2.find());
// Prints "true"
```

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Askaholic** [comment]
The fix is not complete as it doesn’t handle when the username is at the end of the line. It also doesn’t handle the case when the username starts with a dash.

**Comment by 1-alex98** [comment]
One should have limited usernames to be alphanumeric only

**Comment by Sheikah45** [comment]
Yes I am not sure how much more extendable this is without introducing a bunch of false positive mentions

**Comment by Askaholic** [comment]
I think you can reproduce the behavior of `\b` but modify the “word” class to include dashes.

Something like `^|[^A-z-]USERNAME[^A-z-]|$` should do the trick. 

I also firmly disagree that this is “untestable”. There should be at least a few tests that check stuff like:

- `Box-` matches `Box-`
- `-Box` matches `-Box`
-  `cardboard-Box` does not match `-Box`
- `Box-boy` does not match `Box-`
- `Hello Box-!` matches `Box-`

**Comment by 1-alex98** [comment]
> I think you can reproduce the behavior of `\b` but modify the “word” class to include dashes.
> 
> Something like `^|[^A-z-]USERNAME[^A-z-]|$` should do the trick.
> 
> I also firmly disagree that this is “untestable”. There should be at least a few tests that check stuff like:
> 
> * `Box-` matches `Box-`
> * `-Box` matches `-Box`
> * `cardboard-Box` does not match `-Box`
> * `Box-boy` does not match `Box-`
> * `Hello Box-!` matches `Box-`

The actual code this is in

**Comment by Askaholic** [comment]
Btw using `A-z` for the character class was lazy phone typing and will include a few special characters like square brackets, which we probably don’t want.

**Comment by Sheikah45** [comment]
@Askaholic  this pattern matches on just spaces as did @1-alex98. So this is not trivial it seems

**Comment by Sheikah45** [comment]
Actually so did Axel's

**Comment by Sheikah45** [comment]
I think I was able to fix it
