### ISSUE TITLE
Java 15 not available anymore

### ISSUE THREAD

**Issue by ghost** [FAForever/downlords-faf-client#2210]
Hi there,

I tried to install the java FAF-Client, but the package oracle-java15-installer is no longer available in the ppa. 
Installed Java 16 instead, but the launcher insists on using Java 15.

any ideas how to solve this?

**Comment by Sheikah45** [comment]
AdoptOpenJDKs are available here https://adoptopenjdk.net/archive.html?variant=openjdk15&jvmVariant=hotspot
