### ISSUE TITLE
The client does not remember the password on a rehosted game

### ISSUE THREAD

**Issue by mijgame** [FAForever/downlords-faf-client#2218]
**Is your feature request related to a problem? Please describe.**
I don't know whether it is a bug.
Currently, when you rehost a game that originally had a password set, the rehosted game does not retain that password.

**Describe the solution you'd like**
I'd like the client to remember that there was a password set.

**Describe alternatives you've considered**
The workaround is of course to exit and host the game from scratch.

**Comment by tonymmm1** [comment]
This would be a nice added feature to save us hosts some effort :-).

**Comment by 1-alex98** [comment]
I think it is a bug lemme check

**Comment by 1-alex98** [comment]
oh you mean rehost like clicking the rehost button hmm

**Comment by 1-alex98** [comment]
Definetly is a bug there is logic for it

**Comment by 1-alex98** [comment]
Sadly I have no FA installed yo I can not check what the casue is

**Comment by tonymmm1** [comment]
@1-alex98 its definitely possible to rehost but the password is not cached in anyway from what I can tell

**Comment by 1-alex98** [comment]
I was just saying there is code to do that so it is a bug

**Comment by 1-alex98** [comment]
I can reproduce it when clicking rehost button but not on the create game dialog ;)
