### ISSUE TITLE
Always select first game in list

### ISSUE THREAD

**Issue by Androish** [FAForever/downlords-faf-client#222]
Problem: when you click join a game, but a new game is created/launched reordering the tiles so you click to join another game. This has happened to me multiple times

My suggestion: As in title,  "Lock" posisjon of game tile for x(4?) seconds when you hoover your mouse over it.  But maybe there is a better way to solve the problem?

**Comment by micheljung** [comment]
I feel you man. I remember trying to fix it, by always pre-selecting the first game in the list, but either it's bugged or it's not yet in master :)

**Comment by Cheyans** [comment]
We could generate an initial amount of game tiles then populate them with game info, removing the info and not the game tile itself to lock its position. When we add new games we just find the first empty tile. This could get a bit more complex with hiding private games
