### ISSUE TITLE
"Host has left the game" message when other people try to join a game I host

### ISSUE THREAD

**Issue by gregk-git** [FAForever/downlords-faf-client#2222]
**I experienced...** hosting a custom game but nobody could connect. Other people could see my game, and could try to connect, but got the message "Host has left the game".

**how to reproduce** try connecting to a custom game when I host.

**I expected...** that other people would be able to join my game.

**Where the bug is / What should be done** 
I believe it's not a firewall issue, as the issue persists even with my firewall off.

Image of what the person trying to connect sees:
![Host has left the game](https://user-images.githubusercontent.com/11412644/115498733-1a6caf80-a23c-11eb-947b-6195c857191b.png)

Logs folder:
[logs.zip](https://github.com/FAForever/client/files/6348268/logs.zip)

**Comment by 1-alex98** [comment]
```Failed to ping faforever.com``` is really the only interesting thing in the logs I found.

**Comment by 1-alex98** [comment]
Maybe network blocks `ICMP` otherwise no clue how we could help u. Really high chances that this is not client related....

**Comment by 1-alex98** [comment]
Best thing to do is ruling out issue. 
- Try on another PC in the same network. If it does not work, probably down to network set up.

**Comment by Sheikah45** [comment]
Likely caused by end user network configuration
