### ISSUE TITLE
Game crashes when matchmaker finds game while game update not done

### ISSUE THREAD

**Issue by Katharsas** [FAForever/downlords-faf-client#2245]
When there is a new game update, and you queue for matchmaker, and the update doesnt fully get applied before the matchmaker starts, the game itself just crashes because its started while its files are updated.

**Comment by Katharsas** [comment]
Current game files should probably be downloaded at start of client before user can open Play tab.

**Comment by Sheikah45** [comment]
Sure although this doesn't help as much when the patch is deployed while users are online

**Comment by Sheikah45** [comment]
This is mostly caused by not being able to tell when party members are ready and so requires a change to the server protocol to fix.

**Comment by Katharsas** [comment]
It seems like the same problem can happen for slow map downloads according to forum.

**Comment by Sheikah45** [comment]
Yes it only happens when you are in a party as there is no way for the party leader to know if you are ready or not before launching the game.

**Comment by Katharsas** [comment]
Maybe for the maps, but game updates are a problem for solo players too (and maps would be as well if theyr were slower to download, which can happen). I think in general party invitation acceptance or queue joining should both be delayed until all files are ready.

**Comment by Sheikah45** [comment]
forcing it to be during party invitation doesn't really solve the problem as the issue occurs when a patch is released so people would already be in a party when the change happens. The server currently doesn't send any information on what patch a launched game is supposed to run so there is no way to know if you are running the correct version when in queue unfortunately.

**Comment by Katharsas** [comment]
A lot of people (i assume, at least that happened to me) start the client AFTER the patch has already landed and start queueing in TMM in the days or weeks after a patch release. If they didnt start a game before the patch release day, they run into this issue.

A very tiny fraction of people are queuing at the same time as the patch hits. Thats a much harder problem to solve and impatcs a tiny amount of players.

There are really two separate issues here, and the first one is much more important and much easier to fix than the second.
