### ISSUE TITLE
Unhandled Exception after new Windows10 setup

### ISSUE THREAD

**Issue by klaviqula** [FAForever/downlords-faf-client#2259]
**Describe the bug**
After i setup windows10 the first start of game always crash.And i see Unhandled Exception log

**To Reproduce**
Format your pc, reinstall all(windows10,steam, Forged Alliance,Downlord's Faf Client).

**Log or error message**
[game_14639035.log](https://github.com/FAForever/downlords-faf-client/files/6585441/game_14639035.log)

**Expected behavior**
I am actually not sure that this bug happens because of the client.But i face this unhandled exception with other pc's too.Not only my pc

**Screenshots**
![unhandled](https://user-images.githubusercontent.com/54857736/120503284-d7b9fd80-c3cb-11eb-8ead-3dc95eaa6847.png)

**OS**
Windows 10 Pro 20H2

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by klaviqula** [comment]
This bug only happens in first start, i forgot to mention it. In 2nd game, it is always fixed somehow

**Comment by Brutus5000** [comment]
This is a game issue, not a client issue. We can't fix this here.

Well known possible solutions are:
- Disable surround sound
- Disable all mods

You will find more recommendations in our [forum](https://forum.faforever.com).
