### ISSUE TITLE
Make autocomplete scope configurable

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/downlords-faf-client#226]
It should cycle only though names in current channel.

**Comment by micheljung** [comment]
I'm not sure it should only be for names in current channel. Arguments?
Don't say "the current client does it this way"

**Comment by Androish** [comment]
One obvious argument would be that the person can't see you typing their name if you are not in channel.

But if you want to talk behind someones back I guess tabbing their name makes it easier^^

**Comment by speed2CZ** [comment]
dude, it's obvious, I'm in e_clan channel and I wanna ping Blodir as an example, he's the only one with name starting on "B" but if I type "B" and hit TAB it cycles though BasherV2, Bespin, biass, Blackdeath, blitz_shootza and then finally Blodir. It should always cycle only though ppl that are in the channel you're trying to type in

**Comment by micheljung** [comment]
It's not obvious to me. That's just the behavior you're used to. As Androish said, maybe you want to refer to somebody else. Check out slack, there too you can cycle through all names, even in PMs.

**Comment by speed2CZ** [comment]
mkayyyyy, then I'm used to that so much that I find this feature a bug :D

**Comment by themasch** [comment]
How about changing the priorization here? Change the list of names that get auto-complete so, that matches in the current scope (channel) are first, everything else follows later? 
By this, users like @speed2CZ would be happy because `Blodir` would be the first hit, but one can still refer to `BARandomNameWhatever` by pressing Tab again.

**Comment by Sheikah45** [comment]
Current behavior is fine
