### ISSUE TITLE
Java 15 is not available to linux users, only Java 16

### ISSUE THREAD

**Issue by MedliMorrill** [FAForever/downlords-faf-client#2261]
**Is your feature request related to a problem? Please describe.**
Java 15 is not available as an installer for Linux users, painstakingly hard to find even binaries for it.

**Describe the solution you'd like**
I would like compatibility with Java 16

**Describe alternatives you've considered**
It would make it possible to play the game, maybe

I know its a lot to ask, but I can't play without Java 15, so until I have a Java version available for Linux, FAF is out of reach.  Thought I might just put it up here just in case it ever happens.

**Comment by Sheikah45** [comment]
archive binaries for installation can be found here. https://adoptopenjdk.net/archive.html
