### ISSUE TITLE
Tournaments not displayed

### ISSUE THREAD

**Issue by Sheikah45** [FAForever/downlords-faf-client#2299]
Tournaments are not shown due to a deserialization issue. Source is https://github.com/FAForever/faf-java-commons/issues/56

**Comment by Marc-Spector** [comment]
Not sure, but it seems the `Tournaments` tab is working fine in version `2021.12.0`

**Comment by Sheikah45** [comment]
You are right it is working again. Probably fixed by updating java-commons
