### ISSUE TITLE
RC 1.5 Client login lag on big resolution screens

### ISSUE THREAD

**Issue by Katharsas** [FAForever/downlords-faf-client#2302]
Fixed by overwriting webview filter css rule:

In `style-webview.css`:
```
.background {
    filter: none !important;
}
```

Workarounds:
- Reduce screen resolution or window size
- Reduce size of webview element on login page

**Comment by Katharsas** [comment]
@Brutus5000 it WAS the filter effect xD

**Comment by Sheikah45** [comment]
Hmm on my system I am still hitting the function even with filter set to none

**Comment by Sheikah45** [comment]
Although I also can't set my resolution high enough to cause the exception

**Comment by Katharsas** [comment]
You could try to enable Virtual Super Resolution (AMD) or Dynamic Super Resolution (NV) for your desktop and then select higher resolution in OS.

**Comment by Brutus5000** [comment]
Should be fixed by now.
