### ISSUE TITLE
Mockito Unnecessary Stubbings Everywhere in tests

### ISSUE THREAD

**Issue by Sheikah45** [FAForever/downlords-faf-client#2308]
In Junit 5 mockito changed how they detect unnecessary stubbings.

Previously unecessary stubbings were declared when the stubbing was never used during the tests. Now unneccesary stubbings are declared on a test by test basis. So this now throws a bunch of unnecessary stubbing errors for each of our beforeEach methods as not all stubbings in those methods are used every time.

It would be nice to refactor the tests to remove this effect and turn back on strict stubbing guidelines.

**Comment by Marc-Spector** [comment]
Are there any advantages to using strict stubbing?

**Comment by Sheikah45** [comment]
Mainly to make sure that the tests don't become cluttered with unecessary code or setup that could have unintended effects in the future

**Comment by Sheikah45** [comment]
It isn't crucial but still is something

**Comment by Brutus5000** [comment]
In JUnit 5 default, a mock method counts as verify already, so can just run verifyNoMoreInteractions as @AfterEach . I think that's the reason why it's strict by default.
You can disable this for certain mocks (= where it makes sense) by calling lenient().when(...).then...

**Comment by Sheikah45** [comment]
Yeah it is more so that when we moved to junit 5 if a mock was made in the before each that wasn't actually used in the test then it would throw a strict stubbing error.

This caused a lot of errors as the before is used for general setup in a lot of tests and not every mock is used every test but might be used in a few of them.

This the refactor headache

**Comment by Sheikah45** [comment]
This was resolved in #3070
