### ISSUE TITLE
Newline characters in game titles take up whole screen

### ISSUE THREAD

**Issue by Sheikah45** [FAForever/downlords-faf-client#2313]
Currently the games table will display new line characters making a single row very tall and block other games from appearing

https://media.discordapp.net/attachments/476200727912644618/867813526549561425/1.png

**Comment by Marc-Spector** [comment]
How to reproduce this bug?

**Comment by Sheikah45** [comment]
hmm I forget would have to ask phong

**Comment by Marc-Spector** [comment]
Ok. I pmed to phong

**Comment by Marc-Spector** [comment]
From `phong` message:
![image](https://user-images.githubusercontent.com/38242291/148618046-f67041a2-6cf4-4843-bbb1-ef4c4e6413e7.png)
