### ISSUE TITLE
Add amount of ladder games to player card

### ISSUE THREAD

**Issue by FemtoZetta** [FAForever/downlords-faf-client#2322]
![grafik](https://user-images.githubusercontent.com/61892809/128633640-9c92928a-6d78-45f3-8d50-d8a2aaa0e725.png)

The "games played" on the left only shows global games. Just do it like it was done on the right for the rating and show the amount of games for 1vs1 and 2vs2, too.

**Comment by Sheikah45** [comment]
This should already be the case for 1.5.0

**Comment by Sheikah45** [comment]
Just checked this is already the case in 1.5.0

**Comment by Sheikah45** [comment]
Actually probably misunderstood did you mean show them as separate listings?

**Comment by FemtoZetta** [comment]
Yes, it should show 
Global games 3229
1vs1 games 1234
2vs2 games 1234
Or something like that
