### ISSUE TITLE
Fix Matchmaking tab information

### ISSUE THREAD

**Issue by FemtoZetta** [FAForever/downlords-faf-client#2323]
![grafik](https://user-images.githubusercontent.com/61892809/128633900-4d84f870-fbb4-4f32-982d-cb57132c1715.png)

Currently this permanently shows "in placement". I think it was intended to show the matchmaker rating?
Could be done by doing something like this (there easily is enough space in the whole tab to make this a bit bigger, or ask biass how it should be done):
1v1:  Rating: 1234 Games played: 31
2v2:  in placement Games played: 7

The flag can be removed, it serves no purpose, everybody knows which country they are in.

**Comment by Sheikah45** [comment]
This is actually a placeholder for the leagues. Not sure if there is actually enough space to include all the info though as it could technically be arbitrarily many

**Comment by FemtoZetta** [comment]
It's been a placeholder for nearly a year now, I think we should do something with it at this point; especially since it's often asked about on Discord by new players. Also, even with more queues, it will take a while until we even get 4vs4 and I think even with 4 lines it wouldn't take too much space. We will probably have at least a year to think of a solution before it would be a problem.

![grafik](https://user-images.githubusercontent.com/61892809/128634088-8ed57c84-2c6c-4841-8d8c-01030cb50d5d.png)

All the stuff at the bottom is free space, and I haven't even full screened the client

**Comment by Sheikah45** [comment]
That is where the new queues will take up space when they come

**Comment by FemtoZetta** [comment]
I used my epic paint skills for a concept:
![grafik](https://user-images.githubusercontent.com/61892809/128634791-0a8bde0f-8b72-46e2-83ee-18f638f2186e.png)

**Comment by FemtoZetta** [comment]
If it's not a good suggestion, I'd just remove the info entirely until leagues are there, because atm it just confuses people (it gets asked every now and then on Discord why they are permanently in placement).

**Comment by BlackYps** [comment]
I don't want to spend time changing it to a temporary solution when the league system could be ready in 1-2 months.
I know it's confusing, but as you said it has been there for so long, I don't think it hurts too much if it stays a little longer.

**Comment by Sheikah45** [comment]
Fixed with leagues
