### ISSUE TITLE
Remove link to FAF Statuspage

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/downlords-faf-client#2330]
The FAF Statuspage will be taken offline soon.
Please remove the reference on the login screen.

**Comment by micheljung** [comment]
@Brutus5000 why will it be taken offline? Is there a replacement?

**Comment by Sheikah45** [comment]
No one ever has the time or thinks to update it. So it has become more of a source of misinformation than anything else

**Comment by micheljung** [comment]
A health-check service would then be nice :)

**Comment by Brutus5000** [comment]
@micheljung Atlassian statuspage does not offer any automation - at least in the free tier. So I still need to post it in other places as well manually. And they do some internal changes so if we don't do some migration steps they delete the statuspage so why bother ;)
