### ISSUE TITLE
Remove embedded login screen

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#2335]
Having the login screen embedded might seem handy, however, there are some downsides:
1. It doesn't blend in well with the client design
2. A user is forced to trust the client because the client has power over what's displayed
3. The client could steal the user's password
4. The client could potentially approve on behalf of the user, without the user actually clicking
5. The user can't use its usual password manager (e. g. Chrome)

This makes the whole approval process pointless and the client could just as well be configured to not require an authorization screen. However, this would also be problematic since anyone could grab simply grab the client's OAuth secret and gain access to the user's data.

Therefore I suggest removing the embedded login page and provide a button to open the browser instead. This is how other desktop applications, i.e. Google's Backup & Sync, do it as well.

**Comment by Sheikah45** [comment]
So are you imagining implementing this with an browser plugin or communication channel. Otherwise it is unclear how the client will be able to retrieve the token from the browser.

**Comment by micheljung** [comment]
The app opens a socket, the redirect_uri contains the code and points to this socket. This is commonly done, see http://wiki.oauth.net/w/page/27249271/OAuth%202%20for%20Native%20Apps

**Comment by Sheikah45** [comment]
Aight. You will need to ask Brutus to set up the proper redirect uri for the oauth client

**Comment by Sheikah45** [comment]
One thing to consider is whether users machines will allow the app to open a websocket. There were issues in the past when the client accidentally opened connection s but they were refused due to other machine configuration.

**Comment by micheljung** [comment]
Yes, firewalls might be a problem. But I think the advantages of a trustworthy browser and stored password auto-completion outweigh the risk of firewall issues :)

I'm not yet sure how to configure the redirect URI. Either we need a static port or Hydra must allow changing ports. Is this configurable @Brutus5000 ?

**Comment by Brutus5000** [comment]
A dynamic port is nowhere mentioned in the docs and therefore most probably not supported.
We need to set up fixed redirect uris. Potentially we could put a few callback urls in there, to avoid issues when the port is blocked.
Doesn't solve firewall problems though.

**Comment by micheljung** [comment]
Yes, in that case I'd add like 10 ports in the range 50k+. Could you do that please? :) I don't see firewall as an issue. Many apps require ports to be open, and we can easily tell the user (automatically) that this might be the problem if it doesn't work for him.

**Comment by Sheikah45** [comment]
Fixed by #2338
