### ISSUE TITLE
Use OAuth Authorization Code Flow with Proof Key for Code Exchange (PKCE)

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#2337]
I just read that the Authorization Code flow is insecure for native apps and that PKCE should be used: https://auth0.com/docs/flows/authorization-code-flow-with-proof-key-for-code-exchange-pkce

**Comment by Brutus5000** [comment]
We set the `response_type=code` that should be PKCE

**Comment by micheljung** [comment]
That's simply an [Authorization Code Flow](https://auth0.com/docs/flows/authorization-code-flow). For [Authorization Code Flow with PKCE](https://auth0.com/docs/flows/authorization-code-flow-with-proof-key-for-code-exchange-pkce) we also need a `code_verifier` and `code_challenge` which I couldn't see anywhere.

**Comment by Brutus5000** [comment]
What are we waiting for?

**Comment by Sheikah45** [comment]
For the code_verifier and code_challenge to be defined in hydra
