### ISSUE TITLE
Remove usage of EventBus

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#2340]
In a Spring Application, there's no need for Google's EventBus. Therefore, we were migrating away from EventBus towards Spring's Event handling.

However, I saw migrations going in the other direction which is why I now created this issue.

**Comment by Brutus5000** [comment]
@1-alex98 once gave me a thorough explanation about the Spring event handling limitations making it unsuitable for usage everywhere, but I can't remember.

**Comment by Sheikah45** [comment]
The reason it ws the other was was because it looked like most things were using eventBus so I was just making it consistent. But can migrate to the applicationPublisher. One thing to consider is that the spring event publisher is synchronous by default. There might be other issues as well but I will need to look into it.

**Comment by micheljung** [comment]
Yes Sheikah, I was using EventBus everywhere first because I didn't know about the Spring Event Handling. I then started migrating and the code got hybrid, which is bad. Unfortunately, I think I never documented anywhere what the plan was so nobody could know.

Except @1-alex98, he should've known :D I'm not aware of any limitations but I'm happy to learn.

**Comment by Sheikah45** [comment]
Ah yeah I wasn't aware which direction it should have gone. So I went the direction of less work haha

**Comment by Sheikah45** [comment]
From what I can tell the biggest limitation might just be the default synchronous usage where the event calls block until all eventListeners have finished. This can be gotten around by using the Async annotation on all event methods. But then also need to have a task executor for events that doesn't just spawn a bunch of threads as that could be resource hungry with the number of events we have

**Comment by Sheikah45** [comment]
Although thinking about it now I am not sure if eventBus blocks right now

ps: it seems like it does. So not sure why we would use eventBus over applicationEventPublisher. The only thing I can think of is that before spring 4.2 you had to have the listener and event implement a specific interface but that is not longer the case.

**Comment by micheljung** [comment]
I'm pretty sure that both, EventBus and ApplicationEventPublisher, are blocking. Making asynchronous calls is easy in both cases.

**Comment by 1-alex98** [comment]
Somebody said my name :D

**Comment by 1-alex98** [comment]
When you register an event listener in a prototype bean then spring creates a new instance of that bean if an event is called. That is different from what google does. And makes no sense at all in our use case. I found no way to changes springs behavior to call all existing instances instead of creating a new one. Listening to events in controllers (prototypes) happens pretty often and therefore I considered spring events not to be a working alternative.

**Comment by micheljung** [comment]
Damn, you are right (see also: https://stackoverflow.com/questions/33368341/spring-event-handling-for-prototype-components).
That means we need to use Guava's EventBus for at least all prototype beans. However, since a mix of two event buses would be confusing for developers it's probably best to not use Spring's event listener and migrate them all (back xD) to Guava.

**Comment by Sheikah45** [comment]
I think everything except the discord events are converted

**Comment by micheljung** [comment]
Almost:
![image](https://user-images.githubusercontent.com/1864183/132132840-a4295e20-b2e7-47cf-810d-2f02e12d5b01.png)
(Whereas `ClientUpdateServiceImpl` only exists on my current branch)

**Comment by Sheikah45** [comment]
I think you might need to update as those don't exist in develop I think

**Comment by Sheikah45** [comment]
oh never mind most of those just relate to the discord events

**Comment by 1-alex98** [comment]
I mean you can extend AbstractApplicationEventMulticaster and make it behave differently :thinking: but it is a little bit of work I guess

**Comment by 1-alex98** [comment]
Maybe it is even impossible because spring is not even aware of what instances of a prototypes exist :thinking:
