### ISSUE TITLE
Enforce Player Rating vs Lobby Rating Bug

### ISSUE THREAD

**Issue by anthkernan-dev** [FAForever/downlords-faf-client#2341]
**Describe the bug**
When a player joins a lobby their rating is rounded up to the nearest hundred. For example a 680 rated player on the ladder, is displayed as 700 in the lobby. A 650 rated player on the ladder is shown as 600 in the lobby.

Enforce Player Rating takes account of the players global rating which is different from what is shown in the lobby. Furthermore it is not clear that Enforce Player Rating will force the game to remain invisible for all players that are rated below the minimum rating.

**To Reproduce**
Steps to reproduce the behaviour:
- Create a game
- Get a player rated at 680 to join the game
- The lobby will report the player as having a rating of 700
- Create a game and set the minimum rating to 700 and select enforce rating
- The 680 player will not be able to see the game in Play > Custom Games

**Expected behavior**
- Display a GUI warning to the host when they hover over the 'Enforce Min Rating' checkbox:
- "Only players rated within this range can join this game".

**OS**
Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by Sheikah45** [comment]
I don't think that adding an additional tooltip that many people won't notice will make it any more clear than it already is. 
The enforce rating works as intended currently and you can see people's exact rating by bringing up the player info window in the chat tab.

Ultimately there isn't any bug to fix here.

**Comment by Askaholic** [comment]
A tooltip can't hurt though either. I do find that I expect a lot of things in the client to have explanatory tooltips, but they don't.
