### ISSUE TITLE
FAF Java Error

### ISSUE THREAD

**Issue by StrokyBru** [FAForever/downlords-faf-client#2347]
I try launching FAF but i keep getting a Java error message 

**To Reproduce**
Steps to reproduce the behavior: i dont know

**Log or error message**
This is my log file: i dont know where to find that

i expect for the client to launch without problems

![Screenshot (66)](https://user-images.githubusercontent.com/89230338/133629375-3f41538c-4959-4725-a8b8-d74d7f45abd1.png)

Windows

**Comment by Sheikah45** [comment]
Did you manually delete all the downlord's client folders after installation before reinstalling?

**Comment by StrokyBru** [comment]
> Did you manually delete all the downlord's client folders after installation before reinstalling?

omg it worked tysm youre a blessing
