### ISSUE TITLE
"Show rules" leads to nonexistent page

### ISSUE THREAD

**Issue by FemtoZetta** [FAForever/downlords-faf-client#2354]
![grafik](https://user-images.githubusercontent.com/61892809/134658833-3633493b-c135-4c94-85d2-4825f070ed37.png)

This is on the page when uploading a mod. 

![grafik](https://user-images.githubusercontent.com/61892809/134659066-a43a1286-07ec-407d-a402-ec0316c39c7f.png)

**Comment by Sheikah45** [comment]
Yes this is a known issue. Although I guess we lacked an issue to track it.

**Comment by Marc-Spector** [comment]
Already fixed in https://github.com/FAForever/downlords-faf-client/pull/2462
Close the issue, please
