### ISSUE TITLE
Remove usage of @SneakyThrows and NoCatch

### ISSUE THREAD

**Issue by Sheikah45** [FAForever/downlords-faf-client#2368]
**Is your feature request related to a problem? Please describe.**
As described in #2367 the error handling in the client is rather poor with just showing the stack trace to the user. At the moment this is mostly due to using noCatch and SneakyThrows which wraps any exception into a Runtime removing our ability to properly handle errors. 

**Describe the solution you'd like**
To start we should properly check exceptions and remove usages of SneakyThrows and noCatch in the client

**Describe alternatives you've considered**
There is also a possibility of using a global error handler but would like require more error trace parsing rather than a more local solution

**Comment by Brutus5000** [comment]
To be more precise I do believe that it might be "fair" to convert the checked exceptions into properly structured domain related custom unchecked exceptions. However wrapping all of that in a generic RuntimeException loses a lot of required context.

**Comment by Sheikah45** [comment]
Yeah I agree. I view this as a first step
