### ISSUE TITLE
Add setting for 24h time

### ISSUE THREAD

**Issue by Androish** [FAForever/downlords-faf-client#240]
Would be nice to have 24h time when it is the setting on the computer.

Right now it uses AM/PM
http://i.imgur.com/oNVhcZh.png

**Comment by speed2CZ** [comment]
Does it? http://puu.sh/ptE4z/63eb2e6786.png

**Comment by speed2CZ** [comment]
Does it? http://puu.sh/ptE4z/63eb2e6786.png

**Comment by Androish** [comment]
On my PC it does. If it does not happen on every pc I guess one wold try to find out why ^^

Maybe it is OS dependent? I am on windows 10

http://i.imgur.com/7DkbaB5.png

**Comment by micheljung** [comment]
The client uses the default locale, which is system-dependent (e.g. en_US, en_UK or de_DE). It does *not* respect how you configured your windows time.
We can add a configuration for the time format though.

**Comment by Androish** [comment]
I see, it's quite normal to use an English locale even if you preferere the correct way of displaying the time. A toggle will be plenty good enough tho :)
