### ISSUE TITLE
Discord Button List

### ISSUE THREAD

**Issue by mirddes** [FAForever/downlords-faf-client#2409]
![image](https://user-images.githubusercontent.com/13982888/139560780-1a72c7cd-9730-4321-bab9-6ea762e0fee0.png)

It's a simple button which displays a list of links to all the FAF discords when clicked. 

If you're keen here is the relevant commit https://github.com/ta-forever/downlords-taf-client/commit/a998acc421ccada317cbd3e656fe10983e084441.
It requires a couple of conflict resolutions to merge with the latest version of FAF but shouldn't be too much of a problem.

A huge thanks to Axle1975 for forking FAF to make TAF (and for pointing me at his commit). 
Hooray for free open-source software.
Viva la FAF!

**Comment by Sheikah45** [comment]
At the moment FAF only has one official discord so the list is not necessary

**Comment by mirddes** [comment]
что насчет русских?
Ou que diriez-vous des français?
Creative and Nomads?
That's 5 by my count.

Alternatively the button could link directly to just one discord sans list.

I found this screenshot, is the list of discords depicted no longer current? seems to be way more than either 1 or 5...
![image](https://user-images.githubusercontent.com/13982888/139565576-61181c15-9932-4a93-9a31-c72d5f095799.png)
