### ISSUE TITLE
No warning that the title of a game should contain only english text and (or) numbers

### ISSUE THREAD

**Issue by Marc-Spector** [FAForever/downlords-faf-client#2414]
Trying to create a game with the title with non-english text (for example `+800 ты не пройдешь!`) and click "Create". 
Nothing will happen after that.

The following was printed in the log file:

> 2021-11-02 18:29:02.793  INFO 3940 --- [pool-3-thread-10] c.f.c.patch.GameBinariesUpdateTaskImpl   : Updating binaries to 3724
> 2021-11-02 18:29:02.870  INFO 3940 --- [reactor-tcp-nio-2] com.faforever.commons.lobby.FafLobbyApi  : Outbound channel cancelled
> 2021-11-02 18:29:02.871  INFO 3940 --- [reactor-tcp-nio-2] com.faforever.commons.lobby.FafLobbyApi  : Inbound channel cancelled
> 2021-11-02 18:29:02.872  INFO 3940 --- [reactor-tcp-nio-2] com.faforever.commons.lobby.FafLobbyApi  : Disconnected from server

Client Version:
2021.10.0

**Comment by Sheikah45** [comment]
Ah yeah that is probably the combination of the utf-8 encoding and server freaking out that the message doesn't follow protocol

**Comment by Askaholic** [comment]
Yea the server expects that the client should be validating game titles before sending them: https://github.com/FAForever/server/blob/88778a33e5354bd9640261f083cffd731e3f0be0/server/lobbyconnection.py#L968
