### ISSUE TITLE
Do not create a game with empty title using only whitespace

### ISSUE THREAD

**Issue by Marc-Spector** [FAForever/downlords-faf-client#2420]
In the "Custom Games" tab, I saw the game with the empty title. The title contains only a whitespace.

Client Version:
2021.10.0

![image](https://user-images.githubusercontent.com/38242291/142445615-3d10ca31-de5f-4833-9825-9e1693082bae.png)

**Comment by Askaholic** [comment]
I’ll make a server issue as well. Should there be a minimum length for the title?

**Comment by Askaholic** [comment]
Checks for empty titles were added to the server in v1.14.0. Now I am seeing some errors in the log files which means the client' isn't properly sanitizing everything:
```
WARNING  Jan 06  22:47:22 LobbyConnection                Client error: Title must not be empty.
WARNING  Jan 06  20:43:46 LobbyConnection                Client error: Title must contain only ascii characters.
```

This is how the checks look on the server end
```python
if not title.isascii():
    raise ClientError("Title must contain only ascii characters.")
if not title.strip():
    raise ClientError("Title must not be empty.")
```
