### ISSUE TITLE
Separate the version number from the word "version" in "Maps" tab

### ISSUE THREAD

**Issue by Marc-Spector** [FAForever/downlords-faf-client#2422]
![image](https://user-images.githubusercontent.com/38242291/142454900-afa09760-7d55-4a20-a103-b1d482a7437e.png)

Client Version:
2021.10.0

**Comment by Sheikah45** [comment]
This is a translation issue and not a spacing issue. In english it is perfectly fine to have the v# not be separated by a space and is in fact intended that way. So the translation just needs to be fixed.

**Comment by Marc-Spector** [comment]
OK. Then I will correct the translation

**Comment by Sheikah45** [comment]
You have to do that through the POEditor page here https://poeditor.com/join/project?hash=2oWfdaZQZj

**Comment by Marc-Spector** [comment]
I know. Already fixed.
