### ISSUE TITLE
Saraphim co-op missions objectives bugged

### ISSUE THREAD

**Issue by 1ndepth** [FAForever/downlords-faf-client#2423]
As per forum link https://forum.faforever.com/topic/2779/saraphim-co-op-missions-bugged

In short, game objectives are not displayed correctly after cutscenes. 
Worst one affected is "Operation Uhthe-Thuum-QAI". Does not even load the initial objectives. 
See full description in above forum discussion.

Game logs can be provided if required.
Hours of playing/changing map settings have not resolved the problem.

**Comment by bukajsytlos** [comment]
Most probably belongs to https://github.com/FAForever/faf-coop-maps

**Comment by Sheikah45** [comment]
Closing as it applies to the fa repo or the coop maps repo
