### ISSUE TITLE
My rating got set to 0 in the latest release v0.6.12-alpha

### ISSUE THREAD

**Issue by Justify87** [FAForever/downlords-faf-client#245]
I panicked a little :-P
I don't have a screenshot but I have witnesses.

**Comment by micheljung** [comment]
In-game or where?

**Comment by Justify87** [comment]
It seems to happen in the client and in the game. I got asked if I really want to join "that" game, because my rating is lower than 1000. I first though this was just a bug with the rating check, but when I got listed with 365 games and 0 rating in the in game lobby, I realized that its not just a bug with the rating check.

I just tested it again. These are my stats in the profile:
https://i.imgur.com/ZHUcvKt.png

This is what is displayed in the lobby:
http://i.imgur.com/2xa0TJo.jpg

Achievements say, I have played 12 games.

Switching back to the standrd faf client fixed my rating again.

**Comment by tatsujb** [comment]
However this is a recurrent issue on standard FAF as well, I've had it happen to me and plenty of friends. the call to the server on both downloard FAF and FAF is the same. I'm not saying it can't be fixed though.

**Comment by micheljung** [comment]
At least the number in the game is pretty much 1:1 what the server tells the client, not much that could go wrong there. Same thing with the numbers in the profile; that's what the server sends.

I need logs though to be 100% sure :-)

**Comment by Justify87** [comment]
There you go :-)

[logs.zip](https://github.com/FAForever/downlords-faf-client/files/324081/logs.zip)

**Comment by micheljung** [comment]
It seems to be caused by the client being case sensitive for user names
