### ISSUE TITLE
Disable mnemonic parsing

### ISSUE THREAD

**Issue by BlackYps** [FAForever/downlords-faf-client#2497]
I believe that this feaure of javafx is responsible for the "Can't type d in chat after alt-tab" bug. Nobody uses the keyboard to navigate the client anyway, so it should be safe to disable

**Comment by Marc-Spector** [comment]
I can not reproduce the bug on the client version `2021.12.0` on any chat channel including a matchmaker channel.

**Comment by BlackYps** [comment]
Did you have this bug in earlier versions?

**Comment by Marc-Spector** [comment]
Yes. I remember that I reproduced the bug in an early version. And I do not remember which version exactly.

**Comment by BlackYps** [comment]
Maybe it is fixed then. I recently saw someone complaining about it in aeolus, but maybe he wasn't using the latest client. We can reopen if the bug surfaces again.
