### ISSUE TITLE
Cannot host custom games if the password contains "ø"

### ISSUE THREAD

**Issue by teodorlu** [FAForever/downlords-faf-client#2517]
**Describe the bug**
Cannot host custom games if the password contains "ø".

After using a password containing "ø" once, the client fails to host games, even when the password does not contain "ø".

After a FAF Client restart, passords not containg "ø" work again.

**To Reproduce**
1. Go to "Play", then "Custom games"
2. "Create game"
3. Enter a password with "ø" in it
4. Press "Create".
5. Observe that the game does not start - nothing is happening.

On 1.5.0 and before, it was possible to host games with "ø" in the password.

**Log or error message**
No error message.

Log example: https://subcons.teod.eu/static/2021-12-30-debug.log.txt

More details & discussion: https://forum.faforever.com/topic/3114/unable-to-host-custom-games-any-advice/16

**Expected behavior**
Pressing "Create" starts up the game, and we enter a lobby.

**OS**
Windows

**Workaround**

Don't use "ø" in passwords.

This might be an issue for other non ANSI characters too.

**Comment by arnefm** [comment]
I can confirm that I'm affected by the same bug. I can consistently reproduce the behaviour described by @teodorlu. This worked perfectly on versions 1.5.0 and prior.

**Comment by Sheikah45** [comment]
Game properties such as names and passwords are restricted to ASCII characters. This was also updated in the server so the client will be changed to enforce this as well.

**Comment by Sheikah45** [comment]
It is likely because we switched the message encoding backend

**Comment by arnefm** [comment]
> Game properties such as names and passwords are restricted to ASCII characters. This was also updated in the server so the client will be changed to enforce this as well.

That sounds fine! Just spent a good three hours trying to figure this out before realising it was a stupid character causing the whole problem.

Thanks for all your hard work on FAF!

**Comment by teodorlu** [comment]
Yup, thanks for keeping FAF alive!
