### ISSUE TITLE
Increase the importance of avatars, show them wherever possible

### ISSUE THREAD

**Issue by Marc-Spector** [FAForever/downlords-faf-client#2530]

**Comment by BlackYps** [comment]
This needs some specifictation to know when this is fulfilled to be able to close it

**Comment by Marc-Spector** [comment]
What is the specification? Could you give an example?

**Comment by BlackYps** [comment]
What does "wherever possible" mean in practice? Where do you want to see it?

**Comment by Marc-Spector** [comment]
It is examples. 

What is the point of avatars if they are displayed only in chat channels? There are players who do not communicate in chats.

![image](https://user-images.githubusercontent.com/38242291/150676436-96f37cea-6cba-4948-bfe1-4f8c15db7fa9.png)

![image](https://user-images.githubusercontent.com/38242291/150676444-a23beacb-bac3-46c0-8beb-8f4b0fc516ef.png)
