### ISSUE TITLE
Leaderboard updates can cause a concurrent modification exception on the application thread

### ISSUE THREAD

**Issue by Sheikah45** [FAForever/downlords-faf-client#2547]
**Log or error message**
This is my log file:
[client.log](https://github.com/FAForever/downlords-faf-client/files/7959154/client.log)

**Comment by Marc-Spector** [comment]
Are there any steps to reproduce?

**Comment by Sheikah45** [comment]
There were no guaranteed steps to reproduce as it depends on when a server message updating a rating came in. However I believe i already fixed this by just using a copy of the leaderboard ratings when calculating the total games.

**Comment by Sheikah45** [comment]
Yes fixed in 74c6ea4b83215c8699f891c93e5540ae876a35ea
