### ISSUE TITLE
Cache news tab

### ISSUE THREAD

**Issue by BlackYps** [FAForever/downlords-faf-client#2554]
When I originally coded the new news website into the client we decided to reload the website everytime the tab is visited instead of never, to accomodate the use case where people keep the client open for days.
It is now clear that this wasn't a really good decision. Given that the news site basically never gets updated more than once a day we should just reload it after some hours. This way everyone still stays up to date and we get rid of the considerable loading time for 99% of the people.

**Comment by BlackYps** [comment]
Can I get some context please?

**Comment by Sheikah45** [comment]
In #3050 I am removing effectively all caching of controllers as it lead to memory leaks and other transient errors. It also encouraged state and business logic to be put into the UI controllers which is not really maintainable.

And this caching of controllers didn't even really speed things up vs just ensuring that heavy IO operations are not done on the application thread.

So caching of the news tab would require caching the controller which we are moving away from.

**Comment by BlackYps** [comment]
I see
