### ISSUE TITLE
Display map size to game info detail

### ISSUE THREAD

**Issue by Marc-Spector** [FAForever/downlords-faf-client#2558]
Taken from forum: https://forum.faforever.com/topic/3206/small-suggestions-topic/213?_=1644331028614

Examples:
![image](https://user-images.githubusercontent.com/38242291/153010793-8026ed17-93df-4377-904e-126eff706c05.png)

![image](https://user-images.githubusercontent.com/38242291/153010843-9eab596a-ae1e-44ce-a8ab-100ff1615f71.png)

**Comment by Sheikah45** [comment]
This is not really feasible as it requires downloading the map, or querying the API for every map name. Querying the API is a non starter as if every logged in player queried the API for every game info message that would easily overload the server.

**Comment by Marc-Spector** [comment]
You're right. I took a look at the code. `GameBean` does not contain information about the map, except for the name.

**Comment by ghost** [comment]
> This is not really feasible as it requires downloading the map, or querying the API for every map name. Querying the API is a non starter as if every logged in player queried the API for every game info message that would easily overload the server.

Even if you cache this information locally? How about an option:
"To see more information, download map"

**Comment by Sheikah45** [comment]
Even caching that will still be a huge amount of calls to the server API as the cache would only exist per session and there are a lot of maps out there. The issue is the 1000s of simultaneous calls to the API that could happen very frequently.

**Comment by ghost** [comment]
> Even caching that will still be a huge amount of calls to the server API as the cache would only exist per session and there are a lot of maps out there. The issue is the 1000s of simultaneous calls to the API that could happen very frequently.

By locally i meant in local files, not in RAM. Caching locally and in RAM. On launch use local data without calling API
