### ISSUE TITLE
Player context menu in replays shows options that are not applicable

### ISSUE THREAD

**Issue by BlackYps** [FAForever/downlords-faf-client#2560]
When rightclicking a player in the replay detail window (nice work btw!) there are some options that only make sense when the player is online. However, in an arbitrary replay we can't guarantee that.
In particular I mean:
- Private message
- Add friend
- Add foe

A message to an offline player will get swallowed by the void, because IRC doesn't save messages, but the client doesn't communicate that. I guess because the chat window was built with the assumption in mind that you could only ever open it for players that are online.
The friend/foe system will throw exceptions, because the client tries to find that player in the list of online players.

**Comment by Sheikah45** [comment]
Ah good point. AAlthough the friend foe one is easy to get around as the use of that map is entirely redundant.

For the private message we can just add a check before hand.

**Comment by BlackYps** [comment]
I think a check for self is also missing. Right now I could foe myself. Or at least try to do it

**Comment by Askaholic** [comment]
Adding friends and foes for offline players would actually be a useful feature. It should be totally supported by the server.
