### ISSUE TITLE
Murder Party is broken: Players only get normal FFA, no lua logic

### ISSUE THREAD

**Issue by richi235** [FAForever/downlords-faf-client#2575]
**Describe the bug**
When players host and start a Murder Party game nothing described in the mod description happens. No targets are assigned,
no voting etc. just a basic FFA starts like the mod was never selected.

**To Reproduce**
Host a murder party game, invite at least 3 other players (we tried with 6) launch.

**Log or error message**
I'm currently on my notebook, will provide later when I'm on PC again.

**Expected behavior**
See mod description in: https://github.com/FAForever/db/blob/c31743d84ffd74930259de8350b2239cae6fcdfe/migrations/R__010_game_featuredMods.sql 

Line 13 muderparty

**Screenshots**
Maybe later

**OS**
We all tested on Windows, one mate had linux there the game lobby didn't start at all, he got lua bugs, if interested I can ask him for logs and file an extra bug for this.

**Wanna have the bug fixed quickly?**
Not really, this is not urgent imho, just wanted to inform you, maybe the solution is to delete murderparty from the database of officcialy  supported mods

**Comment by Brutus5000** [comment]
Murder party is indeed targeted for removal since it's broken and unmaintained.
https://github.com/FAForever/db/pull/298

**Comment by Sheikah45** [comment]
As Brutus said murder party will be removed and also the client cannot fix it so not a client issue.
