### ISSUE TITLE
Add retry for open files when moving FAF data files

### ISSUE THREAD

**Issue by relent0r** [FAForever/downlords-faf-client#2582]
When trying to move the FAF data directory via the UI I hit an issue where there was an open file(my own fault). The result was that it bombed out and then I lost all the files that were originally in the FAF data directory.

Better solution would be to prompt for a retry if a file is detected as being open during the copy process.
Or wait until all files are copied across successfully before deleting the original.

**Comment by Sheikah45** [comment]
Hmm odd, that method should not delete the old directory if anything failed in the copy. If you have a log that would be nice to see where the failure was

**Comment by relent0r** [comment]
If the log wasn't in the faf data directory I could get it? From a user perspective what I saw was while it was copying it was removing the old files (e.g the free space on the original drive was increasing during the copy).
Then when it failed it just stopped. Then I foolishly tried it again and it deleted everything in the new folder first and tried to copy again from the old which now only had a couple of files left.
For the average user its not a huge drama, I just shed a small tear for all my custom init files I had in the bin folder.

Not sure if it matters, but I also had all mods/maps in that faf data folder as well. Which is actually why it failed as I had a mod folder open in vscode at the time.

**Comment by Sheikah45** [comment]
yes the log is now in the appdata folder, and that is very strange behavior as it definitely is defined as a full copy operation first and then a delete operation in the code

**Comment by Sheikah45** [comment]
I cannot recreate this behavior of the files being erased first

**Comment by relent0r** [comment]
Cool. I'll close it if its not repeatable. Must have just been something unique to how I was using it.
