### ISSUE TITLE
Make the context menu more attractive to the user

### ISSUE THREAD

**Issue by Marc-Spector** [FAForever/downlords-faf-client#2594]
From a freak 

![image](https://user-images.githubusercontent.com/38242291/156139258-be1de91f-981a-4300-83a8-d19e235646c3.png)

to a beauty (include the icons)

![image](https://user-images.githubusercontent.com/38242291/156139440-922dcaad-fd0a-482e-8007-34f16e61478f.png)

**Comment by Marc-Spector** [comment]
It remains to find suitable icons

![image](https://user-images.githubusercontent.com/38242291/156155305-3e901397-233e-45b1-8984-1e518f7c7eed.png)

**Comment by Sheikah45** [comment]
Maybe just a little bit less rounded corners like 3px instead of 5px

**Comment by Brutus5000** [comment]
Don't we use a self-baked fontawesome where we can add more icons if required?

**Comment by Marc-Spector** [comment]
Where can I find self-baked fontawesome?

**Comment by Marc-Spector** [comment]
@Sheikah45 Done. See https://github.com/FAForever/downlords-faf-client/pull/2596#issuecomment-1056867825

**Comment by Sheikah45** [comment]
> Don't we use a self-baked fontawesome where we can add more icons if required?

Yes the icons svg will be added
