### ISSUE TITLE
High GPU usage when progress ring on the screen 

### ISSUE THREAD

**Issue by ghost** [FAForever/downlords-faf-client#2600]
I have noticed it when progress ring appears on screen

![Screenshot 2022-03-03 101824](https://user-images.githubusercontent.com/86099479/156501279-cbe76528-bfe5-4e02-bafc-c3b7906fcab0.png)

![Screenshot 2022-03-03 101841](https://user-images.githubusercontent.com/86099479/156501290-6fdee228-3401-4571-b71e-76b457d61e98.png)

![image](https://user-images.githubusercontent.com/86099479/156501371-184ba742-0ed5-4a55-8c5a-997512c22876.png)

**Comment by Brutus5000** [comment]
Is this still a gif? We had that problem before, that's why we replaced the "native" spinner with a gif.

**Comment by Marc-Spector** [comment]
https://bugs.openjdk.java.net/browse/JDK-8200239

**Comment by Marc-Spector** [comment]
Interesting fact: 
If you run a clean project and show the progress ring, the GPU usage is only 6.3%

**Comment by Marc-Spector** [comment]
Experimentally, it was found out that the more elements are used, the greater the load on the GPU

**Comment by micheljung** [comment]
This might also be caused/amplified by the workaround for https://github.com/FAForever/downlords-faf-client/issues/442. `-Dprism.dirtyopts=false` causes the whole UI to rerender instead of just the areas that changed.

**Comment by Marc-Spector** [comment]
Already fixed in https://github.com/FAForever/downlords-faf-client/pull/2619
