### ISSUE TITLE
When started through FAF on linux, FA crashes on becoming fullscreen

### ISSUE THREAD

**Issue by Angular-Angel** [FAForever/downlords-faf-client#2603]
**Describe the bug**
So, I managed to get the game running on linux, but when I start FA through FAF, and then either make the lobby full screen, or try and start the game and have it become full screen, in crashes, giving me the log below.

**To Reproduce**
Install the FAF client on xubuntu 20.04, using GraalCE 17 java, link the game up using YoslinCakes [instructions](https://gist.github.com/Yoslincake/ddfa6f3f1aedfb6faa5f17ddd7d12f28), then try starting a game.

**Log or error message**
The game log file doesn;t have anything interesting in it, but here it is anyway:
[game_16478686.log](https://github.com/FAForever/downlords-faf-client/files/8180798/game_16478686.log)
The far more interesting error message comes from FAF:
```
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              1024
info:      - Height:             768
info:      - Format:             D3D9Format::A8R8G8B8
info:      - Auto Depth Stencil: false
info:                  ^ Format: D3D9Format::Unknown
info:      - Windowed:           false
info:  Setting display mode: 1024x768@60
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  1024x768
info:    Image count:  2
info:    Exclusive FS: 0
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_FIFO_KHR
info:    Buffer size:  1024x768
info:    Image count:  3
info:    Exclusive FS: 0
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  12 (X_ConfigureWindow)
  Resource id in failed request:  0x6600036
  Serial number of failed request:  1296
  Current serial number in output stream:  1300
```

**Expected behavior**
I would expect the game to go full screen without crashing - or better yet, just stick to the window I already had it in, and let me make it full screen via settings if I want that.

**OS**
Linux, Xubuntu 20.04

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by bukajsytlos** [comment]
I don't think this is related to client

**Comment by Angular-Angel** [comment]
Okay, so, if I add 'PROTON_USE_WINED3D=1' in steam before generating the run script, as per [these directions](https://wiki.faforever.com/en/FAQ/Client-Setup), then it doesn't crash. I do get some annoying errors with the mouse being off target for clicking on buttons - but, if I fumble my way through the settings and make the game windowed, then when I resize the window it sorts all that out, so far as I can tell.
