### ISSUE TITLE
Error: Could not find or load main class install4j.com.faforever.client.Main on linux

### ISSUE THREAD

**Issue by mateuszkozakiewicz** [FAForever/downlords-faf-client#2610]
**Describe the bug**
Client crashes on startup. The last working release for linux was v2022.2.0-alpha-2

**To Reproduce**
1. Download tar for release v2022.2.0
2. Extract
3. Run ./faf-client

**Log or error message**
```
❯ INSTALL4J_JAVA_HOME=/home/max/Games/forged-alliance-forever/openjdk15/ ./faf-client
Error: Could not find or load main class install4j.com.faforever.client.Main
Caused by: java.lang.ClassNotFoundException: install4j.com.faforever.client.Main
```

**Expected behavior**
It works.

**OS**
Linux

**Comment by mateuszkozakiewicz** [comment]
Build [v2022.3.0-alpha-1](https://github.com/FAForever/downlords-faf-client/releases/tag/v2022.3.0-alpha-1) is working

**Comment by 1-alex98** [comment]
Well I guess we close it then
