### ISSUE TITLE
Non ascii characters in vault path

### ISSUE THREAD

**Issue by Garanas** [FAForever/downlords-faf-client#2613]
**Describe the bug**

The game can not load in maps / mods when there are unknown characters in the path of the map / mod. The client can detect that and choose a different location, but in this instance that didn't work.

**To Reproduce**

![image](https://user-images.githubusercontent.com/15778155/157649825-c6f61795-22dc-44e8-85f7-0c854b3e95b0.png)

Any user profile with this type of character, it is polish according to the user.

**Expected behavior**

According to Zlo the client can already detect non-ascii characters in some situations. This would need to be extended.

**OS**

Windows

**Comment by Sheikah45** [comment]
The client used to detect them when there was a hard coded fallback however without the hard coded fallback it is not obvious where they should go. I can probably just add a warning on startup

**Comment by Garanas** [comment]
A warning would be great 👍
