### ISSUE TITLE
Update to JavaFX 18 and use transparent WebView

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#2614]
Very soon, JavaFX 18 should be released. The most important fix for us is [Allow for transparent backgrounds in WebView](https://bugs.openjdk.java.net/browse/JDK-8090547), allowing us to get rid of the WebView patcher.

**Comment by 1-alex98** [comment]
WebView patcher was always a pain

**Comment by 1-alex98** [comment]
Only took them 9 years XD

**Comment by 1-alex98** [comment]
released 3 days ago
