### ISSUE TITLE
Try removing -Dprism.dirtyopts=false

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#2615]
The client has been using `-Dprism.dirtyopts=false` for a long time as a workaround for https://github.com/FAForever/downlords-faf-client/issues/442

The problem is that this causes the whole UI to be rerendered even if just one pixel changes. This is especially bad when animations are used.

Back in time, I was able to reproduce the bug using the code from https://bugs.openjdk.java.net/browse/JDK-8089369
Right now, however, I'm no longer able to reproduce it with, not even with JDK 8 and JavaFX 11 so maybe it's fixed.

If we can make the client small, scroll all the way down or horizontally in a web view, and enlarge the client without this bug occurring, then it's probably fixed.

**Comment by 1-alex98** [comment]
Is that the cause why loading bars cause insane cpu load? XD

**Comment by 1-alex98** [comment]
if so ... really important to get rid of it if possible :D

**Comment by 1-alex98** [comment]
tested it does not seem to cause any issues with web views scrolling or webview scaling
