### ISSUE TITLE
Add a notification that the client is in debugger mode.

### ISSUE THREAD

**Issue by Marc-Spector** [FAForever/downlords-faf-client#2629]
If the logging level is different from the `INFO` or higher

**Comment by Sheikah45** [comment]
I don't think this is necessary. I set the default to debugging just because of some issues people were having. Why do you think a notification is necessary?

**Comment by Marc-Spector** [comment]
I didn't know that the default logging level is `debug`. 
When I updated the client, there was a feeling that the client began to slow down.

**Comment by Sheikah45** [comment]
If there is a performance impact that would be good to know, I personally haven't noticed on my machine, but would be good to know if it measurably does for others
