### ISSUE TITLE
No the install button on a mod details window

### ISSUE THREAD

**Issue by Marc-Spector** [FAForever/downlords-faf-client#2630]
Open mods vault
Select any mod
Try install the mod... No the button

**Screenshots**
![image](https://user-images.githubusercontent.com/38242291/160730342-8cea3ae4-83eb-4ddf-acff-95df5a7669bf.png)

**OS**
Windows

2022.3.0

**Comment by 1-alex98** [comment]
@Brutus5000 am I right in the assumption that the new CDN does not deliver a content size anymore via the header ?

**Comment by 1-alex98** [comment]
Seems like it

**Comment by Sheikah45** [comment]
Ah that is unfortunate
