### ISSUE TITLE
Indeterminate progress indicator for downloads

### ISSUE THREAD

**Issue by BlackYps** [FAForever/downlords-faf-client#2664]
**Describe the bug**
When downloading maps, mods or a new game version the progress indicator in the status bar at the bottom of the client is indeterminate. This is inconvenient because you get no feedback how much the download progressed and if it is making progress at all. Interestingly it works as desired when downloading the next client version from inside the client.

**To Reproduce**
Download a sufficiently large file so you can get a good look at the progress indicator

**Comment by Sheikah45** [comment]
The cloudflare CDN does not provide the Content-Length header to tell us how big the file is without downloading it, so have to figure out some other way to get the size of the files

**Comment by Sheikah45** [comment]
This works for the largest files of the patches as they are not behind the CDN. For the others that are smaller I think the indeterminate is best for now.
