### ISSUE TITLE
Visualize (castomize) channel topic

### ISSUE THREAD

**Issue by Marc-Spector** [FAForever/downlords-faf-client#2671]
How about visualizing, customizing channel topic?
For example:
`\n` - line break
`**text**` - **text**

and so on.
What do you think about it?

**Comment by Sheikah45** [comment]
This could be done but would be on the topic setters to format it. But one issue is that there are users and moderators who normally set the topic who use 3rd party irc clients. So if they were to add the text stylings it would just make it more random and hard to read in that environment.

**Comment by Marc-Spector** [comment]
You're right. Today I learned that there are 3rd party IRC clients. Tried one of them. Cool! 😃 
![image](https://user-images.githubusercontent.com/38242291/163997678-7fe04800-3485-4456-a22e-00dc8062b403.png)
