### ISSUE TITLE
Sorting options when searching for map or mod

### ISSUE THREAD

**Issue by Garanas** [FAForever/downlords-faf-client#2680]
**Is your feature request related to a problem? Please describe.**

When searching in the vault you can only sort on name. This is unintuitive when searching for adaptive or survival maps as you are likely more interested in good adaptive / survival maps over those that happen to start with the letter `a`.

![image](https://user-images.githubusercontent.com/15778155/165736284-e7d05cc3-00a3-4225-8dbd-77d686c02483.png)

**Describe the solution you'd like**

You should be able to sort on:
 - most recent maps / mods
 - most valued maps / mods (using star system)
 - most played maps / mods

And either of these should be the default, I'd argue it should be most valued as that keeps the most relevant maps on top and allows for shifts in the hierarchy that make sense. As an example, if you use most player then it may take years (if not more) for a map or mod to get onto the first page. But when using the most valued criteria it can be achieved within weeks.

**Describe alternatives you've considered**

I don't feel there is an alternative.

**Comment by Sheikah45** [comment]
This is actually a limitation of the underlying api that the vault uses that has been under work to improve here https://github.com/FAForever/faf-java-api/issues/448

**Comment by Sheikah45** [comment]
Although I can look at which ones don't have the underlying limitation

**Comment by Sheikah45** [comment]
Ah yeah never mind can't sort over it because it doesn't support pagination

**Comment by ghost** [comment]
API works like a charm https://youtu.be/gnbehQYP-58

It is just sample, but with additional work it is possible to add multiple sorts i guess

![image](https://user-images.githubusercontent.com/86099479/165912706-abd5f8a5-0d7c-45ac-9bf7-b829dcd264cf.png)

![image](https://user-images.githubusercontent.com/86099479/165912995-08b563a4-187d-4dab-a932-3a3c6d3f22c4.png)

**Comment by Sheikah45** [comment]
Eternal that only works for direct attributes of the objects, sorting will return an error if you try to sort over related object attributes

**Comment by bukajsytlos** [comment]
to be more specific, over one to many relation

**Comment by ghost** [comment]
https://api.faforever.com/data/mapVersion?include=map&sort=-map.gamesPlayed over map attributes from mapVersion

**Comment by bukajsytlos** [comment]
to be more more precise :)
```
//SQL does not support distinct and order by on columns which are not selected
                throw new InvalidValueException("Combination of pagination, sorting over relationship and"
                    + " filtering over toMany relationships unsupported");
 ```
Elide would in this conditions create query, which would sort over not selected fields.
More https://blog.jooq.org/how-sql-distinct-and-order-by-are-related/

**Comment by Sheikah45** [comment]
Does this mean we just have to include anything we sort?

**Comment by bukajsytlos** [comment]
> https://api.faforever.com/data/mapVersion?include=map&sort=-map.gamesPlayed over map attributes from mapVersion

btw that's many to one

**Comment by bukajsytlos** [comment]
> Does this mean we just have to include anything we sort?

theoretically, but it is not possible with one to many relationships. it would break pagination because of duplicates

**Comment by Sheikah45** [comment]
sounds good. For now I will close this though
