### ISSUE TITLE
Long delay in `game_launch` message

### ISSUE THREAD

**Issue by Askaholic** [FAForever/downlords-faf-client#2686]
Sometimes the `game_launch` message takes a long time to arrive when trying to start a game.

To reproduce:
1. Log in
2. Create game. Note that the game is not created
4. Hit create game again. Now two games get created

**Comment by Sheikah45** [comment]
Also notably this allows the for cases when a client can send game_host request or game_join request in quick succession. The server then responds with potentially two game_launch messages when only one game_launch and an error would be expected.

**Comment by Askaholic** [comment]
After testing it on the test server this lag seems to be coming from the client. When sending the message through other means it seems to show up immediately.

**Comment by Sheikah45** [comment]
This is due to the client setting up the files and preferences before launching the game.

As to being able to launch multiple games at once on the server that is something that should be handled in the server code.
