### ISSUE TITLE
Map name in Game Creation dialog map thumbnail is no longer right-clickable since the introduction of map zoom

### ISSUE THREAD

**Issue by phongu** [FAForever/downlords-faf-client#2687]
Before we had [map zoom](https://github.com/FAForever/downlords-faf-client/pull/2641) in the Game creation dialog, one could right click the map name displayed on top of the thumbnail to copy it to clipboard, when that map was a generated one. This was useful in case i had to restart faf because my lobby broke (since restarting faf clears generated maps, i have to get that map name into the clipboard to be able to set the lobby back up fast). With the addition of map zoom, the right click functionality is gone, and instead the right click now behaves exactly like the left click, zooming in the map. This leaves no option for copying the map name of a generated map that's not associated with a replay except for hosting a game on that map and alt-tabbing to the faf client, then highlighting the lobby and right-clicking the map name in the lobby details on the right. Since sometimes broken lobbies disappear from the custom game list, even this option might not be available precisely when it's needed.

**Comment by Sheikah45** [comment]
Ah oops layered the elements incorrectly
