### ISSUE TITLE
OBS Window Capture dosent display dropdown menus

### ISSUE THREAD

**Issue by MrRowey** [FAForever/downlords-faf-client#2707]
**Describe the bug**
When Streaming and using window capture the dropdown lists don't show up on stream.

**To Reproduce**
load up OBS set faf client to Window capture FAF Client and open up COOP mission selection and it wont show up in OBS view

**Comment by Brutus5000** [comment]
That is a common issue with window capture in general.
And the "damage done" here tends to zero.
I don't think we should invest any time here.

**Comment by Marc-Spector** [comment]
He is right. It has nothing to do with the client.
