### ISSUE TITLE
Can't login to faf since the update to v0.6.14-alpha

### ISSUE THREAD

**Issue by Justify87** [FAForever/downlords-faf-client#272]
The server sends a "invalid command" message.
See attached log file

[downlords-faf-client.zip](https://github.com/FAForever/downlords-faf-client/files/334709/downlords-faf-client.zip)

**Comment by micheljung** [comment]
@muellni Can you check with @Justify87 if the new UID works correctly on his system?

**Comment by muellni** [comment]
I'll try

**Comment by muellni** [comment]
Problem should be fixed in uid v2.0.6
