### ISSUE TITLE
FAF client is issuing wrongful connection violations for issues in connection that it itself caused

### ISSUE THREAD

**Issue by tatsujb** [FAForever/downlords-faf-client#2721]
this is the second time this has happened to me. FA fails to connect with the other player and then when it finally closes back on FAF there's a popup waiting for me saying i've been issued a violation.

how is that fair?

also this is darn pattern

**Comment by Sheikah45** [comment]
This was purposefully added to the server protocol in https://github.com/FAForever/server/pull/885


It is to prevent players with bad connections from continuing to break matchmaker games. If you cannot connect to the host you are at fault.

Additionally this is implemented server side and the client has no control over it.

**Comment by tatsujb** [comment]
> If you cannot connect to the host you are at fault.

no that's just plain wrong
