### ISSUE TITLE
Lose Game Audio When Alt-tab

### ISSUE THREAD

**Issue by andrewtvuong** [FAForever/downlords-faf-client#2722]
**Describe the bug**
Lose game audio permanently when in game and alt tab out. Only way to restart the program.

**To Reproduce**
alt tab while in game, including game room lobby.

**Log or error message**
This is my log file:
Not sure how to pull logs.

**Expected behavior**
Alt tab should have no impact on audio

**Screenshots**
n/a

**OS**
Linux or Windows

Windows

**Wanna have the bug fixed quickly?**
Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

Anyone else have this issue? Eager to work on this.

**Comment by Sheikah45** [comment]
The sound and alt-tab issues with the game are well documented and out of our control. The client is unable to affect the behavior of the game when alt tabbing as that is directly controlled by the game engine which we do not have access to.

The recommended way to resolve this is to play the game in windowed mode.
