### ISSUE TITLE
Add Leaderboard Criteria

### ISSUE THREAD

**Issue by MrRowey** [FAForever/downlords-faf-client#2737]
On the Coop tab where the leaderboard Title is could we add a small I in a circle to provide a description to what qualifies to be on the leaderboard. As the leaderboard only show if the game is completed on hard with all secondary mission completed as well

![image](https://user-images.githubusercontent.com/20344151/175830949-84d530a5-85e5-4cae-925d-052fc4968ed4.png)

**Comment by Marc-Spector** [comment]
@MrRowey Could you add description text?
