### ISSUE TITLE
coop replay failures in latest update

### ISSUE THREAD

**Issue by jnorthrup** [FAForever/downlords-faf-client#2747]
**Describe the bug**
![image](https://user-images.githubusercontent.com/73514/177415830-db1d05a3-02ef-4733-bc17-171cbaea0195.png)

loading prothyon coop map replay from leaderboard.  

**To Reproduce**
linux platform, steam installation, launf faf, launch coop replay from net. 

**OS**
Linux

**Comment by Marc-Spector** [comment]
If the game starts and cannot play the replay, then it is something related to the replay, but not to the client.

**Comment by jnorthrup** [comment]
this is what the missing replay file looks like from the dialog box. 

![image](https://user-images.githubusercontent.com/73514/180377637-1d16abae-e648-4bfc-ba68-cadd2ffe1f83.png)

I have noticed the the client uses a CurrentWorkingDir that cannot be changed to an absolute path when for example specifying the run.sh script anywhere other than ~/.faforever/bin (on linux) 

it seems possible that this java CWD could affect replays as well, attempting to find a relative path of /home/jim/.faforever/cache/home/jim/.faforever/cache/temp.scfareplay

**Comment by jnorthrup** [comment]
the usecase is as shown here.

![image](https://user-images.githubusercontent.com/73514/180381707-36a08018-e446-41bd-81b6-dd1a61843126.png)

i have opened the source code and the string "scfareplay" is ~~not (previous file mask hid this)~~ in the project  loaded by intellij from gradle.

the stackrtace is inconclusive as to the source of the method it only goes as far as a javafx library. 

the is the replay as downloaded: 
![image](https://user-images.githubusercontent.com/73514/180381974-0ea9f0e7-633d-471b-a6dd-d3b523b65081.png)


i prepended "z:" to the filename before it calls the exe like so just in case this helped Wine see the VFS better.  

![image](https://user-images.githubusercontent.com/73514/180388635-7b420a6d-7d3b-4e4c-a9bb-53a738133335.png)

the error message dialog shows something like CWD being prepended to z:/

![image](https://user-images.githubusercontent.com/73514/180387087-52ba759e-adf0-4b39-9194-a18df55cb5da.png)

**Comment by jnorthrup** [comment]
removing the z:/ reproduces the error in the beginning of the issue.

client log reports this 
2022-07-22 15:53:59.746  INFO 2091090 --- [ForkJoinPool.commonPool-worker-5] c.f.client.fa.ForgedAllianceService      : Starting Forged Alliance with command: [protontricks-launch, --appid, 9420, %USER_PROFILE%/.faforever/bin/ForgedAlliance.exe, /init, init.lua, /nobugreport, /log, %USER_PROFILE%/.faforever/logs/game_16403379.log, /replay, %USER_PROFILE%/.faforever/cache/temp.scfareplay, /replayid, 16403379] in directory: %USER_PROFILE%/.faforever/bin

**Comment by jnorthrup** [comment]
when prepending a `Z:` to `%USER_PROFILE%` the coop replays fail but otherwise all else still works as to be expected under wine with Z-drive, and to boot, normal replays do still also work.

2022-07-22 16:27:02.662  INFO 2101110 --- [ForkJoinPool.commonPool-worker-10] c.f.client.fa.ForgedAllianceService      : Starting Forged Alliance with command: [protontricks-launch, --appid, 9420, Z:%USER_PROFILE%/.faforever/bin/ForgedAlliance.exe, /init, init.lua, /nobugreport, /log, Z:%USER_PROFILE%/.faforever/logs/game_17565031.log, /replay, Z:%USER_PROFILE%/.faforever/cache/temp.scfareplay, /replayid, 17565031] in directory: Z:%USER_PROFILE%/.faforever/bin


so the question is why do recent coop replays fail ?

**Comment by Marc-Spector** [comment]
@jnorthrup 
Sorry for my mistake. I run the replay specified in your screenshot and get the same error. The problem is that the client does not download the version of the game specified in the replay file (it is 3704). 
Therefore, the replay will not start in the game with version 3740, which we are currently using.

**Comment by jnorthrup** [comment]
@Marc-Spector  @Sheikah45   when i check out faf develop and run ghoullord's prothyon campaign as shown i see the dsync message then the map but the scenario is not running.  I see the chat dialog pop up "ghoullord starting gun upgrade" but the map is empty

**Comment by jnorthrup** [comment]
![image](https://user-images.githubusercontent.com/73514/182019329-6f538458-d53d-45c7-90ba-7142431ab6a7.png)
replay from 1 year ago to the day is working

**Comment by Sheikah45** [comment]
Seems like GhoulLord's replay was run with some mod that is not known to the client so cannot be replayed without that mod else it will desync
