### ISSUE TITLE
local player is exluded from game preview stats

### ISSUE THREAD

**Issue by Justify87** [FAForever/downlords-faf-client#275]
Example: 
a custom game in the client is shown with 7/12 players 
tooltip and preview panel lists 6 players, I'm not listed in any of the teams

**Comment by micheljung** [comment]
I can't reproduce that:
![image](https://cloud.githubusercontent.com/assets/1864183/16502911/f5f0f654-3f10-11e6-9b70-4b24c4631e48.png)

**Comment by Justify87** [comment]
![2016-06-30 23_00_21-apcent](https://cloud.githubusercontent.com/assets/10554299/16504103/8a6a2f3a-3f16-11e6-9540-d3e67df093fd.jpg)

I didn't do anything special. It doesn't matter if I join a game or host a game. I'm not shown.

**Comment by micheljung** [comment]
Alright, must be another case of username insensitivity.
Your username is "Justify" but you logged in with "justify"

**Comment by Justify87** [comment]
I guess so. Maybe the same thing also prevents me from seeing my general player statistics? (Games played, rating evolution over time, etc.) I can see the statistics of other players.

**Comment by Justify87** [comment]
Just tested it. Logging in as "Justify" makes the graph show my rating evolution.
