### ISSUE TITLE
Fix native window behavior on Window 11

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#2762]
FxStage didn't support Windows 11 yet, so the client fell back to non-native window behavior. FxStage 0.8.3 does support Windows 11, fixing it.

**Comment by Sheikah45** [comment]
When you say non native do you mean the snapping or something else?

**Comment by micheljung** [comment]
Yes, snapping and some other native window features. I've just released 0.8.3 so within hours it will be on Maven central. I guess Dependabot will create an MR then?

**Comment by Sheikah45** [comment]
Yes it will. And I am just curious because I have been on Windows 11 for a while and snapping has worked fine for me. I did not notice anything weird

**Comment by micheljung** [comment]
Doesn't it have padding around the window? It's pseudo-snapping; in normal snapping (left/right half of the screen) you can choose which other window to display next to it. This is something that also doesn't work in custom mode.
