### ISSUE TITLE
Rejoining IRC-channel is broken

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/downlords-faf-client#279]
**Steps to reproduce:**

1. Join any channel (e.g. _/join #allhailbrutus_)
2. Close the channel tab
3. Rejoin the channel (send first command again)

**Expected result:** the channel tab opens a second time.
**Observed result:** nothing happens

**Comment by micheljung** [comment]
Probably a result of channels only being added to chatservice but never removed when left.
