### ISSUE TITLE
Implement Replay vault

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#28]

**Comment by Cheyans** [comment]
I think we should push this back more, we need a lot more server side support for this

**Comment by micheljung** [comment]
Let's just implement basic features like the current client has

**Comment by Cheyans** [comment]
Ideas

Suggested map search
Search multiple players
Apm next to player
times watched/downloaded
replay rating (probably 5 star system)
top replays of day/week/month/year/all-time
most watched/downloaded
Player count
Rating bound search
Save replay directly without opening browser (maybe downloaded replay section?)
