### ISSUE TITLE
Add criteria player rating to the replay tab's advanced search

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/downlords-faf-client#2803]
You can use player ratings to find replays in the filter search but not in the advanced search. I guess it's not that advanced :D

**Comment by Sheikah45** [comment]
Advanced search was only still included as a hold over from when the filter search was included. Now for advanced users there is the option to fully customize and save their searches so advanced search is officially deprecated and will be removed at some point so no new features will be added.
