### ISSUE TITLE
Offline mode without ever logging in

### ISSUE THREAD

**Issue by anonghuser** [FAForever/downlords-faf-client#2828]
The currently implemented "play offline" solution relies on having logged in at least once to download something or other that is not explained too well by the message, documentation or website infos that I could find.

My main reason for wanting an offline mode in the first place is because I don't have an account and am not convinced that I want one yet before trying things out. So the suggested "login once first" solution does not help.

Please explain better what needs to be downloaded manually and from where, to make offline mode usable. Or even better - make the installer or launcher download it without the need for an account.

**Comment by Sheikah45** [comment]
You have to login once because in order to download the files to play you have to prove that you already own the game. 

This can only be done when a FAF account is linked to either gog or steam. So this is why you need to log in at least once to download the files and prove you own the game already.

**Comment by anonghuser** [comment]
In that case, I'd suggest you make a steam/gog login instead of requiring email or other unrelated social account oauth logins. 

Without a way to try it, I'm not even convinced your client will crash less than the normal steam version or have any benefit, so I am not eager to give my email or non-game related social accounts for playing a game.

**Comment by anonghuser** [comment]
In addition, I don't see how you can verify I own the game even with my steam account linked. The API does not let anyone aside of the game's actual publisher see ownership information. You may access achievement or time-played statistics but those can be had even without owning it, i.e. after refunding it or by temporarily borrowing it from a friend, or can be missing for people that do own it but never played it. So I don't think your reasoning is correct.

**Comment by Sheikah45** [comment]
> In addition, I don't see how you can verify I own the game even with my steam account linked. The API does not let anyone aside of the game's actual publisher see ownership information. You may access achievement or time-played statistics but those can be had even without owning it, i.e. after refunding it or by temporarily borrowing it from a friend, or can be missing for people that do own it but never played it. So I don't think your reasoning is correct.

For the linking process we require that your games list be made temporarily public for us to check via api.
