### ISSUE TITLE
Display number of filtered out games

### ISSUE THREAD

**Issue by BlackYps** [FAForever/downlords-faf-client#2832]
For the newly introduced game filter it would be awesome if the client would display the number of filtered out games in the lobby and live games tab. This acts as a feedback and reminder to the user that the filter is active.

**Comment by Marc-Spector** [comment]
Showing the number of filtered out items is easy. But... I still can't find a good way to add a footer to the tables.

**Comment by BlackYps** [comment]
Maybe instead of displaying it in the menu, display it next to the entire button that opens the menu? There is enough space next to it

**Comment by Marc-Spector** [comment]
Ok, No problem
