### ISSUE TITLE
The client does not notify that a lobby is full when you watching a replay

### ISSUE THREAD

**Issue by Marc-Spector** [FAForever/downlords-faf-client#2836]
**To Reproduce**
1. Allow watching replays while in a game via `Settings -> Forget Alliance Forever`
2. Host a game or join to any game
3. Watch any replay
4. Wait when a lobby is full

**Log or error message**
No need

**Expected behavior**
Notify an user that the lobby is full

**Screenshots**
No need

**OS**
Windows

**Client Version**
2022.10.0-alpha-2

**Comment by Sheikah45** [comment]
The issue is that the game full notification only plays when FA is not focused. I don't know if we can tell which window belongs to which game. 

Only solution would be to send the game full no matter if the window is focused or not.

**Comment by Marc-Spector** [comment]
It is easier to find out how many game instances were run using the method `getAllWindows(bool)` of class `com.sun.jna.platform.WindowUtils`.
We get all the windows and filter by `Forged Alliance` title. 

![image](https://user-images.githubusercontent.com/38242291/199146212-01e4e436-f011-409a-b1eb-8ae479268f96.png)

**Comment by Sheikah45** [comment]
Yes but is there a way to figure out which one is the game and which one is the replay? Also to figure out if the one that is the lobby already has focus?

I think it might be worse to flash both windows
