### ISSUE TITLE
Map searchbar in 'create game' only shows case-sensitive matches

### ISSUE THREAD

**Issue by IndexLibrorumProhibitorum** [FAForever/downlords-faf-client#2839]
**Bug description:**

The little searchbar on the top right of the 'create game' window does not return (all) search results when looking for a map name. _Sheikah45 identified this was due to case-sensitivity._ 

**Expected behaviour**
Show all maps for which the map name at least partially matches the search string

**screenshots**
Example: search string "adapt"
![image](https://user-images.githubusercontent.com/64420140/199958383-4596e7bb-3132-4fc2-b7ab-77503fccd49c.png)
![image](https://user-images.githubusercontent.com/64420140/199958410-17ffd2df-97fa-4b7d-b593-fbe252a2943e.png)

Example: search string "pla"
![image](https://user-images.githubusercontent.com/64420140/199958564-75018dca-37a9-49f5-a6df-e864a08d040b.png)
![image](https://user-images.githubusercontent.com/64420140/199958778-7b84f2c4-9557-4b0d-ba03-0b4993ec7160.png)

**OS**
Windows 10

**Client version**
2022.10.0

**Comment by Sheikah45** [comment]
This is just showing that right now the search is case sensitive

**Comment by IndexLibrorumProhibitorum** [comment]
Well spotted! Edited post to reflect the need for non-case sensitive searchbars.
