### ISSUE TITLE
Set minimum width and height for the client

### ISSUE THREAD

**Issue by Marc-Spector** [FAForever/downlords-faf-client#2848]
The smallest resolution in the game that can be applied is 1024x768

It must be applicable to the client. This is a way to avoid issues with the display of content (usually these are overlapping views)

**Comment by Sheikah45** [comment]
I don't know if we have to have the same min size as the game. But yeah some min size might be nice although I am not sure if it needs to be set to full screen. I know some people like having the screen split. 

So maybe we just also have to make the client more responsive

**Comment by Marc-Spector** [comment]
> So maybe we just also have to make the client more responsive

Okay. 👍
