### ISSUE TITLE
Outbound Traffic Issue

### ISSUE THREAD

**Issue by TestPlayer** [FAForever/downlords-faf-client#285]
Hello All.

I am having this Outbound Traffic Issue whereby it has gotten worse since the latest update.

I am getting it more often right now, than the previous update. The screen would go white and then inform me that my outbound traffic is blocked. The worst part is that I can hardly even connect to other players in ranked (ladder) now, then previously before. I would have to relogin again and again and hope that it would be okay, but apparently it is not.

Even if I do get the luck of having a game, it is very laggy, since the latest update, and this outbound traffic issue seems to be going on for a long time.

Is there any fix to this issue? Attached below are my logs.

Thanks! :)

[logfile.txt](https://github.com/FAForever/downlords-faf-client/files/367871/logfile.txt)

**Comment by micheljung** [comment]
Hi, please report this issue to the repository of the client https://github.com/FAForever/client/issues

With my client you don't have this issue, but if you have any other (I read something?) then please let me know and I'll look into it.
