### ISSUE TITLE
Change map pool display

### ISSUE THREAD

**Issue by BlackYps** [FAForever/downlords-faf-client#2869]
The matchmaking team wants to switch the bracket of maps that is considered for selection for the matchmaker from the lowest rated to the average rating of the game. This means that someone could end up in games on maps that are not displayed in his map pool, which could be confusing. To prevent this we could show all the maps in the map pool for everyone, but gray out the ones that are not in the rating bucket of that player. A tooltip on hover could explain why the grayed out maps are displayed that way.

**Comment by DotNetSimon** [comment]
Suggested draft UI changes:
![image](https://github.com/FAForever/downlords-faf-client/assets/86734095/ca68b312-32e0-430d-8b92-0675b6a40e46)

**Comment by Sheikah45** [comment]
Sorry @DotNetSimon the grayscale changes was considered to have fixed this issue so it should have been closed when that was merged
