### ISSUE TITLE
Ladders for popular maps like Dual Gap or Astro Crater? Map specific ratings?

### ISSUE THREAD

**Issue by mankinskin** [FAForever/downlords-faf-client#2878]
Could we have auto matched games and ladders for specific maps like dual gap or Astro? I also think it would be cool if we had a specific rating for each map, so maybe in the Matchmaker tab we could have a list of queues on specific maps and each match gets made automatically.

I know this is probably a bigger feature, especially if we want to integrate the map specific rating nicely and this is only to get some feedback on the idea and have a place to talk about it.

**Comment by Sheikah45** [comment]
The matchmakers were not intended for single map queues. Additionally it is already easy to get games on the maps you mentioned so would have little benefit. Lastly this isn't really a client issue and would be taken up by the matchmaker team.
