### ISSUE TITLE
Don't crash on invalid map installed

### ISSUE THREAD

**Issue by tatsujb** [FAForever/downlords-faf-client#288]
http://pastebin.com/whhJKMsf

this is what I get after the splash screen when I run DFAF

![image](https://cloud.githubusercontent.com/assets/5132359/17085693/98fa86d2-51de-11e6-94c6-382e61961622.png)

**Comment by micheljung** [comment]
Apparently you have a map with an invalid LUA file. Seems I have to catch that:

`C:\Users\tatsu\Documents\My Games\Gas Powered Games\Supreme Commander Forged Alliance\maps\Open Waters.v0001\open waters_scenario.lua`

**Comment by tatsujb** [comment]
so i deleted that map and
Permafrost Pass.v0002

and now the error is : "Invocation of init method failed; nested exception is com.faforever.client.map.MapLoadException: Map folder does not contain a *_scenario.lua"

http://pastebin.com/PQ1VJTUD
