### ISSUE TITLE
Add `Generate map` button in replay card for generated map

### ISSUE THREAD

**Issue by BlackYps** [FAForever/downlords-faf-client#2904]
The new generate map button for lobbies is very nice. Would be amazing to also have this option when browsing through replays.

**Comment by Sheikah45** [comment]
Unfortunately there is no way to know if a replay is a generated map or not from the replay metadata. Right now though it is set that if you download more info about the replay and it turns out to be a generated map the map will be generated.

**Comment by BlackYps** [comment]
Is there a reason to wait with downloading the replay info until the user requests it?

**Comment by Sheikah45** [comment]
Mainly just to conserve bandwidth and not make unnecessary requests. Since most people don't care about downloading every replay. As the replay info is read from the replay itself.
