### ISSUE TITLE
Launcher not starting properly on Linux

### ISSUE THREAD

**Issue by Anax-M** [FAForever/downlords-faf-client#2912]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior: Run [faf-client-2023.2.0-alpha-1](https://github.com/FAForever/downlords-faf-client/releases/tag/v2023.2.0-alpha-1) in Archlinux with that command:
Install FAF to your desired DIR (In my case ~/Spiele: German word for Games)
Install Java 17 with that command: `pacman -S jre17-openjdk`
Run that Command to run FAF `INSTALL4J_JAVA_HOME=/usr/lib/jvm/java-17-openjdk ~/*Desired-Dir*/faf-client-2023.2.0-alpha-1/faf-client`

**Log or error message**
This is my log file:
[error.log](https://github.com/FAForever/downlords-faf-client/files/10710488/error.log)

**Expected behavior**
Launcher starts up

**Screenshots**
![ArcoLinux-2023-02-10-1676057266_screenshot_1920x1080](https://user-images.githubusercontent.com/79524821/218180262-8500c342-acc8-474b-ab78-b0dad8c45eb3.jpg)
Used Enviroment and Command ( Please Ignore DE, it was wrong defined in .profiles)

![ArcoLinux-2023-02-10-1676057370_screenshot_1920x1080](https://user-images.githubusercontent.com/79524821/218180584-6a3bcdef-59b8-4415-a6fd-80fcb4fc7076.jpg)
The Only Graphical Thing you can before it crashes

![ArcoLinux-2023-02-10-1676057358_screenshot_1920x1080](https://user-images.githubusercontent.com/79524821/218180698-abf1c61f-7dfd-4703-b807-567a972eec28.jpg)
Error GUI

**OS**
Linux
Distro: ArcoLinux (In Fact ArchLinux with some help packages)
Kernel: 6.1.10-arch1-1
WM: i3

**Comment by Brutus5000** [comment]
`cannot use an unresolved DNS server address`
Fix your system, bro

**Comment by Sheikah45** [comment]
This is due to a misconfigured DNS on the machine

**Comment by iczero** [comment]
Netty does not support scoped IPv6 addresses in `/etc/resolv.conf`. Install `systemd-resolved` if possible. Please see https://github.com/faforever/faf-linux for more information.
