### ISSUE TITLE
startup error after clean instal

### ISSUE THREAD

**Issue by Jasperguymann** [FAForever/downlords-faf-client#2930]
Description:
When opening FAF Client, after loading for 5 sec, Startup error prompt shows. I tried to re-install, gave more permisions to the game folder and disabled my windows defender. The error, however, keeps occuring.

Error occurs while starting FAF Launcher v2023.2.0 and desktop shortcut to launcher

This is my log file:
[Startup Bug FAF.txt](https://github.com/FAForever/downlords-faf-client/files/10876085/Startup.Bug.FAF.txt)

Expected behavior:
Faf Client should start up

Screenshots
![image](https://user-images.githubusercontent.com/126822689/222562861-8ab0a297-2b83-411c-9c64-4c8b0f7d9564.png)

OS:
Windows 10 Pro
64 bit

Visit Issue hunt...
[![Issue hunt](https://github.com/BoostIO/issuehunt-materials/raw/master/v1/issuehunt-button-v1.svg?sanitize=true)](https://issuehunt.io/r/FAForever/downlords-faf-client)

**Comment by magge-faf** [comment]
Are you starting it from a network path, or is it related to a network path in your OS somehow?

 The error "Caused by: com.sun.jna.platform.win32.Win32Exception: Kan het netwerkpad niet vinden." translates to "Can't find the network path"

**Comment by Jasperguymann** [comment]
that's the weird thing, its on my C drive, which is a m.2. SSD.

How can I check if there is a relation? (during the re-install I did not have to select a network path or tick a network box, so I wouldn't know how any kind of relation might have occured? )

**Comment by Jasperguymann** [comment]
> that's the weird thing, its on my C drive, which is a m.2. SSD.
> 
> How can I check if there is a relation? (during the re-install I did not have to select a network path or tick a network box, so I wouldn't know how any kind of relation might have occured? )

FIXED! I was not aware that my NAS was turned off. On this NAS is my entire library. Apparently the game, even tho it is installed on my c-drive, needs acces to my video/immages/files ?? I do not know why or how (cant find any folder made by the game on there, not even hidden folders), but as soon as my NAS booted, the bug was gone :)

**Comment by bukajsytlos** [comment]
didn't you move maps folder or some other folder in client preferences to your NAS?

**Comment by Jasperguymann** [comment]
I settup my NAS one year ago (before I even heard of FAF) and have not changed any settings since... My guess is that FAF needs a place to store screenshots or whatever and chooses the default user immages library? (which has been setup to be on my NAS)

**Comment by bukajsytlos** [comment]
Looks like issue is with defaultVaultDirectory (storing replays, maps, mods) and defaults to location of `My Documents\My Games\Gas Powered Games\Supreme Commander Forged Alliance` folder.
