### ISSUE TITLE
Add an explicit search button for matchmaker

### ISSUE THREAD

**Issue by BlackYps** [FAForever/downlords-faf-client#2938]
This is a proposal to rework the matchmaking ui a little. Apparently some people simply refuse to read any text and are therefore unaware of the concept of multiqueueing. We could improve this by making all queues selected by default similar to the factions. For this we need an additional button that triggers the actual queueing. I think we can do this without any change of the protocol by simply changing the logic when the client sends the "start search" messages.

The new button has the additional benefit that the text changes that e.g. inform you about reasons why you are unable to queue are now in a prominent button instead of the gray on black text above the queues.

![grafik](https://user-images.githubusercontent.com/52536103/223877306-dd02886c-c07b-43d7-ad47-d891b16f972f.png)

**Comment by Sheikah45** [comment]
I don't know if having it at the bottom is good as it will jsut get pushed down if more queues are added. Additionally as it is right now it looks like I just need to press it to play. But that isn't true I first need to select a queue then press the play button

**Comment by Sheikah45** [comment]
Why not just add play before the name of the queue on the buttons we currently have?

**Comment by Brutus5000** [comment]
I'd rather suggest "Enroll for xVx"

**Comment by BlackYps** [comment]
We comfortly have enough space for a second row of queues. I realized my screenshot is actually a bad showcase. By default all queues would be selected. This way you can just hit the play button. Ideally it would prevent you from deselecting all queues similar to the faction buttons, but this might be a bit complicated to implement.

Adding "Play" or something else in front of the queue name doesn't actually achieve anything as we want to highlight that you can multiqueue. Changing the queue text doesn't help with this.

**Comment by Sheikah45** [comment]
Ah got it so your intention would be to default to multi queue and have people opt out of queues. Then this would make more sense from that perspective

**Comment by BlackYps** [comment]
Yes, exactly
