### ISSUE TITLE
Client UI is extremely laggy

### ISSUE THREAD

**Issue by mankinskin** [FAForever/downlords-faf-client#2952]
**Description**
Client often becomes unresponsive for a few seconds, especially when interacting with the chat, either private chat or the player search. Also the tab bar is unresponsive pretty much most of the time except occasionally.

**To Reproduce**
Start the client and click through tabs, search for players and write chat messages.

**OS**
Windows 10

**Comment by Sheikah45** [comment]
Include a log as well as what version you are using

**Comment by mankinskin** [comment]
version 2023.3.0

[client.log.zip](https://github.com/FAForever/downlords-faf-client/files/11226620/client.log.zip)

**Comment by Sheikah45** [comment]
This should be resolved with some of the garbage collection fixes recently made.

Also generally this issue is very broad so if it still happens making narrower scoped issues is preferred
