### ISSUE TITLE
FAF client freezing and crashing when switching between tables and tiles in rapid succession

### ISSUE THREAD

**Issue by magge-faf** [FAForever/downlords-faf-client#2954]
When switching between tables and tiles in a short timeframe (<1s), the FAF client freezes and crashes. The error can be reproduced consistently by switching between tables and tiles 6-12 times in rapid succession. It is possible that this error occurs with regular tabs as well when the client has been open for a longer period.

Steps to reproduce:

Open the FAF client
Switch between tables and tiles 6-12 times in rapid succession (<1s)
The FAF client freezes and crashes

 "Unexpected exception from an event executor" error that was previously reported. The error message in the Client.log file indicates a Java heap space error.
[client.log](https://github.com/FAForever/downlords-faf-client/files/11242290/client.log)

![image](https://user-images.githubusercontent.com/101107758/232312322-5555df6d-4f22-4e78-8100-1d4d14ef2207.png)

Expected behavior:

The FAF client should not freeze or crash when switching between tables and tiles.

Actual behavior:

The FAF client freezes and crashes when switching between tables and tiles in rapid succession.

Additional information:

The fix of this issue solves maybe this one as well https://github.com/FAForever/downlords-faf-client/issues/2952

**Comment by MantisMaestro** [comment]
Had a bit of a play around, there definitely seems to be a memory leak in the CustomGamesController, regarding the GamesTilesContainerController and the GamesTableController. I've not dealt with Java for a long while though so I could be barking up the wrong tree. I'll take a better look tonight and see what else I can find.

**Comment by magge-faf** [comment]
Thanks for the fast fix - Amazing work as usual.  The CPU spikes when switching tabs disappeared, and the whole UI feels more responsive now.
