### ISSUE TITLE
Add ready check for automatch games

### ISSUE THREAD

**Issue by DeadMG** [FAForever/downlords-faf-client#2955]
I started searching in ladder at 9am. A game started at 11:30am. I'd long forgotten I'd queued up and was in the shower. The game launched. The issue here isn't that I lost rating as my team inevitably lost. The issue is that _they_ lost rating for my mistake.

The preferred solution would be for the player to click a button to join the match or any other affirmative action to make sure they are present.

**Comment by Sheikah45** [comment]
Duplicate of #1783
