### ISSUE TITLE
Better alerts when a game is found

### ISSUE THREAD

**Issue by haifron** [FAForever/downlords-faf-client#2984]
**Is your feature request related to a problem? Please describe.**
I often leave the client searching for a game while doing something else & don't notice it has found a game until it is launching & I have seconds to react. This has sometimes been about half an hour after I started searching, and I've forgotten I'm searching so I'm suddenly warping into a game - the extra few seconds of warning would make a big difference.

**Describe the solution you'd like**
As an option, the FAF client becomes the top window when you find a match - e.g this behaviour appears in dota 2 when you find a game (I believe it's optional there too).

**Describe alternatives you've considered**
There've also been suggestions on the discord of a sound playing when you find a game which is another good option, though I wouldn't say it's a total replacement.

**Comment by xpertauctionsoftware** [comment]
I agree completely. I have created a few sounds can can be used.
Source is from Pixabay and my own editing.
[match-found.zip](https://github.com/FAForever/downlords-faf-client/files/14785974/match-found.zip)

**Comment by BlackYps** [comment]
I like the sound without voice. Nice work! I assume the license is such that we can use it without attribution?

**Comment by BlackYps** [comment]
related to #1783

**Comment by warrenkc** [comment]
Yes, I give you permission to use it how you want. I got it from here: https://pixabay.com/sound-effects/biodynamic-impact-braam-tonal-dark-176441/

**Comment by DotNetSimon** [comment]
@warrenkc  Hi, Thanks for this sound. I am trying to include it but it is quite loud and unexpected when the match starts. Do you think we can adjust it ?
I have also tried this alternative from PIxabay: https://pixabay.com/sound-effects/countdown-sound-effect-8-bit-151797/ which works better (I think).

I tried launching games with both sounds and even though I anticipated it, this game launch sound you suggested made my heart jump out of my chest. It's a little difficult to simulate perhaps, but assume the sound plays unexpected, and possibly louder than you thought :)

Maybe we should make another 'ping' or 'pwoop' type of notification sound instead?

**Comment by warrenkc** [comment]
@DotNetSimon Would you like me to lower the volume of the audio file? Your idea for the [countdown sound](https://pixabay.com/sound-effects/countdown-sound-effect-8-bit-151797/) is good too!

I will try to get back to you with some more samples to try.


I used the loud and unexpected sound because oftentimes I will leave the room and want to be alerted if a match is found. I think I must be searching for matches when very few players are online so it takes a long time to find a match.

**Comment by DotNetSimon** [comment]
Yeah this happened to me many times, that's why I am working on it now :D

We could make it more fancy and do a dropdown for the sound to pick, or people can change it with the Theme already too.

**Comment by DotNetSimon** [comment]
Ok I tried having this sound and I swear, I have had a heart attack when the game launched. I'm replacing it with the 8-bit beepbeepboop and we can iterate from there.
If you want to try, I can send you a copy of the version that has your sound 😬  but I expect you will 💀 also 😅

**Comment by warrenkc** [comment]
You make me laugh. That is funny. I think it would probably be a good option to have a setting for the path of the audio file. Then if necessary a user can change the setting to point to any audio file.
Thanks for your awesome work!

I setup a python script for my own computer that would play the sound I created. It would play anytime Forged Alliance was launched. It was definitely attention grabbing. 

Match found audio - lowered by 8db:
[match-found-audio-lowered-8db.zip](https://github.com/user-attachments/files/16015402/match-found-audio-lowered-8db.zip)
Feel free to use it if you would like.

Match found audio - Original volume level.
[match-found-audio.zip](https://github.com/user-attachments/files/16015412/match-found-audio.zip)

**Comment by BlackYps** [comment]
Have a look at this: https://www.youtube.com/watch?v=3taTQYor7ZQ it's similar and I don't think it's too scary. If the impact sound effect (this is what I'm gonna call it now) from pixabay is too loud then we can easily adjust this. What I don't like about the countdown is that it is veeeery barebones and sounds unpleasant because it is such a sharp frequency. Also the concept of the countdown doesn't really make too much sense because we can't time it with the game actually launching.

**Comment by DotNetSimon** [comment]
All fair comments. The countdown sound definitely doesn't fit with the other sound effects either so it's just there for a placeholder. I guess our choice could be to lower the volume, use a different notification sound (like some phone alarm) or keep the one suggested by Warren. Theme overrides allow players to change it however they feel like. (which is easier than adding selection as a feature).

**Comment by DotNetSimon** [comment]
Some alternatives that I found with a quick search 🤷 
https://pixabay.com/sound-effects/choir-notification-ringtone-tone-e-major-95172/
https://pixabay.com/sound-effects/level-up-2-199574/
https://pixabay.com/sound-effects/success-fanfare-trumpets-6185/
https://pixabay.com/sound-effects/ringtone-bubbly-bubbles-188202/
https://pixabay.com/sound-effects/short-success-sound-glockenspiel-treasure-video-game-6346/
https://pixabay.com/sound-effects/echo-alert-177739/
https://pixabay.com/sound-effects/xylesizer-163606/
https://pixabay.com/sound-effects/bell-123742/


I'd love to have something like this: https://www.wowhead.com/sound=8960/readycheck but I don't think we would have rights for it :(

Honestly, I think about half the people will hate whatever sound we pick :p But they can disable it right, or replace it if they wish. 
We just have to make sure we don't make too many people angry when they install the new version and suddenly get their ears blasted out by an alert (alternatively, we set the default to disabled?).

**Comment by xpertauctionsoftware** [comment]
[audio-lowered-8db.zip](https://github.com/user-attachments/files/16014561/audio-lowered-8db.zip)
Here is the audio I created lowered by 8db.
Feel free to use it if you would like.
Original volume: 
[match-found.zip](https://github.com/user-attachments/files/16014571/match-found.zip)

**Comment by DotNetSimon** [comment]
ok!

**Comment by DotNetSimon** [comment]
Yeah this works a lot better ❤️
