### ISSUE TITLE
Getting disabled factions in ladder

### ISSUE THREAD

**Issue by mankinskin** [FAForever/downlords-faf-client#2994]
Occasionally I get a faction I have deselected/disabled when playing ladder games.

v2023.5.0
Windows 10

**Comment by Sheikah45** [comment]
This is an issue where the client doesn't resend factions after a connection hiccup

**Comment by Giovle** [comment]
> This is an issue where the client doesn't resend factions after a connection hiccup

Would that mean we can just toggle all factions as a "workaround" so that the client again has the factions?

**Comment by magge-faf** [comment]
@Giovle 

Turn on all factions, then select favorite faction again will work as a temporary workaround. A restart of the FAF client works as well, but not needed with the first approach.
