### ISSUE TITLE
Scrolling takes up a lot of resources

### ISSUE THREAD

**Issue by Garanas** [FAForever/downlords-faf-client#3015]
**Describe the bug**

The client uses a lot of resources while scrolling in Aeolus:

https://github.com/FAForever/downlords-faf-client/assets/15778155/1fddf601-3b12-47ae-8be5-0e61942cedad

**To Reproduce**

With a decent history (100+) messages it lags quite a bit

**OS**
Windows

**Comment by Sheikah45** [comment]
This isn't really a bug. The chat is just a webview/browswer and the chat is converted to html for display. So the scrolling just causes the page to render the new content.

You get the same usage if you scroll through the discord chat as well.

**Comment by Garanas** [comment]
How is the HTML built? Because this is something that started recently for me, I've had the client open for a while but without any problems in framerate in the past
