### ISSUE TITLE
Custom lobbies don't show in the play tab

### ISSUE THREAD

**Issue by bullydozer** [FAForever/downlords-faf-client#3018]
Some custom games don't show when I get on the client unless i click "Hide modded games" in the filter function twice. I'm on Downlords client 2023.7.0. I have "Hide private games" and "Hide modded games" ticked on by default, though ticking these off and then refaffing still hides most of the custom games from me

Steps to reproduce the behavior: Get on the client and check the play tab, then hit "Hide modded games" twice to see if more lobbies pop up

This bug has been persisting for a while, so I'll share log files of the past three days, hope they're the right ones
[client.log.2023-07-26.0.log](https://github.com/FAForever/downlords-faf-client/files/12207340/client.log.2023-07-26.0.log)
[client.log.2023-07-27.0.log](https://github.com/FAForever/downlords-faf-client/files/12207339/client.log.2023-07-27.0.log)
[client.log.2023-07-28.0.log](https://github.com/FAForever/downlords-faf-client/files/12207338/client.log.2023-07-28.0.log)

**Expected behavior**
I expect the client to show me all of the non-modded and non-private games

**Screenshots**
Screenshot after just getting on the client:
![image](https://github.com/FAForever/downlords-faf-client/assets/52135330/a36838ee-37bb-47b7-9d93-730d823a6c1e)

Then I tick "Hide modded games" in the filter function twice and get this (one of the games had just launched, that's why you won't see that one, but a seton's did pop up out of nowhere). During active FAF times it'll hide multiple lobbies from me
![image](https://github.com/FAForever/downlords-faf-client/assets/52135330/60506f7b-f22d-498e-9728-3b28fa4d78ed)

**OS**
Windows

**Comment by neorai** [comment]
same problem windows 10
