### ISSUE TITLE
Updating stuck at 100%

### ISSUE THREAD

**Issue by alphahex99** [FAForever/downlords-faf-client#3045]
When client updating automatically from 2023.10.0 to 2023.11.1 the download always gets stuck at 100% no matter how many times I restart.

Manual install by downloading release exe from here was required to fix.

**Comment by Brutus5000** [comment]
Actually it is not stuck. The progress bar just jumps to 100% for no appearant reason. The download happens in the background and eventually launches the installation process.
(Still a bug worth fixing, if we figure out the reason.)

**Comment by jaques-sam** [comment]
No, it does not start the installation process. It stays at this screen forever (12 minutes with a high speed internet line):
![afbeelding](https://github.com/FAForever/downlords-faf-client/assets/42445148/a9486430-b980-4a51-a64a-9459cfdad1d8)

**Comment by BlackYps** [comment]
I can confirm that normally it starts the installation process as soon as the download is finished. I'm not sure why it doesn't on your machine, but that seems to be a different bug.

Could it be that the wrong percentage is because the client is not able to retrieve the correct file size. I recall that we had this issue with other downloads inside the client. Maps for example

**Comment by jaques-sam** [comment]
At that time I was using a 5 GHz Wifi connection with sudden hiccups or very long latency, which can explain the matter. In any case, the percentage seems to go to 100% immediately, in all cases. 
I have some coding skills (mainly C++, Rust & a bit of Java & C#) so I could help if you can point me to the place in the source code ;-)

**Comment by Brutus5000** [comment]
https://github.com/FAForever/downlords-faf-client/blob/develop/src/main/java/com/faforever/client/update/DownloadUpdateTask.java#L52

I assume the updateInfo.getSize() returns a wrong number or even 0
