### ISSUE TITLE
Feature: Filter Maps by Map Rating

### ISSUE THREAD

**Issue by MrRowey** [FAForever/downlords-faf-client#3051]
![image](https://github.com/FAForever/downlords-faf-client/assets/20344151/e8107441-9fe4-44f3-a591-fdda141a0e53)

In the Sort by options is it possible to filter it by the map rating in the vault?

**Comment by Sheikah45** [comment]
Do you mean filter or sort? You can search using the average score in your screenshot

**Comment by MrRowey** [comment]
Ahh yes that's what i was after, I didn't even see that option just when straight to sort by :)
