### ISSUE TITLE
Lobby Hosting Duration Indicator

### ISSUE THREAD

**Issue by magge-faf** [FAForever/downlords-faf-client#3054]
**Issue:**

Sometimes a lobby is idling for many hours because the hosting player has forgotten about it for whatever reason.

**Causing:**

Players are waiting in that lobby until it fills, then they leave after host does not respond; The lobby still exists, and new people join the lobby again - new cycle of waiting and leaving begins.

**Solution:**

Indicate the hosting time to see which lobbies are idling for many hours/days which are most likely dead ends.

![image](https://github.com/FAForever/downlords-faf-client/assets/101107758/69a59777-aed8-4e46-8b01-a2af9220419b)

**Comment by Brutus5000** [comment]
Very interesting suggestion. Might need the lobby server to send the lobby creation time.

**Comment by Sheikah45** [comment]
I just checked and it does require changes to the lobby server to send creation time.

**Comment by fcaps** [comment]
if we manage to produce some events for this (lobby started, joined, started, changed etc.) we get more out of it than just "how old it is". 
Thinking about "expected waiting time for a lobby", "host is a fast starter badge - got lobbies filled <5min" etc.

**Comment by HermanSkop** [comment]
Field for GameInfo in [faf-java-commons](https://github.com/FAForever/faf-java-commons) is required.

**Comment by HermanSkop** [comment]
The field for GameInfo in [faf-java-commons](https://github.com/FAForever/faf-java-commons) is required.
