### ISSUE TITLE
Switch to constructor injection

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#306]
Originally I was using `@Resource` to autowire fields. As part of #307, this was changed to `@Inject`. Next step is to use constructor injection instead of field injection.

Since this is a lot of work and affects almost every file, this should be done gradually.

Example:

```
  private final PreferencesService preferencesService;

  @Inject
  public FaInitGenerator(PreferencesService preferencesService) {
    this.preferencesService = preferencesService;
  }
```

**Comment by Geosearchef** [comment]
circular reference between gameservice and replayservice:

https://github.com/FAForever/downlords-faf-client/blob/develop/src/main/java/com/faforever/client/game/GameServiceImpl.java#L116

https://github.com/FAForever/downlords-faf-client/blob/develop/src/main/java/com/faforever/client/replay/ReplayServiceImpl.java#L88

**Comment by Geosearchef** [comment]
Another circular reference in unused class ForgedAllianceServiceImpl. (see TODO)
