### ISSUE TITLE
Filters clear for "Live Replays" tab when switching

### ISSUE THREAD

**Issue by piisawheel** [FAForever/downlords-faf-client#3093]
**Describe the bug**
Filters in newest client (23.12.0) reset when tab changes in "Live Replays"

**To Reproduce**
Goto "Replays" tab.
Goto "Live Games"
Open Filters and check a box (I like to ignore games with 1 player, for example)
Click the "Play" tab (I'm usually on custom games, not sure if relevant)
When going back to "Replays" tab, the filters have reset, and I must recheck the "Ignore games with 1 player" option again.

**Log or error message**
None

**Expected behavior**
Previous version remembered that I checked the "Ignore games with 1 player" box and filtered accordingly when switching tabs.

**Screenshots**
None

**OS**
Windows 10 Home N using Faf Client 23.12.0

**Comment by sulikdan** [comment]
@Sheikah45 any idea for an approach? I've check a few commits related to the LiveReplayController, but couldn't find anythign that would be related to saving filter values. The whole LiveReplayController is created anew with no "memories". Could create singleton wrapper service, that would remember these filter values during runtime. Are you okay with that?

**Comment by Sheikah45** [comment]
The way to do it would be to create a new preferences object like is used for the online replay vault search and then you would just inject that prefs object and bind it to the relevant fields in a similar fashion.

That will also allow it to be stored in client.prefa as well.
