### ISSUE TITLE
Minimize when clicking on taskbar icon

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#31]

**Comment by axel1200** [comment]
http://stackoverflow.com/questions/26972683/javafx-minimizing-undecorated-stage

**Comment by micheljung** [comment]
I actually upvoted this post already and tested it locally - worked :) It's still lying around somewhere

**Comment by germanicianus** [comment]
Just stumbled upon that also. Luckily I searched before creating an own issue :smile: .

**Comment by 1-alex98** [comment]
Can you have a look so we can close it
