### ISSUE TITLE
Feature Suggestion - Auto-loading Last Chat Aeolus History in FAF Client

### ISSUE THREAD

**Issue by magge-faf** [FAForever/downlords-faf-client#3107]
Feature Suggestion:

By automatically loading the last chat history from Aeolus on startup, this will enhance the user experience by providing instant access to recent conversations.

The Message History Size is 500 by default; It would be a nice addition to use that value to autoload the last messages until the size is reached.

![image](https://github.com/FAForever/downlords-faf-client/assets/101107758/9d875394-7840-4c75-a72c-a5c038b812c7)

**Comment by Sheikah45** [comment]
This is already the case client side.The chat server just has to be configured to send the history on join. Which is planned soon.

**Comment by Sheikah45** [comment]
And now the server has been reconfigured. Although restarting it for now also wipes out all the history XD
