### ISSUE TITLE
Add hover highlight to chat messages

### ISSUE THREAD

**Issue by Garanas** [FAForever/downlords-faf-client#3114]
**Is your feature request related to a problem? Please describe.**

On a large monitor (2k+) it is difficult to find the reply button of the correct chat message.

![image](https://github.com/FAForever/downlords-faf-client/assets/15778155/cd2457e4-720d-4be2-b82e-25252a4526e6)

**Describe the solution you'd like**

Add a subtle hover highlight when your mouse is over a message to make it easier to see if you're replying to the correct message.

**Comment by RoraRaven** [comment]
Looks like this has already been implemented.

![image](https://github.com/FAForever/downlords-faf-client/assets/36416337/a09ca3f2-3b96-41ae-bb2e-51c54dae654c)

**Comment by Garanas** [comment]
I think so too 😃
