### ISSUE TITLE
Create MSI

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#316]
People are having a problem with Avast thinking the client installer is a virus.
MSIs are nicer anyway so let's try what we can do.

Hint: JavaFX comes with a packager, which is supported by IntelliJ (but I prefer having something that runs from Gradle)

**Comment by Sheikah45** [comment]
Do we still want this or will we just stick with install4j?

**Comment by micheljung** [comment]
We can drop this; IIRC MSI doesn't support several features that Install4J odes, some of which are vital to us.
