### ISSUE TITLE
Maps and Mods Location Field Issue: Causing Folder Structure Distortion When Typed

### ISSUE THREAD

**Issue by magge-faf** [FAForever/downlords-faf-client#3160]
**Describe the bug**

When typing characters, such as "test," into the `Maps and Mods location field`, the folder structure instantly distorts. Can be really getting out of hand when a player starts typing `C:\`

Reported via FAF forum thread

https://forum.faforever.com/post/56828

**Possible Solution:**

Do not allow a user to type anything in both fields (But allow copy via CTRL+C) - Manually choosing only.

**Screenshots**

![image](https://github.com/FAForever/downlords-faf-client/assets/101107758/410d2814-31a8-4b4e-96d0-3b319097d41f)

**Comment by Sheikah45** [comment]
Already handled in 60c84a7c96e827b7d96265a7f18e73a09edf2f6e
