### ISSUE TITLE
Question: Replay file includes victor info?

### ISSUE THREAD

**Issue by mrchris2000** [FAForever/downlords-faf-client#3161]
If I download a replay file. is there a way to determine the victorious team from the JSON header data?
If not, is there an API call I can make with a replay ID to get that info? Or some other way to get that specific piece of data?

Thanks

**Comment by Sheikah45** [comment]
This was recently added

**Comment by mrchris2000** [comment]
I don't see it in the JSON header, whats the field called?
I decompiled the zst to look at the inner file and I don't see anything obvious there either.

I see in the client it now decorates the Winner/Loser, I guess I could dig through the code to work out how its determining that, but I hoped it was a simple header field.

**Comment by Sheikah45** [comment]
There is no simple header field. The client puts it together from a few fields and some API data
