### ISSUE TITLE
Don't generate 4/5 player maps for 3 player matchmaking

### ISSUE THREAD

**Issue by mankinskin** [FAForever/downlords-faf-client#3169]
It doesn't really make sense to generate more player spots for a game of 3 players. It only results in an unbalanced number of mexes and in a point symmetric game it is basically impossible to hold against an opponent that simply has double your mexes. It makes much more sense to just increase the generated mex count instead. or at least generate 6 player maps so each player gets the same amount of mexes.

**Comment by Sheikah45** [comment]
This is not controlled by the client and is set by the matchmaker team directly. You should make a post on forum.faforever.com in the matchmaker pool feedback thread.

**Comment by mankinskin** [comment]
Oh, sorry, thanks for the apt response
