### ISSUE TITLE
Date language mixup

### ISSUE THREAD

**Issue by Backspace345** [FAForever/downlords-faf-client#3176]
**Describe the bug**
In leaderboards tab the current season period is shown in French, while client language is set to English. Changing client language doesn't change date language in leaderboards. Date format in settings is set to Day/Month/Year, if that's related.

**To Reproduce**
Go to settings > appearance, set date format to Day/Month/Year, go to Leaderboards tab.

**Expected behavior**
Dates changing according to client language. 

**Screenshots**
![1](https://github.com/FAForever/downlords-faf-client/assets/170477845/281779f5-42ca-4925-ad06-77c729ab9c86)

**OS**
Windows 10

**Comment by Sheikah45** [comment]
This is an artifact of the time locale being able to be set independently of the language in settings.

**Comment by magge-faf** [comment]
FYI: In the context of 'mai', 'juin' is most likely French.

**Comment by Backspace345** [comment]
> FYI: In the context of 'mai', 'juin' is most likely French.

Thanks! Post updated

**Comment by sulikdan** [comment]
@Sheikah45 Were you able to reproduce it by description? I tried to look into, but the date is following a user's setting of preferred language.  Tried multiple combination.

@Backspace345 If you change a language(to somethign different) and restart the client, is it still same? Do you still get french one? Even when you get back to origin language?

Tested on Win11.

**Comment by Backspace345** [comment]
@sulikdan yes, tried multiple times now, for some reason it just stays there. Complete reinstall removed the bug though. I wonder if it's because my windows install broke once. Due to that i had to reformat drive with it, which apparently contained some of the metadata client files, but the client itself was installed on a separate drive, and after reinstalling windows i just went to the client folder and created a shortcut manually. Surprisingly enough it worked just fine. So i guess there never was any issue?

**Comment by Sheikah45** [comment]
Yes it is because of this setting being not auto 
![image](https://github.com/FAForever/downlords-faf-client/assets/66929319/f5526208-4e02-4d4e-9ec3-66b6f4912f47)

**Comment by Backspace345** [comment]
> Yes it is because of this setting being not auto ![image](https://private-user-images.githubusercontent.com/66929319/333885442-f5526208-4e02-4d4e-9ec3-66b6f4912f47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzMxNDMsIm5iZiI6MTcxNjczMjg0MywicGF0aCI6Ii82NjkyOTMxOS8zMzM4ODU0NDItZjU1MjYyMDgtNGUwMi00ZDRlLTllYzMtNjZiNmY0OTEyZjQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE0MTQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyODJlNmRkZGMxNTk1NTBlNWQ4NGMwM2YzNjdmMWIxMzk0NzI0MzhhNmVjYzYyYTY4YTJlM2IzNDAzMjY0MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yvm86JwsCBMr9OBNVKUP_mxlr2Q1SNYZolY-7gc42Vs)

Can confirm, this is what causing it. Surprisingly setting date format to Month/Day/Year doesn't do it. Post updated

**Comment by sulikdan** [comment]
@Sheikah45 can I take it?

**Comment by Sheikah45** [comment]
In terms of fixing it sure.
