### ISSUE TITLE
Focus game when clicking on "Game is full" notification or when game starts

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#318]
Let the FAF icon go crazy and play a continuous alert sound when the game started but the user does not have the game focused.

(Make it configurable in the options)

**Comment by Cheyans** [comment]
Could we force the game to be the top window and focused?

**Comment by micheljung** [comment]
Yes we can, that would be even better I guess :)

**Comment by tatsujb** [comment]
OMG that'd be amazing!
