### ISSUE TITLE
Add map version to Manage installed maps dialog

### ISSUE THREAD

**Issue by RecklessCharger** [FAForever/downlords-faf-client#3197]
**Is your feature request related to a problem? Please describe.**
When managing installed maps via the Managed installed maps dialog the version of the map is not shown. Therefore its impossible to know which ones to delete if multiple versions of the same map are installed.

**Describe the solution you'd like**
Show the map version number so I can choose the correct version.

**Describe alternatives you've considered**
The maps can be deleted by showing the map folder (from the hamburger in the top left of the client) and manually deleting the relevant folder.

**Comment by Sheikah45** [comment]
The client is not setup to handle multiple installed versions of a map.

The client assumes only one version of a map is installed at a time and even will sometimes remove old versions and auto update them.

**Comment by RecklessCharger** [comment]
But it doesnt seem to be doing this for maps for me even though I have checkbox in settings enabled. Maybe something to do with versioning of maps?

**Comment by Sheikah45** [comment]
Did you manually download and add any maps?

**Comment by obydog002** [comment]
What do we want to do here exactly?

**Comment by RecklessCharger** [comment]
In answer to Sheikah45, no not that I am aware - I just used the client to download maps.
As an example here is a screenshot showing 2 versions of the The Crucible, which are indistinguishable. Would be good if the client could read the map version and put it in a column.
![FAF_issue_3197](https://github.com/user-attachments/assets/b24a3ee1-b5e1-4869-9429-3a0b40e25c4c)
