### ISSUE TITLE
Please update Traditional Chinese localizations.

### ISSUE THREAD

**Issue by Yuchenjimmy** [FAForever/downlords-faf-client#3207]
**Is your feature request related to a problem? Please describe.**
Some strings are missing/wrong/outdated in current localizations.

**Describe the solution you'd like**
I've updated translations in Poeditor.

**Comment by Sheikah45** [comment]
Unfortunately we have lost access to the POE translations due to some changes on their end. I have trying to get the original admin to transfer it but haven't been able to get it set yet.

**Comment by Sheikah45** [comment]
Duplicate of #3171
