### ISSUE TITLE
[Bug]: All variants of "Setons's Clutch" are set as "Unranked Map"

### ISSUE THREAD

**Issue by RoraRaven** [FAForever/downlords-faf-client#3219]
### Describe the Bug

All maps with the name "Seton's Clutch", including the original "scmp_009" and "Setons Clutch - FAF version" are set as unranked maps.

### Log file or Error Message

Game was not rated. Reason: Unranked Map

### Reproduce the bug

Play a complete match on a Seton's Clutch map.

### Expected Behavior

Expected Behaviour: Game should show result and affect rating.

![image](https://github.com/FAForever/downlords-faf-client/assets/36416337/dfa36649-980d-44aa-b19d-182097f535de)

Actual Behaviour: Game does not show result nor affect rating.

![image](https://github.com/FAForever/downlords-faf-client/assets/36416337/49831a60-9cd5-43a3-a6b3-d512286cf8e4)

### Screenshots

![image](https://github.com/FAForever/downlords-faf-client/assets/36416337/2fd2a1fa-91dd-4e37-b4b2-f960a34d7db2)

### Additional context

I believe devs are already aware of this bug, but thought it should be logged here.

### Which Operating System are you using?

Windows

**Comment by Sheikah45** [comment]
This has already been resolved and is waiting a server restart
