### ISSUE TITLE
Uploading new map revision wont work

### ISSUE THREAD

**Issue by seero11** [FAForever/downlords-faf-client#322]
If there is a map which has been uploaded to map vault earlier, it seems to be impossible to get new version of it to vault.

I tried with few of my maps, and if previous map version existed with same filename it just completed upload bar and returned to "upload now" window. I didnt get "upload completed" message and map didnt appear to vault.

If i completely renamed the map, upload was succesfull.

**Comment by micheljung** [comment]
In order to upload a map with the same name, the map_version needs to be changed.
Are you saying that this does not work? If so, can you provide logs plz?

**Comment by seero11** [comment]
Yea, i have raised that number but upload just wont work. Seems that none of my uploaded maps work. If you can give me the path where i can find logs, i can try again tomorrow and provide them.

**Comment by micheljung** [comment]
so uploading works but downloading doesn't? I'm currently looking at that

**Comment by seero11** [comment]
Downloading works fine right now, also map revisioning works as it is supposed to work! Did you already change something or what was that?

**Comment by seero11** [comment]
If you try to upload a map which has same version as current version in vault, it just returns to upload menu after uploading. You could add there some error message.

**Comment by micheljung** [comment]
yes i will
