### ISSUE TITLE
Integrate unit database

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#331]
> in general we are missing : the links/HELP (that are in the top right of usual client)
> --> especially the "unit database" and "show logs"

Maybe we could add a webview somewhere under "learn"

**Comment by Cheyans** [comment]
I think the current unit db is broken and out of date, maybe use spooky's, also it matches the theme better. http://spooky.github.io/unitdb/#/

**Comment by micheljung** [comment]
Yes! I liked this one better anyway, but didn't know how to find it. Thanks :-)
