### ISSUE TITLE
Automatic update doesn't work anymore

### ISSUE THREAD

**Issue by Justify87** [FAForever/downlords-faf-client#332]
I don't get any notifictions about new versions anymore. Have to install new releases manually.

**Comment by micheljung** [comment]
which version did you have? Because it was broken once, but that's a while ago

**Comment by Justify87** [comment]
v0.6.19.3

**Comment by micheljung** [comment]
I just checked, update notification for v0.6.20.alpha worked in v0.6.19.3-alpha as well as in v0.6.18-alpha.
I assume you had v0.6.15-alpha installed
