### ISSUE TITLE
Map Upload 401 error

### ISSUE THREAD

**Issue by PlaYsiA** [FAForever/downlords-faf-client#336]
All maps I try and upload give me a 401 error. (see attachment pic)
![capture](https://cloud.githubusercontent.com/assets/20159802/17614283/7a66e3c2-60a8-11e6-9795-e00e4e5d07b9.JPG)

Example of a map I am uploading:
https://dl.dropboxusercontent.com/u/49003257/TKP_SETON_LOWTIDE_TEAMPLAY_AI.v0001.7z

**Comment by micheljung** [comment]
Hi!

Please close the client, delte %APPDATA℅\Forged Alliance Forever\oauth and try again!

Cheers
