### ISSUE TITLE
Name history

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#35]
"[VoR]TA4Life: 
I want a lobby mod where I can rename everyone to what I want to call them, which would not change when people attempt to smurf. Then also there should be a place where you can see all the different names that people have given someone"

**Comment by Cheyans** [comment]
Maybe have a profile page for individual users which list name history with other things such as stats which can be seen now, join date, last long in, etc.

**Comment by micheljung** [comment]
For now, let's just add the "Aliases" page like the python client does

**Comment by axel1200** [comment]
Using the php Skripts is not the way to go anymore, there is an api call that can answer you the question
