### ISSUE TITLE
Integrate raven for automatic error reporting

### ISSUE THREAD

**Issue by Cheyans** [FAForever/downlords-faf-client#351]
https://getsentry.com

**Comment by axel1200** [comment]
ok but it is not free!!

**Comment by Cheyans** [comment]
Yes it is https://sentry.io/pricing/

**Comment by axel1200** [comment]
True must have overseen that...

**Comment by axel1200** [comment]
https://docs.sentry.io/clients/java/modules/spring/
een that...

**Comment by Cheyans** [comment]
Doing some work on this, since we use nocatch everywhere, we'll need to add some sort of adapter to the library to propagate the exception up.

**Comment by Cheyans** [comment]
Actually never mind, a `setDefaultWrapperException` method exists, we can report to sentry from there.

**Comment by 1-alex98** [comment]
Let's face it there is already too much to do. Automatically Exceptions that flood us is probably not gonna help

**Comment by Brutus5000** [comment]
I don't know how Raven works, but I know Sentry. And the point behind sentry is that it aggregates same exceptions. So you can just look at the ones with very high occurrence.

**Comment by Cheyans** [comment]
As @Brutus5000 mentioned it will provide you with aggregation and general insights along with user environment info. This video will give you a good overview https://player.vimeo.com/video/340759078
Raven was the old implementation of the sentry library, it's now just called sentry-sdk I believe.

I'm not really involved with this project anymore, but I did some early work with integration here https://github.com/FAForever/downlords-faf-client/pull/845
Feel free to pull it + change it as needed if you find it relevant.

Also to the point of pricing, you can use the free variant or alternatively you can spin up and host your own sentry stack: https://github.com/getsentry/onpremise. It's not too difficult to setup, I was able to do it at my previous employment

**Comment by Sheikah45** [comment]
Seems like this was not desired
