### ISSUE TITLE
Integrate Discord

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#353]

**Comment by axel1200** [comment]
https://discordapp.com/gamebridge

**Comment by axel1200** [comment]
Can not be wrong to fill out the form no?

**Comment by micheljung** [comment]
For integration into the game, yes, for integration into the client, probably not. For that I guess we're interested in signing it up as an application.
Still, I applied. Maybe we can build it into the game some day.

**Comment by axel1200** [comment]
So do we actually want to integrate Discord into the client?
That would mean we would need an App then:
https://discordapp.com/developers/docs/intro

**Comment by micheljung** [comment]
It's certainly not high priority, and the scope of the integration isn't clear either. Let's focus on the 0.8.0-beta features first.
