### ISSUE TITLE
uid.exe missing

### ISSUE THREAD

**Issue by heelix** [FAForever/downlords-faf-client#357]
Looks like this file is created by another FA Forever project. This might just be a documentation issue.  I do see a uid.dll in the python version, but no uid.exe.  The Java client needs the new new uid.exe built first, or is this binary something that should be bundled in this project?

09:53:39.381 [Thread-15] WARN  c.f.c.remote.AbstractServerAccessor - Error while handling server message: {"session": 2362109117, "command": "session"}
com.github.nocatch.NoCatchException: java.io.IOException: Cannot run program "lib/uid.exe": CreateProcess error=2, The system cannot find the file specified

**Comment by micheljung** [comment]
The `uid.dll` is old and being replaced by `uid.exe`. The uid.exe is installed properly, but I assume you have an anti-virus software that doesn't like that and therefore removed the file.

**Comment by heelix** [comment]
I'm running from IntelliJ.  Is there an extra install step?

**Comment by micheljung** [comment]
Oh well then make sure you use the "Prod" run configuration

**Comment by heelix** [comment]
Ah.  I get a different error with prod, but not the missing UID
executable.  I was running the Main, incorrectly.  Ty.

**Comment by micheljung** [comment]
Let me guess without any error message ;)

![image](https://cloud.githubusercontent.com/assets/1864183/18018194/db84c646-6bd5-11e6-9df9-d656ddc3cead.png)

**Comment by heelix** [comment]
Not quite, but I should be able to trace it down.  Fresh pull from Git,
setup as a new project.

"C:\Program Files\Java\jdk1.8.0_102\bin\java" -XX:+UseConcMarkSweepGC
-Djava.library.path=src/main/native -Xmx256m
-javaagent:build/libs/webview-patch-agent.jar -Duid.dir=src/main/native
-Didea.launcher.port=7534 "-Didea.launcher.bin.path=D:\IntelliJ IDEA
2016.1.2\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program
Files\Java\jdk1.8.0_102\jre\lib\charsets.jar;C:\Program
Files\Java\jdk1.8.0_102\jre\lib\deploy.jar;C:\Program
Files\Java\jdk1.8.0_102\jre\lib\ext\access-bridge-64.jar;C:\Program
Files\Java\jdk1.8.0_102\jre\lib\ext\cldrdata.jar;C:\Program
Files\Java\jdk1.8.0_102\jre\lib\ext\dnsns.jar;C:\Program
Files\Java\jdk1.8.0_102\jre\lib\ext\jaccess.jar;C:\Program
Files\Java\jdk1.8.0_102\jre\lib\ext\jfxrt.jar;C:\Program
Files\Java\jdk1.8.0_102\jre\lib\ext\localedata.jar;C:\Program
Files\Java\jdk1.8.0_102\jre\lib\ext\nashorn.jar;C:\Program
Files\Java\jdk1.8.0_102\jre\lib\ext\sunec.jar;C:\Program
Files\Java\jdk1.8.0_102\jre\lib\ext\sunjce_provider.jar;C:\Program
Files\Java\jdk1.8.0_102\jre\lib\ext\sunmscapi.jar;C:\Program
Files\Java\jdk1.8.0_102\jre\lib\ext\sunpkcs11.jar;C:\Program
Files\Java\jdk1.8.0_102\jre\lib\ext\zipfs.jar;C:\Program
Files\Java\jdk1.8.0_102\jre\lib\javaws.jar;C:\Program
Files\Java\jdk1.8.0_102\jre\lib\jce.jar;C:\Program
Files\Java\jdk1.8.0_102\jre\lib\jfr.jar;C:\Program
Files\Java\jdk1.8.0_102\jre\lib\jfxswt.jar;C:\Program
Files\Java\jdk1.8.0_102\jre\lib\jsse.jar;C:\Program
Files\Java\jdk1.8.0_102\jre\lib\management-agent.jar;C:\Program
Files\Java\jdk1.8.0_102\jre\lib\plugin.jar;C:\Program
Files\Java\jdk1.8.0_102\jre\lib\resources.jar;C:\Program
Files\Java\jdk1.8.0_102\jre\lib\rt.jar;D:\IntelliJ IDEA
2016.1.2\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain
com.faforever.client.Main
FATAL ERROR in native method: processing of -javaagent failed
java.lang.NoClassDefFoundError: javassist/ClassPool
at
com.faforever.client.fx.TransparentWebViewPatch.<clinit>(TransparentWebViewPatch.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at
sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
at
sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.ClassNotFoundException: javassist.ClassPool
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 7 more
Exception in thread "main"
Process finished with exit code 1

**Comment by micheljung** [comment]
That's exactly the problem I assumed and that will be fixed if you follow my screenshot

**Comment by heelix** [comment]
Perfect.  Looks like my version is slightly different. (2016.1.4) but that
screen shot was exactly the clue stick I was looking for.

**Comment by heelix** [comment]
Missed the image last time.  Thank you for the screenshot.   I noticed gradle was using an older version of the JDK, so fixed that too.  The rest of these setting look right?

![settings](https://cloud.githubusercontent.com/assets/2110284/18019001/9e88e8d4-6b9f-11e6-9838-f3c7de9b1895.png)

**Comment by micheljung** [comment]
Yes looks good - I guess it works now?
Idk yet why this setting is necessary, haven't had time to look into it :-) This is a fairly new option in Gradle.

**Comment by heelix** [comment]
Seeing the same error, I think.

"C:\Program Files\Java\jdk1.8.0_102\bin\java" -XX:+UseConcMarkSweepGC -Djava.library.path=src/main/native -Xmx256m -javaagent:build/libs/webview-patch-agent.jar -Duid.dir=src/main/native -Didea.launcher.port=7532 "-Didea.launcher.bin.path=D:\IntelliJ IDEA 2016.1.2\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_102\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_102\jre\lib\rt.jar;D:\IntelliJ IDEA 2016.1.2\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain com.faforever.client.Main
java.lang.NoClassDefFoundError: javassist/ClassPool
FATAL ERROR in native method: processing of -javaagent failed
	at com.faforever.client.fx.TransparentWebViewPatch.<clinit>(TransparentWebViewPatch.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.ClassNotFoundException: javassist.ClassPool
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more
Exception in thread "main" 
Process finished with exit code 1

It looks like I have a maven issue, but I don't think we are using the ej.technologies repository.  May or may not be related.  I've restarted since the change. 

3:49:50 PM Unindexed remote maven repositories found. Disable...
           The following repositories used in your gradle projects were not indexed yet: 
           http://maven.ej-technologies.com/repository
           If you want to use dependency completion for these repositories artifacts,
           Open Repositories List, select required repositories and press "Update" button (show balloon)
3:49:56 PM All files are up-to-date

**Comment by micheljung** [comment]
I'm busy right now but see https://www.youtube.com/watch?v=0s7YYjQEsfU&index=3&list=PLJw66dNaSqHVxo5tK45CqLbH1ePiDBKz5

**Comment by micheljung** [comment]
Oh and the maven repo thing is a non-issue, just ignore it as intellj suggests

**Comment by heelix** [comment]
Silly question, but 64-bit JVM is fair game now, right?

**Comment by micheljung** [comment]
Yes it is

**Comment by micheljung** [comment]
I'm closing this. Let me know if you need further assistance, and if you'd like to contribute, I'd love to see you on [slack](https://salty-fjord-26094.herokuapp.com/)!
