### ISSUE TITLE
No JVM found on machine

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/downlords-faf-client#375]
![error](https://cloud.githubusercontent.com/assets/5166284/18517166/56ff5eb4-7a93-11e6-9b3b-6826214d18ee.png)
I get this error when trying to run the client. I had it install everything required during installation. I already had a jdk and jre installed so perhaps that is the problem?

**Comment by micheljung** [comment]
As discussed in Chat. Please download the latest version (which doesn't allow you to mess things up with Java anymore ;-))
If you get the "Main class" error, please remove the directory `Downlord's FAF Client` manually.

Let me know if problems persist.

**Comment by JaggedAppliance** [comment]
Using the new version i first got an error saying the maximum heap size was too large or something, sorry i don't have a screenshot. Trying to start it subsequent times gave me the same error as above. I think I will just delete all java shit and try once more

**Comment by micheljung** [comment]
If you give me the error message I can help ;)

**Comment by JaggedAppliance** [comment]
It only appeared the first time, I will reinstall and see if it appears again.

**Comment by JaggedAppliance** [comment]
https://www.dropbox.com/s/bblduj4pmsjvyam/error2.png?dl=0

**Comment by micheljung** [comment]
Well... did you check your antivirus?

**Comment by JaggedAppliance** [comment]
Yes, it didn't do anything.

**Comment by Katharsas** [comment]
Did you try going to the installation folder and editing memory usage in the `downlords-faf-client.vmoptions` file behind -Xmx?

**Comment by JaggedAppliance** [comment]
Was this fixed? or should I make another issue for the second error?

**Comment by micheljung** [comment]
No, I'm not able to reproduce this. I assume it still happens? Yes please file a new one if so.
