### ISSUE TITLE
No JVM found on machine

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/downlords-faf-client#383]
![error](https://cloud.githubusercontent.com/assets/5166284/19169484/9f261b30-8c0c-11e6-84dd-c1ae28f89571.png)
I still get this error, no idea what to do. I tried installing a few times, deleted the jre and jdk on my computer and tried again, still got the same error.

**Comment by JaggedAppliance** [comment]
I found this page http://wincrunch.com/exe4j-java-home-no-jvm-could-be-found-on-your-system/
Followed the instructions and now it works.

**Comment by micheljung** [comment]
Glad you fixed it, this should not be necessary though since I tested the client on a virgin windows 10 installation recently.

Closing this for now.
