### ISSUE TITLE
Locals replays have incorrect metadata

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/downlords-faf-client#384]
![screenshot 2016-10-06 22 45 26](https://cloud.githubusercontent.com/assets/5166284/19171813/9c4b2c48-8c16-11e6-93cd-c836091e95d9.png)
Most of my local replays have this problem.

**Comment by micheljung** [comment]
Can you attach such a replay plz?

**Comment by JaggedAppliance** [comment]
[5240193-JaggedAppliance.zip](https://github.com/FAForever/downlords-faf-client/files/514977/5240193-JaggedAppliance.zip)
