### ISSUE TITLE
Add option to use 24-hour notation in chat timestamps

### ISSUE THREAD

**Issue by doodhout** [FAForever/downlords-faf-client#387]
Because, you know, some people are completely not familiar with 12-hour timestamps.

**Comment by micheljung** [comment]
Absolutely! Duplicate of #240

Thanks for reporting anyway, keep it up.

**Comment by doodhout** [comment]
I'm sorry, I tried looking for it by using the keywords 'timestamp' (nothing) and 'time' (too much clutter). Next time I'll try to search more thoroughly. ;-)

**Comment by micheljung** [comment]
Don't worry, I rather get duplicates than no reports :-)
