### ISSUE TITLE
Please deactivate unnecessary AI bot comments

### ISSUE THREAD

**Issue by irswat** [FAForever/downlords-faf-client#388]
I'm offended at the blasphemous shit ai bot has been coded to spew upon aeolus. I humbly request that the unnecessary and offensive commenting be omitted and/or deactivated. Why does FAF need a bot telling people they need to sell their soul? What is the necessity of alienating an entire population of people by blasphemous sentences like "the holy trinity of forged alliance." Such notions are not lore friendly.

**Comment by micheljung** [comment]
I feel you man, I already fought to ban such bots, no success. I forward your request, but since this has nothing to do with my client, I'll close this issue :-)
