### ISSUE TITLE
mod upload does not work

### ISSUE THREAD

**Issue by Bra1nwash3d** [FAForever/downlords-faf-client#391]
no error message, the mod does not show up in the vault

[downlords-faf-client.zip](https://github.com/FAForever/downlords-faf-client/files/519617/downlords-faf-client.zip)

**Comment by micheljung** [comment]
All known issues have been fixed, can you try again with the newest version? You should at least get an error message now.

Oh, and please delete `C:\Users\Downlord\AppData\Roaming\Forged Alliance Forever\oauth\StoredCredential`, haven't found (searched :P) a solution to this problem so far.

**Comment by Bra1nwash3d** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/13085405/19274206/af900c58-8fcf-11e6-82cb-b1d30cea0ab5.PNG)

**Comment by micheljung** [comment]
Replaced by FAForever/api#107
