### ISSUE TITLE
Working replays marked as corrupt

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/downlords-faf-client#394]
Every replay from the 14th October 2015 until 6th October this year has been put into a folder marked corrupt in my replay folder. The games I played after installing this client are not marked as corrupt. I didn't actually use this client to play those games however.

**Comment by micheljung** [comment]
Please attach one

**Comment by JaggedAppliance** [comment]
[5110133-JaggedAppliance.zip](https://github.com/FAForever/downlords-faf-client/files/520156/5110133-JaggedAppliance.zip)
Here's 3 to be sure ;)

**Comment by micheljung** [comment]
Have you tried the latest client version? It doesn't happen for me

**Comment by JaggedAppliance** [comment]
I can't reproduce it with the latest version, closing.

**Comment by micheljung** [comment]
*yay*
