### ISSUE TITLE
Some messages not showing in Chat

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/downlords-faf-client#396]
I wrote a couple messages, switched tabs and then returned to the pm and only one of the two messages i wrote would be there. I'm pretty sure the other person got both messages.
[downlords-faf-client.zip](https://github.com/FAForever/downlords-faf-client/files/520155/downlords-faf-client.zip)

**Comment by micheljung** [comment]
Related to #377 
Display bug in webview

**Comment by micheljung** [comment]
Fixed with ab5e2c9
