### ISSUE TITLE
Pagination in leaderboard

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/downlords-faf-client#414]
As of now the leaderboard loads the scores of all people that ever played ladder.
This takes quite a while and is slower than the classic client.

I propose we do it like in the classic client and show only 50 entries per page (or make the number configurable).

**Comment by micheljung** [comment]
I used pagination back in time, here's why I removed it:
* The leaderboard loads all *active* players, that's way less than *all* players.
* The 1v1 leaderboard data response from the API right now is 779KiB - basically nothing
* I'm in the school now, at my notebook (aka. slow notebook, slow internet). It takes me <2s to load the leaderboard.
* Pagination requires server-roundtrips
* Pagination doesn't allow instant-searches (w/o server roundtrips)
* Pagination is [bad UX design](https://blog.jooq.org/2016/08/10/why-most-programmers-get-pagination-wrong/)
* If the current implementation gets too slow, there are two steps to take first: Caching on API side, loading it in background in the client
