### ISSUE TITLE
Modify FAF account settings from client

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/downlords-faf-client#417]
Add a new tab in the settings. Add various features:
- [x] Change Password (merged with #419)
- [ ] Change username
- [ ] Link to steam
- [ ] Change Email

**Comment by axel1200** [comment]
What about Smurf protection? Currently if u log in and smurf protection stops you from logging in, the logging in wheel just pins forever!

**Comment by 1-alex98** [comment]
Do we still want this?

**Comment by Brutus5000** [comment]
Probably not, the website can do it by now.
