### ISSUE TITLE
Support emojis

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#436]

**Comment by axel1200** [comment]
Apprently there seems to be no emoji keyboard supporting libary for java fx, only plain emoji libaries. Seems to be difficult....

**Comment by micheljung** [comment]
I hoped that we somehow can "merge" two fonts; A standard font for text and a emoji font. This would give us super easy emoji support. But from my researches, it looks like it's not going to be so easy. Best solutions I found so far are JS libraries that replace things like `:smile:` with `<img>` tags.

Our current font does support emojis AFAIK, however they are colorless and ugly.

**Comment by Geosearchef** [comment]
Is the client currently using a default font from the system or loading a custom font from a file? If it's a custom font, maybe we could manipulate the font file.

**Comment by micheljung** [comment]
It's using a custom font, OpenSans. I think the problem is that the operating systems (or JavaFX, or both) doesn't support fonts with colors.
OSX and Android solved this problem by extending TTFs so that they allow PNGs. Then Microsoft came along and introduced a new way to add color to fonts. Have to do more research whether or not we could use that.

**Comment by micheljung** [comment]
http://stateofwebtype.com/#Color%20fonts

**Comment by axel1200** [comment]
What if we move the text input into the WebView, then u could use something like twitter emoji( https://github.com/twitter/twemoji ) libary(or whatever ) for Websites and so u needn't care about a solution for the client itself no?
