### ISSUE TITLE
Integrate Clan-Website

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#450]
![grafik](https://cloud.githubusercontent.com/assets/19996713/21294216/1e6fd840-c538-11e6-9e50-098e11f74af6.png)

with Auto-Login

**Comment by axel1200** [comment]
Is that a good idea? @micheljung

**Comment by micheljung** [comment]
Yeah I think that'd be nice

**Comment by axel1200** [comment]
But then we need to do it by passing on the oauth token right? How would we go about this?
