### ISSUE TITLE
Display clan information in clan tooltip

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#452]
(Requires API support)
- [x] Decide which information to show about clans
- [x] Implement the tooltip

**Comment by axel1200** [comment]
![grafik](https://cloud.githubusercontent.com/assets/19996713/21962191/1b5783da-db20-11e6-9266-9c36e2f516ab.png)
![grafik](https://cloud.githubusercontent.com/assets/19996713/21962198/253bc4f6-db20-11e6-9845-6cd5d2f7433e.png)

**Comment by micheljung** [comment]
How about we style the dropdown so that it doesn't look like a dropdown until the user hovers over it?
Otherwise it will look very ugly I assume :)

**Comment by axel1200** [comment]
Yeah i already thought about that... Not sure how to do that yet but ill find out ;)

**Comment by axel1200** [comment]
I managed to do so
