### ISSUE TITLE
Remove channel topic

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#453]
The channel topic is a very bad way to communicate with users; most just don't read it.
Which I find understandable, because aside from bad UI design, it barely ever changes. So after a user read it once or twice, he stops paying attention.

Therefore, it should be removed in order to push us towards a better solution.

**Comment by speed2CZ** [comment]
Maybe in aeolus it doesn't change that much, but it's not such a bad way of informing, especially in other channels.
In clan channels it has some info for the clans, we have out ts adress there and some other things.

Then in temporary channels like tourneey channels it's good for providing basic info, including link to the brackets.

**Comment by PhilipJFryFAF** [comment]
I'd prefer having channel topics since it's an easy way to provide some basic info/links etc
Very nice for tourney channels or clan channels but also aeolus

If we don't have a topic then we should have some other way of providing the info that is currently stored in it

**Comment by micheljung** [comment]
I'd be okay to display the channel topic when users join
