### ISSUE TITLE
Faf icon(for login) is not shown when the window is in full size mode

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#459]

**Comment by axel1200** [comment]
Same goes for resizing, but i did not find out how to reproduce it...

**Comment by Geosearchef** [comment]
For me, it works perfectly fine when resizing but disappears when in full size.

**Comment by axel1200** [comment]
We need to find outhow to reproduce it

**Comment by Geosearchef** [comment]
login.fxml:21 defines the component being displayed, in fullscreen the "text" property is displayed:

<Text strokeType="OUTSIDE" strokeWidth="0.0" text="">

**Comment by Geosearchef** [comment]
Also happens to the exclamation mark in front of the "Login not found ..." message

**Comment by Geosearchef** [comment]
The symbol displayed instead is the same unicode character in the default font (OpenSansRegular). instead of dfc-icons.ttf. Loading the font manually in LoginController fixes the problem, still trying to locate the bug itself.

**Comment by micheljung** [comment]
Ooooh I see now. The font is loaded in `TrayIconManager`:
```
 graphicsContext2D.setFont(javafx.scene.text.Font.loadFont(TrayIconManager.class.getResourceAsStream("/font/dfc-icons.ttf"), dimension));
```

So depending on whether this happens before or after the login logo is rendered, it fails.
See my review comments on how to fix it :)
