### ISSUE TITLE
Fix game paths on linux

### ISSUE THREAD

**Issue by W-M-D** [FAForever/downlords-faf-client#460]
I am getting this error after running gradle build on debian sid 

com.faforever.client.game.FaInitGeneratorTest > testGenerateIni FAILED
    java.lang.AssertionError at FaInitGeneratorTest.java:65 

is there a binary that i can use on linux instead of compiling ?

**Comment by micheljung** [comment]
Hi, linux is not yet supported (some FA paths need to be fixed) and the `develop` branch isn't compatible with the currently deployed server anymore. Meanwhile you can use the linux version of the original client, I was told there is one.

**Comment by Brutus5000** [comment]
Obsolete
