### ISSUE TITLE
Remove game from list if the game started

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#463]
Even if a game has started it is shown as a game that's available....

**Comment by axel1200** [comment]
It still shows the game that I did play 20 min ago in the  "Play" Tab and if I join it (what a surprise) it give me the mewssage host left game....

**Comment by Geosearchef** [comment]
As far as I have experienced from my testing with the game preview in private chat, the gameStatusProperty is set correctly, so I'd guess it's just a problem with the UI

**Comment by axel1200** [comment]
Yeah it might need to be refreshed

**Comment by axel1200** [comment]
Probably Server Issue

**Comment by micheljung** [comment]
Duplicate of #435
