### ISSUE TITLE
Display the users global rating and games played above the list of open lobbies

### ISSUE THREAD

**Issue by n3roxis** [FAForever/downlords-faf-client#465]
Many lobbies require you to have a specific rating or game count to join. To speed up the process of identifying which lobbies you can join, i'd suggest to write the users global rating and games played above the list of open lobbies.

**Comment by axel1200** [comment]
Or colour the games green/red (maybe other colours ) to provide visual support ....

**Comment by ThrashAbaddon** [comment]
If there is no way to enter that game then it's useless to the user. It shouldn't pollute his  viewing space. Coloring does seem like a good idea but gray is more of a indicator of uselessness/ that something is disabled. But what about the users that don't see colors?

**Comment by micheljung** [comment]
For now, nobody is prevented from joining a game even if his rating doesn't match. Once the server supports min/max ratings, we can add additional options. But right now we don't even know what the requirements are, because all we can do is parse the game title - not very reliable.

**Comment by Geosearchef** [comment]
Do will still want this? From the recent discussions about rating (and trying not to put that much emphasis on it), I'd say showing it in the profile information (2 more clicks) should be enough.

**Comment by 1-alex98** [comment]
no i think we dont want it
