### ISSUE TITLE
Notifications shown on wrong monitor

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/downlords-faf-client#468]
When using a multiple monitor setup, notifications are not always shown on the monitor, where the client is located. When the client is maximized on the primary monitor, all notifications show up in the bottom left of the second monitor (which is located right of the primary one in my case).

Maybe show them all on primary monitor/the monitor the client is located.

**Comment by micheljung** [comment]
This is configurable in the settings; a default screen is also calculated. Sounds like it's still a bit buggy though.

**Comment by Geosearchef** [comment]
Discovered the option right now, i could close this issue, but there is no default monitor selected, i guess this should be changed.

**Comment by Geosearchef** [comment]
It is buggy, when set to right bottom on screen 2, it is displayed on the secondary monitor in the right bottom, when set to right bottom on screen 1, it is display on the secondary monitor in the bottom left corner (which is, where the screen transitions to the next monitor.  
![capture](https://cloud.githubusercontent.com/assets/5748922/21908650/db003d34-d914-11e6-85db-8fbb0b2528af.PNG)

**Comment by micheljung** [comment]
Is still still case in the current development version? The screenshot shows the release version of the client.

**Comment by Geosearchef** [comment]
Yes, just confirmed it on branch develop, last commit: 3eb7d37

![capture](https://cloud.githubusercontent.com/assets/5748922/22038587/17c45332-dcfc-11e6-9774-65f7181aa2b5.PNG)
