### ISSUE TITLE
Wrapping Issue with LoginError 

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#469]
![grafik](https://cloud.githubusercontent.com/assets/19996713/21886502/4981240c-d8bc-11e6-930b-d172bae6dbf3.png)
wraptext property is turned on, but does not apply....
Text is set in com/faforever/client/login/LoginController.java : 111

**Comment by Geosearchef** [comment]
Try adding the minHeight="-Infinity" property. This should cause the LayoutManager to increase the size of the label to completely show the text at any circumstance. (Could also try with minWidth, to test, if it's only the line wrapping, that doesn't work)

**Comment by axel1200** [comment]
thanks worked
