### ISSUE TITLE
One should be able to set negative numbers for required rating

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#474]

**Comment by Geosearchef** [comment]
I'm actually against this enhancement. There's no consensual opinion if negative rating should even be displayed.

**Comment by axel1200** [comment]
But if they are then players with negative rating are theoretical unwanted
in any game... As it is always 0+

Am 17.01.2017 9:34 PM schrieb "Geosearchef" <notifications@github.com>:

I'm actually against this enhancement. There's no consensual opinion if
negative rating should even be displayed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/FAForever/downlords-faf-client/issues/474#issuecomment-273291334>,
or mute the thread

**Comment by Geosearchef** [comment]
That's true, so there is a solution needed, I would suggest not displaying ratings below 0 (showing and treating them like they are 0), so that those players who often have a very large deviation due to loosing their first games have a chance to increase the rating again.

**Comment by axel1200** [comment]
But that's probably a decision that goes beyond the client... One thing we
might also think about in this context is if payers with negative ranking
do also get a waring if the game is 0-(to) whatever.

Am 18.01.2017 10:50 PM schrieb "Geosearchef" <notifications@github.com>:

**Comment by germanicianus** [comment]
Just had the same problem/question. It's just confusing if a user has a negative rating but isn't able to create a game honoring that.

**Comment by micheljung** [comment]
I see no advantage in enforcing positive numbers

**Comment by 1-alex98** [comment]
well this needs server support
