### ISSUE TITLE
Zipper Mystic empty folder

### ISSUE THREAD

**Issue by IDragonfire** [FAForever/downlords-faf-client#484]
I used your [Zipper ](https://github.com/FAForever/downlords-faf-client/blob/develop/src/main/java/com/faforever/client/io/Zipper.java )in https://github.com/FAForever/faf-java-api

I have allways a magic empty folder in [7Zip](http://www.7-zip.de/):
![image](https://cloud.githubusercontent.com/assets/1217999/22315851/83f1bf0e-e369-11e6-919b-0cc81372b2ee.png)

In Window zip View I have **NOT** this empty folder:
![image](https://cloud.githubusercontent.com/assets/1217999/22315877/a6fe76a4-e369-11e6-9f6b-601b453fc725.png)

File:
[sludge_test.v0001.zip](https://github.com/FAForever/downlords-faf-client/files/731304/sludge_test.v0001.zip)

**Comment by micheljung** [comment]
May be related to #506

**Comment by micheljung** [comment]
Fixed with next version.
