### ISSUE TITLE
Notification Count is bugged

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#493]
![grafik](https://cloud.githubusercontent.com/assets/19996713/22507548/4e736658-e886-11e6-933a-b30969745e52.png)

**Comment by micheljung** [comment]
The notification count is for chatmessages only, at the moment. Should we mix this?
See also: #302

**Comment by axel1200** [comment]
Like for message you get in IRC chat? I supposed it was for all the warings, error and infos of persistent notifications?!

**Comment by micheljung** [comment]
Sorry I now get what you mean; There is a notification but the bell says 0. I thought you meant the badge in the taskbar icon :)

**Comment by PhilipJFryFAF** [comment]
![downlords-faf-client_2017-08-11_21-00-30](https://user-images.githubusercontent.com/24656673/29228771-74f62342-7edb-11e7-924d-fef80d08e221.png)
got this (i assume it's the same) issue in 0.7.1
