### ISSUE TITLE
Improve async image loading

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/downlords-faf-client#499]
AssetServiceImpl.java:43:

This is difficult to implement due to async loading and the default supplier that is used, when there is no image available at the URL specified.

This also causes some very weird code in GamesTableController.java:103.

**Comment by micheljung** [comment]
Not sure whether I solved this already in the fixes I'm working on. Let's check back once I merged them.

**Comment by micheljung** [comment]
Can you verify that this is no longer the case?

**Comment by micheljung** [comment]
I cleaned it all up
