### ISSUE TITLE
Chat with friends

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#505]
If a friend joins u get a toast to start a conversation and this works, but it should also open the chat tab otherwise this is useless.

**Comment by micheljung** [comment]
So you mean when the users clicks on the notification the private message tab doesn't open or the "Chat" tab doesn't open?
It should indeed do that

**Comment by axel1200** [comment]
Yeah thats what i mean. How ever I could also do that, won't be that hard ;)
