### ISSUE TITLE
Uploaded mods contain garbage directories

### ISSUE THREAD

**Issue by Wesmania** [FAForever/downlords-faf-client#506]
Some recently uploaded mod zips (e.g. [http://content.faforever.com/faf/vault/mods/tvg_working_v1_sera_fixed.v0001.zip](url)) have an empty directory corresponding to every subdirectory of the mod, and named like the path to the subdirectory. I was told that this client is the only way to upload mods right now, so it might be caused by some bug in the mod upload code.

**Comment by micheljung** [comment]
Are you sure you linked the right mod? I don't see such a directory:
![image](https://cloud.githubusercontent.com/assets/1864183/23758233/61c14282-04e9-11e7-923c-3126d95e49c5.png)
![image](https://cloud.githubusercontent.com/assets/1864183/23758254/77cad386-04e9-11e7-82e3-760bf46efc02.png)

**Comment by Wesmania** [comment]
In that case it must be a Linux-specific issue. This is what I get when treating this zip file with unzip on Linux:
![2017-03-09-205326_1920x1080_scrot](https://cloud.githubusercontent.com/assets/4634112/23768124/4151d7f6-050b-11e7-86ed-c8ecc40924d0.png)

**Comment by Wesmania** [comment]
To clarify - by Linux-specific I mean that Linux triggers the issue. These zips do (wrongly) contain these extra directories, it's just that apparently Windows does not display them, or unpack them.

**Comment by micheljung** [comment]
I've seen (and supposedly fixed) this before, it happens when the ZIP entries are created with backslashes as path separators instead of forward slashes. Works under windows, fails under linux.
I'll take a look (or anyone else?) and fix it, thanks for reporting!

**Comment by micheljung** [comment]
Fixed in next version
