### ISSUE TITLE
Implement new tutorials

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/downlords-faf-client#508]
Info: https://docs.google.com/document/d/1dZShYfOeiSvRSTmQZ6G3rHPZ0UdpsgG6GqvgYIDYGPY/edit#heading=h.xvlsnmn4fogn

**Comment by axel1200** [comment]
What about implementation on the Server? We cant start until that's done no?

**Comment by Brutus5000** [comment]
If I see this correctly, we do not require a server change, but we need to add the categories and maps in the database (together with an url where to download it). And then offer a way via Java API to query for this data. The client would then download it and run it locally.

While this can be done in a manageable amount of time we run into the same issue we have with coop and all other stuff: no gui to actually change and upload these replays. So in the end every change needs to be done by server admins.

**Comment by speed2CZ** [comment]
What replays? These are tutorials, they don't need to upload any replays. You just need to launch them.

**Comment by Brutus5000** [comment]
I meant files. In the end it's the same problem.

**Comment by 1-alex98** [comment]
Waiting for tutorials featured mod

**Comment by 1-alex98** [comment]
<a href="https://trello.com/c/vXHfwY0A/10-test-tutorial-changes-on-test">Test tutorial changes on test</a>
