### ISSUE TITLE
Game min and max rating parsing

### ISSUE THREAD

**Issue by JeroenDeDauw** [FAForever/downlords-faf-client#511]
For some time now I've been wanting to improve this code since I saw many instances of it providing the wrong result, and I figured this would be easy to change and test (string input, two integer output, no further dependencies). I finally got round to looking at this and found that the code (Game.java, line 114...) has a comment:

> // TODO this can be removed as soon as we get server side support. Until then, let's be hacky

What exactly does that mean? Will such parsing become obsolete? (Then where will you get the min and max rating from?)

**Comment by micheljung** [comment]
Yes, the current implementation that parses the game title is a hack because the server does not allow the host to specify min/max ratings. As soon as there is server support for it (and there will be, in the foreseeable future), this parsing will become obsolete. The information will then be provided by the server.

**Comment by JeroenDeDauw** [comment]
What will that look like? Users being able to input this in dedicated UI fields and the lobby enforcing the restriction on joining?

**Comment by JeroenDeDauw** [comment]
Anyway, no point putting effort into this then. Any suggestions for similar tasks that can be done without knowing the wider codebase much and can be tested easily?

**Comment by micheljung** [comment]
Yes, those fields already exist but they have no effect yet. The server won't enforce it but the player can be warned (I guess we could extend this the let the host choose whether it should be enforced or not)
