### ISSUE TITLE
Unable to move client window by clicking and dragging title menu when client is maximized.

### ISSUE THREAD

**Issue by ThrashAbaddon** [FAForever/downlords-faf-client#518]
I often use mouse to grab window by its title menu and move it to another screen, but it seems this client is unresponsive. Also `win + left_arrow_key` and `win + right_arrow_key` don't work but `up` and `down` do.

ps: You guys are doing a great job :)

**Comment by micheljung** [comment]
Related to #232

**Comment by micheljung** [comment]
Fixed in next release
