### ISSUE TITLE
Repeated installing/uninstalling of maps (mods?) causes errors

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#525]
As soon as a map has been installed or uninstalled, the client keeps a handle open on all map directories:
![image](https://cloud.githubusercontent.com/assets/1864183/26521506/1e89691a-42ea-11e7-88d7-e0d1fd345274.png)

This causes an access violation when trying to open or write the folder of a map that has been uninstalled, because `Files.delete` deleted the map folder but the client is still locking it (so the map folder only gets removed as soon as the client closes but is inaccessible until then).

**Comment by Sheikah45** [comment]
is this still an issue? I was not running into it.

**Comment by 1-alex98** [comment]
Well if you can not reproduce it let's close it.
