### ISSUE TITLE
Splash Screen Suggestion

### ISSUE THREAD

**Issue by jeg623** [FAForever/downlords-faf-client#526]
Why not just include the logo from the steam page? I mean, It'd probably be alright, as the company is defunct anyway. Here is the picture and the link:
![download](https://cloud.githubusercontent.com/assets/17114650/26525174/fdd19a48-4303-11e7-9dcd-641225598567.jpg)

http://store.steampowered.com/app/9350/Supreme_Commander/

**Comment by micheljung** [comment]
Thanks for the suggestion. However, not only is this using artwork without permission, but also it doesn't fit as a splash screen of the client itself which is a "Forged Alliance Forever" software and not a "Supreme Commander" software (and it doesn't look 2017 either ;)).

**Comment by jeg623** [comment]
As I did say, the company is defunct. Who would one have to ask anyway, out of curiosity?

**Comment by micheljung** [comment]
You'll find out the moment you receive as cease-and-desist ;) But yeah, other than that, my client is not "Supreme Commander" :)

**Comment by jeg623** [comment]
Ok
