### ISSUE TITLE
Admin panel

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#527]
Provide an admin panel for administrative actions

**Comment by axel1200** [comment]
Can we specify what the panel needs to be able to do?

**Comment by micheljung** [comment]
For now:
* Display a list of all online players
* Provide actions like Kick, Ban, Close Game per user
* Send a broadcast message to all players

More to come :)

**Comment by axel1200** [comment]
Waits for the Implantation of kicking banning on the Server

**Comment by micheljung** [comment]
This has already been implemented:
https://github.com/FAForever/server/blob/dc963f4e0568bc3703012b5c28ed78422170c34c/server/lobbyconnection.py#L339

**Comment by Geosearchef** [comment]
What is the current state? What is this issue waiting for?

**Comment by 1-alex98** [comment]
The thing is now we have the moderator client we probably dont want to have it any more no?

**Comment by Brutus5000** [comment]
The moderator client cannot perform actions of the server protocol. 
Kick from server, listing online users and broadcasting messages can only be done via server.

**Comment by 1-alex98** [comment]
Ok so we want this actions in the client?
