### ISSUE TITLE
Support all FAF languages 

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#535]
Client currently supports English and German.
A File for Russian was made, but is empty. The client however should support:
DE
ES
FR
IT
RU
TZM
UK/US
What you need to do:

- Make a new branch after project was cloned https://www.youtube.com/watch?v=utfdOCpNEkQ&list=PLJw66dNaSqHVxo5tK45CqLbH1ePiDBKz5
- Checkout
- A File for each language needs to be create res/i18n/messages.properties
- Go to the Resource Boundle Manager and add a name for each language
- Language needs to be added to the LanguageInfo enum with (LanguageCode, CountryCode, key of the name )
- In the Ressource Boundle Manager (its in the left bottom corner if u open a Resource Boundle) translation can be added
- Create a Pull Request

**Comment by themasch** [comment]
What do you think about using a tool like for example [jabylon ](http://jabylon.org/) for the translations? It would make the translation process feasible for non-devs. 
Maybe there should be some research first on which tool to use since jabylon is pretty archaic, its just the first one that came to my mind ;)

**Comment by germanicianus** [comment]
Language file handling will be enhanced in the future:
#798 "List found translation files (.properties) dynamically in language settings (currently hardcoded)"

Russian (RU) is ready to be merged:
#776 "Add Russian translation to Java Client"

French (FR) translation is also complete.

Chinese translation is in progress:
#805 "Provide Chinese as UI language (i18n/internationalization)"

**Comment by micheljung** [comment]
Also, we use https://poeditor.com to translate.

**Comment by jNullj** [comment]
Fully translated to hebrew using poeditor, is there anything else i need to do for the changes to take place?

**Comment by 1-alex98** [comment]
Yes I need to merge the changes in to develop

**Comment by 1-alex98** [comment]
And release the client....

**Comment by 1-alex98** [comment]
Probably gonna do so in version 1.0.1

**Comment by 1-alex98** [comment]
Because I already built version 1.0.0
