### ISSUE TITLE
Remember Sorting criteria

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#541]
I like to have my games sorted by player numbers as the one that are almost full are most interesting to me. Maybe we could remember the preference of sorting the games.

- make a new property in gamepreferences
- set this property if the gamesTable is sorted (don't forget preferenceService.storeInBackground())
- set sorting criteria in the initializeGameTable method of the GameTableController

**Comment by themasch** [comment]
I'll see if I'm able to implement this.
