### ISSUE TITLE
Hide win loss ration in leaderboard

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#543]
![image](https://user-images.githubusercontent.com/19996713/27256595-551d6ce8-53ba-11e7-95a4-457bac1a62a3.png)
win/lose ratio is always 0%

**Comment by micheljung** [comment]
While it's true that this is a bug, it's also not really worth fixing it since the win/loss value has not been updated anymore since the february 2016 server update or so. We should probably just hide the column, for now.
