### ISSUE TITLE
Mod search broken

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#544]
![image](https://user-images.githubusercontent.com/19996713/27256649-cd3dc6b2-53bc-11e7-8349-8520676988f9.png)
Does not load any mod for whatever search. Only loads start up page.

**Comment by axel1200** [comment]
works

**Comment by micheljung** [comment]
Not really, no. I have a branch open for this where I fix and improve the search, like in the map and replay vault.
![399507f1-3f57-4447-a2c9-0c74b769ee03](https://user-images.githubusercontent.com/1864183/31833247-47cdcf20-b5ca-11e7-865d-cb37a0f357d2.gif)
