### ISSUE TITLE
Most liked maps should be sorted for the most liked

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#547]
![image](https://user-images.githubusercontent.com/19996713/27256821-e2fad7a6-53c1-11e7-98df-842cd7272662.png)
Sort those with most stars to front

**Comment by Geosearchef** [comment]
related #568

**Comment by micheljung** [comment]
Thanks to the latest DB update, we now have the number of reviews and average review score available. I'll update the API to provide this information, so this can finally be implemented.

**Comment by axel1200** [comment]
Did you implemt it yet?

**Comment by Brutus5000** [comment]
Yes https://github.com/FAForever/faf-java-api/pull/189

**Comment by axel1200** [comment]
relates to #665

**Comment by micheljung** [comment]
Fixed by f82433f
