### ISSUE TITLE
Context menu visual bug after adding friend

### ISSUE THREAD

**Issue by Cheyans** [FAForever/downlords-faf-client#55]
After adding a user as a friend the context menu seems to have moved the remove friend button or the other one i can't tell over the top button

http://imgur.com/3JHZXsk
![image](https://cloud.githubusercontent.com/assets/8811789/8510190/c313a400-22a3-11e5-8f83-aaa9b9d3f204.png)

**Comment by micheljung** [comment]
Are you able to reproduce this? I observed it as well, but not by adding friends. I'm not sure, however this could've been the result of an error in the background that has already been solved.

**Comment by Cheyans** [comment]
Our test today:
Right clicked downloard
right click aulex
added aulex to friend
right clicked aulex
added aulex to foe
issue aulex produces issue
also aulex found in both general and foe
when aulex is added from general list to friend list (still being in the foe list from previous) duplicate is found in general

**Comment by micheljung** [comment]
Haven't been able to reproduce this anymore
