### ISSUE TITLE
Game Full Notification

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#556]
I am really sad 😢 I loved this notification but it is not showing lately, so I guess we broke it...

Its my favorite featrure... It was 😬

**Comment by axel1200** [comment]
It is also not flashing the icon

**Comment by axel1200** [comment]
It simply does nothing

**Comment by axel1200** [comment]
![image](https://user-images.githubusercontent.com/19996713/27455273-0d35be94-579d-11e7-8f23-3133147c433e.png)
I guess it got lost when @micheljung reimplemented the old connectivity code, as I only find posting the event in the IceAdapterImpl.class

**Comment by micheljung** [comment]
Reimplementing the old connectivity code was a rather desperate and a big time waster. I decided to keep the new connectivity code in place, but disable it. Hopefully we can kill the old code soon again, then we'll have the notification back :)

**Comment by axel1200** [comment]
Cool I love the notification ❤️
