### ISSUE TITLE
Broken preview in Tiles layout

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/downlords-faf-client#557]
When you move cursor from outside on the game hosted, it shows the players in the lobby correctly
![downlords-faf-client_2017-06-26_10-10-00](https://user-images.githubusercontent.com/10947024/27530176-d00776a8-5a57-11e7-8bb7-da3ca78b2473.png)
But moving the cursor from one game to another leads to this empty one
![downlords-faf-client_2017-06-26_10-10-07](https://user-images.githubusercontent.com/10947024/27530179-d2450b7e-5a57-11e7-8e34-48fda5d03776.png)

**Comment by micheljung** [comment]
@axel1200 this has something to do with when the popup is displayed vs. when the contents are created. For some reason, the popup's content doesn't update when you change the content.
You'll see in the code that I tried to fix it but I failed. Maybe the easiest solution is to not auto-update the popup while it's being displayed (IIRC that's what I was trying to achieve)
