### ISSUE TITLE
Log files aren't written properly anymore

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#561]
The client doesn't write log files anymore, or not to the correct location.

**Comment by jvaane** [comment]
Would you know where in the system log files are written. Repo is kinda big compared to what i'm used to :o

**Comment by micheljung** [comment]
@jvaane what do you mean by "where in the project", and what do log files have to do with the repository size?

**Comment by jvaane** [comment]
I am new to this project so I thought lets start with a beginner bug. So when I saw this issue I thought, to solve this problem I should probably look for a utility class or something that writes the client logs into files. Then I looked at the repository and there were so many folders and I tried a few of them but I couldn't find it. I usually work for smaller oieces od software /apps  so thats why i said i had some trouble searching to the repo and perhaps/ probably  you do know what a good starting point for this issue would be

**Comment by Brutus5000** [comment]
This application is using Spring Boot framework. It comes with prepared logging, there is no custom implementation of logging. For further documentation see https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html

Please note, that the dependency spring-boot-starter-logging is used. This may already set some configurations by default. I haven't looked into it in detail, but it's probably a configuration issue.

**Comment by micheljung** [comment]
@jvaane  aah :) I should indeed provide entry points whenever I label a task as "beginner". Guess I just didn't expect someone completely new :)

In the previous version, [the `Main` class called `PreferencesService.configureLogging()`](https://github.com/FAForever/downlords-faf-client/commit/6b8de78704862f4e5db5c506d4f72bc16e3a08ec#diff-71c047d17ec1c9cbcd774d5b151384adL32) which [was declared here](https://github.com/FAForever/downlords-faf-client/commit/6b8de78704862f4e5db5c506d4f72bc16e3a08ec#diff-fa4142c0d66c988c9ed0d0181c0d9b14L126). This caused `PreferencesService` to be initialized, which in turn caused [the log directory to be set](https://github.com/FAForever/downlords-faf-client/commit/6b8de78704862f4e5db5c506d4f72bc16e3a08ec#diff-fa4142c0d66c988c9ed0d0181c0d9b14L85). It's a bit hacky unfortunately, but I didn't see a cleaner solution.

Either we can do the same thing again, or since the logging is now initialized by `spring-boot-logging` as brutus mentioned, there might be a better or different way to do it.
