### ISSUE TITLE
Selection Tile is in a different Location

### ISSUE THREAD

**Issue by jeg623** [FAForever/downlords-faf-client#562]
When trying to download a mod from the Vault, the actual selection tile is in a different place from where the button it's supposed to look like is located. It is also very small, resulting in making sure my selection is pixel-perfect. The actual tile itself is located just above the selection button if that helps.

**Comment by micheljung** [comment]
Can you add a screenshot or [record a GIF](http://www.screentogif.com/)? I'm not sure what you describe and I have no client available right now.

**Comment by micheljung** [comment]
@axel1200 In the commit message you wrote "Prepares #562", but testing it I see no issue anymore. Is this fixed or not?

**Comment by axel1200** [comment]
ups missreferenced it

**Comment by axel1200** [comment]
It is fixed or I dont know what is meant by this Issue
