### ISSUE TITLE
Map upload gives HTTP 400

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#563]
Probably not a client issue, but that's where people see it.
Can someone figure out what happens? You probably need to test against a locally running API.

**Comment by micheljung** [comment]
Biass sent me an example map https://www.dropbox.com/sh/tjsberr0qzvdqsa/AACzP1a3bty_4R6S88h53CDSa?dl=0

**Comment by seero11** [comment]
[downlords-faf-client.zip](https://github.com/FAForever/downlords-faf-client/files/1132092/downlords-faf-client.zip)

**Comment by Geosearchef** [comment]
I'll take a look and see if I can do sth in the client. Talked to someone who couldn't uploud a map and he solved it by just installing an old version of the java client he had lying around somewhere.

**Comment by micheljung** [comment]
I guess we need to look at the API logs

**Comment by Geosearchef** [comment]
Concerning which API? Java or Python?

**Comment by Geosearchef** [comment]
Finally got database, server and api running locally (some flyaway scripts didn't do their job), am now investigation this.

**Comment by Geosearchef** [comment]
![capture](https://user-images.githubusercontent.com/5748922/28242132-2cec0efa-69a4-11e7-9cf7-be4e329630d5.PNG)
Gonna see if I can reconstruct the missing parameter.

**Comment by Geosearchef** [comment]
Ok, this problem is fixed, now I'm getting 500 server error on local due to missing table map_statistics in db. On production I get
`org.springframework.web.client.HttpClientErrorException: 422 Unprocessable Entity`

**Comment by Geosearchef** [comment]
resolved, next problem: https://github.com/FAForever/faf-java-api/issues/113

**Comment by micheljung** [comment]
We don't close issues before its PR (#570 in this case) has actually been merged into develop
