### ISSUE TITLE
Allow loading more than 100 replace search results

### ISSUE THREAD

**Issue by OCGDFS** [FAForever/downlords-faf-client#571]
currently u can find about the last 100 replays if search by username.
so u have no access to older replays unless u know the ID.

add options like "view 100", "view 500", "view all"

**Comment by axel1200** [comment]
OK there is a variable for this that defines the max number of results in the querry, we might let the user decide on the variable.

**Comment by micheljung** [comment]
For map search, I implemented a button at the bottom that allows the user to load more results:
![image](https://user-images.githubusercontent.com/1864183/30418582-c5a65f10-9933-11e7-86c1-d70665dc6d47.png)

I plan to implement the same for online replays. Meanwhile you can add a filter "End time is less than" to find older replays.

**Comment by axel1200** [comment]
Ok I can transfer is behaviour then I think

**Comment by axel1200** [comment]
Did refactored to do the same thing with online replays. Only misses Unit tests
