### ISSUE TITLE
Bitdefender false positive on uid.exe

### ISSUE THREAD

**Issue by jeg623** [FAForever/downlords-faf-client#580]
This may not be a priority, but I was wondering if you were planning to change installers. My antivirus sees it as a Trojan and disables the application because of it. I have it recover the files but it leaves the application itself in a broken state. For example, it can't initialize a game. And when I can it takes an unusually long time to connect to the lobby.  Because of this, I switched back to the regular client. My antivirus is Bitdefender.

**Comment by micheljung** [comment]
Submitted a sample of uid.exe to https://www.bitdefender.com/submit

**Comment by jeg623** [comment]
Thanks

**Comment by micheljung** [comment]
@axel1200 why did you close this? It's not yet solved.

**Comment by axel1200** [comment]
I though so 😬
