### ISSUE TITLE
With almost every online replay i try to watch it gives following error

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#584]
![image](https://user-images.githubusercontent.com/19996713/30424132-39741d90-9945-11e7-98f9-d23195235e40.png)

**Comment by micheljung** [comment]
What's the file's content?

**Comment by axel1200** [comment]
I'll check when I got time

**Comment by axel1200** [comment]
It's not there, so that's the reason it can not be loaded

**Comment by micheljung** [comment]
Any chance you are connected to the test server? Because I can watch any replay just fine.

**Comment by axel1200** [comment]
I'll try again
