### ISSUE TITLE
One should be able to see who won in a replay detail

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#597]

**Comment by axel1200** [comment]
Is there any way I can get the information which team won over the api?

**Comment by axel1200** [comment]
![image](https://user-images.githubusercontent.com/19996713/31729380-1fee29a6-b42f-11e7-8475-c4dd65ea4208.png)
Can I calculate if the Player won or lost be the score before and after and should I?

**Comment by micheljung** [comment]
Sounds like you're mixing things up here; mean/deviation shouldn't be used to calculate who won. Instead, `score` should be used (which doesn't have a "before" and "after"). AFAIK, the only way we have so far to detect the winning team (or player) is to look at who has a score of 10.
