### ISSUE TITLE
Game path not recognized

### ISSUE THREAD

**Issue by NiklasKopp** [FAForever/downlords-faf-client#599]
I first thought this was an issue with my development setup, but I could recently reproduce on an other machine using the alpha client exe (0.74) from faforever.com.

Both systems have the following in common: Windows 10, 64 bit and Forged Alliance installed under the Windows 10 default location: `C:\Program Files (x86)\THQ\Gas Powered Games\Supreme Commander - Forged Alliance`
The old python client works on both of these systems.

The Client starts just fine, no sign of anything going wrong, except for some log messages:

 `2017-10-07 11:05:30.223  INFO 2624 --- [JavaFX-Launcher] c.f.c.preferences.PreferencesService     : Game path is not specified or non-existent, trying to detect
2017-10-07 11:05:30.231  INFO 2624 --- [JavaFX-Launcher] c.f.c.preferences.PreferencesService     : Game path could not be detected`

Every click on a "play" button then just does nothing, which renders the client unusable. 

I think there should be at least a notification or a file chooser if the client isn't able to find the game on it's own. 

I could look into that myself since it's fairly easy to reproduce for me

EDIT: Found a possible source of this problem: The MissingGamePathNotifier is registered to the eventbus after the PreferenceService fires the MissingGamePathEvent, so it never gets the event.

EDIT2: You might actually be able to reproduce this by just deleting the client.prefs file and restarting the client.

**Comment by NiklasKopp** [comment]
The `isGamePathValid(Path binPath)` method apparently doesn't get the /bin Path but the path above. When doing `binPath = binPath.respolve("bin")` in there, the game is being detected correctly.

**Comment by micheljung** [comment]
Wow, I'm surprised this hasn't been reported for so long. I never had the game installed in a default location :D
