### ISSUE TITLE
Different Notification Sounds and Enable/Disable

### ISSUE THREAD

**Issue by ModcaFox** [FAForever/downlords-faf-client#60]
Have a different notification sound for when someone comes online or hosts a game and when i am pm'ed. So i don't have to tab out of something to check every time someone comes online. Also have the ability to disable the popup that comes with it so that FAF does not screw with some game that i am playing and get me killed.

**Comment by micheljung** [comment]
We currently have different sounds for "mention" and "private message" (I'm open to use the same sound however; if it was a PM you'd see it; if not you know you got mentioned)

Sound for "friend online" is planned but not yet found. Feel free to propose one.
The settings to enable/disable particular toasts are already there (the settings dialog is an ugly draft however)
The setting to "disable toasts when in-game" yet needs to be added.

![image](https://cloud.githubusercontent.com/assets/1864183/8511177/29b4d798-230c-11e5-89c4-ccd715a24e71.png)
