### ISSUE TITLE
Feature: Add custom groups in chat

### ISSUE THREAD

**Issue by OCGDFS** [FAForever/downlords-faf-client#609]
We have currently "Friends", "Foes", "Other" etc...
It would be nice to make custom groups of ppl.

**Comment by axel1200** [comment]
Thats also something that would need to be implemented in the server or api... so thats gonna be a whole lot of work I suppose

**Comment by axel1200** [comment]
You might color users acordingly

**Comment by Brutus5000** [comment]
Not necessarily. It could also be done client-side only.

**Comment by micheljung** [comment]
Yes, we could store custom groups and the users they contain in the settings file. The downside is, when the user loses his settings he has to reconfigure it.

**Comment by 1-alex98** [comment]
dupicate
