### ISSUE TITLE
Fix and remember selected mods

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#623]
In the "Create Game" dialog, there is a list of mods:
![image](https://user-images.githubusercontent.com/1864183/32278209-3e842c80-bf15-11e7-8a15-70b3c84d9efb.png)

However, selected mods are not yet activated in the game. Their UIDs needs to be written into the `game.prefs`. I thought I implemented this already but apparently, it's not/no longer there, or broken (but I can't even find `game.prefs` in the code).

After this has been implemented, the "Create Game" dialog needs to read the game.prefs in order to figure out which mods had been enabled in the last game and preselect them (mods can also be enabled within the game, and the client should be aware of that). Make sure that the client doesn't fail if no game.prefs yet exists.

**Comment by axel1200** [comment]
There is a com.faforever.client.game.KnownFeaturedMod that is saved in the Preferences

**Comment by axel1200** [comment]
I am sure I implemented that that it is scrolled down to the selected feature mod, so it must be broken or accidently removed

**Comment by micheljung** [comment]
> There is a com.faforever.client.game.KnownFeaturedMod that is saved in the Preferences as lastGameType
Yes, game type (aka "featured mod"), which is the first column. This is about the second, highlighted column.
>I am sure I implemented that that it is scrolled down to the selected feature mod, so it must be broken or accidently removed
This is not about featured mods, this is about mods users can enable/disable at will.

**Comment by axel1200** [comment]
There is the readModStates() in the ModeService that reads the game.prefs

**Comment by axel1200** [comment]
And the writeModStates()

**Comment by axel1200** [comment]
Maybe not, what about 1v1 games and co-op what is the procedure there? Disable all mods? And do those alter the game.prefs file?

**Comment by micheljung** [comment]
(for the protocol) as explained, they don't alter game.prefs.
