### ISSUE TITLE
Malformed tooltips of Game Tiles

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#625]
If there is only one team the tooltip is to big, that looks awful

**Comment by axel1200** [comment]
Thts the problem: 

> Setting the preferred number of columns and/or rows in the TilePane determines the calculation for the prefWidth and prefHeight values for that tile pane. 

For the tile pane of teams!
But I can not change anything about it....

**Comment by micheljung** [comment]
As we saw yesterday, it's not just this. The tooltip is twice as large than it needs to be. Cause unknown.

**Comment by Katharsas** [comment]
Closed duplicate of #804
