### ISSUE TITLE
Add "Support" button

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#632]
There are various ways to provide support. I'd like to integrate some sort of service where users can easily submit reports or even chat directly with us developers.

Let's see what floats around.

**Comment by KaukaHan** [comment]
woudnt it enought to add a developer channel to the client chat or a developer role to mark them in aeolus ? Despite that one can argue that most gamers have discord anyway, thus everyone has a easy way to contact a developer if he/she wants to.

**Comment by Brutus5000** [comment]
I think Discord #technical-help is as close as you can get.
