### ISSUE TITLE
Make sure Advanced Strategic Icon Pack is supported

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#633]
> I just tried the 0.7.6 client and noticed it doesn't seem to support the use of the Advanced Strategic Icons pack like the vanilla client. Is this possible to fix?

Maybe the init file needs some adjustment?

**Comment by 20seven** [comment]
Fixed by adding "advanced strategic icons.scd" in whitelist. There's a "advanced strategic icons.nxt", which I think is useless as game works fine when replaced with the ".scd" above.

**Comment by axel1200** [comment]
@micheljung I got no idea what the Advanced Strategic Icon Pack is :(

**Comment by micheljung** [comment]
@axel1200 https://forums.faforever.com/viewtopic.php?f=41&t=2740

**Comment by axel1200** [comment]
OK cool instaled it. But not clear to me what needs to be done.

**Comment by micheljung** [comment]
When the game starts, an "init" file is passed to it. This mounts various files into the game's virtual file system.

The init file is generated, based on `init_template.lua`, which contains a blacklist (files not to mount) and whitelist (files that are ok) - the whitelist already contains `advanced strategic icons.nxt`. I haven't looked into details but apparently, the file is called `advanced strategic icons.scd` instead. So all we need to do is to fix this entry.

Could've done it myself while I wrote this, but doesn't hurt if you get to know the mechanism :D
