### ISSUE TITLE
Co-op not working

### ISSUE THREAD

**Issue by RafaelSousa1** [FAForever/downlords-faf-client#634]
So, after watching Medicraze's videon on the client and hearing that the Co-op worked i tested it, and the client seems to be treating the game as a normal game, no cutscenes, no objectives and the maps starts fully expanded, also seems like it messes it the other client since i need to clean gamedata for it to work on the other client.
I have both clients installed.
I tested on both it no mods. 
Here are the log files, i hope the download i started on the original client didn't mess it them.
[downlords-faf-client.log](https://github.com/FAForever/downlords-faf-client/files/1463944/downlords-faf-client.log)
[forever.log](https://github.com/FAForever/downlords-faf-client/files/1463945/forever.log)
[game.log](https://github.com/FAForever/downlords-faf-client/files/1463946/game.log)

**Comment by axel1200** [comment]
@micheljung would if you could tell me something about co-op, no clue how it works, like non at all

**Comment by speed2CZ** [comment]
I would blame the generated init file since the game actually starts, just broken.

So it either doesn't load something needed for coop or it loads things in a wrong order.

**Comment by speed2CZ** [comment]
First thing I noticed from the game.log is that it loads all the maps twice. This is probably not causing this bug, but it's surely slowing down the game start a lot.

**Comment by speed2CZ** [comment]
Here's a game.log https://gist.github.com/speed2CZ/c82812f0bf98033a1382f19b0bbdb93f

It loads the game files at the beginning https://gist.github.com/speed2CZ/c82812f0bf98033a1382f19b0bbdb93f#file-coop_game-log-L21-L34

and then again?
https://gist.github.com/speed2CZ/c82812f0bf98033a1382f19b0bbdb93f#file-coop_game-log-L1124-L1137

Also all the maps are mouted twice? This is surely slowing the game down. Maps probably not breaking it but loading the other files twice might.

**Comment by axel1200** [comment]
@speed2CZ but it says mounting the first time and AddSearchPath the second time

**Comment by axel1200** [comment]
Not sure if it mounts it twice...
The first Time:
https://gist.github.com/speed2CZ/c82812f0bf98033a1382f19b0bbdb93f#file-coop_game-log-L21-L34
...it says mounting
The second time:
https://gist.github.com/speed2CZ/c82812f0bf98033a1382f19b0bbdb93f#file-coop_game-log-L1124-L1137
...it is AddSearchPath(what ever that means)!

What I think might be breaking it that the second time the:
https://gist.github.com/speed2CZ/c82812f0bf98033a1382f19b0bbdb93f#file-coop_game-log-L1124-L1137
... it can not find /modules, probably because C is uppercase.

**Comment by axel1200** [comment]
its definetly abou the init file
I started the game with the python client init file

**Comment by axel1200** [comment]
The Python client init file:
´´´
sc_path = ""
dofile(InitFileDir .. '\\..\\fa_path.lua')

path = {}

whitelist =
{
    "effects.nx2",
    "env.nx2",
    "etc.nx2",
    "loc.nx2",
    "lua.nx2",
    "meshes.nx2",
    "mods.nx2",
    "modules.nx2",
    "projectiles.nx2",
    "schook.nx2",
    "textures.nx2",
    "units.nx2",
    "murderparty.nxt",
    "labwars.nxt",
    "units.scd",
    "textures.scd",
    "skins.scd",
    "schook.scd",
    "props.scd",
    "projectiles.scd",
    "objects.scd",
    "moholua.scd",
    "mohodata.scd",
    "mods.scd",
    "meshes.scd",
    "lua.scd",
    "loc_us.scd",
    "loc_es.scd",
    "loc_fr.scd",
    "loc_it.scd",
    "loc_de.scd",
    "loc_ru.scd",
    "env.scd",
    "effects.scd",
    "editor.scd",
    "ambience.scd",
    "advanced strategic icons.nxt",
    "lobbymanager.scd",
    "texturepack.nxt",
    "sc_music.scd"
}

local function mount_dir(dir, mountpoint)
    table.insert(path, { dir = dir, mountpoint = mountpoint } )
end


local function mount_contents(dir, mountpoint)
    LOG('checking ' .. dir)
    for _,entry in io.dir(dir .. '\\*') do
        if entry != '.' and entry != '..' then
        local mp = string.lower(entry)
        local safe = true
        mp = string.gsub(mp, '[.]scd$', '')
        mp = string.gsub(mp, '[.]zip$', '')
        mount_dir(dir .. '\\' .. entry, mountpoint .. '/' .. mp)
        end
    end
end

local function mount_dir_with_glob(dir, glob, mountpoint)
    sorted = {}
    LOG('checking ' .. dir .. glob)
    for _,entry in io.dir(dir .. glob) do
        if entry != '.' and entry != '..' then
            table.insert(sorted, dir .. entry)
        end
    end
    table.sort(sorted)
    table.foreach(sorted, function(k,v) mount_dir(v, mountpoint) end)
end

local function mount_dir_with_whitelist(dir, glob, mountpoint)
    sorted = {}
    LOG('checking ' .. dir .. glob)
    for _,entry in io.dir(dir .. glob) do
        if entry != '.' and entry != '..' then
            local mp = string.lower(entry)
            local notsafe = true
            for i, white in whitelist do
                notsafe = notsafe and (string.find(mp, white, 1) == nil)
            end
            if notsafe then
                LOG('not safe ' .. dir .. entry)
            else
                table.insert(sorted, dir .. entry)
            end
        end
    end
    table.sort(sorted)
    table.foreach(sorted, function(k,v) mount_dir(v, mountpoint) end)
end

local function mount_dir_with_blacklist(dir, glob, mountpoint)
    sorted = {}
    LOG('checking ' .. dir .. glob)
    for _,entry in io.dir(dir .. glob) do
        if entry != '.' and entry != '..' then
            local mp = string.lower(entry)
            local safe = true
            for i, black in blacklist do
                safe = safe and (string.find(mp, black, 1) == nil)
            end
            if safe then
                table.insert(sorted, dir .. entry)
            else
                LOG('not safe ' .. dir .. entry)
            end
        end
    end
    table.sort(sorted)
    table.foreach(sorted, function(k,v) mount_dir(v, mountpoint) end)
end

local function mount_map_dir(dir, glob, mountpoint)
    LOG('mounting maps from: '..dir)
    mount_contents(dir, mountpoint)

    for _, map in io.dir(dir..glob) do
        for _, folder in io.dir(dir..'\\'..map..'\\**') do
            if folder == 'movies' then
                LOG('Found map movies in: '..map)
                mount_dir(dir..map..'\\movies', '/movies')
            elseif folder == 'sounds' then
                LOG('Found map sounds in: '..map)
                mount_dir(dir..map..'\\sounds', '/sounds')
            end
        end
    end
end

-- mount maps
mount_map_dir(SHGetFolderPath('PERSONAL') .. 'My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\maps\\', '**', '/maps')
mount_map_dir(InitFileDir .. '\\..\\user\\My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\maps\\', '**', '/maps')

-- mount mods
mount_contents(SHGetFolderPath('PERSONAL') .. 'My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\mods', '/mods')
mount_contents(InitFileDir .. '\\..\\user\\My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\mods', '/mods')

mount_dir(InitFileDir .. '\\..\\gamedata\\*.cop', '/')
mount_dir_with_whitelist(InitFileDir .. '\\..\\gamedata\\', '*.nxt', '/')
mount_dir_with_whitelist(InitFileDir .. '\\..\\gamedata\\', '*.nx2', '/')

mount_dir_with_whitelist(fa_path .. '\\gamedata\\', '*.scd', '/')
mount_dir(fa_path, '/')
mount_dir(InitFileDir .. '\\..\\movies', '/movies')

mount_dir_with_glob(InitFileDir .. '\\..\\gamedata\\', '*_VO.nx2', '/')



hook = {
    '/schook',
    '/mods/coop/hook'
}



protocols = {
    'http',
    'https',
    'mailto',
    'ventrilo',
    'teamspeak',
    'daap',
    'im',
}




´´´
 And the java one:
´´´ 
-- TODO this file can surely be reduced, but for now I don't want to risk breaking anything so I keep it as-is.
fa_path = 'C:\\Users\\trostorff\\Documents\\delete'

path = {}
blacklist = {
    "00_BigMap.scd",
    "00_BigMapLEM.scd",
    "fa-ladder.scd",
    "fa_ladder.scd",
    "faladder.scd",
    "powerlobby.scd",
    "02_sorian_ai_pack.scd",
    "03_lobbyenhancement.scd",
    "randmap.scd",
    "_Eject.scd",
    "Eject.scd",
    "gaz_ui",
    "lobby.nxt",
    "faforever.nxt"
}
whitelist =
{
    "effects.nx2",
    "env.nx2",
    "etc.nx2",
    "loc.nx2",
    "lua.nx2",
    "meshes.nx2",
    "mods.nx2",
    "modules.nx2",
    "projectiles.nx2",
    "schook.nx2",
    "textures.nx2",
    "units.nx2",
    "murderparty.nxt",
    "labwars.nxt",
    "units.scd",
    "textures.scd",
    "skins.scd",
    "schook.scd",
    "props.scd",
    "projectiles.scd",
    "objects.scd",
    "moholua.scd",
    "mohodata.scd",
    "mods.scd",
    "meshes.scd",
    "lua.scd",
    "loc_us.scd",
    "loc_es.scd",
    "loc_fr.scd",
    "loc_it.scd",
    "loc_de.scd",
    "loc_ru.scd",
    "env.scd",
    "effects.scd",
    "editor.scd",
    "ambience.scd",
    "advanced strategic icons.nxt",
    "lobbymanager_v105.scd",
    "texturepack.nxt",
    "sc_music.scd"
}

local function mount_dir(dir, mountpoint)
    table.insert(path, { dir = dir, mountpoint = mountpoint })
end

local function mount_contents(dir, mountpoint)
    LOG('Checking ' .. dir)
    for _, entry in io.dir(dir .. '\\*') do
        if entry ~= '.' and entry ~= '..' then
            local mp = string.lower(entry)
            local safe = true
            for i, black in blacklist do
                safe = safe and (string.find(mp, black, 1) == nil)
            end
            if safe then
                mp = string.gsub(mp, '[.]scd$', '')
                mp = string.gsub(mp, '[.]zip$', '')
                mount_dir(dir .. '\\' .. entry, mountpoint .. '/' .. mp)
            else
                LOG('Blacklisted: ' .. entry)
            end
        end
    end
end

local function mount_dir_with_whitelist(dir, glob)
    local sorted = {}
    LOG('Checking ' .. dir .. glob)
    for _, entry in io.dir(dir .. glob) do
        if entry ~= '.' and entry ~= '..' then
            local mp = string.lower(entry)
            local notsafe = true
            for i, white in whitelist do
                notsafe = notsafe and (string.find(mp, white, 1) == nil)
            end
            if notsafe then
                LOG('Not in whitelist: ' .. dir .. entry)
            else
                table.insert(sorted, dir .. entry)
            end
        end
    end
    table.sort(sorted)
    table.foreach(sorted, function(k, v) mount_dir(v, '/') end)
end

local function mount_dir_with_blacklist(dir, glob)
    local sorted = {}
    LOG('Checking ' .. dir .. glob)
    for _, entry in io.dir(dir .. glob) do
        if entry ~= '.' and entry ~= '..' then
            local mp = string.lower(entry)
            local safe = true
            for i, black in blacklist do
                safe = safe and (string.find(mp, black, 1) == nil)
            end
            if safe then
                table.insert(sorted, dir .. entry)
            else
                LOG('Blacklisted: ' .. dir .. entry)
            end
        end
    end
    table.sort(sorted)
    table.foreach(sorted, function(k, v) mount_dir(v, '/') end)
end

local function mount_map_dir(dir, glob, mountpoint)
    LOG('mounting maps from: ' .. dir)
    mount_contents(dir, mountpoint)
    for _, map in io.dir(dir .. glob) do
        for _, folder in io.dir(dir .. '\\' .. map .. '\\**') do
            if folder == 'movies' then
                LOG('Found map movies in: ' .. map)
                mount_dir(dir .. map .. '\\movies', '/movies')
            elseif folder == 'sounds' then
                LOG('Found map sounds in: ' .. map)
                mount_dir(dir .. map .. '\\sounds', '/sounds')
            end
        end
    end
end

local function mount_mod_sounds(modFolder)
    -- searching for mods inside the modfolder
    for _, mod in io.dir(modFolder .. '\\*.*') do
        -- do we have a true directory ?
        if mod ~= '.' and mod ~= '..' then
            -- searching for sounds inside mod folder
            for _, folder in io.dir(modFolder .. '\\' .. mod .. '\\*.*') do
                -- if we found a folder named sounds then mount it
                if folder == 'sounds' then
                    LOG('Found mod sounds in: ' .. mod)
                    mount_dir(modFolder .. '\\' .. mod .. '\\sounds', '/sounds')
                    break
                end
            end
        end
    end
end

-- Begin mod mounting section
-- This section mounts sounds from the mods directory to allow mods to add custom sounds to the game

mount_map_dir(SHGetFolderPath('PERSONAL') .. 'My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\Maps\\', '**', '/maps')
mount_map_dir(InitFileDir .. '\\..\\user\\My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\Maps\\', '**', '/maps')

mount_mod_sounds(SHGetFolderPath('PERSONAL') .. 'My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\Mods')
mount_mod_sounds(InitFileDir .. '\\..\\user\\My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\Mods')
-- End mod mounting section

-- these are the classic supcom directories. They don't work with accents or other foreign characters in usernames
mount_contents(SHGetFolderPath('PERSONAL') .. 'My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\Mods', '/Mods')
mount_contents(SHGetFolderPath('PERSONAL') .. 'My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\Maps', '/Maps')

-- these are the local FAF directories. The My Games ones are only there for people with usernames that don't work in the uppder ones.
mount_contents(InitFileDir .. '\\..\\user\\My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\Mods', '/Mods')
mount_contents(InitFileDir .. '\\..\\user\\My Games\\Gas Powered Games\\Supreme Commander Forged Alliance\\Maps', '/Maps')

-- Generated
-- @formatter:off
mountSpecs = {
    {'C:\\ProgramData\\FAForever\\repos\\httpsgithubcomFAForeverfacoopgit\\lua', '/lua'},
    {'C:\\ProgramData\\FAForever\\repos\\httpsgithubcomFAForeverfacoopgit\\mods\\coop\\hook', '/schook'},
    {'C:\\ProgramData\\FAForever\\repos\\httpsgithubcomFAForeverfacoopgit\\units', '/units'},
    {'C:\\ProgramData\\FAForever\\repos\\httpsgithubcomFAForeverfagit\\textures', '/textures'},
    {'C:\\ProgramData\\FAForever\\repos\\httpsgithubcomFAForeverfagit\\meshes', '/meshes'},
    {'C:\\ProgramData\\FAForever\\repos\\httpsgithubcomFAForeverfagit\\lua', '/lua'},
    {'C:\\ProgramData\\FAForever\\repos\\httpsgithubcomFAForeverfagit\\effects', '/effects'},
    {'C:\\ProgramData\\FAForever\\repos\\httpsgithubcomFAForeverfagit\\units', '/units'},
    {'C:\\ProgramData\\FAForever\\repos\\httpsgithubcomFAForeverfagit\\modules', '/modules'},
    {'C:\\ProgramData\\FAForever\\repos\\httpsgithubcomFAForeverfagit\\etc', '/etc'},
    {'C:\\ProgramData\\FAForever\\repos\\httpsgithubcomFAForeverfagit\\schook', '/schook'},
    {'C:\\ProgramData\\FAForever\\repos\\httpsgithubcomFAForeverfagit\\env', '/env'},
    {'C:\\ProgramData\\FAForever\\repos\\httpsgithubcomFAForeverfagit\\loc', '/loc'},
    {'C:\\ProgramData\\FAForever\\repos\\httpsgithubcomFAForeverfagit\\projectiles', '/projectiles'}
}
-- @formatter:on

for _, mountSpec in mountSpecs do
    LOG('Mounting ' .. mountSpec[1] .. ' to ' .. mountSpec[2])
    mount_dir(mountSpec[1], mountSpec[2])
end


-- these are using the newly generated path from the dofile() statement at the beginning of this script
mount_dir_with_whitelist(fa_path .. '\\gamedata\\', '*.scd', '/')
mount_dir(fa_path, '/')

-- Generated
-- @formatter:off
hook = {
    '/schook'
}
-- @formatter:on

protocols = {
    'http',
    'https',
    'mailto',
    'ventrilo',
    'teamspeak',
    'daap',
    'im',
}

´´´

**Comment by axel1200** [comment]
Notice how it misses
 hook = {
    '/schook',
    **'/mods/coop/hook'**
}

**Comment by axel1200** [comment]
So I copied the python init file and added the parameters that are filed by the client. And this works fine, however :
hook = {
'/schook',
**'/mods/coop/hook'**
}
...Is missing
 '/schook' is registered under hooks in the fa repo(mod_info.lua), but '/mods/coop/hook' is registered in the coop repo but under mountpoints(mod_info.lua), with ['/mods/coop/hook']='/schook'

**Comment by axel1200** [comment]
It was a problem of the metadata provided by the mod coop

**Comment by speed2CZ** [comment]
Fixed by https://github.com/FAForever/fa-coop/commit/fa12f850177ecd4e36949ac46843c8b7cfaad77b
