### ISSUE TITLE
option to hide modded games

### ISSUE THREAD

**Issue by OCGDFS** [FAForever/downlords-faf-client#641]
in addition to the option to hide private games

**Comment by axel1200** [comment]
Changes need to be done in src\main\resources\theme\play\custom_games.fxml and src\main\java\com\faforever\client\game\CustomGamesController.java... have a look at how hide password protected games works(it filters the list of games) another ChoiceBox would probably be fine

**Comment by axel1200** [comment]
Relates to #537
