### ISSUE TITLE
Show ladder map pool

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#650]
You can't see when you want to play a ladder game the different maps available for it (unless you do some dirty solution for example search on vault 1v1 ladder replays and find the maps...)

It would be nice to have a preview of all the maps somewhere near the start ladder button (could be a button show map or something). I heard it was possible before but not anymore.
Copy of https://github.com/FAForever/client/issues/889

**Comment by Brutus5000** [comment]
The elide route you are looking for is https://api.faforever.com/data/ladder1v1Map
