### ISSUE TITLE
map upload too unrestricted 

### ISSUE THREAD

**Issue by CookieNoob** [FAForever/downlords-faf-client#659]
it is possible to upload a map that has
- map files that start with a number
- characters in the name that are not letters (i.e. brackets and so on)

Farmsletje uploaded a map where all files were called "1v1shit.scmp", "1v1shit_script.lua"... this caused the game to swich the map to the default fallback when it was hosted with the map. However, swiching in the lobby to the map was possible.

He also made a map and uploaded it (as a second version) where he added "(fixed)" to the map name. This had the same effect as described above.

The map upload should check for these cases and prevent the map from uploading (maybe this issue should be in the api?). It would also be nice to prevent numbers at the start of the map name (i.e. "8 - mynewmap" or "7test" as this screws with the alphabetic ordering in the map selection window.

**Comment by axel1200** [comment]
I think the api should prevent this instead of the client no?

**Comment by Brutus5000** [comment]
Yes this needs to be done in API, but in cases like this I would ask for moderator action instead.
