### ISSUE TITLE
Unknown game state PLAYING

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#662]
The following does not look healthy:
![image](https://user-images.githubusercontent.com/19996713/33809857-a9c50828-ddfd-11e7-980a-99d8435ec8df.png)
My log when running develop

**Comment by axel1200** [comment]
Its because it is upper case(PLAYING), we might just convert everything to lowwercase

**Comment by micheljung** [comment]
This has been fixed in df58448 but issue #622 has been referenced.
