### ISSUE TITLE
Wrong map size when uploading map

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/downlords-faf-client#666]
![2017-12-17_13-13-28](https://user-images.githubusercontent.com/10947024/34173704-a5d491e8-e4f6-11e7-9d44-d8b6c9edb789.png)
when uploading a map the client is showing the map size, but the size is game units, not km
This above is an example of 5x5km map.

The size needs to be translated into km

km | game units
5x5 | 256x256
10x10 | 512x512
20x20 | 1024x1024
40x40 | 2048x2048
80x80 | 4096x4096

**Comment by micheljung** [comment]
https://github.com/FAForever/downlords-faf-client/blob/cf88622ae374b53690d8da799e45d7f401dba603/src/main/java/com/faforever/client/map/MapUploadController.java#L131

use `getWidthInKm()` and `getHeightInKm()` instead.

**Comment by axel1200** [comment]
Shell I fix it or leave it for potential beginners?

**Comment by micheljung** [comment]
No beginners around, go ahdea.

**Comment by axel1200** [comment]
@20seven wanna do this?
