### ISSUE TITLE
Client window out of screen bound

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#667]
When minimizing the client window the window is gone it seems to be out of the screen. See the stored location of the minimized window is x>1700 but screen is only abut 1300 pixel in width!

[client.txt](https://github.com/FAForever/downlords-faf-client/files/1584399/client.txt)

**Comment by axel1200** [comment]
What do we wanna do about it? Search for the reason the value got in there or simply correct values that are out of screen?

**Comment by micheljung** [comment]
I would log such cases as `warn` and with stacktrace and then fix it to be within the bounds.
I thought I already did something somewhere.. window positions sometimes stored as negative coordinates.

**Comment by axel1200** [comment]
Yeah you did but it was negative now it is positive but out of the screen

**Comment by axel1200** [comment]
You are right you fixed that case, but only on display and not on restore...
