### ISSUE TITLE
Game list fails to update if user has older JRE installed

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#668]
The game list does show outdated games. We thought we had fixed the issue but I just saw it happen(with my brother) again the the current release...

**Comment by axel1200** [comment]
The log was spammed with the following warning:
`2017-12-29 17:23:18.379  WARN 6348 --- [JavaFX Application Thread] javafx                                   : Loading FXML document with JavaFX API of version 8.0.111 by JavaFX runtime of version 8.0.102`

**Comment by axel1200** [comment]
I told him to update the java version

**Comment by axel1200** [comment]
Can we detect such things and notify the user?

**Comment by micheljung** [comment]
We need to make sure that the client never uses the system's JRE

**Comment by micheljung** [comment]
Turns out it's ok to use the system's JRE, however, the required minimum version wasn't set to 1.8.111+
