### ISSUE TITLE
Update feature comparison

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#670]
In wiki and project page. Are out of date...

**Comment by axel1200** [comment]
I updated wiki

**Comment by micheljung** [comment]
There's a wiki entry?

**Comment by axel1200** [comment]
Yeah and it is linked in there.... https://faforever.com/client

**Comment by micheljung** [comment]
Ah you mean GitHub wiki, not FAF wiki :)

**Comment by 1-alex98** [comment]
yeah I do

**Comment by 1-alex98** [comment]
And the one on the website

**Comment by Brutus5000** [comment]
https://github.com/FAForever/website/issues/133
https://github.com/FAForever/website/pull/124
