### ISSUE TITLE
Catch access denied

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#684]
If the user starts the client as admin and later on starts it as normal user he might get access denied exceptions because he has not all permissions for the game files....

**Comment by axel1200** [comment]
Thats not what we should do...
There is a better solution:
The error is caused by the client being unable to delete the stylesheet cache, if we delted that files on close up, no problems will occur. As on close up we have the same permission as on creation.

**Comment by axel1200** [comment]
Thats not what we should do...
There is a better solution:
The error is caused by the client being unable to delete the stylesheet cache, if we delted that files on close up, no problems will occur. As on close up we have the same permission as on creation.

**Comment by micheljung** [comment]
It's not just the cache directory, the same problem occurs with the game files and we shouldn't just delete those when the client closes.

**Comment by axel1200** [comment]
Ok then I'll look at this as well ;)

**Comment by micheljung** [comment]
This not yet fixed

**Comment by Brutus5000** [comment]
User gets a warning now etc.
