### ISSUE TITLE
Currupted map/mods

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#687]
![image](https://user-images.githubusercontent.com/19996713/34889724-614fce02-f7cf-11e7-91d6-c31464bcd142.png)

Hi @micheljung 
Could you tell me something, about how we detect if a mod/replay is currupted?

**Comment by axel1200** [comment]
Could not reproduce it locally.

**Comment by micheljung** [comment]
We need logs to figure out why.
Also, see https://github.com/FAForever/downlords-faf-client/blob/e40efee48153eac4a0c8e3b800f17714047e459e/src/main/java/com/faforever/client/replay/ReplayServiceImpl.java#L180

**Comment by axel1200** [comment]
Yeah I asked him to send it but no response...

**Comment by micheljung** [comment]
Maybe files are considered corrupt if the client has no permission to read them? Then again, it wouldn't have permission to move them, I guess.

Unable to reproduce, no response from NEX, closing.
