### ISSUE TITLE
Implement that installed Mods and Maps are shown differently

### ISSUE THREAD

**Issue by axel1200** [FAForever/downlords-faf-client#702]
Modify the ModCardControllers setInstalled() Method....
@20seven if you got time and fun doing it...

**Comment by 20seven** [comment]
![mapcards](https://user-images.githubusercontent.com/33601179/35007172-0e34b980-faf9-11e7-96fb-f8a45531e839.jpg)
do you mean something like this?

**Comment by 20seven** [comment]
This works fine now, but when testing on MapCards it cannot update the installedLabel on uninstall. I think it could be related to issue #525 .

I have  a green "arrow pointing down to a hard drive"-icon. It might follow the scheme better if it's white as the rest of the text, just let me know if i should change it.

**Comment by 1-alex98** [comment]
#525 is really a pain

**Comment by 1-alex98** [comment]
We need to be careful with red and green, as people are colour blind, but yeah... I don't know. I am not good when it comes to design :D @micheljung

**Comment by micheljung** [comment]
Icons are always better than text
1. They don't need a color to be meaningful (making it not only color-blindness friendly but also theme-friendly (even though themes could override the color))
1. They don't need to be translated (Less work, no different text lengths to be considered)
1. They look better

But it's not always easy to find an icon that is meaningful ;)

**Comment by 20seven** [comment]
![installed map](https://user-images.githubusercontent.com/33601179/36645809-8f06efc6-1a6e-11e8-9580-7a879fbcbfe7.jpg)

@micheljung how about this? (gap is installed, Waters of Isis is not)

**Comment by 1-alex98** [comment]
Seems reasonable to me

**Comment by Sheikah45** [comment]
Is this still desired?

**Comment by 1-alex98** [comment]
I would say so. Maybe use the new way for icons then tho maybe
