### ISSUE TITLE
Review text cut off

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#710]
When a review text is too long, it's cut off after 2 lines.

![image](https://user-images.githubusercontent.com/1864183/35152212-ac153f1a-fd21-11e7-93df-d2b0099f3c11.png)

**Comment by micheljung** [comment]
![image](https://user-images.githubusercontent.com/1864183/35152206-a706b058-fd21-11e7-9597-356ad470b11e.png)

**Comment by 1-alex98** [comment]
Maybe also seperators between reviews would be nice

**Comment by PhilipJFryFAF** [comment]
https://i.imgur.com/e7EkRYD.png
noticed that now the my review text is being cut off v 0.9 rc9

**Comment by Sheikah45** [comment]
this seems to have been fixed should it be closed?

**Comment by 1-alex98** [comment]
yes if its not the case any longer
