### ISSUE TITLE
Mutiple messages when friend conmes online or goes offline

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#713]
Thats the case with you start a chat with this friend...

**Comment by Askaholic** [comment]
Does this still happen? Is this beginner friendly? Maybe add some detail to the description.

**Comment by 1-alex98** [comment]
If you have a chat open with your friend u get two messages. One for him leaving chat and one for leaving because he is your fiend. Idk if that's still the case

**Comment by Sheikah45** [comment]
Not an issue anymore
