### ISSUE TITLE
Add "Report abuse" to player context menu

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#715]
Open this URL in a browser: https://docs.google.com/forms/d/e/1FAIpQLSfeg4ywc4JVC4frnpkPi6udTRpPqti0d4lH1DEmlRhWOnpagg/viewform?c=0&w=1

**Comment by axel1200** [comment]
What do you want to happen just open the link?

**Comment by 1-alex98** [comment]
Use the platformService bean for that

**Comment by 1-alex98** [comment]
now the reporting can be done on https://faforever.com.

**Comment by 1-alex98** [comment]
https://www.faforever.com/account/report
