### ISSUE TITLE
Wrong statistics

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#718]
![image](https://user-images.githubusercontent.com/19996713/35481871-9f13614a-042c-11e8-927b-58fed8618995.png)
Does need no words, the statistic is wrong. All games lost must be wrong....

**Comment by 1-alex98** [comment]
If I look at my own they seem to be correct....

**Comment by 1-alex98** [comment]
It's the api delivering wrong data

**Comment by 1-alex98** [comment]
https://github.com/FAForever/faf-java-api/issues/198

**Comment by germanicianus** [comment]
Was there any change? It seems it works now:
![image](https://user-images.githubusercontent.com/37223176/37875593-ebddffd0-3041-11e8-89dd-6cb290a871d1.png)

**Comment by 1-alex98** [comment]
always worked with my username but not with his

**Comment by 1-alex98** [comment]
acctually mine is also wrong as I have >900 games and this never adds up to 900. I remember @micheljung  told me the Server stopped writting some of the  events some day and as these are events. It is no suprise I have some statistics up they are outdated

**Comment by micheljung** [comment]
The stats are based on events and events have been introduced in 2016 or so. We didn't retroactively generate them, so they won't match up with the number of games of older players.

**Comment by germanicianus** [comment]
My statistics on that tab don‘t seem to update. They are still the same despite the General tab shows 8 played games. I know that at least one of my last games was a rated one. Have a look at my rating graph in my profile.

**Comment by 1-alex98** [comment]
Can you open a server issue?

**Comment by Sheikah45** [comment]
This seems to not be a client issue,
