### ISSUE TITLE
Fix "Create Game" button in map vault

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#720]
![image](https://user-images.githubusercontent.com/1864183/35514752-8d28f0fe-0507-11e8-8807-7b22941fdd47.png)

The "Create Game" button should either only be visible if the map is installed OR clicking it should install the map first, before trying to create a game.

Opinions appreciated.

**Comment by 1-alex98** [comment]
And it does only creat a game with any map. It should also create a game with that particular map!

**Comment by 1-alex98** [comment]
I would say only if the map is installed, I think that is most intuative :#
