### ISSUE TITLE
Error message on starting 1v1

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#724]
![image](https://user-images.githubusercontent.com/19996713/35589144-262e4b04-0603-11e8-8ef4-caa304bbbe5f.png)

**Comment by 1-alex98** [comment]
it is also an issue in the beta version

**Comment by 1-alex98** [comment]
When starting 1v1 it disconnects the proxy and faf server

**Comment by 1-alex98** [comment]
After using the alpha client I can also not play 1v1 with the python client XD

**Comment by 1-alex98** [comment]
Can we close @micheljung

**Comment by micheljung** [comment]
So I take it there is no issue after all?
