### ISSUE TITLE
Replay search is too complicated

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/downlords-faf-client#739]
There are lots of essentially useless search terms and too many dropdown menus and items.

The python client search is much better, you have a field for player name, a field for map name, a dropdown to select the base mod(1v1ladder, faf, fafbeta, phantom etc.) and a field for minimum rating.

**Comment by 1-alex98** [comment]
Hmm you might have a point there, but maybe we would need a little more concrete suggestion on how to change.

**Comment by EmielWitteman** [comment]
I like the search ability with several criteria, but most users probably will only search for Player names and map names.  Especially the "contains" filter is handy for obscure player and map names.
If the default criteria setting would be remembered and/or initialized with "Player name is <own name>" it will be more pleasant for most users I guess. Now the default criteria is "ID contains" which is less useful.

**Comment by micheljung** [comment]
I think it's time to tackle this. @BlackYps already took a shot at it in #1805 but I'm not yet convinced.

IMO, one case of "filtering done right" can be seen on digitec.ch.

For instance, if you're [looking for a graphics card](https://www.digitec.ch/en/s1/producttype/graphics-cards-106?tagIds=76), this is their filter:

![e060ac60-0337-44d5-a0db-8cf73e0d1866](https://user-images.githubusercontent.com/1864183/87143960-47e8fd80-c2a7-11ea-8d32-5de3f8f1250d.gif)

I think this is what we should aim for.

**Comment by BlackYps** [comment]
These filters are really nice for categories. Maybe we can use the [CheckMenuItems](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/control/CheckMenuItem.html) for this. But we have to find a way to disable that the menu closes each time you select one Item. I also found [this](https://controlsfx.bitbucket.io/org/controlsfx/control/CheckComboBox.html).

**Comment by JaggedAppliance** [comment]
I'm glad this is being looked at. I like the power of the search in general, my hope is that common searches can be made much more quickly and with less clicks. Being able to save particular queries would be useful but if searching is made more efficient that won't be necessary.
