### ISSUE TITLE
Support basic Markdown in chat

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#747]
If a user writes *bold* should be bold.

**Comment by axel1200** [comment]
*bold*
/italic/
_underline_
-stroke-
[code]

**Comment by 1-alex98** [comment]
`*bold*
/italic/
_underline_
-stroke-
[code]`

**Comment by 1-alex98** [comment]
Maybe https://github.com/atlassian/commonmark-java

**Comment by Sheikah45** [comment]
Don't really want to increase the complexity of chat display as currently the webview is already a pain and will likely be changed in the near future
