### ISSUE TITLE
Allow game file location to be configured

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#749]
From rackover:
> could you make it so `C:\ProgramData\` is the **default** path for the game, but that it can be changed in the options of the client ?
> There are multiple obvious reasons of why that would be better : apart from pure file-regroupment and sorting, there's a lot of people that like to separate their games / game softwares from the rest (another partition or disk) and the client downloading stuff in C:\ isn't very pleasing if you cannot change it

**Comment by Sheikah45** [comment]
Combined with the vault fallback location being the default this would require the ability to set an arbitrary vault location that the game would then load as currently all the paths are hardcoded
