### ISSUE TITLE
Green font on green background

### ISSUE THREAD

**Issue by Brutus5000** [FAForever/downlords-faf-client#751]
In the logical operator column of all vault searches, you get green font on green background in the selected option entry.
![2018-02-11 23_04_31-downlord s faf client](https://user-images.githubusercontent.com/6843462/36079178-ad733922-0f80-11e8-9c52-7c55d8e2feab.png)

**Comment by 1-alex98** [comment]
probably need to update css

**Comment by micheljung** [comment]
This is the case for all dropdowns, never took the time to fix it

**Comment by 1-alex98** [comment]
I reaally need to dig into that

**Comment by germanicianus** [comment]
Same for game sorting dropdown:
![image](https://user-images.githubusercontent.com/37223176/37990654-39f50594-3207-11e8-899c-e86486103465.png)
