### ISSUE TITLE
Create Game: Map preview issues

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#754]
It shows the map size in pixels instead of 
km:
![image](https://user-images.githubusercontent.com/1864183/36222773-ae3c5732-11c2-11e8-9182-68bba63d049e.png)

It's not restricted in height, overlapping with other elements:
![image](https://user-images.githubusercontent.com/1864183/36222831-d526f212-11c2-11e8-9d43-2484ba35dfaa.png)

**Comment by germanicianus** [comment]
The map preview also isn't shown initially but only after changing the map selection:
![image](https://user-images.githubusercontent.com/37223176/39423336-ba53af40-4c71-11e8-8292-6d5f8f70aba3.png)
