### ISSUE TITLE
Api calls with no results should be handled accordingly

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#757]
![image](https://user-images.githubusercontent.com/19996713/36503894-040a8f3a-174f-11e8-97cb-880a959360ea.png)

**Comment by micheljung** [comment]
Thanks for creating a bug report, however, this is an API problem and not a client problem.
With the link in the screenshot, the API returns an empty response and the client handles it properly. However, with rackover's *actual* URL (with includes and such) the API took too long and timed out. The client properly displayed an API timeout exception then.
