### ISSUE TITLE
Replays marked as corrupt

### ISSUE THREAD

**Issue by JaggedAppliance** [FAForever/downlords-faf-client#763]
All my replays from 2018 were moved to a folder marked corrupt, plus a few more. They are not corrupt.

**Comment by 1-alex98** [comment]
Could you provide such a replay ?

**Comment by JaggedAppliance** [comment]
[7381860-JaggedAppliance.zip](https://github.com/FAForever/downlords-faf-client/files/1755827/7381860-JaggedAppliance.zip)

**Comment by 1-alex98** [comment]
thx

**Comment by 1-alex98** [comment]
It seems to be that the client does not know the featuredmod ladder1v1 maybe it is an issue in spelling ladder1v1 or so. Will have a look at it

**Comment by 1-alex98** [comment]
It can not find the map, but that is due to some broken logic in the client. I will need to ask downlord about it

**Comment by axel1200** [comment]
So you need to have the map as it seems and you probably have not good the maps of this "old replays", but i will ask @micheljung if we should not search this map online if you dont have it on your disk

**Comment by 1-alex98** [comment]
![image](https://user-images.githubusercontent.com/19996713/36640587-3256cf7c-1a22-11e8-8bfe-bf5dd0a1ce0d.png)
lol i am sure that does not do what it is supposed to do XD

**Comment by 1-alex98** [comment]
got it

**Comment by 1-alex98** [comment]
nice replay
