### ISSUE TITLE
Seperate log file per game

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#777]
![image](https://user-images.githubusercontent.com/19996713/36734524-0490a744-1bd4-11e8-9275-c020ad8c951f.png)

**Comment by 1-alex98** [comment]
Do we wanna keep all files or only the last 10 what would you say?

**Comment by micheljung** [comment]
I'd only keep the last 10. Otherwise, we're spamming the user's file system.
