### ISSUE TITLE
Colouring of moderators

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#785]
![image](https://user-images.githubusercontent.com/19996713/36936607-d20ef58c-1f07-11e8-81e4-a06ba83f4efd.png)

**Comment by 1-alex98** [comment]
duplicate

**Comment by micheljung** [comment]
Duplicate of...?

**Comment by Geosearchef** [comment]
Duplicate, I already worked on this, now let's just find out where. :joy:
