### ISSUE TITLE
Create channel links in IRC

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/downlords-faf-client#786]
Is it possible to turn channel names in IRC into a link you can click to open the respective channel?

**Comment by 1-alex98** [comment]
Do you think we should transfer every #(somethig) into a link, also replays are oftern refered to by #aNumber

**Comment by Geosearchef** [comment]
No, i'm currently implementing this by scanning through all channels when someone posts a "#^[a-zA-Z]+$". Already noticed the thing about replays.

**Comment by micheljung** [comment]
Wasn't there a PR?
