### ISSUE TITLE
Bad UnitDB rendering - outdated web engine ?

### ISSUE THREAD

**Issue by Rackover** [FAForever/downlords-faf-client#791]
I was told to open an issue for that by @Geosearchef , so here it is.
It seems the browser agent the java client uses is uncapable of interpreting CSS/HTML5 the way it was intended when I created the FAF UnitDB.

Despite the unitDB passing all the validation tests on w3c.com, and therefore being completely valid HTML5, it does not display correctly under the client : the strategic icons lack color for example, on windows, and on linux its a complete mess as the flexboxes aren't interpreted at all.

I feel like windows java-client is using iexplore as part of its web rendering engine, because it suffers from the exact same display glitches at the exact same places than the iexplore installed on my PC. 
However, edge, firefox and chrome displays it like they should.

So maybe there is a way to update/change the internal web rendering library used to render the webpage ? I wouldnt want to have to make five separate versions of the exact same strategic icons with a dumb colorswap, that would be wasting bandwidth, disk space, and time. I can do if needed, but only as a last resort.

Screenshot on windows : 
![downlord s_faf_client_2018-03-04_21-32-30](https://user-images.githubusercontent.com/33836535/37066391-81924b4a-21a5-11e8-873d-0f8c8ac5cb38.jpg)

**Comment by 1-alex98** [comment]
I think we have our own css that overwrites yours ....

**Comment by Rackover** [comment]
CSS doesn't (shouldn't?) work like this, stylesheets sum up but do not replace each other. If my stylesheet was voided by yours, there would be no colors on the < details > and the font would be Times New Roman. The absence of CSS coloration on the icons is the sign of an outdated browser, not of a stylesheet replacement.
Try the page on old browser / old version browser and on recent ones, you'll notice the icon coloration will be the first thing to disappear.

**Comment by micheljung** [comment]
Fixed in next release
