### ISSUE TITLE
List found translation files (.properties) dynamically in language settings (currently hardcoded)

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#798]
Currently one can add a translation file, e. g. messages_ko_KR.properties for Korean, by placing then into a directory 'i18n' located at the same place where the client jar is located (e. g. downlords-faf-client-0.7.6-alpha.jar). However this is not enough because the selectable languages are hardcoded which needs to be changed.

Additionally, the Java mechanism for automatic determination of the language display name should be used to show the localized language names in the settings dropdown to add consistency and remove the need for manual translation. Example:
```Java
final Locale locale = new Locale("cn", "ZH");
final String displayName = locale.getDisplayName(locale);
```
How it could look like:
![settings_languages](https://user-images.githubusercontent.com/37223176/37546111-b360c98a-296b-11e8-806b-5f2b660b9f21.png)

Places to start at:
```Java
com.faforever.client.config.BaseConfig.messageSource()
com.faforever.client.preferences.LanguageInfo
com.faforever.client.i18n.I18nImpl
```

**Comment by micheljung** [comment]
Sounds good. One thing: the proper place for the `i18n` directory is the client's local app data directory (`%LOCALAPPDATA%` on Windows). And there I'd call it `languages` since users don't understand `i18n`.

**Comment by micheljung** [comment]
Fixed in next release
