### ISSUE TITLE
Context menu for text edit has no translation/message keys

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#799]
![context_menu_text_edit_untranslated](https://user-images.githubusercontent.com/37223176/37546381-cf4c945c-296c-11e8-936d-0428a4f6f0ed.png)

**Comment by micheljung** [comment]
I don't know if setting [Locale.setDefault(Locale)](https://docs.oracle.com/javase/8/docs/api/java/util/Locale.html#setDefault-java.util.Locale-) solves this.
If not, we might need to set `user.language` as a command line parameter (in the `.vmoptions` file). But this resides in `C:\Program Files` which needs admin permissions (but I plan to install the client into the user's application data directory anyway, as this doesn't require admin permissions and makes it easier for us to auto-update the client in future).

**Comment by 1-alex98** [comment]
works now
