### ISSUE TITLE
Hide avatar selection if there are no avatars to select

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#800]
![chat_user_context_menu_empty_box](https://user-images.githubusercontent.com/37223176/37546614-e6da851a-296d-11e8-8bf9-6155a5f44dbf.png)

**Comment by 1-alex98** [comment]
I think it is not because you got no games but because you got no avatar, I can select my avatar in it ;)

**Comment by germanicianus** [comment]
So it seems to be an easy fix: Either disable the dropdown or show a placeholder-avatar. I vote for the latter because it‘s obvious then :) .

**Comment by germanicianus** [comment]
I thought the dropdown belongs to „Show replays“ (string above), that‘s why I assumed it has to to with no games played.

**Comment by 1-alex98** [comment]
This seems to be an Server Issue, the thing is there should always be the "no avatar" option as soon as the Server told the client which avatars are available for you as a player. So the Server seems to not respond when you have no avatars 😬

**Comment by 1-alex98** [comment]
![image](https://user-images.githubusercontent.com/19996713/37664705-2119ee5a-2c5c-11e8-8098-e5a80dc9b8ea.png)
pROBABLY RUNS IN THAT timeout

**Comment by micheljung** [comment]
I think I'm the one responsible for that crap of code :D

**Comment by 1-alex98** [comment]
No suprise when 80% of code is from you right?
