### ISSUE TITLE
Play -> Co-Op -> Leaderboard -> All (dropdown item) shows no games

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#802]
No error in log.

![coop_leaderboard_all_no_games](https://user-images.githubusercontent.com/37223176/37547622-1dc15658-2973-11e8-9c12-8f1b21b81640.png)

![coop_leaderboard_4_players_games](https://user-images.githubusercontent.com/37223176/37547628-239e5fa8-2973-11e8-8047-79aa1ac28ba0.png)

**Comment by micheljung** [comment]
Also, notice how it displays 4 leaderboard entries if you select "4 players", 3 if you select "3 players" and so on :D I thought there was already an issue for this but I can't find one.

**Comment by 1-alex98** [comment]
I remember there was something broken on server or api that caused the leaderboard to be incorrect, because python client also shows outdated leaderboard
