### ISSUE TITLE
Play -> Co-Op - Make layout work on smaller window sizes (currently cut and overlapping elements)

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#803]
Leaderboard table colums to narrow even with maximized window:
![coop_leaderboard_4_players_games](https://user-images.githubusercontent.com/37223176/37547628-239e5fa8-2973-11e8-8047-79aa1ac28ba0.png)

Overlapping and cut elements:
![coop_overlapping_and_cut_elements](https://user-images.githubusercontent.com/37223176/37547904-b0cba506-2974-11e8-8621-7b39462c70d3.png)

**Comment by micheljung** [comment]
May or may not have been fixed/improved in dbc6a130fa41fa6c51633e02d2c329085ab57970
But also, if a player isn't even giving the UI enough space to lay out all it's components, what does he expect? Best we can offer is a ScrollView around all views but I don't see it worth the effort.

**Comment by germanicianus** [comment]
I'm on the latest code of master.

The first screenshot shows the UI maximized on my monitor, but the table columns are still cut.

The second one still uses 3/4 of my screen. The elements already start to overlap if I downsize it to about 2/3 of my screen. In fact it seems that I can use the UI only in fullscreen. My monitor is only 1360x768.

I didn't expect the elements to overlap but that big component groups get a scrollbar, if some minimum size is reached. It seems that some components also get to much space, like the game info box at right hand side which covers the game table 1/2 to 2/3. One can see the table rows at the very right hand side of the game info box. We can have some talk in Slack what can be done about this issue :) .

**Comment by germanicianus** [comment]
I changed this to an enhancement because one could argue that it currently works as designed.

**Comment by 1-alex98** [comment]
duplicate
