### ISSUE TITLE
Play -> Custom Games game tooltip to large

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#804]
![play_custom_games_game_tooltip_to_large](https://user-images.githubusercontent.com/37223176/37548165-5f6c9650-2976-11e8-807a-512c326aa57b.png)

**Comment by axel1200** [comment]
We know abut that issue apparently it is pretty hard to fix :(

**Comment by germanicianus** [comment]
So now we have a tracking issue :smile: .

**Comment by germanicianus** [comment]
@axel1200 I've just searched the issues and now I got what you mean. It seems my issue is a duplicate of #625 "Malformed tooltips of Game Tiles", just with a helpful screenshot :smile:. Shall we merge them?

**Comment by 1-alex98** [comment]
They are automaticly merged by you commenting  #625 ;) no?

**Comment by Katharsas** [comment]
The tooltip always makes space for exactly twice the amount of teamcards that are shown.

**Comment by Katharsas** [comment]
Fixed
