### ISSUE TITLE
Provide Chinese as UI language (i18n/internationalization)

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#805]
Before the translation properties file can be merged, #780 "Support non latin alphabets in i18n" needs to be merged.

The current status of the translation can be found on POEditor (currently ~ 11 % for Chinese):
https://poeditor.com/projects/po_edit?id_language=31&id=126971

**Comment by micheljung** [comment]
Has been added

**Comment by germanicianus** [comment]
Reopening because the translation isn't complete yet :smile: .

**Comment by micheljung** [comment]
If we wait until it is completed 100%, we will never close this because new messages are added every now and then and I don't expect (or wait) for all languages to catch up for each release.

Translation is now at 76%, this good enough to consider it "implemented" :)
