### ISSUE TITLE
Installation fails and says it has not found a jre

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#811]
At my machine it seemed to install jre in temp folder

**Comment by micheljung** [comment]
Does this happen with the latest 51mb installer as well? https://github.com/FAForever/downlords-faf-client/releases/download/v0.8.0-beta/dfc_windows_0_8_0-beta.exe

**Comment by 1-alex98** [comment]
Np now that issue is fixed as we pack jre within the client
