### ISSUE TITLE
Autojoin chat channels on startup

### ISSUE THREAD

**Issue by 20seven** [FAForever/downlords-faf-client#816]
The python client has an autojoin channels setting:
![autojoinchannels](https://user-images.githubusercontent.com/33601179/37830583-e00fabd6-2ea2-11e8-8804-1678a0879a7c.png)
https://github.com/FAForever/client/pull/901

 Seems to be a very appreciated feature.

**Comment by 1-alex98** [comment]
Is it send to the Server?

**Comment by 20seven** [comment]
@axel1200 No, it is not

**Comment by micheljung** [comment]
@20seven can you open a pull request for your changes? :)
