### ISSUE TITLE
Vault -> Maps -> any map: Open game must not be presen for maps not installed

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#818]
![image](https://user-images.githubusercontent.com/19996713/37864471-a1914c52-2f6f-11e8-95e1-cadf32c9e251.png)

**Comment by micheljung** [comment]
There is a subject missing in the title

**Comment by 1-alex98** [comment]
the button

**Comment by 1-alex98** [comment]
It is from the map detail
