### ISSUE TITLE
Outdated url for rackovers db

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#820]

**Comment by germanicianus** [comment]
Result:
![result](https://user-images.githubusercontent.com/37223176/37867406-2b5893a0-2f98-11e8-9861-540fcbc7d92b.png)

You were faster :smile: .

**Comment by Geosearchef** [comment]
included in PR: https://github.com/FAForever/downlords-faf-client/pull/790
as the URL is changed their anyways to include the encoded language settings.
