### ISSUE TITLE
UI crashes when starting it with java.exe because missing install4j

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#821]
Workaround is to comment the following line in MainController.java:
noCatch(SplashScreen::hide);

This is the one and only place where install4j is referenced in the code.

**Comment by 1-alex98** [comment]
But do we wanna support starting it that way, I would say we dont care

**Comment by Geosearchef** [comment]
We do wanna support starting it without Install4J, but that has very low priority. I had a discussion with downlord on this, we shouldn't invest into linux compatibility, but the client has already come a long way and is only missing packaging steps and some minor fixes to be fully linux compatible. So I'd say we care. If you wanna discuss if we'll do this please move to slack.

**Comment by micheljung** [comment]
Try to load the class via classloader (Class.forName()), if it's there execute the code else don't
