### ISSUE TITLE
Vault -> Local Replays: Improve table formatting

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#822]
This table has some formatting issues which may be present in the other tables also:
![local_replays_table_format](https://user-images.githubusercontent.com/37223176/37867616-a1fe7918-2f9b-11e8-9963-e09e57d2da38.png)

Namely:
- Column width should be adjusted automatically (done manually for the screenshot).
- Player names don't fit in.
- No line wrapping, no row height change possible.
- No tooltip for overflowing cells containing the value.
- Row text not centered vertically except for first column. Possible cause: One has a StringCell and the other render the string using the default mechanism.

Problem: Sizing the columns automatically hasn't been solved for the UI because of JavaFX constraints, at least with constrained column sizes (always fit the table width).

**Comment by Sheikah45** [comment]
Not relevant anymore with local replay pagination change
