### ISSUE TITLE
Vault -> Local Replays: No values in column "Game type"

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#823]
![local_replays_table_format](https://user-images.githubusercontent.com/37223176/37867616-a1fe7918-2f9b-11e8-9963-e09e57d2da38.png)

**Comment by 1-alex98** [comment]
Duplicate of #732, ther is a Pr that fixes it already

**Comment by micheljung** [comment]
"Duplicate of #..." would help to know where :)

**Comment by germanicianus** [comment]
Oh. But I would have expected that the issue ("bug") stays open until the pull request ("fix") is merged ("checked-in"). Maybe that's just still Bugzilla and SVN thinking of myself.

**Comment by 1-alex98** [comment]
I always do it this way

**Comment by micheljung** [comment]
Closing duplicates is common practice, the initial issue stays open
