### ISSUE TITLE
Provide means to copy/export table content (e. g. as text/csv)

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#824]
Example-table:
![local_replays_table_format](https://user-images.githubusercontent.com/37223176/37867616-a1fe7918-2f9b-11e8-9963-e09e57d2da38.png)

**Comment by 1-alex98** [comment]
Is that really necessary?

**Comment by germanicianus** [comment]
It doesn't need to be super fancy. Making it possible to select/mark/highlight values to copy them to clipboard like in a simple text editor would be enough. Like making the cell content selectable but not editable.

**Comment by micheljung** [comment]
Yes to make it editable-but-not-editable, no to export  function
