### ISSUE TITLE
Add visual indication to table columns(/rows) if they are sortable/movable/resizable

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#825]
Example-table with resizable, sortable and movable columns but no visual indicators that they are:
![local_replays_table_format](https://user-images.githubusercontent.com/37223176/37867616-a1fe7918-2f9b-11e8-9963-e09e57d2da38.png)

**Comment by germanicianus** [comment]
wontfix? Why? Do all tables have this functionality?

**Comment by 1-alex98** [comment]
I mean we can do everything but I dont think this is worth the work

**Comment by Brutus5000** [comment]
JavaFX table columns are sortable by default. You can override the default sorting method, if required (i.e. if it contains numbers like game id you can switch to integer sorting). Maybe adding usefull sorting is actually required instead of indicating.

**Comment by germanicianus** [comment]
I'm so blind. They already have a sorting indicator (see "When" column). The other indicators are not so important -> closing.
