### ISSUE TITLE
Play -> 1v1 ranked match: Incorrect values

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#826]
See red circles:
![1v1_ranked_match_statistics_incorrect](https://user-images.githubusercontent.com/37223176/37867991-48668120-2fa0-11e8-880d-a4f05a13265e.png)

**Comment by 1-alex98** [comment]
Why should your rank be wrong I assume it is simply correct

**Comment by 1-alex98** [comment]
So yeah Win/ Loss ration seems incorrect

**Comment by Geosearchef** [comment]
WinLoss ratio looks like divison by zero/NaN

**Comment by micheljung** [comment]
Just fyi the server doesn't update wins anymore

and that his rank 20'000 of 5'000 doesn't feel correct is kind of understandable :P

**Comment by 1-alex98** [comment]
Yeah that the Server does not update wins I realised this already and made an issue on it but it is probably never gonna be fixed....

**Comment by 1-alex98** [comment]
So do we wanna hide it then? Ok i did not read the numbers that closely

**Comment by germanicianus** [comment]
The circles were supposed to hint you to read those places carefully :stuck_out_tongue_winking_eye: .

**Comment by 1-alex98** [comment]
server
