### ISSUE TITLE
Improve new chat notification highlighting

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#827]
See pink circles:
![bug_missing_chat_notification](https://user-images.githubusercontent.com/37223176/37868303-5f3a6156-2fa4-11e8-8c7b-01f980ab34c7.png)

**Comment by germanicianus** [comment]
Ok, now I've got it. The green colored tab is the indication. So this is not a bug.

**Comment by 1-alex98** [comment]
So what do you thing needs to be done...?

**Comment by micheljung** [comment]
We could add a badge or at least a `(1)` to the channel tab, I always wanted that. Let's rename the issue accordingly

**Comment by germanicianus** [comment]
I suggest to remove the green color or change it to another color at least. It's very confusing because the active tab also uses green as indication, just as an underline. Better would be to either add (count) in red to the bell or to the chat tab as micheljung already commented :smile: .

**Comment by micheljung** [comment]
I always wanted the badge instead of the color, but a contributor added the color :D

**Comment by Sheikah45** [comment]
Color confusion no longer applicable
