### ISSUE TITLE
Loading indicator missing if initial tab is Leaderboards and changing to tab Chat

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#828]
Follow-up of issue #827.

It would be nice to have a loading indicator because I changed tabs a few times because I thought the tab Chat displays wrong content. But maybe I got confused by the green tab coloring. Currently I am not so sure anymore.
![tab_chat_missing_loading_indicator](https://user-images.githubusercontent.com/37223176/37868427-53ac117a-2fa6-11e8-998d-2e2a324f2fb4.png)

**Comment by 1-alex98** [comment]
I dont get what you wanna say :(

**Comment by germanicianus** [comment]
When tab Leaderboards is the initial tab on starting up the UI and then changing to tab Chat, there is no Loading indicator (green circle):
![image](https://user-images.githubusercontent.com/37223176/37874920-32285ae4-3038-11e8-8793-8089eb36615c.png)

**Comment by germanicianus** [comment]
So in the end I got very confused by the combination green chat indicator (#827) + no loading indicator when changing to tab chat.

**Comment by micheljung** [comment]
Fixed in 0.9.0-beta
