### ISSUE TITLE
Show profile -> Statistics -> Techs built: Seems to be incorrect

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#829]
At the following screenshot one can see that Tech 3 is missing completely. I am 100 % sure that I've built tech 3 units. The only thing that may have happened is that the fraction is in relation so small that it cannot be displayed.
![user_statistics_missing_tech_3](https://user-images.githubusercontent.com/37223176/37868521-02c459d2-2fa8-11e8-8c1f-1769492b44a3.png)

**Comment by 1-alex98** [comment]
I think it only shows ranked games, most games you played were not ranked. But I would need to check

**Comment by 1-alex98** [comment]
Hard to tell on which games Events are created, do you know @micheljung

**Comment by germanicianus** [comment]
> I think it only shows ranked games

That doesn't seem to be the case. But at least the graph meaning is a bit unclear. I now think the graph is global and I just built to few tech 3 units in relation to tech 2 and tech 1 to show up in the graph, but it's strange that the Tech 3 label is missing completely at the graph - maybe because it would overlap with the other label. I think we should at least show additionally the absolute number.
![image](https://user-images.githubusercontent.com/37223176/37874988-2d637484-3039-11e8-812e-4971f543f0b4.png)

**Comment by micheljung** [comment]
+1 for showing the absolute number.
As long as we display the exact data the API is telling us, there is no issue in the client.

I think there are still problems in the python ~client~ server reporting events and achievements to the API sometimes, but I was never able to fix it completely.

**Comment by germanicianus** [comment]
>I think there are still problems in the python client reporting events and achievements to the API sometimes [...]

Maybe that’s the issue. I played using the Python client (low on memory).

**Comment by micheljung** [comment]
Actually, I meant "server"

**Comment by 1-alex98** [comment]
we know sever issue
