### ISSUE TITLE
messages_de_DE.properties still ASCII encoded instead UTF-8

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#830]
![de_ascii_instead_utf-8](https://user-images.githubusercontent.com/37223176/37868701-1cf42442-2fab-11e8-804d-0d32582f5766.png)

A similar issue could also be the question mark problem shown on screenshot of issue #826.

**Comment by Geosearchef** [comment]
https://github.com/FAForever/downlords-faf-client/pull/781

**Comment by Geosearchef** [comment]
PR https://github.com/FAForever/downlords-faf-client/pull/781
