### ISSUE TITLE
Error dialog has no window/taskbar icon (Java default icon is used)

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#834]
![image](https://user-images.githubusercontent.com/37223176/37875662-d5b9b400-3042-11e8-9c71-4d2ad6a21786.png)

**Comment by micheljung** [comment]
Will be obsoleted by #880

**Comment by Geosearchef** [comment]
Does #880 create a new window for the dialog? Currently the errror dialog opens in full screen due to not telling my tiling window manager it want's to float.

**Comment by micheljung** [comment]
It doesn't create a new window, it's kind of an inline node
