### ISSUE TITLE
Error dialog button "Melden" ("Report") is disabled

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#835]
![image](https://user-images.githubusercontent.com/37223176/37875662-d5b9b400-3042-11e8-9c71-4d2ad6a21786.png)

**Comment by micheljung** [comment]
It's disabled on purpose since it's not yet properly implemented

**Comment by germanicianus** [comment]
Oh. So currently it should be hidden instead of being disabled.

**Comment by 1-alex98** [comment]
There is an issue for this already

**Comment by germanicianus** [comment]
Where? Couldn't find it. Link, please.

**Comment by 1-alex98** [comment]
https://github.com/FAForever/downlords-faf-client/issues/351
