### ISSUE TITLE
GameTooltipController memory leak

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/downlords-faf-client#836]
Hovered over some games in the play tab in TILED mode. Client now uses 1 GB of RAM and 30-40% CPU.

Here's a memory dump order by allocation by method call:
![capture](https://user-images.githubusercontent.com/5748922/37879951-184ef9a4-3081-11e8-87cd-3b791522821a.PNG)

createAndAdd method allocated 70 % of current RAM usage.

**Comment by Geosearchef** [comment]
TeamCardController:63 is called very often (new card created and added) even after taking your mouse off the game and minimizing the client. (hovering above 4-6 games gives you around 10 new TooltipCards each second)

**Comment by micheljung** [comment]
Fixed in #853 (so we hope)
