### ISSUE TITLE
nil value and inconsistency in map tiles

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#847]
I've noticed some things in the map tiles (see screenshot below).
1. From create game dialog. It shows a 'nil' value and the map size in pixels.
2. From a game on the Play tab. It shows an internal name and is missing the map size.
3. From Vault search. It shows the map size in km.

![image](https://user-images.githubusercontent.com/37223176/38050521-9a796986-32cb-11e8-9fe4-a9fb1dcfec45.png)

**Comment by germanicianus** [comment]
The map size display issue mentioned in '1.' (pixel instead of km) is fixed in pull request #879.

**Comment by Brutus5000** [comment]
Regarding scmp_002: This is one of supcoms default maps, afaik the don't have a better name.
