### ISSUE TITLE
Play -> Create game dialog: Not resizable, not movable, vanishes if click-hold-move-mouse outside

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#848]
![image](https://user-images.githubusercontent.com/37223176/38051184-cef8f45e-32cd-11e8-99c3-a6643d58e9f3.png)

**Comment by Brutus5000** [comment]
Please exclude the "Friends only" part from this issue. This is not trivial and afaik also broken server side.

**Comment by germanicianus** [comment]
Usually I create one issue for one problem, but I didn't want to spam issues and thought we can split an issue if necessary. Apparently it is in this case :smiley: .

**Comment by micheljung** [comment]
This is supposed to be a popup like when you right-click somewhere. As such, it is supposed to close when you click somewhere else, and it's not supposed to be resizable.

I'm not sure we want to turn it into a dialog that has its own window. If you observe what other UIs do (e.g. Discord) you'll notice that they almost never open an additional window. Dialogs in Material Design (as of Google) also work that way.

So the question is: What advantage do we get if we make this a separate stage? Generally speaking, I want the client to have as few windows as possible.
