### ISSUE TITLE
Flag tooltips show ISO country code instead country name, flags don't have tooltips at all places

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#849]
ISO country codes are not user-friendly. Country names are - they are also shown in the in-game lobby:
![image](https://user-images.githubusercontent.com/37223176/38106689-17f99060-3390-11e8-807a-18faf64ef22a.png)

Example for missing flag tooltips: Tooltip shown for user in chat user list, but not on Play tab on game info tile. Also, when chatting, the conversation window showing the messages has no tooltip for the flags, but everything else (except badge) in the user name.

**Comment by 1-alex98** [comment]
This is a game issue pls create the issue on the game repository

**Comment by micheljung** [comment]
The screenshot is from the game as a comparison, but he's still talking about the client ;)

We show country codes, the game shows country names. We should also show country names.

**Comment by 1-alex98** [comment]
Ups

**Comment by germanicianus** [comment]
Tooltips are even created if there is no country info available which leads to an empty tooltip:
![image](https://user-images.githubusercontent.com/37223176/39418690-1ccf4654-4c5c-11e8-8129-457a1e75c93f.png)

**Comment by germanicianus** [comment]
Country name in user-info window is not localized:
![image](https://user-images.githubusercontent.com/37223176/39418839-e7ccfe64-4c5c-11e8-8d59-ad8d9b61cf97.png)

**Comment by germanicianus** [comment]
Blue flag is not used on tab Chat but at other places, e. g. user info window and game info:
![image](https://user-images.githubusercontent.com/37223176/39436666-f218cc76-4c9e-11e8-8b60-de036eeb2d82.png)

![image](https://user-images.githubusercontent.com/37223176/39436655-e5f462ca-4c9e-11e8-8b0f-efa154753c4d.png)

**Comment by Geosearchef** [comment]
When there is no country info, i think we should still display a tooltip displaying "Earth". (like the earth flag that you get in situations like this)

**Comment by germanicianus** [comment]
I do - see my pull request :D . Exception: User info window.

Edit: I have to correct myself. I remember having implemented to show a tooltip 'EARTH' for the blue flag, but it isn't shown with my current code. I also remember having some blue flags in the chat tab, but maybe I'm mistaken. People having a blue flag on the teams card don't have a flag on the chat tab:
![image](https://user-images.githubusercontent.com/37223176/39485815-44faeb28-4d7a-11e8-9bbb-5bdb5602c712.png) ![image](https://user-images.githubusercontent.com/37223176/39485779-218bd9d6-4d7a-11e8-83a3-c514ba7d1051.png)

**Comment by Geosearchef** [comment]
Ok :+1: , I saw your PR, but it was too long for me wanting to read it on my phone. Gonna have a look later.
