### ISSUE TITLE
Add "Friends only" option in "Create Game" dialog

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#850]
Split from #848.

Thy Python client has the "Friends only" option:
![image](https://user-images.githubusercontent.com/37223176/38059634-7649681a-32e7-11e8-914a-372bca82db59.png)

Labeling as minor issue because it's the impact on the user, not the complexity. I even would say it's cosmetic because a user could provide a password.

**Comment by micheljung** [comment]
I also thought this was broken server-side (or maybe it was just python client-side) but apparently, it's been implemented/fixed https://github.com/FAForever/server/blame/eff0729087a0b56e8ce1388da99c766409d80d08/server/__init__.py#L112

So yes, we should support it.

**Comment by 1-alex98** [comment]
Classes are already there but can not be set in UI
