### ISSUE TITLE
Friend online notification is displayed despite being turned off

### ISSUE THREAD

**Issue by 20seven** [FAForever/downlords-faf-client#862]
![settinge](https://user-images.githubusercontent.com/33601179/38514855-a8a03fec-3c32-11e8-8a0b-7fb4a41b840a.png)

"Display Toast" is unchecked yet I still get notifications whenever friends come online

**Comment by micheljung** [comment]
I never encountered this. Oh, I have no friends. Sad world.

**Comment by PhilipJFryFAF** [comment]
just encountered this bug (currently using 0.9.0 RC8)

**Comment by 1-alex98** [comment]
Maybe the rebase for none-ice version destroyed that:thinking:

**Comment by 1-alex98** [comment]
duplicate
