### ISSUE TITLE
Remove redundant interfaces

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#869]
Currently, each service has its interface, i.e. GameService is the interface and GameServiceImpl is its implementation. I never felt like this was a smart thing to do but it was and still is [recommended by the Spring Framework](https://docs.spring.io/spring/docs/current/spring-framework-reference/core.html#aop-proxying) ("JDK dynamic proxies are preferred whenever you have a choice").

Still not seeing any benefit after years, but seeing the unnecessary noise it causes, I want to get rid of all service interfaces that only have one "Impl"-implementation.

There are some classes who don't just have the "Impl" implementation, but also a Mock implementation. These can be omitted for now.

# Caveat

I'm not sure how Git will see the change if we remove the interfaces and rename the classes to what used to be the interface's name. It will probably not see rename operations like `GameServiceImpl -> GameService` but the deletion of `GameServiceImpl` and a change of all lines of `GameService`. I don't want the implementor of this issue to become the author of almost every line of every service ;)

Therefore, I recommend doing this in two steps:

1. Delete all service interfaces that only have one implementation, commit
1. Remove the "Impl" suffix of all affected classes, commit

**Comment by dknz2008** [comment]
I'm on it!
