### ISSUE TITLE
Linux: Cannot run client due to missing javassist.ClassPool (javaagent)

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/downlords-faf-client#906]
maybe create a fat jar instead

**Comment by germanicianus** [comment]
For me it's working. I am using Ubuntu 18.04 LTS and the Oracle JDK 1.8.0 Update 171. The Gradle build runs without problems and I can extract and run the zip build (e. g. `downlords-faf-client-0.9.0-beta-rc.3.zip`) using the commandline. Just switch to the directory where you extracted it and run:
```
java -cp downlords-faf-client-0.9.0-beta-rc.3.jar:commons-compress-1.9.jar:./*:./ -XX:+UseConcMarkSweepGC -DnativeDir=. -Dprism.dirtyopts=false -Xmx512m -XX:+HeapDumpOnOutOfMemoryError -Dsun.java2d.opengl=true com.faforever.client.FafClientApplication
```

**Comment by Geosearchef** [comment]
I can run the packaged version aswell. Running it out of IntelliJ finishes gradle build and throws an exception on start. Packaging the Javassist library into the java agent jar (fat jar) solves this issue. This is due to the the classpath libraries not being present when starting the jvm. It can be solved by setting `-cp` manually, but then the normal libraries won't be found anymore.

**Comment by germanicianus** [comment]
I am able to run it from within Eclipse :) .

**Comment by Sheikah45** [comment]
Doesn't seem to be an issue anymore
