### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/downlords-faf-client#908]
Client freezing after 5-10 minutes of runtime probably due to high memory usage and garbage collection. (windows and linux)

**Comment by Katharsas** [comment]
Probably not related , but i found 2 file handle leaks:
- https://github.com/FAForever/downlords-faf-client/blob/6efa201b3884f260e8e82af6360bdd25885e6e83/src/main/java/com/faforever/client/map/MapService.java#L185
- https://github.com/FAForever/downlords-faf-client/blob/6efa201b3884f260e8e82af6360bdd25885e6e83/src/main/java/com/faforever/client/patch/GameBinariesUpdateTaskImpl.java#L123

**Comment by 1-alex98** [comment]
We sometimes have some problems with files being locked maybe they that is related to any of them

**Comment by micheljung** [comment]
FIxed in 0.9.0-beta
