### ISSUE TITLE
Message clan leader -> check for SELF

### ISSUE THREAD

**Issue by Geosearchef** [FAForever/downlords-faf-client#912]
Remove context menu entry "Message clan leader" when you're the clan leader.

**Comment by micheljung** [comment]
Achievements timing out has little to do with messaging yourself ;)

**Comment by Geosearchef** [comment]
Oh, should have thought of that, the exception just popped into existence at the the perfectly timed moment. (I'm too tired now ;) )

Nonetheless we should probably disable the "message clan leader option" in that case.
