### ISSUE TITLE
FYI - negative infinite power affects entire enemy team during online match

### ISSUE THREAD

**Issue by faf-nsw** [FAForever/downlords-faf-client#920]
Midway through a dual gap match, the enemy team suddenly experienced negative infinite power.  They were then unable to build anything.  I don't know if it is a bug or a hack,

Replay - 8013587 @ 26:56

[forever.log](https://github.com/FAForever/downlords-faf-client/files/2056489/forever.log)
[game.log](https://github.com/FAForever/downlords-faf-client/files/2056490/game.log)

Defiant

**Comment by micheljung** [comment]
Can you please open this in FAForever/fa?
