### ISSUE TITLE
Trips Virus protection

### ISSUE THREAD

**Issue by Burner-Fuel** [FAForever/downlords-faf-client#927]
Is detected as a Trojan by Kaspersky anti virus due to "suspicious activity"

**Comment by 1-alex98** [comment]
Well that happens, some anti viruses are a little over sensetive

**Comment by 1-alex98** [comment]
Especially the uid executable that genrates a unique id for you r device(smurf protection and ban) is often misinterpreted I guess

**Comment by micheljung** [comment]
AFAIK all we can do is report the false positive to Kaspersky. I can't change the fact that the client has to execute an exe file.

**Comment by 1-alex98** [comment]
Wow I can not send them files >50 mb ... https://virusdesk.kaspersky.com/?_ga=2.26434042.617383082.1528300385-2140799293.1528300385

**Comment by 1-alex98** [comment]
@Burner-Fuel Maybe you can mark it as turstforthy on your pc's local version

**Comment by 1-alex98** [comment]
We could write an email info@kaspersky.com
