### ISSUE TITLE
notify map-maker how map upload, versioning and naming works

### ISSUE THREAD

**Issue by badbwoi** [FAForever/downlords-faf-client#929]
Hey, could you give the ppl who like to upload a map the information on how to do it, before they actually do it?! This way we could explain map versioning and naming to everyone who likes to upload. I believe this would be a great help in keeping the vault cleaner in the future.

Maybe something like this:

How to upload a map/replace a map version?!
-Remove ".v000x" from folder (best_map-name.v0001) and in files (best_map-name_scenario.lua and best_map-name_script.lua)
-Add the right map version to scenario.lua file: "map_version = x,"
-Don't change the map name (name = "Best Map-Name") or the versioning is not working and a new map is created
-Map upload will create folder and path in files from scenario.lua file via:
(name = "Best Map-Name") + (map_version = 2) = (created folder-/pathname = "best_map-name.v0002")

**Comment by Sheikah45** [comment]
Now we have proper errors from the api that inform people I think the rest of these suggestions are best for something like the wiki
