### ISSUE TITLE
Display server status on login page

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#930]
Try to connect to the server's TCP socket and if it fails, display a message in the login window, including a link to https://statuspage.faforever.com.

**Comment by 1-alex98** [comment]
Dont we wanna display it all the time on login page, so people that have any kind of problems can click on it

**Comment by 1-alex98** [comment]
So maybe they find out the server is online so something else is not running and maybe if the api is done they can go to their login screen and check status page there...
