### ISSUE TITLE
Reduce lag and memory consumption of replays list

### ISSUE THREAD

**Issue by micheljung** [FAForever/downlords-faf-client#933]
The reason why the replay list slows down the client is because it's adding one element per replay to a vertical pane instead of using the more efficient list view (which only renders elements that are visible).
This consumes a lot of memory and once the heap gets full, there's a lot of GC activity that causes high CPU load as well.

https://www.youtube.com/watch?v=-QQvybRgSUc

**Comment by Sheikah45** [comment]
Fixed with the pagination and flow pane
