### ISSUE TITLE
Show years in rating graph of user profile

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#935]
Currently no years are shown on the x-axis of the rating graph in the user profile. This makes it hard to read if a user has a history of more than a year:
![image](https://user-images.githubusercontent.com/37223176/41199627-5bc081e4-6c95-11e8-8ae3-3a2e2568244e.png)

I am aware of 3 possibilities to solve this:
1. Add the year to the x-axis-labels. This would be a waste of space: 
![image](https://user-images.githubusercontent.com/37223176/41199671-32f5527a-6c96-11e8-869c-2705302088bb.png)
2. Introduce auto-format of the tick labels like [this.](http://myjavafx.blogspot.com/2013/09/javafx-charts-display-date-values-on.html)
3. Show data points in the graph and add tooltips to them like [this.](https://stackoverflow.com/questions/25892695/tooltip-on-line-chart-showing-date/25906039#25906039)

**Comment by JeroenDeDauw** [comment]
I second this. After playing several years the graph looks really silly:

![image](https://user-images.githubusercontent.com/146040/50047467-29fcec00-00b6-11e9-971a-52f22ab4f921.png)

Just showing the first date (with year!) and the last one would already be an improvement.
