### ISSUE TITLE
0.9.0 - Online replay vault search filter missbehaving

### ISSUE THREAD

**Issue by FlyingThunder** [FAForever/downlords-faf-client#948]
What i expected:
- i enter criteria "player name: FlyingThunder" and "max. Players: 2" and receive all games this apply to.

What i got:
- nothing happened at first. then i removed the max player filter, and _only then_ were the 1v1 games displays. though i could not "remove" the "max player == 2" filter it seems - i had to restart the client in order to display all games with my name again.

log:
[downlords-faf-client.log](https://github.com/FAForever/downlords-faf-client/files/2215755/downlords-faf-client.log)

**Comment by Brutus5000** [comment]
Max. players does not refer to the amount of players in the game. It refers to the maximum amount of players on the map version the game was played on. The naming should be changed.
The amount of players in a game is not available (would require implementation in api)
If you want to see ladder games go for `Game mod name` is `Ladder1v1`
