### ISSUE TITLE
0.9.0 - log isnt written to

### ISSUE THREAD

**Issue by FlyingThunder** [FAForever/downlords-faf-client#949]
i had my client open for a while, and i noticed that - when searching for log errors for another issue i had - that at one point, there was nothing written to the log anymore.

this is the log: https://pastebin.com/qtvXaCTW

i had several errors between 02:08 and 02:26 (i closed the client at 02:26).
i do not know if its normal that theres nothing written to log for 15 minutes, but i find this very weird as it made it impossible for me to post the log for another issue i had...

**Comment by 1-alex98** [comment]
> i had several errors

 what were the errors you expect????

**Comment by FlyingThunder** [comment]
the errors arent the issue here - i just ment that there should have been something in the log but as you can see, between :08 and :26 theres nothing there

**Comment by 1-alex98** [comment]
Well they might be

**Comment by FlyingThunder** [comment]
i guess thats possible, i think my issue was that when searching through my online replay vault, the "show more" button did not react at all

**Comment by 1-alex98** [comment]
Yeah i can tell you why most probably if you clicked it too often you caused the client to have a memory leak, which leads to high cpu usage which might lead to client unresponsive and also to it not writting its log

**Comment by 1-alex98** [comment]
I experienced that witha development version. It also stopped writting to the log. I used the client extensively but no log was written... @micheljung is the log wriiten in development versions

**Comment by 1-alex98** [comment]
I had another user today. It was the first time he used the java-client. And he had no log the second time he used it he had a log. So might be related to some setup missing the first time

**Comment by 1-alex98** [comment]
unreproducable
