### ISSUE TITLE
Resizing the client seems to be randomly not working

### ISSUE THREAD

**Issue by FlyingThunder** [FAForever/downlords-faf-client#950]
I experienced random issues of being unable to resize the client on the left and right side of the client, it seems a little as if when it does not work, the cursor is trying to resize another object than the outer client border? I dont know, look at the GIF, this issue combined with the missing autosnap feature makes using the client very awkward imo
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/39583733/43045986-b68d8eac-8dc2-11e8-9229-131267520afa.gif)

**Comment by 1-alex98** [comment]
I wonder if there is already an issue but i am sure we are aware of this
