### ISSUE TITLE
Files .lua in programdata are not created when launching a game

### ISSUE THREAD

**Issue by Deceitfox** [FAForever/downlords-faf-client#951]
Hello, i report the fact that when we launch once the game in downlord, a bunch of .lua files are not created inside the programdata. I needed to launch the Official FAF to create it.

**Comment by Geosearchef** [comment]
Thx for the report. Do you now which lua files? A log would be helpful. What kind of game did you create first time, standard FAF(or phantom, lab wars,...) ?  And the second one not launching. Which error did you get? None at all, black screen, nothing happening,...? Did you use coop?

**Comment by Deceitfox** [comment]
which lua files no i don't know... i begin to download the downlord version and launch game using it. Then with another problem a moderator told me how to launch FAF offline. And at this moment i posted on discord the new problem that some lua files are missing. So i tried to launch a game with old FAF . And i get a update of my game with all lua files.

**Comment by 1-alex98** [comment]
Well that problem is known and fixed in 0.9

**Comment by 1-alex98** [comment]
It is called path.lua or something similar, it tell the lua script where the game is. That one is not created, but only needed for updates via the legacy updater... So what featured mod did you wanna play? Plain faf?
