### ISSUE TITLE
Setting for advanced logging

### ISSUE THREAD

**Issue by 1-alex98** [FAForever/downlords-faf-client#955]
@micheljung is that possible. Pretty sure it is, not sure how tho, but I wanna keep the idea. So we should make a setting to turn on advanced logging, so that everything is logged including debug, I would say so people can turn that on if they have an issue and aditionally information is needed.

**Comment by Brutus5000** [comment]
This is possible. Spring Boot Actuator does [this ](https://github.com/spring-projects/spring-boot/blob/master/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/logging/LoggersEndpoint.java) and you can also do it directly [with logback](https://stackoverflow.com/questions/3837801/how-to-change-root-logging-level-programmatically)

**Comment by 1-alex98** [comment]
Ok what we want is setting the log level on runtime in the settings.

**Comment by Atrocyte** [comment]
How about setting this toggle under Settings > General > below the "Write ICE Log File"
![image](https://user-images.githubusercontent.com/7738847/96111977-38023a80-0ee2-11eb-96e5-b7ea3f9b6dee.png)

**Comment by 1-alex98** [comment]
Yes I guess would be good

**Comment by Atrocyte** [comment]
I got the toggle working with the following behaviour:
- Switch from default (INFO) to DEBUG
- Switch from DEBUG to INFO.
- Client starts with the debug toggle off.

**Comment by 1-alex98** [comment]
Very interesting are also the settings for the remote package. That is where server messages get logged. I am not sure if you only turn the debug log on for all packages where it is not set separately or set it for all packages there are. But maybe turning it on for all packages there are would be the correct thing to do. Cause otherwise all the interesting stuff is not logged

**Comment by Atrocyte** [comment]
I've tested the logging for the remote package, also created the installer to verify behaviour.
Changing the log level of a package does not propagate the change in log level parent package to child packages as I expected it to. I had to set log level on each logger individually instead.
