### ISSUE TITLE
UI - can't move window by bar

### ISSUE THREAD

**Issue by norraxx** [FAForever/downlords-faf-client#963]
On windows 10 can't move client window by grabbing it by top bar 
![top_cant_move_only_green_small_line_is_ok](https://user-images.githubusercontent.com/26487134/45585779-82232700-b8ea-11e8-933d-926fc944f03d.png)

**Comment by micheljung** [comment]
I'd like to solve it like Chrome; when the window is maximized, this area can always be grabbed:
![image](https://user-images.githubusercontent.com/1864183/49955876-2de90c80-ff04-11e8-8f73-9d12e42173e8.png)

And when it's in normal state, there's an additional border at the top:
![image](https://user-images.githubusercontent.com/1864183/49955966-64268c00-ff04-11e8-9191-177aabf09a67.png)
