### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by speed2CZ** [FAForever/downlords-faf-client#968]
I just got version 0.8 from the webpage and this error pops out right after the initial "logo screen" or whatever it's called
https://pastebin.com/WnTvfUrm

**Comment by 1-alex98** [comment]
@speed2CZ error is known
You downgraded from 0.9 version either from ice test or from some other RC. Please delete your client.prefs in AppData/Roaming/ForgedAll...

**Comment by speed2CZ** [comment]
Thanks
