### ISSUE TITLE
Replay stream is being buffered

### ISSUE THREAD

**Issue by norraxx** [FAForever/downlords-faf-client#973]
Replay server (https://github.com/FAForever/faf-aio-replayserver) needs to have continuous stream from game, as the game sends, otherwise replay server won't be able to stream live replay fluently.
Now, buffer size is 8192. It would be nice, if network stream behavior will be fluent/continuous.
Every 1/10 of second game sends at least 7 bytes of data, it would be nice to have same behavior on java client side, like a simple proxy.

`src/main/java/com/faforever/client/replay/ReplayServerImpl.java:105` has `BufferedOutputStream`. Default buffer size is 8k for jre 1.8 on windows. Also `BufferedOutputStream` has second parameter, buffer size, it might help.

**Comment by 1-alex98** [comment]
I think a buffer in general is good we might just make it smaller

**Comment by Brutus5000** [comment]
Our observation for a sandbox game with fee commands was that the stream got flushed roundabout every 2 minutes. 8192 bytes / 70 bytes per second = 117 seconds.

If you look to the method `recordAndRelay` you will set that there is a buffer in place, but maybe it's not working as intended. This buffer has 512 bytes and would only be flushed every 7 seconds.

While buffering in general is a nice idea, the FAF client acts as a proxy between the game and the replay server. Therefore it should not introduce any timelags or other behavior and just pass through any data.
So maybe in addition to the buffer we should flush the stream once a second.

**Comment by norraxx** [comment]
How about to use: https://docs.oracle.com/javase/7/docs/api/java/io/DataOutputStream.html
