### ISSUE TITLE
Recognize and download sim_mods from replay header

### ISSUE THREAD

**Issue by norraxx** [FAForever/downlords-faf-client#974]
Newer version of replay server will give additional information about replay, it's simulation mods.
Info will be stored in replay header (in JSON) on first level of JSON object as `sim_mods` key.
It'll be object, that contains mod UID and version of the game, examle:
```
{'uid': 802819405, 'sim_mods': {"DF8825E2-DDB0-11DC-90F3-3F9B55D89593": 1}, ...}
```
Client will download this version of simulation mod and after that run replay.
Maybe I'm wrong, but as I know, all sim mods have unique UID, so there is no need to read version.

**Comment by 1-alex98** [comment]
I am not sure on this issue looking at the code we already do this and which sim mods where used in game was stored in old format already and I think you should simply stick to old format(it was fine). But maybe I am also mistaking.

**Comment by norraxx** [comment]
Give me link on that java code, please.

**Comment by 1-alex98** [comment]
https://github.com/FAForever/downlords-faf-client/blob/2ab525bcb6b9c0183c9b266fc9ccb4dd8636b10e/src/main/java/com/faforever/client/replay/LocalReplayInfo.java#L26 that is the object that we read out from first line of the replay

**Comment by 1-alex98** [comment]
https://github.com/FAForever/downlords-faf-client/blob/2ab525bcb6b9c0183c9b266fc9ccb4dd8636b10e/src/main/java/com/faforever/client/replay/ReplayFileReaderImpl.java#L38
