### ISSUE TITLE
Constant disconnects

### ISSUE THREAD

**Issue by ArXen42** [FAForever/downlords-faf-client#986]
I made several attempts to use this client during the last year but unfortunately every game like 6x6 usually breaks immediately or after a few minutes. Usually I'm losing connection to one player with all the numbers in `behind` column (F11) being negative.

Reinstalls (including Windows), changing the port number, forwarding the port manually on home router (DIR-620) doesn't help.

Original client seems to work, although sometimes with disconnects (but not so consistent) and much more frequent `Host abandoned lobby` problem. Don't know if this is related somehow.

Simple 1v1 custom game with the player from my city seems to work, however.

Here are the logs of the last unsuccessful game. Got disconnect in the first minutes.

[game.uid.8663196.log](https://github.com/FAForever/downlords-faf-client/files/2457270/game.uid.8663196.log)
[gamesession.log](https://github.com/FAForever/downlords-faf-client/files/2457271/gamesession.log)
[downlords-faf-client.log](https://github.com/FAForever/downlords-faf-client/files/2457272/downlords-faf-client.log)

**Comment by 1-alex98** [comment]
We understand your concerns and we would investigate you issue however the new ICE connection will be released soon(not fixed date but appr. 1 month), which will change 100% of connection code and how connection works.

**Comment by ArXen42** [comment]
That's great, thanks!

**Comment by Geosearchef** [comment]
I can always welcome more people ready to test ;). If you're interested join the faf discord and execute `!subscribe ICE Tester` to be notified of new test games.
