### ISSUE TITLE
Language Chinese should be labeled as simplified

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#993]
The Chinese characters used in the translation are simplified, so the language entry should be labeled accordingly. Currently it's not (v0.9.0-beta.RC8):
![image](https://user-images.githubusercontent.com/37223176/46940914-2aebb000-d06a-11e8-9afc-1716ea6570ec.png)

**Comment by 1-alex98** [comment]
Gonna leave it like that unless somebody gives me an ISO 693-3 code for that
