### ISSUE TITLE
Map column title cut off in German and maps misaligned in column

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#994]
v0.9.0-beta.RC8:
![image](https://user-images.githubusercontent.com/37223176/46941090-90d83780-d06a-11e8-98c5-257a3de8282d.png)
![image](https://user-images.githubusercontent.com/37223176/46942015-b403e680-d06c-11e8-873c-caf4894bb028.png)

**Comment by 1-alex98** [comment]
Well what do you suggest we do. I would leave it as it is to be honest

**Comment by germanicianus** [comment]
I suggest to resize the colums on creation to at least the width of the heading and to center icons/images like the lock symbol and map  horizontally and vertically.

Btw. - There is no heading for the protected game (lock) column, but I think this is intended which I can understand.

**Comment by micheljung** [comment]
Duplicated by #1017
