### ISSUE TITLE
No "Close" button in error dialog - only closable with ESC key

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#995]
v0.9.0-beta.RC8:
![image](https://user-images.githubusercontent.com/37223176/46941243-ff1cfa00-d06a-11e8-88fb-8422b65443cf.png)

**Comment by 1-alex98** [comment]
Not if you click beside it?

**Comment by 1-alex98** [comment]
Geo says it goes for all notifications

**Comment by micheljung** [comment]
We need to explicitly add a "Cancel", "Dismiss" or "Close" button to all dialogs (as appropriate). Per material design guidelines, we won't add a typical "close" button in the top right corner (wouldn't even be easy as JFoenix provides the dialog)

**Comment by 1-alex98** [comment]
So what do we do close button or fix that the dialog close not close when clicking beside it

**Comment by germanicianus** [comment]
I vote for both because clicking outside is not obvious.

A button to adhere to the standards and clicking outside to make it consistent.

**Comment by micheljung** [comment]
Depending on the notification, closing the dialog when clicking on the overlay is intended and, therefore, does not need to be "fixed":
Whether or not this behavior should be enabled or disabled depends on the nature of the specific dialog; is a user input required or can it be dismissed.

https://github.com/jfoenixadmin/JFoenix/blob/master/jfoenix/src/main/java/com/jfoenix/controls/JFXDialog.java#L137
