### ISSUE TITLE
Some captions barely readable

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#996]
Examples in v0.9.0-beta.RC8:
![image](https://user-images.githubusercontent.com/37223176/46941421-5d49dd00-d06b-11e8-80b0-9e503fc9fedc.png)
![image](https://user-images.githubusercontent.com/37223176/46941484-85d1d700-d06b-11e8-8086-261d6aa849f9.png)
![image](https://user-images.githubusercontent.com/37223176/46941524-984c1080-d06b-11e8-9ea8-a7a0848656d8.png)
![image](https://user-images.githubusercontent.com/37223176/46941541-a1d57880-d06b-11e8-855c-099bd2dbf49f.png)

**Comment by micheljung** [comment]
Fixed
