### ISSUE TITLE
Tab 'Tournaments' has no loading indicator but stays white until loaded

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#997]
![image](https://user-images.githubusercontent.com/37223176/46941724-13152b80-d06c-11e8-80de-e69fadcea6d0.png)

**Comment by 1-alex98** [comment]
It never had I guess I think that is no bug but rather an improvement

**Comment by Brutus5000** [comment]
That is correct. Unfortunately the challonge images take quite a while to generate.

**Comment by 1-alex98** [comment]
Same goes for Unit db btw

**Comment by germanicianus** [comment]
In general a user would expect all main tabs to have a loading indicator 🙂 .

**Comment by Brutus5000** [comment]
Fixed by 8ef228b3407ac1de7c7055d21f70efa1965ba082

**Comment by micheljung** [comment]
Dammit, I referenced #996 in the commit message
