### ISSUE TITLE
2 chat tabs active at same time -> user lists overlay

### ISSUE THREAD

**Issue by germanicianus** [FAForever/downlords-faf-client#998]
How to reproduce:
1. Start client, select tab Play, close client.
2. Start client, select tab Chat immediately.
3. Tabs aeolus and DEV_clan (my clan) are both selected and chat user lists overlay each other

Result:
![image](https://user-images.githubusercontent.com/37223176/46942293-4e642a00-d06d-11e8-9cf4-12600932b08d.png)
![image](https://user-images.githubusercontent.com/37223176/46942369-7bb0d800-d06d-11e8-847d-4c1b650d1d32.png)

Remedy:
Click on one chat tab.

**Comment by petervasil1234** [comment]
Hello, can I help with this one?
